### ISSUE TITLE
[Feature Request] Support Vcard

### ISSUE THREAD

**Issue by HumanG33k** [profanity-im/profanity#1004]
Hello i don’t know how it’s possible even if it’s relevant but it can be cool if profanity can support vcard for contacts. 

I thought something like it’s done with mutt, and khard. 
It find vcf files in a directory and find XMPP contact in private_objects Jabber or xmpp (maybe can be configure in profanity). The contact sync is done by vdirsyncer in this case but it is an other story.

**Comment by pasis** [comment]
For reference: there is vcard example in libstrophe https://github.com/strophe/libstrophe/blob/master/examples/vcard.c

**Comment by HumanG33k** [comment]
So we "just" need to implement the functionnality. Good to know i will try to do it.

**Comment by mdosch** [comment]
I would recommend to not name the command for this feature not `vcard` but e.g. `contact` as in my opinion this command should be reserved in case later profanity versions support [XEP-0054](https://xmpp.org/extensions/xep-0054.html).

**Comment by jubalh** [comment]
No progress here it seems.
Probably https://github.com/profanity-im/profanity/issues/1158 will be enough anyways.
