### ISSUE TITLE
Add buddy/muc names in statusbar

### ISSUE THREAD

**Issue by varac** [profanity-im/profanity#1005]
I'd love to see the names of buddy/muc names next to the window numbers like irssi does.

i.e. from now:

`[1][2]-3-[4][ ][ ][ ]…`

to 

`[1 main][2 alice]-3 bob-[4 profanity-muc][ ][ ][ ]…`

Maybe this is already possible but I missed some config options ?

**Comment by jubalh** [comment]
Yes it's already possible.

https://profanity-im.github.io/reference.html#statusbar
