### ISSUE TITLE
Remember status on reconnect

### ISSUE THREAD

**Issue by yuha0** [profanity-im/profanity#1006]
When Profanity loses connection to the server, it keeps trying to reconnect. Once it manages to establish connection to the server again, it set my status to "online" automatically.

```
17:32:49 - Status set to away (priority 0), "OOO".
04:05:34 - Lost connection.
04:06:15 - user.name@server/profanity logged in successfully, online (priority 0).
04:06:15 - TLS connection not established
04:06:15 - Autoping response timed out after 20 seconds.
04:06:16 - Lost connection.
04:06:53 - user.name@server/profanity logged in successfully, online (priority 0).
04:06:53 - TLS connection not established
```

Is it possible to remember my status from last session and do not set to "online" when reconnect?

**Comment by AdrianVollmer** [comment]
Perhaps related: I'd like to be able to make the status message persistent. So if I set `/online Up the Irons!` I want it to be the same in subsequent sessions.

**Comment by jubalh** [comment]
We will do this after https://github.com/profanity-im/profanity/issues/1116 is sorted out.

**Comment by xenrox** [comment]
> Is it possible to remember my status from last session and do not set to "online" when reconnect?

`/account set <account> status last` should work (see https://profanity-im.github.io/guide/latest/reference.html#account)

I am working on the status message, but it is not trivial.

**Comment by jubalh** [comment]
@xenrox any progress?

**Comment by xenrox** [comment]
> @xenrox any progress?

I am currently migrating my server and have no XMPP acoount because of that. After the migration is done, I can hopefully finish this patch.

**Comment by jubalh** [comment]
@xenrox I think I know some people who could offer you a test account on their server, interested?

**Comment by xenrox** [comment]
Thanks, but I expect to be done by this weekend, only ejabberd and nextcloud missing, so hopefully this won't be necessary.

**Comment by jubalh** [comment]
@xenrox ping :)
