### ISSUE TITLE
Copy Paste long text

### ISSUE THREAD

**Issue by HumanG33k** [profanity-im/profanity#1013]
I don’t know if can it be fix but when we receive a long text there is an issue with space for example :

14:01:03 - user@domain.ext/WebChat: | blablablabla blablablabla blablablabla
<space><space><space><space><spa>blablablabla blablablabla blablablabla
<space><space><space><space><spa>blablablabla blablablabla blablablabla |

if we select with mouse text between pipe  | (add for the ie) copy and paste all <space> are paste and text need to be clean. I don’t know if there is a way to deal with that.

**Comment by jubalh** [comment]
Please read https://github.com/profanity-im/profanity/issues/1060
