### ISSUE TITLE
Cygwin - W10 - Unable to locate package libisl10

### ISSUE THREAD

**Issue by GuillaumeGas** [profanity-im/profanity#1030]
Hi,
I can't install profanity on my Windows 10 using Cygwin, I get the following error during the install process : 
```
Installing libisl10
Unable to locate package libisl10
Error 1 with command 'apt-cyg install git make gcc-core m4 automake autoconf pkg-config openssl-devel libexpat-devel zlib-devel libncursesw-devel libglib2.0-devel libcurl-devel libidn-devel libssh2-devel libkrb5-devel openldap-devel libgcrypt-devel libreadline-devel libgpgme-devel libtool libpcre-devel libisl10 libcloog-isl4 autoconf-archive python' on line 71. Exiting.
```

Any idea of how to fix this issue ?

**Comment by GuillaumeGas** [comment]
I don't think so, I tried to install this package using the apt-cyg command (just like the install script does...).

No, I think I installed the 0.5.1 (because of this link : http://www.profanity.im/install.html#windows).

Should I try with another version ?

**Comment by jubalh** [comment]
> (Anyway, I managed to install it by using the Windows Subsystem for Linux ;) )

We should fix the Windows version anyways (if it's broken).
But actually I think you were just missing this dependency.

Can you tell me how you did the installation via the Subsytem?

> No, I think I installed the 0.5.1 (because of this link : http://www.profanity.im/install.html#windows).

Yes 0.5.1 is the last stable release. We will release 0.6.0 soon, and thus have just released the [RC1](https://github.com/boothj5/profanity/releases/tag/0.6.0.rc1) for testing.

**Comment by GuillaumeGas** [comment]
I installed it by using the `apt install profanity` command.

**Comment by jubalh** [comment]
Good to know. So this is this Ubuntu subsystem.

I think we need someone who tests whether the release on Windows still works anyways. Not the subsystem way.

I'll add the help wanted label in case anyone is willing to.

**Comment by jubalh** [comment]
@kaffeekanne graciously took the time to update the Cygwin instructions. Merged in https://github.com/profanity-im/profanity-im.github.io/pull/34.
It's for basic behaviour without crypto libs and thus no OMEMO/OTR.

I'll close this issue now since @GuillaumeGas uses the windows subsystem, and I left it only open to remember to update the Cygwin instructions.

Thanks @kaffeekanne !
