### ISSUE TITLE
Profanity seen as "Available" and "Idle" when they are chatting by pidgin users

### ISSUE THREAD

**Issue by arthurlogilab** [profanity-im/profanity#1041]
As a user of pidgin, I have three users in my roster that use profanity (other users use pidgin or gajim mainly). Even when they are typing in group chats or 1-to-1 chats, their status appears as "Available" *and* "Idle". Is this is a bug in pidgin or in profanity (or a configuration setting in profanity?)

![pidgin](https://user-images.githubusercontent.com/445200/54353590-b2a70c00-4654-11e9-8fc6-40f161b37c6d.png)

**Comment by kaffeekanne** [comment]
Looks like they have set `/autoaway mode off`, which is default. Then again it is a UI/UX decision what Pidgin does with the information it gets. You or your chat partners can check for settings here, if they want to send away/xa presence: http://www.profanity.im/reference.html#autoaway

**Comment by arthurlogilab** [comment]
Hi, I'm not sure I understand. How can my contact show  "Idle 5d ..."  when I'm chatting to them ? Maybe I don't understand the meaning of *Idle* ? Do you have documentation about that ? I think that when they are away (for lunch for example), their status goes correctly to away, so I don't think they are using the `/autoaway mode off`.

**Comment by jubalh** [comment]
My guess is that your contacts clients can send their status (online, idle etc), but also your client can decide to set info based on other factors.

Did you test this with other clients to be sure that this is a profanity issue?
Can you test the option kaffekanne told you about and whether it makes a difference?
Please report your findings.

**Comment by jubalh** [comment]
@arthurlogilab any update?

**Comment by arthurlogilab** [comment]
Thanks for getting back to me. 

Other clients (psy, gajim) show the same problem. I've checked with these users and they didn't set the `/autoaway mode off`  as suggested by @kaffeekanne

**Comment by jubalh** [comment]
Hmm I use gajim on some devices, and profanity users still look online. Never idle.
@kaffeekanne you also use multiple devices and contacts with different devices, have you ever experienced this?

**Comment by arthurlogilab** [comment]
Sorry, I just re-tested with psi and I am getting different results, and in pidgin a weird thing happened : when I click "Get info" on my contacts who use profanity, the idle gets reset. I'm off to file a bug on pidgin.

**Comment by jubalh** [comment]
Thanks. I'll close this one as I think it's probably a pidgin issue. Feel free to link the pidgin bug here for reference :)

**Comment by kaffeekanne** [comment]
i rarely see other people with profanity. But in crowded MUCs i happened to see some online profanity users. So in general it should work. I consider setting up a test account with some major clients to test against profanity directly. I use profanity and conversations, casually gajim. So guessing my idle state should be hard to decide.

**Comment by kaffeekanne** [comment]
@arthurlogilab you could ask your chatpartners to check their `/states` and `/gone` settings. 
- `/states` Send chat state notifications to recipient during chat sessions, such as typing, paused, active, gone.
- `/gone` Send a 'gone' state to the recipient after the specified number of minutes.

Maybe there is a correlation. I don't use that settings, so i am not sure. Also i don't know how others see my client, but i don't hear complains :)
