### ISSUE TITLE
Receiving an OTR-encrypted message should always be a highlight, even if it couldn't be decrypted

### ISSUE THREAD

**Issue by vrs** [profanity-im/profanity#1042]
Version 0.6.0.

Often, other users will send messages that I can't decrypt (usually because the OTR session was lost in the meantime). I then fail to notice them because neither do they highlight me (unlike regular messages), nor does the message stand out next to all the other red text. This has so far not cost me a friendship but is hugely annoying when I see an important message hours to days too late, and could be improved.

**Comment by jubalh** [comment]
Where does it print the red text now and what would you like to have instead?

**Comment by vrs** [comment]
Usually it's this, printed in the message window I have open with a contact: https://github.com/profanity-im/profanity/blob/706af9a9008d33bb33372b4700465ed9027084f2/src/otr/otrlibv4.c#L137-L139

Since it represents a message sent by a contact, it should act like a message and trigger a highlight.

**Comment by jubalh** [comment]
@vrs can you step by step describe what one needs to go to get that message?

**Comment by vrs** [comment]
Since I don't have control over the clients that usually trigger this, no, but try the following:
1. start an OTR conversation between two clients, one of them profanity, the other, say, pidgin (but iirc, I've also had this happen with two profanities).
2. close+reopen, or reconnect profanity.
3. from the other client's still-open chat window, send a message.

**Comment by jubalh** [comment]
I tried this with two instances of profanity, and I still can't reproduce it. Which clients are you using?
