### ISSUE TITLE
Autocomplete login limited list don't work

### ISSUE THREAD

**Issue by TechCatOther** [profanity-im/profanity#1043]
Version 0.6

After update don't work autocomplite with <TAB>. 

**How to reproduce:** 
For example, I write message to SomeLogin, but in my list ASomeLogin too. 

1. Start typing /msg Som
2. Press <TAB>
3. See /msg ASomeLogin

In version 0.5 work correct and after <TAB> was SomeLogin, not ASomeLogin

**Comment by jubalh** [comment]
I tested this on 0.6.0 and master. Works for me on both.
It also works whether I use `/msg beginning_of_jid` or `/msg beginning_of_nick`.

**Comment by TechCatOther** [comment]
I checked current version from master branch. Still have the issue. With ascii chars in login works fine but if nick of user have Unicode symbols as first all broken. 


In roster:
>Абс
>ЛогинПользователя
>somelogin

Example work:
> /msg somelo TAB
> /msg somelogin

Example errors:

>/msg Логи TAB
>/msg "Абс"

Expected:
>/msg Логи TAB
>/msg "ЛогинПользователя" 

In 0.5 all ok.

**Comment by jubalh** [comment]
Well try to replicate this later.

**Comment by jubalh** [comment]
Well I tried with cyrillic characters now and it still works ;)
