### ISSUE TITLE
Update website with OMEMO documentation

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1048]
Once https://github.com/boothj5/profanity/pull/1039 is merged, and 0.7.0 is going to be released we need to update the website (repo at: https://github.com/boothj5/www_profanity_im) to include instructions for OMEMO.

[PGP source](https://github.com/boothj5/www_profanity_im/blob/master/pgp.html) [PGP rendered](http://www.profanity.im/pgp.html) can be used as a template.

**Comment by willeponken** [comment]
From #1055: 
> As an alternative "workaround" (not really as /omemo gen is only run once, so why bother), one can set Gcrypt to use urandom by adding only-urandom to /etc/gcrypt/random.conf. Or install haveged (and make sure it starts at boot, as I had forgot).

**Comment by kaffeekanne** [comment]
Can we tell gcrypt to use `/dev/urandom` at runtime? We had issues with entropy before.

**Comment by paulfariello** [comment]
@kaffeekanne I haven't found a way to do this at runtime.

**Comment by jubalh** [comment]
Content is added. So far available at https://profanity-im.github.io/www_profanity_im/
More website news will follow later. But this issue can be closed.
