### ISSUE TITLE
Unexpected disconnect with error log message "tls: DBG: error=5 errno=32"

### ISSUE THREAD

**Issue by errhammr** [profanity-im/profanity#1082]
About my machine and profanity version:
```
$ uname -a
OpenBSD hostname.home 6.5 GENERIC.MP#3 amd64
$ ~/git/profanity/profanity --version          
Profanity, version 0.6.0dev.master.722cb5fd
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.12.0)
OMEMO support: Enabled
C plugins: Disabled
Python plugins: Disabled
GTK icons: Enabled
```

About the symptoms:
Using my conversations.im account I frequently get disconnected. The log file says `tls: DBG: error=5 errno=32` which I suspect is the reason for that.

When starting profanity it asks for my password, connects to the server and fetches the roster. It automatically joins some bookmarked MUCs. Then after a few seconts it says "connection lost" and tries reconnecting 30 seconds later. The cycle repeats.

Sometimes I get a solid connection at the first attempt or a few attempts into the cycle, sometimes it just disconnects and reconnects until my patience makes me `/quit` and just use a different client.

I have another account on a different server (dismail.de) and I am unable to reproduce the error there. On dismail.de I have a very small roster, on conversations.im there are loads of contacts, maybe that is part of the problem.

The error log file can be found here: https://paste.dismail.de/?14fc56789a71155b#sZ+lDk+VDuAXCBm587lirkipr0D4jqk3MhMDMl3+ZLc=

**Comment by errhammr** [comment]
Since that might be related, IPv6 is disabled on my machine.
I could not figure out if it is a server issue, but this looks promising: https://xmpp.net/result.php?id=1455806

**Comment by jubalh** [comment]
Do you have any idea since when this happens? Also with the last two stable releases of profanity?

**Comment by errhammr** [comment]
I tried commit 95741271 before and it happened there too if I remember correctly.
I haven't tried the stable versions because they don't have OMEMO support (yet) so they are not that useful to me.
I haven't found any documentation of the TLS error codes yet. Do you know where I can find them?

**Comment by pasis** [comment]
`error=5` means:
```
# define SSL_ERROR_SYSCALL               5/* look at error stack/return
                                           * value/errno */
```
`errno=32` means EPIPE

**Comment by errhammr** [comment]
I got a backtrace out of gdb which might help
https://paste.dismail.de/?2062c411c4887b38#E0F2c9no2BkhF6t0xWtmnVnb1rn7Qhf1/ewZ/HQt6OU=

**Comment by jubalh** [comment]
Do those pastes have a limited time or will the be available forever? If they get removed then it would be awesome if you could attach the actualy content here :-)

**Comment by errhammr** [comment]
They'll stick around basically forever. You're right tho, it would be easier if I just posted them here.
```
Program received signal SIGPIPE, Broken pipe.
_thread_sys_write () at -:3
3       -: No such file or directory.
        in -
Current language:  auto; currently asm
(gdb) bt
#0  _thread_sys_write () at -:3
#1  0x000000ea8b29494e in _libc_write_cancel (fd=Variable "fd" is not available.
) at /usr/src/lib/libc/sys/w_write.c:27
#2  0x000000ea9493698a in sock_write (b=0xeb063d1200, in=Variable "in" is not available.
) at /usr/src/lib/libcrypto/bio/bss_sock.c:154
#3  0x000000ea949377a2 in BIO_write (b=0xeb063d1200, in=0xeada625003, inl=260) at /usr/src/lib/libcrypto/bio/bio_lib.c:303
#4  0x000000eaa8a2f014 in ssl3_write_pending (s=0xeae95ce900, type=Variable "type" is not available.
) at /usr/src/lib/libssl/ssl_pkt.c:840
#5  0x000000eaa8a2e91b in ssl3_write_bytes (s=0xeae95ce900, type=Variable "type" is not available.
) at /usr/src/lib/libssl/ssl_pkt.c:599
#6  0x000000eac19e07c2 in tls_write () from /usr/local/lib/libmesode.so.0.0
#7  0x000000eac19d4652 in xmpp_run_once () from /usr/local/lib/libmesode.so.0.0
#8  0x000000e8895cd492 in connection_check_events () from /home/hartmann/git/profanity/profanity
#9  0x000000e8895ccb29 in session_process_events () from /home/hartmann/git/profanity/profanity
#10 0x000000e8895c6d87 in prof_run () from /home/hartmann/git/profanity/profanity
#11 0x000000e88963dbe4 in main () from /home/hartmann/git/profanity/profanity
```

**Comment by jubalh** [comment]
Which SSL library is OpenBSD using?

**Comment by errhammr** [comment]
```
$ openssl version -a
LibreSSL 2.9.1
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/etc/ssl"
```

**Comment by jubalh** [comment]
@pasis do you have any idea what we can do here?

**Comment by pasis** [comment]
@jubalh, unfortunately, no. EPIPE (errno=32) is expected when TCP connection is broken. The question is why it is broken. And Profanity logs can't answer the question, because the problem occurs on a lower level or server side.

**Comment by jubalh** [comment]
Then it seems we cannot do anything about this issue. I'll close it. @errhammr feel free to reopen/commment if persists or we can get more info.
