### ISSUE TITLE
Homebrew Installation | SHA256 Missmatch

### ISSUE THREAD

**Issue by GrowBo** [profanity-im/profanity#1088]
I got this Error when **installing profanity** with the help of `brew install profanity`

It seems that the **expected hash is wrong**, because I checked MD5 and SHA1 and they match with the codes on the website.

```javascript
==> Downloading http://www.profanity.im/profanity-0.6.0.tar.gz
########################################## 100.0%
Error: An exception occurred within a child process:
ChecksumMismatchError: SHA256 mismatch
Expected: 51b0932924a391656423af0d85f14dde049ac1e94214f948849d37df1c2759c4
Actual: f1b2773b79eb294297686f3913e9489c20effae5e3a335c8956db18f6ee2f660
Archive: /usr/name/Library/Caches/Homebrew/downloads/d0a7d7dcee5e393725dec3e6ae466d9354211d69331ed138bf3c9294dc7ef4ae--profanity-0.6.0.tar.gz
To retry an incomplete download, remove the file above.
```

Thank you :cyclone::wavy_dash::cyclone:

**Comment by jubalh** [comment]
Yes it's wrong. We uploaded another tarball after the release because the first one created some files that were not needed. We udpated our hashes on the website.
So it could be the case that the homebrew hashes are from the old tarball. Please fix it in brew or create a bug there.
