### ISSUE TITLE
Show info message in console window when already in encrypted session

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1093]
When already in an OMEMO session with a contact issueing `/omemo start <contact>` from a muc/chat window throws ` ! You are already in an OMEMO session.` as informational message in that starting muc/chat window.

The message is correct since the session was started, i would expect that it in the console window or the chat window of the contact i falsly tried to start the session with. Unfortunately i have no idea hot OTR or PGP handle that situation.

**Comment by kaffeekanne** [comment]
Looking into the code,i see this applies to all info messages about started encrypted sessions, be it OTR, GPG or OMEMO. I think that information does not belong in the chat window where i try to start the OMEMO session, since i am moved to the newly created window and will not see that notice. It either should be shown in the newly created window or in the console window.

**Comment by jubalh** [comment]
I guess the right behaviour would be to write it in the console always.
Only to write it in the window if the window actually is the chat window with that partner.

**Comment by kaffeekanne** [comment]
Chat window is probably enough. If also console, then the contact needs to be mentioned so you know where the informational message belongs to.
