### ISSUE TITLE
profanity-0.6.0.tar.gz checksum change

### ISSUE THREAD

**Issue by tschoonj** [profanity-im/profanity#1094]
Hi,

I am a maintainer of [Homebrew](https://brew.sh) and would like to report that the sha256 checksum of the [profanity-0.6.0.tar.gz](http://www.profanity.im/profanity-0.6.0.tar.gz) tarball has changed from 51b0932924a391656423af0d85f14dde049ac1e94214f948849d37df1c2759c4 to f1b2773b79eb294297686f3913e9489c20effae5e3a335c8956db18f6ee2f660 sometime between 21/02/2019 and 10/05/2019.

Any thoughts on what happened here?

Thanks,

Tom

**Comment by jubalh** [comment]
We got this reported a couple of days ago. Please take a look at https://github.com/profanity-im/profanity/issues/1088

**Comment by tschoonj** [comment]
Ok thanks for the explanation.
