### ISSUE TITLE
Theme setting statusbar text gets misinterpreted

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1095]
Because of #1077 i was testing some theme stuff and found the following behavior when trying to set the color for inactive (default cyan) windows in statusbar. Everything gets bold, screenshot does not really tell that, nevertheless:

![themes_wrong_color](https://user-images.githubusercontent.com/21034294/57604680-11113d80-7565-11e9-8df6-0238ec54c1f5.png)

Reproduce by placing a minimal theme file in `~/.config/profanity/themes/` containing:
```
[colours]
statusbar.text=bright_red
```

What i expected was to set the text color of my jid only. What i was searching for, was a way to set the color of inactive windows. Also setting a bracket/char apart from default `-` for active windows would be nice.

**Comment by jubalh** [comment]
Sorry. I read it three times, but I dont get what is happening :S

**Comment by optmzr** [comment]
I'm not sure it's the same issue, but I get that the color from the previous field "leaks" over to the next field, e.g. if the first field is red and the second white (no color), the second fields becomes red.

I suppose this is due to a missing `\e[0m`?

**Comment by jubalh** [comment]
> I suppose this is due to a missing \e[0m?

I suppose this has to be somewhere. I remember another issue about something similar, but can't find it right now.

**Comment by jubalh** [comment]
When/where exactly does it happen for you guys?

**Comment by jubalh** [comment]
@kaffeekanne @optmzr ping :)

**Comment by jubalh** [comment]
> `statusbar.text=bright_red`

`bright` is not a valid value.

**Comment by jubalh** [comment]
> when trying to set the color for inactive (default cyan) windows in statusbar.

`statusbar.active=` sets the color of the not currently selected tab.
`statusbar.current=` sets the color of the currently selected tab.
`statusbar.text=` sets the color of the general text in the statusbar (to my knowledge this is user/barejid/fulljid).

Since there was no response, and I think it was just using the theme attrs wrongly I'll close this.
