### ISSUE TITLE
Profanity can't be installed on fedora 30 due to  libreadline.so.7

### ISSUE THREAD

**Issue by klm46** [profanity-im/profanity#1096]
While trying to install profanity from repo, yum shows following error:

```
Error: 
 Problem: conflicting requests
  - nothing provides libreadline.so.7()(64bit) needed by profanity-0.5.1-1.fc29.x86_64
```

Fedora 30 comes with this lib in version 8 and a downgrade is not possible.

**Comment by jubalh** [comment]
> While trying to install profanity from repo

From *which* repo? AFAIK profanity is not in official Fedora repositories. Also 0.5.1 is old. 0.6.0 is the latest stable release.

> Fedora 30 comes with this lib in version 8

I use libreadline 8 on openSUSE Tumbleweed for profanity without problems.

**Comment by pasis** [comment]
@klm46, this is issue with how the rpm is built. You should post a bug report to the maintainer or yum repository tracker (if it exists). If the maintainer doesn't read this page, we can only assist you with building Profanity from sources. But unfortunately, we can't fix the rpm.

**Comment by klm46** [comment]
Hi, thanks for your answers. 

@jubalh 
`Name         : profanity
Version      : 0.5.1
Release      : 1.fc29
Architecture : x86_64
Size         : 272 k
Source       : profanity-0.5.1-1.fc29.src.rpm
Repository   : linkdupont-fedora-link-extras
Summary      : A console-based XMPP client written in C using ncurses
URL          : http://profanity.im/
License      : GPLv3
Description  : Profanity is a console based XMPP client written in C using ncurses and
             : libstrophe, inspired by Irssi.`

I know, this is for FC29, i got 30. But this was my last chance.

@pasis 

I tried to build it from profanity0.6 source. But this is buggy to :/ 
The ./configure Script tells me:
`configure: error: Neither libmesode or libstrophe in version >= 0.9.2 found, either is required for profanity`

But my system has another meaning :)
```
[root@pc2382 profanity-0.6.0]# rpm -qa |grep libstrophe
libstrophe-0.9.2-1.fc29.x86_64
```

So i do not know, how to tell the script, that libstrophe is installed.

**Comment by pasis** [comment]
@klm46, in binary distributions such as Fedora, there are devel packages. You need to install something like libstrophe-devel or libstrophe-dev. This package will contain files necessary for building from sources.

**Comment by klm46** [comment]
Thank you @pasis. This was my fault ;)
