### ISSUE TITLE
Auto completion for /sendfile doesn't show new files

### ISSUE THREAD

**Issue by optmzr** [profanity-im/profanity#1099]
Steps to reproduce:
 1. Create a directory with a single file, `test1`.
 2. Start Profanity and write `/sendfile <dir>` and press tab to cycle through the available files.
 3. While Profanity is running, create a new file `test2`.
 4. Re-try step 2, the new file doesn't appear.

Workaround: Do autocompletion for a different directory and then with the original directory, and it'll show the new file.

I guess this is due to this line here:
https://github.com/profanity-im/profanity/blob/883dbe1911766e31e4483eabe713edb89e1eec4f/src/command/cmd_ac.c#L1340

Where the directory won't be re-opened if the `last_directory` matches with the current.

**Comment by jubalh** [comment]
Right, that should be it (thanks for not just reporting but checking this also!!).

I'm not sure what's better: remove that and always check (so it costs more) or leave it as is and have the user search for something else first. The latter is not a very clean solution so probably we should change it.

**Comment by optmzr** [comment]
As `filepath_ac` is reset every time it goes into that `if`-statement, if the `if`-statement is just removed and the user uses tab to cycle through the files, it'll only show the first file in that directory.

One could maybe update `filepath_ac` but keep the current position of the search when `last_directory` and `directory` equals?

I'm kind of unsure about all this, I can look into it more and try to fix it, but I have exams coming up so it will have to wait :)
