### ISSUE TITLE
OMEMO: received untrusted message cause SIGABRT

### ISSUE THREAD

**Issue by vinegret** [profanity-im/profanity#1101]
Profanity crashed, while received new message with untrusted fingerprint.

Profanity, version 0.6.0dev.makepkg.91d17edc .

Build information:
```
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.3)
GTK icons: Disabled
```

Backtrace:
```
#0  0x00007ffff730d82f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff72f8672 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff734fe78 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff735678a in  () at /usr/lib/libc.so.6
#4  0x00007ffff7357eb4 in _int_free () at /usr/lib/libc.so.6
#5  0x00005555555f8342 in omemo_key_free ()
#6  0x00007ffff7ce1acd in g_list_foreach () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff7ce2fcc in g_list_free_full () at /usr/lib/libglib-2.0.so.0
#8  0x00005555555fd1a1 in omemo_receive_message ()
#9  0x000055555559c3e6 in  ()
#10 0x00007ffff74cb819 in  () at /usr/lib/libmesode.so.0
#11 0x00007ffff74c824c in  () at /usr/lib/libmesode.so.0
#12 0x00007ffff74d4bef in  () at /usr/lib/libmesode.so.0
#13 0x00007ffff6269927 in  () at /usr/lib/libexpat.so.1
#14 0x00007ffff626a3cc in  () at /usr/lib/libexpat.so.1
#15 0x00007ffff626c946 in XML_ParseBuffer () at /usr/lib/libexpat.so.1
#16 0x00007ffff74cb115 in xmpp_run_once () at /usr/lib/libmesode.so.0
#17 0x000055555558fb89 in prof_run ()
#18 0x000055555558c104 in main ()
```

Sender use pidgin with lurch 0.6.8

**Comment by jubalh** [comment]
@paulfariello maybe you can take a look.

**Comment by paulfariello** [comment]
@vinegret thanks for reporting.
Unfortunately I don't see anything wrong with the stack trace you provided.
Can you reproduce the segfault with a debug build of profanity. Or even better with valgrind attached?

**Comment by paulfariello** [comment]
Ok I can reproduce a segfault when sending messages with lurch.
@vinegret don't bother with debug or valgrind until I fix that.

**Comment by paulfariello** [comment]
I fix the way we handle incorrect OMEMO messages so we don't segfault anymore.
Anyway I was unable to send correct OMEMO messages with lurch.

@vinegret if you can confirm that lurch messages aren't correctly formated maybe you or your contact should open an issue on lurch.

Profanity log corresponding to OMEMO message deserialization failure is:
```
prof: ERR: OMEMO: cannot deserialize message
```
