### ISSUE TITLE
Profanity won't decrypt  OMEMO messages sent from other clients

### ISSUE THREAD

**Issue by moppman** [profanity-im/profanity#1107]
Profanity Version 0.6.0dev.debian/experimental

- Log into account on profanity, trust all own fingerprints and the buddy's fingerprints
- /carbons on
- log into account on Dino and Converse
- /msg buddy
- buddy can read all my messages from all 3 clients
- Dino and Converse display all messages correctly
- profanity won't decrypt messages sent via Dino or Converse, it only displays the respective fallback message sent by Dino and Converse
- profanity log:
`prof: WRN: Carbon received with no message.`
` prof: ERR: OMEMO: cannot decrypt message: Checksum error `
for Converse carbons and
`prof: WRN: Carbon received with no message.`
` prof: ERR: OMEMO: invalid key length `
for Dino carbons.

**Comment by paulfariello** [comment]
Could you tell us which version of Dino was used?
Testing with latest profanity and Dino, everything seems right.

**Comment by jubalh** [comment]
@paulfariello tested with dino and conversejs.

**Comment by moppman** [comment]
> Could you tell us which version of Dino was used?
> Testing with latest profanity and Dino, everything seems right.

I used Dino 0.0.git20181129-1 (dino-im package from Debian)

**Comment by jubalh** [comment]
Dino had huge changes since 2018 ;)

Please read https://github.com/dino/dino/wiki/Distribution-Packages
It is recommended to use the dino package that I build using OBS: https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino

It is always latest git master.

**Comment by moppman** [comment]
I didn't want to open another issue, but maybe this is relevant:
profanity (git) can't decrypt omemo messages from Converse.Js(6.0.0 and before): 
I'm still seeing a checksum error in the logs thrown by https://github.com/profanity-im/profanity/blob/695694051e2f56d947ea8baf9199c1ff7bf81121/src/omemo/crypto.c#L262

I recently stumbled upon a blog post by the Monal IM dev: https://monal.im/blog/omemo-is-broken-in-general-across-the-ecosystem/
Maybe IV size is part of the problem?

**Comment by paulfariello** [comment]
thanks @moppman for reporting. I can reproduce your issue. Please open a dedicated issue since it seems specific to converse.js.

**Comment by moppman** [comment]
> thanks @moppman for reporting. I can reproduce your issue. Please open a dedicated issue since it seems specific to converse.js.

https://github.com/profanity-im/profanity/issues/1253
