### ISSUE TITLE
Feature request: manage bookmarks also locally

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1115]
Right now profanity respects bookmarks and their set auto-join flag. Using different clients that can be annoying since you might not want all your MUCs autojoind at home, at work or on mobile phone. Therefore other clients offer possibilities of local bookmarkmanagement. What should be done can be discussed here.

- bookmarks that are on the server should be available and autojoined if set
- i still would like to (un)set autojoin on server bookmark
- but also indivually on client side (so others are not affected)

Further ideas or approaches?

**Comment by pasis** [comment]
For me it looks like a reasonable feature. Technically, it should be hard to implement and the question is how it will look for users. Personally I see two options: extend existing `/bookmark` command or add new command and call these local bookmarks as a separated entity. Both options have cons and pros.

**Comment by kaffeekanne** [comment]
I like the way gajim does it. If we keep information locally, that is contradictory to xmpp with its servera itself.

**Comment by ccxcz** [comment]
I think the most straightforward approach here is to have a per-account flag telling us whether to honour the auto-join flag on bookmarks or not, like Conversation does. If disabled one could use e.g. post-connect script to auto-join whichever MUCs and open direct chat windows in order they prefer.

**Comment by jubalh** [comment]
> I like the way gajim does it. If we keep information locally, that is contradictory to xmpp with its servera itself.

And how does Gajim do it?

**Comment by jubalh** [comment]
Seems this is currently discussed here https://mail.jabber.org/pipermail/standards/2020-May/037452.html

**Comment by jubalh** [comment]
Commands will follow. For now you can do:

```
cat ~/.local/share/profanity/bookmark_ignore
[jubalh@domain.org]
profanity@rooms.dismail.de=true

[testuser@domain.org]
testr@rooms.domain.org=true
```

**Comment by jubalh** [comment]
`/bookmark ignore`
`/bookmark ignore add profanity@rooms.dismail.de`
`/bookmark ignore remove profanity@rooms.dismail.de`
