### ISSUE TITLE
Decrypt OMEMO messages before initial trust

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1122]
Right now OMEMO encrypted messages get decrypted only if we trust the sending key fingerprint. I see no harm in decrypting even if we don't trust ouer opponent yet, bcause we only gain information but don't risk anything as we still don't send messages encrypted for that opponents device.

This way somebody can trust our key, send us encrypted messages, that we can read and answer encrypted, if we want to. 

This is not blind trust before verification, BTBV!

**Comment by paulfariello** [comment]
We should at least clearly show that messages are untrusted. Something like red text. Otherwise impersonation is not prevented.

**Comment by jubalh** [comment]
Its possible that the user defined red to be the normal text color for his theme. But I don't know of a better way.
Maybe: Print text red and notice in titlebar too where we currently have [OMEMO] -> [OMEMO untrusted].

**Comment by kaffeekanne** [comment]
i think it can not be [OMEMO untrusted], but [untrusted] alone. [OMEMO] means, we have started an OMEMO session, but has nothing to do with trusting keys. also you can trust one key, but not the other (sending) one.

My idea append/prepend the actual message with [untrusted] because of the mentioned problems. 

Second idea, i like in this context: colorize the encryption/omemo char. green received from trusted device id, red receved from untrusted device id. If we actively stored untrusted device id fingerprints, we cour even use yellow for "not decided" fingerprints. thats how gajim vizualizes fingerprints of new device ids, before sending or not sending encrypted to them. that would chime in nicely with gajims behaviour.

**Comment by optmzr** [comment]
As @kaffeekanne, appending the messages with `[Untrusted]` should be "perfectly" annoying so that the user will make sure to trust the user.
