### ISSUE TITLE
libgcrypt not found despite being installed along with its dev files

### ISSUE THREAD

**Issue by hyphenrf** [profanity-im/profanity#1128]
when building from source, configuring throws this error:
```
configure: error: gcrypt >= 1.7.0 is required for OMEMO support
```
I get this when I run `./configure --prefix=/usr` despite having all the relevant libgcrypt files in place:
```
usr/bin/dumpsexp
usr/bin/hmac256
usr/bin/libgcrypt-config
usr/bin/mpicalc
usr/include/gcrypt.h
usr/lib64/libgcrypt.so -> usr/lib64/libgcrypt.so.20.2.4
usr/lib64/libgcrypt.so.20 -> usr/lib64/libgcrypt.so.20.2.4
usr/lib64/libgcrypt.so.20.2.4
usr/share/aclocal/libgcrypt.m4
usr/share/info/gcrypt.info-1
usr/share/info/gcrypt.info-2
usr/share/info/gcrypt.info
usr/share/man/man1/hmac256.1
```
also `/usr/lib` is symlinked to `/usr/lib64`

any idea what could be causing this error? I tried looking for answers or previous issues but I couldn't find anything that helped.

**Comment by jubalh** [comment]
Which distribution? Which version of libgcrypt is installed?

**Comment by hyphenrf** [comment]
Solus
libgcrypt-config --version => 1.8.4

**Comment by jubalh** [comment]
I have the same version here. Travis shows that it works for Arch, Debian, openSUSE and OS X.
I'm not sure what's special about your case.

**Comment by optmzr** [comment]
Have you looked in `./config.log`, maybe there's some hints there?

Hazem <notifications@github.com> skrev: (14 juni 2019 09:53:18 CEST)
>Solus
>libgcrypt-config --version => 1.8.4
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/profanity-im/profanity/issues/1128#issuecomment-502008253

-- 
MVH/Regards, William Wennerström.
Phone: +46 (0) 707 21 82 10

**Comment by hyphenrf** [comment]
I think it might be best if I let you guys see the config.log file instead of me trying to find relevant debugging info in a file I haven't dealt with before.

https://files.catbox.moe/8k8fv3.log

**Comment by jubalh** [comment]
> /usr/bin/ld: cannot find -lassuan

Maybe try installing libassuan

**Comment by bitkeks** [comment]
Same on my system, with libgcypt 1.8.4 installed. Didn't we talk about this in the MUC @jubalh? There's probably a bug in the error output, because it's not missing libgcrypt, but the OMEMO lib.

@hyphenrf in your logs, `LDFLAGS=''` seems to indicate you have not set `LDFLAGS`. If I reproduce this with `./configure` I get 

```
checking for gcry_md_extract in -lgcrypt... no
configure: gcrypt >= 1.7.0 not found, OMEMO support not enabled
```

The fix for me was to use `export LDFLAGS=-L/tmp/omemo/usr/lib/` where `/tmp/omemo` is the `make install` target dir for libsignal-protocol-c.

```
checking for libsignal... yes
checking for gcry_md_extract in -lgcrypt... yes
```
This is even more necessary when compiling with `--enable-omemo`. In summary, for me the following env vars are needed to configure profanity for OMEMO usage:

```
libsignal_CFLAGS=-I/tmp/omemo/usr/include/
libsignal_LIBS=-L/tmp/omemo/usr/lib/
LDFLAGS=-L/tmp/omemo/usr/lib/
```

**Comment by jubalh** [comment]
To me:
```

    AC_CHECK_LIB([gcrypt], [gcry_md_extract],
        [LIBS="-lgcrypt $LIBS"],
        [AM_CONDITIONAL([BUILD_OMEMO], [false])
         AS_IF([test "x$enable_omemo" = xyes],
               [AC_MSG_ERROR([gcrypt >= 1.7.0 is required for OMEMO support])],
[AC_MSG_NOTICE([gcrypt >= 1.7.0 not found, OMEMO support not enabled])])])
```

looks correct. @paulfariello what do you think?

**Comment by paulfariello** [comment]
I don't see any error in the AC_CHECK_LIB but clearly the build test for gcrypt is failing to compile:
```
   611 /usr/bin/ld: cannot find -lassuan                                               
   612 collect2: error: ld returned 1 exit status                                      
   613 configure:12797: $? = 1                                                         
```
@jubalh is right, in order to have a quick fix you should install `libassuan`.
Maybe we should avoid to link with `$LIBS`.

**Comment by hyphenrf** [comment]
> Maybe try installing libassuan

I'll try this first and report back

> could you try to compile without `--enable-omemo` or even with `--disable-omemo`?

I can try sure, but I'm attempting to build this project from source just because profanity in the repos is built _without_ OMEMO support.

@bitkeks I'm not sure I understand your proposition. Indeed I didn't specify LDFLAGS but that's because my libraries (that includes libsignal-protocol-c) exist in the standard /usr/lib and /usr/include locations. And ./configure managed to find libsignal-protocol-c just fine.
```
/usr/lib/libsignal-protocol-c.a
/usr/lib/pkgconfig/libsignal-protocol-c.pc
/usr/include/signal/curve.h
...
```

**Comment by hyphenrf** [comment]
alright guys configuring after installing libassuan-dev worked

**Comment by jubalh** [comment]
>  the error message was a bit misleading I have to admit haha

I think `/usr/bin/ld: cannot find -lassuan` was not misleading :)

**Comment by hyphenrf** [comment]
I was referring to the configure output complaining about a completely different library (libgcrypt). That was misleading
That being said, do you thing libassuan-dev should be added as an optional dependency, for clarity's sake?

**Comment by jubalh** [comment]
>  That being said, do you think libassuan-dev should be added as an optional dependency, for clarity's sake?

I'm currently thinking about that. I don't know yet when it's needed and when not, so that we only add it in a certain case. If anybody has knowledge about this: PRs welcome! :)

**Comment by pasis** [comment]
AC_CHECK_LIB() simply tries to link a simple program which calls required function from the main(). If such a symbol exists in the library linking succeeds, otherwise linking fails because of unresolved symbol. But (!) autotools also adds variable `LIBS` to linker.

So, for example, if you have `LIBS='-lassuan'` and you check for `-lgcrypt`, the final string will be something like `ld test.o -lgcrypt -lassuan`. The problem here is that `LIBS` is incorrect and causes troubles with linking. So, autotools report an error and Profanity's configure prints a hardcoded message that gcrypt doesn't exist.

Now, why is `LIBS` incorrect? We need to find where `-lassuan` gets there first. Maybe via `pkg-config`. And check if something missed there.

**Comment by paulfariello** [comment]
@pasis I suppose it comes from pkg-config of GPG.

My point was that if build fails even without OMEMO it means that the error of missing `libassuan` should be reported sooner. Somewhere around tests for GPG.

btw it's not autotools that adds `LIBS` to the linker, it's us in
```
AC_CHECK_LIB([gcrypt], [gcry_md_extract],
        [LIBS="-lgcrypt $LIBS"],
```

**Comment by hyphenrf** [comment]
> don't know yet when it's needed and when not

> I suppose it comes from pkg-config of GPG.

Well, I'm open to test anything since this case can be reproduced on my system. Just tell me where to look and I'll report back.
