### ISSUE TITLE
main.text.them has no effect in omemo chat

### ISSUE THREAD

**Issue by c-alpha** [profanity-im/profanity#1138]
## Expected Behavior

The color configured in a theme for `main.text.them` should be used for rendering incoming text from peers, including in OMEMO chats.

## Current Behavior

Message text from peers in OMEMO chats are always rendered in red.

`me`, `them`, and `main.text.me` work as expected, including in OMEMO chats.

## Steps to Reproduce (for bugs)

1. start an OMEMO chat
2. modify the `main.text.them` parameter in a theme
3. `/theme load ...`
4. observe test message colour of messages from the peer
5. go to step 2

## Context

A fixed text colour can adversely affect readability an deye strain, depending on the other colour settings. Also, the effect of the `main.text.them` parameter should be orthogonal, i.e. the same in all types of chats.

## Your Environment
* Give us the version and build information output generated by `profanity -v`
  * Profanity, version 0.6.0dev.master.165602e
* Operating System/Distribution
  * macOS 10.14.5 (18F132)
  * iTerm2 3.2.9

**Comment by jubalh** [comment]
Thanks for the report @c-alpha.
Did you trust the keys of your partner?
Just recently, in https://github.com/profanity-im/profanity/pull/1126, @paulfariello implemented that untrusted OMEMO messages are decrypted but shown in red.
This will be added to documentation later, but since it's only on master it's not in there yet.

**Comment by c-alpha** [comment]
> Did you trust the keys of your partner?

Yes, all of them. But messages still show in red.

> Just recently, in #1126, @paulfariello implemented that untrusted OMEMO messages are decrypted but shown in red.
> This will be added to documentation later, but since it's only on master it's not in there yet.

I see.

Here is what I **think might** be happening: in addition to profanity, I am also logged into the same account from a mobile client (ChatSecure). My contact sends his messages encrypted to both instances (the desktop me and the mobile me). But the desktop me doesn't know about the certs of the mobile me (because they never talk to each other), and vice versa. Hence, from profanity's point of view, untrusted certs (those belonging to the mobile me) are involved, and consequently the text is rendered in red? Just my two cents anyway...

**Comment by jubalh** [comment]
Yesterday @paulfariello created a new pull request: https://github.com/profanity-im/profanity/pull/1137
Which is about marking messages received from a session as trusted.

You tested with 165602e5c705cd73f83c32b1333ab7258c4d54b2. Can you please test again with latest master 9f813445b719ed0201a432c3c6a7dfeceaa5da83.
I think this could fix it.

**Comment by c-alpha** [comment]
> [...]
> You tested with [165602e](https://github.com/profanity-im/profanity/commit/165602e5c705cd73f83c32b1333ab7258c4d54b2). Can you please test again with latest master [9f81344](https://github.com/profanity-im/profanity/commit/9f813445b719ed0201a432c3c6a7dfeceaa5da83).
> I think this could fix it.

That fixes it indeed. Many thanks!

If you want to keep this one open as a reminder for the documentation update, that'd be fine by me. Otherwise feel free top close.
