### ISSUE TITLE
OMEMO encryption failure

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1140]
Not sure why this happens in my current test.

## Expected Behavior
Be able to read OMEMO messages.

## Current Behavior
Can't read them.

## Possible Solution
Did the key not get published?

## Steps to Reproduce (for bugs)
1. sign in as user1@test.org in profanity (has already omemo material)
2. sign in as user2@test.org in another profanity instance (new users)
3. as user2: /omemo gen
4. as user2: /omemo start users1@test.org
5. as user2: /omemo trust fingerprintofuser1
6. as user2: write a message
7. user1 receives: user2@test.org/profanity.aTGD: You received a message encrypted with OMEMO but your client doesn't support OMEMO.
8. as user1 (in chat window): /omemo fingerprint
9: user1 receives: There is no known fingerprints for user2@test.org
10. as user2 (in console window): /omemo fingerprint

```
10:46:12 - Your OMEMO fingerprint: 038c7bc2-28b736ac-edd21095-7fd0072e-9fa07c29-801d52b5-c629df80-3afe1a56
10:46:12 - There is no known fingerprints for user2@test.org
```

## Your Environment
0.6.0dev.master.684fdf68
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16)
GTK icons: Enabled

**Comment by kaffeekanne** [comment]
So i worked through your "playbook" and it all worked fine. On step 7 client 1 received the message from client 2, decrypts it and paints it red, because i did not trust client 2 before. Checking `/omemo fingerprint` shows that client 1 knows about the key of client 2, but did not trust him.

I did that on ejabberd, pretty recent stable. If you need any more information, just ping me.

**Comment by jubalh** [comment]
Thanks a lot for testing. I'm not sure why it happened for me, whether I did something wrong or whether its a very special case. I'll close this for now.
