### ISSUE TITLE
Offline MUC participants see "Message was not encrypted for this device."

### ISSUE THREAD

**Issue by vacuumbeef** [profanity-im/profanity#1143]
## Current Behavior

Everything with OMEMO ON and with all devices trusted:
MUC participants who was offline when messages from profanity was sent, after going online will see "Message was not encrypted for this device." instead of those messages. And while they are online, messages from profanity will decrypt for them as it should be. 

## Steps to Reproduce (for bugs)

In MUC with more than 2 participants with trusted devices:
1. Participant X must go offline.
2. You are sending some messages from Profanity
3. Participant X goes online and gets "Message was not encrypted for this device." instead of those messages.

## Environment

Profanity, version 0.6.0dev.master.9f813445
Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.3)
GTK icons: Enabled

**Comment by jubalh** [comment]
Does Participant X also use profanity?

**Comment by vacuumbeef** [comment]
@jubalh No, sorry, I should have specify it.

**Comment by jubalh** [comment]
@paulfariello any ideas? :)

@vauumbeef, please ask your contact the fingerprint of his device. And then check if its also trusted.
I think it could be that  you trusted all keys, but that this specific key got not listed and thus would not be trusted. In this case the retrieving of all keys would be wrong in profanity. If you check this it would be helpful for us.

**Comment by vacuumbeef** [comment]
@jubalh Unfortunately, no, everything is okay with fingerprints.

**Comment by jubalh** [comment]
That's a shame. Otherwise I would have guessed it's related to https://github.com/profanity-im/profanity/issues/1140

**Comment by kaffeekanne** [comment]
This sounds like a known issue in #1070:
>  OMEMO MUC should encrypt to all jid present in affiliation. Not only those currently connected.

At the moment we have a technical limitation in profanity that we can only get JIDs of currently online users in a MUC. So before we can encrypt to all occupants (online and offline) some heavier works needs to happen in profanity. Until then OMEMO in 1:1 chats is stable and MUC is considered experimental.

**Comment by jubalh** [comment]
Thanks @kaffeekanne. I'll move this to 0.8.0.
Also on https://profanity-im.github.io/omemo.html we wrote `We consider OMEMO MUC as experimental. You might encounter problems there. Make sure to check our tracker bug for details. ` so hopefully that helps.

**Comment by jubalh** [comment]
PR 1242 should fix this. Everybody please test this and give feedback here.
