### ISSUE TITLE
CentOS7 profanity 6.0 compilation failure

### ISSUE THREAD

**Issue by reardenlife** [profanity-im/profanity#1152]
* profanity-0.6.0

```bash
checking for libmesode >= 0.9.2... no
checking for libstrophe >= 0.9.2... no
configure: error: Neither libmesode or libstrophe in version >= 0.9.2 found, either is required for profanity
Error 1 with command './configure' on line 100. Exiting.
```

Huh?

The installation script was:

```bash
wget --no-clobber https://github.com/strophe/libstrophe/archive/master.zip
unzip master.zip

cd libstrophe-master
./bootstrap.sh
./configure
make
make install
cd ..
rm -rf libstrophe-master
rm -f master.zip

wget --no-clobber http://www.profanity.im/profanity-0.6.0.zip
unzip profanity-0.6.0.zip
cd profanity-0.6.0
wget http://www.profanity.im/install-all.sh
chmod u+x install-all.sh
./install-all.sh
cd ..
rm -rf profanity-0.6.0
rm -f profanity-0.6.0.zip
```

**Comment by reardenlife** [comment]
Going to switch to 5.1 then.

**Comment by reardenlife** [comment]
Not sure what to do..

**Comment by optmzr** [comment]
Concerning the first issue: Have you looked in `./config.log` after the compilation failure?
Would be nice if you could post the content of the file on https://paste.dismail.de/ or some other pastebin.

**Comment by optmzr** [comment]
Are you using a key ID, like `63C1CF3264BDC8E384D33629E1382990BEDD319B` or you mail address/user ID when running `/pgp setkey`? 

I've not used GPG in a while but I think I used the key ID. :)

**Comment by reardenlife** [comment]
2 @optmzr
> Are you using a key ID, like 63C1CF3264BDC8E384D33629E1382990BEDD319B or you mail address/user ID when running /pgp setkey?

I am using key ID, which I copied from the output of:
```bash
gpg --list-key --key-id-format=LONG
```
which outputs the same keyids as profanity's /pgp keys


Just reconnected to my old account and tried /pgp setkey ...
... it worked.

**Comment by reardenlife** [comment]
Oh.  I had to do /account set pgpkeyid for my new account.  I was doing it wrongly, through /pgp setkey. :)
The error message could be more helpful, though.

**Comment by reardenlife** [comment]
@ optmzr

> "Concerning the first issue: Have you looked in ./config.log after the compilation failure?"

Well, no.  I looked into the output of the install-all.sh and tried to use google, which was unsuccessful.

The log is here:

https://da.gd/LhdN -> https://paste.fedoraproject.org/paste/9R36ODrFxNUTc32Xulr6Aw/

**Comment by optmzr** [comment]
Ah! Of course, you set the key for your contact! :) 

Maybe (probably) `pkg-config` doesn't look in `/usr/local`, could you try to install libstrophe into `/usr` with:
```
wget --no-clobber https://github.com/strophe/libstrophe/archive/master.zip
unzip master.zip

cd libstrophe-master
./bootstrap.sh
./configure --prefix=/usr  # <---- This
make
make install
cd ..
rm -rf libstrophe-master
rm -f master.zip

...
```

**Comment by reardenlife** [comment]
@optmzr

I looked into the log now and I see that there is a problem with a version of libmesode.  I looked into the installation directory of profanity and found 0.9.1 version of that library.  Strange.  Lets build 0.9.2 and see what happens.

**Comment by optmzr** [comment]
> ... The error message could be more helpful, though.

Indeed, it should say that no key has been set instead.

**Comment by optmzr** [comment]
@reardenlife 
> I looked into the log now and I see that there is a problem with a version of libmesode. I looked into the installation directory of profanity and found 0.9.1 version of that library. Strange. Lets build 0.9.2 and see what happens.

FYI both `libmesode` and `libstrophe` will work, as `libmesode` is just a fork of `libstrophe`, so you only need one of them installed :)

**Comment by reardenlife** [comment]
Huh.  I found this line in the install-all.sh in the libmesode install function:

```bash
git checkout 0.9.1
```

Though the installator later checks if 0.9.2 is present. :)
Let me comment it out and restart the installer...

**Comment by reardenlife** [comment]
Well, yeah.
There seems to be a problem at http://www.profanity.im/install-all.sh , it requests the wrong version.

**Comment by optmzr** [comment]
Aha!

Yes, the site http://www.profanity.im is outdated (see: https://profanity-im.github.io/ instead).
We're currently unable to redirect (at least I think so) to the Github pages variant. 

It should be updated on the other site, though:
https://github.com/profanity-im/profanity-im.github.io/commit/558c45d41f638ca3c21586c14b0ec8ea1dc24b2a

**Comment by jubalh** [comment]
The original author of profanity owns http://www.profanity.im 
The plan was for him to forward from there to the new GitHub hosted domain. Seems he didn't yet have time to do so :)
I encourage everybody to use the new URL since it's the only one we have access too ourselves without delay.
