### ISSUE TITLE
Save preferences only when explicitly asked to

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1164]
Currently profanity saves the preferences whenever you change them.
For example `/roster resource char X` will change it to X and save it to your `profrc` file.

I think it would make sense to only change it. And have a separate command `/save` for saving the currently set preferences. Then users could experiment with various settings but revert back easily (by quitting without saving), without first backing up their configuration file.

**Comment by kaffeekanne** [comment]
I like my settings being stored immediatly, althoug i understand your thoughts. I would forget to save/commit my changes or even not notice i changed something and wonder why profanity acts differently the next time i start it.

What do you think about profiles? If one wants to test some changes, create another profile switch to it and test. Or save the current state in another profile and test in the main profile.

**Comment by jubalh** [comment]
I think most applications have a 'apply changes/settings' button.
