### ISSUE TITLE
dozens of open windows on connect for subscribed contacts

### ISSUE THREAD

**Issue by claviola** [profanity-im/profanity#1165]
When I connect to a server I get a new window for every single subscribed contact in my roster with the same text:

```
01/08/19 13:10:54 - *joe.foo@domain.com Subscribed
```

All my presence settings are off:

```
13:15:17 - Titlebar presence (/presence)       : OFF
13:15:17 - Console presence (/presence)        : none
13:15:17 - Chat presence (/presence)           : none
13:15:17 - Room presence (/presence)           : none
```

It might be unrelated, but whenever I connect I always get lots of "subscription received from..." notices:

```
13:15:58 - Connecting with account booking as carlos.laviola@domain.com/Lappy
13:15:58 - carlos.laviola@domain.com/Lappy logged in successfully, online (priority 0).
13:15:58 - Subscription received from joe.foo@domain.com
13:15:58 - Subscription received from jay.foo@domain.com
13:15:58 - Subscription received from jon.foo@domain.com
13:15:58 - Subscription received from jan.foo@domain.com
13:15:58 - Subscription received from jen.foo@domain.com
```

This makes it very hard to actually find a new chatroom window once I join them.

**Comment by jubalh** [comment]
I updated your comment to format it properly. Because without it it's actually hard to read ;)

**Comment by jubalh** [comment]
The solution to your problem is to actually deny or accept the subscription requests.

```
13:15:17 - Titlebar presence (/presence)       : OFF
13:15:17 - Console presence (/presence)        : none
13:15:17 - Chat presence (/presence)           : none
13:15:17 - Room presence (/presence)           : none
```

These have nothing to do with subscription.

**Comment by claviola** [comment]
Are these requests? In Pidgin I do not get any kind of notification. Usually when a contact adds me I receive one and approve or deny. Since I see about 70 people in new windows it seems like it's my entire buddy list too.

**Comment by claviola** [comment]
As I suspected, these don't seem to be pending subscriptions -- `/sub received` shows:

`13:38:22 - No outstanding subscription requests.`

**Comment by jubalh** [comment]
```
01/08/19 13:10:54 - *joe.foo@domain.com Subscribed
```

this is put out in `sv_ev_subscription()` this is only run if the subscription handler in `src/xmpp/presence.c` kicks in.

If you restart profanity does the same happen again?
Which server (and version) are you using?

**Comment by claviola** [comment]
The server is Cisco Jabber, I am not sure about the version as I don't administer it. I can try to inquire, though. Locally I'm running Profanity 0.7.0.

It does happen consistently after restarts.

**Comment by claviola** [comment]
Asking the server nicely through raw XMPP I get this:

```
	<query xmlns='jabber:iq:version'>
		<name>tc</name>
		<version>5.9.2.53979</version>
	</query>
```

**Comment by jubalh** [comment]
My guess is that this is due to Cisco Jabber. I don't think it is compatible with XMPP.
You could start profanity with `profanity -l DEBUG`.
And show the output of $XDG_DATA_HOME/profanity/logs/profanity.log to us. Make sure to hide private information.

**Comment by jubalh** [comment]
@claviola can you build from the `fix/1165-subscribed-msg` branch and see if that is better? Since I don't have access to a Cisco Jabber server I need your help testing it.

**Comment by jubalh** [comment]
@claviola if you need help building from that branch let us know.

**Comment by claviola** [comment]
After a look at #903 I managed to get it built, but I still see the issue. Passing `-l DEBUG` didn't really seem to affect anything either (I don't see a `~/.config/profanity/profanity.log`).

The running version:
`11:16:24 - Version 0.7.0dev.fix/1165-subscribed-msg.658e36a0`

**Comment by claviola** [comment]
So I just noticed that 53c31159769296a9797da6653bc070b9467f3c08 isn't actually in that branch. I'm cherry-picking it and trying again.

**Comment by claviola** [comment]
Yep, this works. I only see a ton of spam in the console as expected, but no windows are created.

**Comment by jubalh** [comment]
> Yep, this works. I only see a ton of spam in the console as expected, but no windows are created.
