### ISSUE TITLE
OTR Backup for Omemo

### ISSUE THREAD

**Issue by beli3ver** [profanity-im/profanity#1168]
Good morning,

is there a way to say profanity, when a contact has no omemo support to use otr or pgp instead?

Thanks

**Comment by jubalh** [comment]
No, you need to specify the encryption method.

**Comment by beli3ver** [comment]
OK. Could this maybe implemented in the next version.

Am 3. August 2019 08:45:48 MESZ schrieb Michael Vetter <notifications@github.com>:
>No, you need to specify the encryption method.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/profanity-im/profanity/issues/1168#issuecomment-517900171

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jubalh** [comment]
I don't think thats something valuable.
If you settle of an encryption method you need to check keys etc. We want people to check this, and not have everything just start itself.

Also I'm not sure if all encryptions are detectable.
And it will create many new cases and settings for users that want to have OMEMO as primary, OTR as second. OTR as first and PGP as backup...

I just think that it's much easier to just select this yourself, don't see what's bad about it.

**Comment by beli3ver** [comment]
Ok.
Thanks for your work.
