### ISSUE TITLE
allow colorization of chatroom history

### ISSUE THREAD

**Issue by claviola** [profanity-im/profanity#1170]
All messages I receive have no colorization (either in names/nicknames or for the messages themselves).

I believe this has something to do with the server I'm connecting to somehow sending messages in a way that makes clients believe they are receiving messages from the chatroom's history instead of "live". I also see this behavior with my own messages, as I get a new identical message in the room immediately after the one I actually wrote, and the first one actually is in color (different ones for the timestamp, nickname and message).

Note that none of this happens in the other client I use, though (Pidgin).

**Comment by jubalh** [comment]
You can use `main.text.history` in your theme files now.
Both nick and text that comes from history will be printed with the same color.
