### ISSUE TITLE
Add e-mail adress to contact information in source code

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1171]
According to your recent addition of your e-mail adress to the website, you might want to add it to the source too, @jubalh. 

https://github.com/profanity-im/profanity/blob/d8d6aa4b888a6a19133e5a48a32387451afdca44/docs/profanity.1#L60-L66

In the man page for example! Probably there are other places.

**Comment by jubalh** [comment]
Actually I wanted to leave the man page as it is. And in source code I think it's displayed at proper locations.
