### ISSUE TITLE
OMEMO does not function for all intents and purposes

### ISSUE THREAD

**Issue by IamPARANOID** [profanity-im/profanity#1176]
## Expected Behavior

Should display **_ALL_** fingerprints for the given ""JID"".
## Current Behavior

It does not display the fingerprint for one user, unless run as itself, where it gives a fingerprint but still gives the error ``There is no known fingerprints for seconduser@host``.
If seconduser runs ``/omemo fingerprint firstuser@host``, then it gives ONLY the fingerprint for a different associated device (**_NOT_** Profanity).

## Possible Solution

1. "seconduser" has "tls trust" set, as they connecting essentially from localhost, could this be why they have no fingerprint (can't easily solve this, though, without faking some different IPs)?
2. ``sudo prosodyctl deluser`` the first JID to get rid of the other device, then OMEMO would have no choice but to display the correct one (though it should be displaying **_BOTH_**, no)?

## Steps to Reproduce (for bugs)

1. Setup a LAN only Prosody server, with self signed certs (no one uses Let's Encrypt for a LAN afaik).
2. Create 2 users, second and first users.
3. Login as first user, from Conversations.im "app" on a mobile device, then after on a regular PC from Profanity.
4. Login as second user on the same machine as the server.
5. Set both accounts as default on each respective Profanity.
6. Despite using Prosody to generate certs for both ``localhost`` & ``127.0.0.1``, seconduser still has trouble logging in (it still has cert issues), so ``/account set seconduser@host tls trust``
7. Generate OMEMO on each respective Profanity.
5. As second user, ``/omemo fingerprint firstuser@host``, which gives the fingerprint of Conversation.im's login.
6. As first or second user, do ``/omemo fingerprint seconduser@host``, resulting in ``There is no known fingerprints for seconduser@host``.

This is great if seconduser **_ONLY_** wants to talk to firstuser on Conversations, but **_NOT_** Profanity to Profanity.

## What are you trying to accomplish?

A basic LAN XMPP setup with functional OMEMO.

## Environment
* Give us the version and build information output generated by `profanity -v`
```
Profanity, version 0.7.0dev.makepkg.d8d6aa4b
Copyright (C) 2012 - 2019 James Booth <jubalh@iodoru.org>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.4)
GTK icons: Enabled
```
* Mention the revision you try to build from
``yay -S profanity-git``
* Operating System/Distribution
Artix Linux (both computers), LineageOS (mobile)
* glib version
2.29

**Comment by jubalh** [comment]
@paulfariello will take a look once he finds time :-)

**Comment by paulfariello** [comment]
@IamPARANOID Thanks for reporting.

Could you do the following test and tell me if you have the bug.

1. Create both users
2. Generate firstuser@'s OMEMO key on Conversation
3. Generate firstuser@'s OMEMO key on Profanity
4. **Only then**, start profanity with seconduser@
5. Run /omemo fingerprints firstuser@

Thanks,

**Comment by IamPARANOID** [comment]
>Thanks for reporting.

@paulfariello Sure thing, thank you!

>1. Create both users

Done.

>2. Generate firstuser@'s OMEMO key on Conversation

It seems there is no direct button/command for this in Conversations, but there is an option in Settings->Expert Settings for "Delete OMEMO Identities", which then shows a check box for firstuser@host, heavily implying that it automatically generated one.  
I will move on and count this as having completed step 2.

>3. Generate firstuser@'s OMEMO key on Profanity

Done.

>4. **Only then**, start profanity with seconduser@

I assume by "start" you mean "connect", as I already had it open (lol).
If so, done.

>Run /omemo fingerprints firstuser@

I assume you mean to run this command as ``seconduser@host``.
Command not found, assuming typo and removing the s from "fingerprints".
In which case, it will not allow me to do so, saying:
 ``You have not generated or loaded a cryptographic materials, use '/omemo gen'``
After doing this (generating them), and running ``/omemo fingerprint firstuser@host`` again, I get ``There is no known fingerprints for firstuser@host``.
If I do this command as firstuser, & not as seconduser, it shows both of them correctly.

**Comment by IamPARANOID** [comment]
Just re-tested to see if Conversations had anything to do with this, it does not.
I dropped all tables on the database, removed ``.local/share/profanity`` and re-gened the keys with a new user.  Now neither profanity instances can see each other's keys.

Similar to #1140, except no keys to trust in the first place.

**Comment by immae** [comment]
(I think my issue is same as this one, please tell me if I’m wrong I’ll post it elsewhere)

I have three clients (namely profanity, converse.js and -Android- Conversation). I tried many combination between those client, and they always work correctly, except for the profanity <-> converse.js part which never works.

More precisely, I can sometimes sent a message from profanity to converse.js, but never the other way (I always get a "This is an OMEMO message bla bla"). Every other combination (even with two resources connected to the same account) work seamlessly. I don’t really know how to debug that, but I can provide more information if you tell me what I can try.

NB: all my accounts are on the same server, but I don’t think it’s a relevant information

**Comment by cockroach** [comment]
I seem to be having the same issue: two instances of profanity, both built with OMEMO support, connected to the same server but they can't seem to talk to one another, both keep showing the "You received a message encrypted with OMEMO [..]" message.

Also, I keep getting the error "There is no known fingerprints for [..]" when I try /omemo fingerprint (right after it shows my fingerprint).

Could it be that there is something missing on the server? I'm running prosody there.

**Comment by immae** [comment]
It’s normally transparent for the server provided that it supports `XEP-0060 Publish-Subscribe` (which prosody seem to according to https://en.wikipedia.org/wiki/Comparison_of_XMPP_server_software )

In my case, I "kind of" worked around the issue by deleting every keys attached to my account (you need access to the server pubsub storage for that I don’t know if there are facilities to do that in a nice way), then starting profanity + generating keys, and only then opening other clients. But the solution is very fragile

**Comment by cockroach** [comment]
Interesting, thanks. I don't think I currently have pubsub enabled on my prosody instance, at least I can't find it anywhere in the configuration. I'll check whether that makes a difference...

**Comment by cockroach** [comment]
Now it seems to work. I'm not sure whether it was a pubsub issue, profanity's error messages are also a bit confusing. Apparently, the message "You received a message encrypted with OMEMO but your client doesn't support OMEMO." can also mean "Your client is working just fine but you will need to /omemo trust this person" :)

**Comment by jubalh** [comment]
"You received a message encrypted with OMEMO but your client doesn't support OMEMO."  is not an error message. It's what is send in the stanza body in case the message is not encrypted. Various clients send different stuff here.

BTW, did you read https://profanity-im.github.io/guide/070/omemo.html ? It tells you that you need to trust keys. General understanding of the process is required for it to work :-)

**Comment by cockroach** [comment]
Indeed I _did_ read that and it makes perfect sense that I have to trust the keys, and if there had been a warning about untrusted keys or something I would have known what to do and I wouldn't have come here, posting in someone else's bug :)

But to my untrained eye it looked as if profanity somehow failed to understand the OMEMO message, thus the confusion. But it's all good now, just ignore everything I posted.

**Comment by jubalh** [comment]
It's no problem at all. I'm glad to know that you think the documentation is ok. If you see room for improvement we are happy to adapt it with your suggestion. Or you can file a pull request at https://github.com/profanity-im/profanity-im.github.io

**Comment by jubalh** [comment]
Several OMEMO issues got fixed recently. Mostly by @paulfariello.
This issue is written very strangely, it's hard to understand what the actual problem is.
I'll close this. If there is still something not working for your please check if there is already an open issue for it, and if not create a new one. A well formulated one.. ;)
