### ISSUE TITLE
Upgrade profanity via homebrew does not upgrade to 7.0 

### ISSUE THREAD

**Issue by Bedrovelsen** [profanity-im/profanity#1182]
When using homebrew to upgrade from 0.6.0 to the latest version 0.7.0 it does not work and thinks the currently installed 0.6.0_2 is latest when running

## Expected Behavior
```
brew upgrade profanity
```
Installs 0.7.0 

```
#> profanity -v
Profanity, version 0.7.0
```

## Current Behavior
```
#> profanity -v
Profanity, version 0.6.0

#> brew upgrade profanity
Error: profanity 0.6.0_2 already installed
```

## Possible Solution
Make the latest release included in the default profanity homebrew tap or provide a 0.7.0 variant of current homebrew install steps. not sure

## Steps to Reproduce (for bugs)
Have profanity installed via homebrew already

```
#> brew upgrade profanity
```

## Context
Trying to upgrade to latest version on OS X with homebrew

## Environment
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1)
C plugins: Enabled
Python plugins: Enabled (2.7.10)

Mac OS 10.14.6

**Comment by jubalh** [comment]
And why don't you file this in homebrew s bugtracker?

**Comment by Bedrovelsen** [comment]
> And why don't you file this in homebrew s bugtracker?

Due to being unsure if the expectation for brew upgrade/install of profanity is to upgrade/install version 0.7.0 or if 0.7.0 was not as of yet part of the brew installation method in which case this would be normal behaviour. 

So I assume your response is indicating that using the brew install/upgrade profanity command should install the latest profanity 0.7.0? If that is the case I have no issue doing further tinkering on the side of homebrew and you can close this issue.

 Thanks.

**Comment by pasis** [comment]
@Bedrovelsen , As I see in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/profanity.rb`, this formula installs 0.6.0. It should be updated by Homebrew project (perhaps, there is a maintainer for the profanity formula).

**Comment by jubalh** [comment]
> Due to being unsure if the expectation for brew upgrade/install of profanity is to upgrade/install version 0.7.0 or if 0.7.0 was not as of yet part of the brew installation method

**Comment by tschoonj** [comment]
@Bedrovelsen I recommend you open a PR in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) to update profanity to 0.7.0.

**Comment by Bedrovelsen** [comment]
> @Bedrovelsen I recommend you open a PR in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) to update profanity to 0.7.0.

Okay, submitted (Still WIP from some bundler gem install issues during brew audit stage 
https://github.com/Homebrew/homebrew-core/pull/43789

**Comment by jubalh** [comment]
@Bedrovelsen PR got merged as https://github.com/Homebrew/homebrew-core/commit/ff29ea45a26f8d7f2c71dd2f38ecc2f188fd7722

So I'll close this.
