### ISSUE TITLE
Improve MUC 1:1 logging

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1184]
## Expected Behavior
`/grlog on` should enable MUC logging.

## Current Behavior
No new files in `~/.local/share/profanity/chatlogs/account-name/channel-name`.

## Possible Solution
On a test machine the last log was from August 2019. Let's check the commits since then.

## Context
Encountered when testing https://github.com/profanity-im/profanity/issues/1181

**Comment by jubalh** [comment]
I was wrong :-)
Location is not `~/.local/share/profanity/chatlogs/account-name/channel-name/2019_08_02.log` but it is: `~/.local/share/profanity/chatlogs/account-name/rooms/channel-name/2019_08_02.log`.

So the MUC messages are in the `rooms` subfolder.
However profanity creates the `~/.local/share/profanity/chatlogs/account-name/channel-name/2019_08_02.log` too. They actually contain MUC 1:1 messages.

So for example Martin messages me via MUC 1:1 and in profanity I see:

```
Wed 10:23:23 AM - profanity@rooms.dismail.de/Martin: Hi
```

The log file will then be: `.local/share/profanity/chatlogs/my-account-at-server/profanity_at_rooms.dismail.de/2019_09_04.log` and look like:

```
10:48:13 - profanity@rooms.dismail.de: Hi
```

So one has no idea who actually sent this message retrospectively.

**Comment by jubalh** [comment]
Seems there is no nice solution. Since from the `from` field we don't know whether its a regular message from `user@server.org/resource` or `room@server.org/user`.

So we could compare the barejid against the list of joined channels. But doing this for every message sounds wasteful to me. And it could be that we get such a MUC PM without being in the MUC..

@weiss advised to check for `<x xmlns='http://jabber.org/protocol/muc#user' />` which clients *should* send.

(Also have to remember to check whether we send it..)

**Comment by kaffeekanne** [comment]
where would you want to store MUC PMs when the "how" is resolved? In case of your example `.local/share/profanity/chatlogs/my-account-at-server/profanity_at_rooms.dismails.de_<nickname>/2019_09_04.log` or somewhere in `.../rooms/...`?

**Comment by jubalh** [comment]
@kaffeekanne `~/.local/share/profanity/chatlogs/my-account-at-server/profanity_at_rooms.dismail.de_nick`
