### ISSUE TITLE
Use consistent color generation for nicks (XEP-0392)

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1191]
## Expected Behavior
Have a consistent color for nicknames (etc).

## Current Behavior
Use the color defined in the theme.

## Solution
We should implement [XEP-0392](https://xmpp.org/extensions/xep-0392.html).

**Comment by mdosch** [comment]
Right now profanity shows the online status by color of the nickname in the occupants list. Will this behavior remain?
I could imagine to keep a fixed color depending on the online state in the occupants list to prevent it from looking like a rainbow but use the consistent nickname colors in the message area.

**Comment by jubalh** [comment]
Good point. Your suggestion makes sense. I can also see me implementing it as a setting.

**Comment by mdosch** [comment]
According to the XEPs business roules it SHOULD be optional anyways:

* Implementations SHOULD allow the user to turn off any colorization 
 completely.
*Implementations SHOULD implement the Color Vision Deficiency profiles 
and SHOULD allow the user to choose any of these profiles or to disable 
the correction.
* Implementations MUST NOT share the Color Vision Deficiency correction 
settings with other entities.

**Comment by jubalh** [comment]
Which means generally turning of this color feature, not individual for the roster/occupants.

**Comment by jubalh** [comment]
Colors for the roster and occupants can now also be enabled!
