### ISSUE TITLE
User messages double logged in MUC logs

### ISSUE THREAD

**Issue by Shungy** [profanity-im/profanity#1201]
* Enable MUC logging
* Write something
* Check the log file
* What you write is double-logged

v. 0.7.1

**Comment by jubalh** [comment]
We log both outgoing MUC messages and incoming MUC messages.
Logging only the latter should suffice.

**Comment by jubalh** [comment]
With the current fix we also filter out messages sent from ourselves by other clients.

**Comment by jubalh** [comment]
To solve this nicely we will need https://github.com/profanity-im/profanity/issues/1207 XEP-0359: Unique and Stable Stanza IDs.
Then we can filter incoming messages based on origin-id.

**Comment by jubalh** [comment]
@Shungy should be fixed now!

**Comment by Shungy** [comment]
Great! Thank you.
