### ISSUE TITLE
Profanity with python plugins won't build on Gentoo (conflict of _XOPEN_SOURCE)

### ISSUE THREAD

**Issue by pasis** [profanity-im/profanity#1203]
## Expected Behavior
Profanity builds.

## Current Behavior
```
gcc -DHAVE_CONFIG_H -I. -I./src  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi-3.2.1/include -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid    -I/usr/include/python3.6m  -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -I./src -g -O2 -pthread -I/usr/include/libxml2  -MT src/plugins/python_plugins.o -MD -MP -MF $depbase.Tpo -c -o src/plugins/python_plugins.o src/plugins/python_plugins.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/python3.6m/Python.h:8,
                 from src/plugins/python_plugins.c:35:
/usr/include/python3.6m/pyconfig.h:1493: error: "_XOPEN_SOURCE" redefined [-Werror]
 #define _XOPEN_SOURCE 700

<command-line>: note: this is the location of the previous definition
cc1: all warnings being treated as errors
```

## Possible Solution
```C
/* just before #include <Python.h> */
#undef _XOPEN_SOURCE
```

## Steps to Reproduce (for bugs)
1. ./bootstrap.sh && configure && make
2. Python plugins are enabled

## Context
The problem is that pyconfig.h (included in Python.h) defines `_XOPEN_SOURCE` unconditionally. At the same time, pkg-config defines the same macro for ncursesw:
```
# cat /usr/lib64/pkgconfig/ncursesw.pc | grep Cflags
Cflags:  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I${includedir}
```
As result, `_DEFAULT_SOURCE` defined in command line and then redefined in pyconfig.h.

This is not Profanity issue itself, but I think we can make Profanity build out of box somehow.

## Environment
* Master (commit b3ed21366879c53792277c069766e2d7f6cd5c5b)
* Gentoo Linux
* sys-libs/ncurses-6.1_p20181020
* dev-lang/python-3.6.5

**Comment by jubalh** [comment]
Does it help to include python.h first if they define the macro unconditionally?

I sorted the includes in d3dd95963e354c3e75f4a6e627acb3644c679fbf, can you check whether that works?

**Comment by jubalh** [comment]
I don't see where/why ncurses defines it.
And I don't understand what we can do here to improve the situation :-/

**Comment by pasis** [comment]
For me it's defined in `/usr/lib64/pkgconfig/ncursesw.pc`. So, ncurses developers decided to put it there when the `pc` file was generated at build-time. Same issue may happen with any other library in the future.

Looks like python developers don't care much about this issue ([link](https://bugs.python.org/issue7573)).

There are few candidates for solution:
1. `undef` the macro before Python.h. Need to check that all supported python versions define the macro in Python.h. I would prefer this approach if we don't find a good solution. Besides, there are only 2 files include Python.h.
2. Filter `-D_XOPEN_SOURCE=XXX` from CFLAGS inside autotools scripts. This approach may cause errors if the macro is really needed outside the pythons plugins. I don't like this way.

**Comment by optmzr** [comment]
Not sure if it's any help, but I just tried building with the `python-plugins` USE-flag with this ebuild:
https://github.com/optmzr/gentoo-overlay/blob/master/net-im/profanity/profanity-9999.ebuild

And I didn't get any errors, but it's towards Python 2.7, so that is probably why it succeeds?

**Comment by jubalh** [comment]
> And I didn't get any errors, but it's towards Python 2.7, so that is probably why it succeeds?

I think so. I asked someone else to try it too, and he also said it works with Python 2.7. But when he tried with 3.X it didn't.

**Comment by pasis** [comment]
python 2.7 defines _XOPEN_SOURCE with other value than python 3.6:
```
grep _XOPEN_SOURCE /usr/include/python2.7/pyconfig.h
#define _XOPEN_SOURCE 600
```
And ncursesw defines it with 600 as well. This is the reason why it builds for @optmzr. Redefining macro with the same value is not a warning in gcc.

**Comment by jubalh** [comment]
So what will we do? `undef` `_XOPEN_SOURCE` in all files that include `Python.h` ?
