### ISSUE TITLE
Response of command from plugin?

### ISSUE THREAD

**Issue by massanchik** [profanity-im/profanity#1208]
Hi! 
Can I somehow get response from prof.send_line within a plugin?
Or is there some other methods to execute command and get response?

I need to execute "/otr theirfp" and get result from plugin to compare fingerprint.

**Comment by jubalh** [comment]
I read the code, doesn't seem there is a way currently.

**Comment by DebXWoody** [comment]
I will try to have a look into plugins and this issue.

**Comment by jubalh** [comment]
I just started to read the plugin code yesterday :)
But I'm happy if you want to do it! Cool!

**Comment by jubalh** [comment]
@massanchik still relevant?
