### ISSUE TITLE
Add support for XEP-0045 7.13 "Requesting voice"

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1211]
I would appreciate support for [XEP-0045 7.13](https://xmpp.org/extensions/xep-0045.html#requestvoice):

> It is not possible for a visitor to speak (i.e., send a message to all occupants) in a moderated room. To request voice, a visitor SHOULD send a <message/> stanza containing a data form to the room itself, where the data form contains only a "muc#role" field with a value of "participant".

Some MUCs have switched to moderated and deactivated PMs due to spam and trolling. So you have to find some moderator in another MUC with no disabled PMs to request voice which is no good UX (and sometimes annoys the moderators "why don't you use the voice request of your client?"). Afaik Gajim is the only client supporting this so far.

**Comment by jubalh** [comment]
Thanks for the request. Makes sense to have this.
I'll close this until we are down to 50 ;)
Feel free to reopen then.
