### ISSUE TITLE
Add support to read CA cert from CA cert bundle file

### ISSUE THREAD

**Issue by petvoigt** [profanity-im/profanity#1212]
Expected Behavior:
Linux and FreeBSD offer system wide CA certs all bundled in one single file (CA cert bundle file).
Under Linux additionally separate files for each CA cert are provided. Profanity should read a CA cert from a CA cert bundle file.

Current Behavior:
Profanity currently only reads a CA cert, if provided in a separate file. Therefore Profanity cannot verify a server cert under FreeBSD unless you extract its CA cert from the CA cert bundle file and save in to a separate file.

Environment:
* Profanity 0.7.1
* FreeBSD 11.3-RELEASE-p3
* Build from ports: https://www.freshports.org/net-im/profanity with OMEMO enabled according to
  description under https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241381

**Comment by jubalh** [comment]
@pasis can you maybe take a look at this?

**Comment by pasis** [comment]
@petvoigt, Profanity doesn't control what certs are used. All the work is done in libstrophe. In turn, libstrophe uses openssl API without providing any path to certs - openssl does all the work in all OSes.

In this scenario, what is the proper way to use the bundled file? Should it be provided manually by user or openssl finds it automatically?

**Comment by petvoigt** [comment]
OK, as far as I know OpenSSL evaluates environment variables
SSL_CERT_PATH and SSL_CERT_FILE to find CA certs for verification.
There are OpenSSL defaults for both variables that are depending
on platform. Both can be set manually system wide or session
specific.

In our case under e.g. FreeBSD where there are not single CA certs
under SSL_CERT_PATH Profanity should also evaluate SSL_CERT_FILE. Only
if both locations fail, Profanity should complain about not being able
to find an issuer certificate.

FreeBSD installs CA cert bundle files from port security/ca_root_nss
(https://www.freshports.org/security/ca_root_nss/) to the following
locations:

* /etc/ssl/cert.pem
* /usr/local/etc/ssl/cert.pem
* /usr/local/openssl/cert.pem

Accordingly, I would set my environment variable e.g. like:
SSL_CERT_FILE=/usr/local/etc/ssl/cert.pem

**Comment by petvoigt** [comment]
@pasis, please leave a message, if you need further information.

**Comment by pasis** [comment]
@petvoigt , sorry for delay. I guess I understand the issue. Unfortunately I don't have environment to debug openssl behaviour. However, I can move /etc/ssl/certs (I don't have a bundled file) to check if SSL_CERT_PATH works, right?

I pushed a patch to libstrophe's openssl branch, could you check it on your system? No idea if it will help. The branch: https://github.com/strophe/libstrophe/tree/openssl

**Comment by petvoigt** [comment]
On Fri, 01 Nov 2019 03:43:18 -0700
Dmitry Podgorny <notifications@github.com> wrote:

> @petvoigt , sorry for delay. I guess I understand the issue.
> Unfortunately I don't have environment to debug openssl behaviour.
> However, I can move /etc/ssl/certs (I don't have a bundled file) to
> check if SSL_CERT_PATH works, right?
> 
> I pushed a patch to libstrophe's openssl branch, could you check it
> on your system? No idea if it will help. The branch:
> https://github.com/strophe/libstrophe/tree/openssl
> 

I could provide a copy of the correspondig FreeBSD and/or Debian CA
bundle file, if it makes it easer for you to test. Just leave a message
in this case.

**Comment by petvoigt** [comment]
@pasis, sorry, I did not read your comment careful enough.

If you are testing under Linux, you could temporarily for one test
rename the CA cert directory and copy the CA cert file bundle to a
location which is addressed by your (temporary) environment
SSL_CERT_FILE.

Could you please provide a direct link to your corresponding commit
under https://github.com/strophe/libstrophe/tree/openssl - I simply
cannot find your commit.

**Comment by jubalh** [comment]
> Could you please provide a direct link to your corresponding commit
under https://github.com/strophe/libstrophe/tree/openssl - I simply
cannot find your commit.

You should not care about the commits. You need to use the openssl branch. I assume it's the last two commits, but that doesn't really matter for you.

**Comment by pasis** [comment]
@jubalh is right, you can use the whole branch. The commit is https://github.com/strophe/libstrophe/commit/284fa4d46ea0c60ec3eb7778acdbf3ff608b1652.

I tried to rename `/etc/ssl/cert` dir to `/etc/ssl/cert.bak` and set SSL_CERT_PATH accordingly. OpenSSL ignored the variable even with the patch. My command line was:
```
$ SSL_CERT_PATH=/etc/ssl/cert.bak ./examples/basic <jid> <password>
```

openssl version: 1.0.2.

@petvoigt, if you send me your CA cert file (or attach it here) I will check also `SSL_CERT_FILE`.

**Comment by petvoigt** [comment]
On Mon, 04 Nov 2019 00:26:19 -0800
Dmitry Podgorny <notifications@github.com> wrote:

> @jubalh is right, you can use the whole branch. The commit is
> https://github.com/strophe/libstrophe/commit/284fa4d46ea0c60ec3eb7778acdbf3ff608b1652.
> 
> I tried to rename `/etc/ssl/cert` dir to `/etc/ssl/cert.bak` and set
> SSL_CERT_PATH accordingly. OpenSSL ignored the variable even with the
> patch. My command line was: ``` $
> SSL_CERT_PATH=/etc/ssl/cert.bak ./examples/basic <jid> <password> ```
> 
> openssl version: 1.0.2.
> 
> @petvoigt, if you send me your CA cert file (or attach it here) I
> will check also `SSL_CERT_FILE`.
> 

@pasis, I strongly suppose you are testing under Linux. At least under
Debian there is a package "ca-certificates" which contains one CA cert
per file:
https://packages.debian.org/buster/ca-certificates
which are all stored under /etc/ssl/certs. Renaming that dir should
have the effect that all these certs are no longer found by Profanity
and other program evaluating SSL_CERT_PATH. Instead you can force
Profanity for testing purposes to use a CA cert bundle file instead.

Supposed all CA certs are stored in the one CA cert bundle file
/usr/local/etc/ssl/cert.pem then your correspondig test command from
your last message should look like:
```SSL_CERT_FILE=/usr/local/etc/ssl/cert.pem ./examples/basic <jid> <password>```

You can download my FreeBSD CA cert bundle file for testing from here:
https://www.drpetervoigt.eu/download/cert.pem
It is the CA cert bundle file from the "security/ca_root_nss" FreeBSD
port:
https://www.freshports.org/security/ca_root_nss/

**Comment by kousu** [comment]
I think #1234 is indeed the same bug as this; same problem: a bundle /etc/ssl/cert.pem instead of a directory /etc/ssl/certs/. And I am pretty sure I fixed it for libmesode; but if FreeBSD is building against libstrophe, well that _should_ already be working too because of this line (from 3 years ago): https://github.com/strophe/libstrophe/blame/6852da97aef2b0e690b0c442bd58219e0dcf2ffb/src/tls_openssl.c#L139.

**Comment by jubalh** [comment]
@petvoigt @pasis @kousu what to do with this? :)

**Comment by jubalh** [comment]
No reactions.
