### ISSUE TITLE
Google chat/hangouts login failure

### ISSUE THREAD

**Issue by scfrank** [profanity-im/profanity#1215]
Hi,
Over the weekend I stopped being able to log in to my google hangouts/talk/messenger account on profanity: I get a login failed error.

The logs indicate a TLS failure:
```
28/10/2019 13:39:59: xmpp: DBG: proceeding with TLS
28/10/2019 13:39:59: tls: DBG: Certificate verification FAILED
28/10/2019 13:39:59: tls: DBG: error=1 errno=0
28/10/2019 13:39:59: tls: DBG: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
28/10/2019 13:39:59: conn: DBG: Couldn't start TLS! error -3 tls_error 1 
28/10/2019 13:39:59: conn: DBG: SENT: </stream:stream>
28/10/2019 13:39:59: xmpp: DBG: Send error occurred, disconnecting.
```
I use an app password for authentication which according to google is still valid; last active last Friday. I'm using profanity 0.7.0 on a Mac (mojave 10.14.6).

I'm wondering whether this is connected to google removing support for hangouts (silently and overnight, as far as I'm concerned)? Or has something else gone wrong?
 
Thanks!

**Comment by pasis** [comment]
Have you updated openssl recently? I have the same issue when I switch to the newer openssl-1.1.1 and connect to some server (not all servers affected).

Maybe related: #1202

**Comment by scfrank** [comment]
I appreciate the quick response! However I don't think openssl is the problem:
1, I'm on a mac which (homebrew tells me) has deprecated use of openssl in favour of their own TSL and crypto libraries
2, I have openssl 1.0.2 installed (last updated about a month ago) with homebrew but it's "keg-only" i.e. not in my path.
3, when I change my path to use the homebrew openssl, the login in profanity still doesn't work, with or without the fix suggested in the linked issue.

**Comment by pasis** [comment]
Fix from the linked issue didn't work for me neither. But older versions (including 1.0.2) still work for me. 

What I can suggest else here is to try verify certificate manually with openssl tool (from the same package which fails with Profanity). Not sure how much info you can get with this approach.

Btw, if you would like to trust "failed" certificate, you can use `tls trust` option in `/connect` or `/account`.

**Comment by scfrank** [comment]
The last option (`tsl trust`) works! Thanks for this.
Not being a crypto person I don't have a good sense of how dangerous/foolhardy this option is though.

**Comment by jubalh** [comment]
So can we close this?

**Comment by scfrank** [comment]
Yes, inasmuch blindly trusting the tls certificate works for me, and it's
probably not a problem on profanity's end.
