### ISSUE TITLE
Settings remain even without saving

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1218]
Changed settings remain, even when they are not saved via `/save` and profanity gets restarted.

## Expected Behavior
After `/quit` without `/save`the changed settings should be reverted when restarting.

## Current Behavior
* My settings are e.g. 
     * Theme in use solarized-dark
     * No name in status bar chat tabs
     * No resource, presence status, online status are shown in roster
     * Time format dd.mm.yyyy hh:mm:ss
* `/theme load boothj5`
* All above settings are changed
* `/theme load solarized-dark`
* Changes remain (the theme doesn't touch them)
* `/quit`
* Open profanity
* Changes remain
     * Names in status bar chat tabs
     * Resource, presence status, online status are shown in roster
     * Time format changed to dd/mm/yyyy

```
diff profrc profrc-before-themeswitching 
19c19
< statusbar.show.name=true
---
> statusbar.show.name=false
32,34c32,34
< roster.resource=true
< roster.presence=true
< roster.status=true
---
> roster.resource=false
> roster.presence=false
> roster.status=false
47,52c47,52
< time.console=%H:%M:%S
< time.chat=%d/%m/%y %H:%M:%S
< time.muc=%d/%m/%y %H:%M:%S
< time.config=off
< time.private=%d/%m/%y %H:%M:%S
< time.xmlconsole=%H:%M:%S
---
> time.console=%d.%m.%y %H:%M:%S
> time.chat=%d.%m.%y %H:%M:%S
> time.muc=%d.%m.%y %H:%M:%S
> time.config=%d.%m.%y %H:%M:%S
> time.private=%d.%m.%y %H:%M:%S
> time.xmlconsole=%d.%m.%y %H:%M:%S
86,87d85
< 
< roster.resource.char=/
```

## Environment

Version 0.7.1dev.master.725cf3e4
Debian bullseye (testing)

**Comment by jubalh** [comment]
/save only saves the preferences.
But /theme loads and applies a theme. Themes can have colours and other look options, like what date to use etc.

So in my opinion theme vs preferences handling is borked. And I opened a issue quite a while ago to discuss how to improve it: https://github.com/profanity-im/profanity/issues/1077
