### ISSUE TITLE
Profanity is sometimes highlighting a mention wrong.

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1220]
Profanity is configured to highlight my Nickname for mentions but sometimes it highlights something wrong.

![2019-11-01-141849_scrot](https://user-images.githubusercontent.com/5103003/68027801-96271500-fcb3-11e9-86d0-b5aa3288432c.png)

## Expected Behavior
In this example it should highlight "Martin"

## Current Behavior
It highlights other stuff and also mixes in the username "debacle" maybe caused by the [<200e>](https://en.wikipedia.org/wiki/Left-to-right_mark).

## Context
```
01/11/2019 14:17:25: xmpp: DBG: RECV: <message id="e7de6887-7feb-4925-ba8a-39ae4a0c3379" type="groupchat" lang="en" to="REDACTED" from="chat@dino.im/debacle"><body>I hope, this quoting style never makes it to XMPP.
<200e>&gt; [13:00:19] <200e>Martin<200e>: Yeah, at least we get paid for that. :D
<200e>&gt; &gt; [12:58:30] <200e>Ge0rG<200e>: Martin: I know. My personal and my business behaviors in that regard are opposite as well
&gt; <200e>&gt; &gt; [12:55:25] <200e>Martin<200e>: Ge0rG: In my company they want TOFU as the expect to be able to scroll through the full history if needed...</body><origin-id id="e7de6887-7feb-4925-ba8a-39ae4a0c3379" xmlns="urn:xmpp:sid:0"/><active xmlns="http://jabber.org/protocol/chatstates"/></message>
```

## Environment
Version 0.7.1dev.master.f71de61b
Debian Bullseye (testing)

```
gnome-terminal --version                                                                      :(
# GNOME Terminal 3.34.2 using VTE 0.58.2 +BIDI +GNUTLS
```

**Comment by jubalh** [comment]
Another example:

Gajim output:
```
‎[04:06:29 PM] ‎jubalh‎: DebXWoody, not yet. Does it work?
‎[04:07:17 PM] ‎debacle‎: ‎[15:04:27] ‎Martin‎: debacle: Let's throw some stuff at me, let's see if it happens again.
```
![issue](https://user-images.githubusercontent.com/1658215/68034564-29674700-fcc2-11e9-9e5d-41e845201269.png)

**Comment by mdosch** [comment]
It seems these <200e> are coming from Gajim. This excerpt is from the Gajim MUC:

```
01.11.19 14:46:49 - Martin: Does gajim insert <200e>? https://en.wikipedia.org/wiki/Left-to-right_mark
01.11.19 14:47:59 - Martin: Because I had a problem with profanity and assume it is caused by this control character
                    (see https://github.com/profanity-im/profanity/issues/1220 ) and I think the sender used Gajim (at
                    least according to the version request answer on his muc nick).
01.11.19 14:54:13 - Link Mauve: Martin, yes, it does that.
01.11.19 14:54:21 - Link Mauve: Should be only for display though.
01.11.19 15:49:07 - debacle: Martin, Link Mauve, I copy/pasted from and to Gajim. Maybe that caused the <200e>?
01.11.19 15:52:31 - Link Mauve: It indeed is in the UI.
01.11.19 15:52:41 - Link Mauve: IIRC it was a workaround to help rtl languages.
01.11.19 15:53:13 - Link Mauve: Imo it shouldn’t be present when we know everything is ltr, or everything is rtl, but
                    that’s harder to do than putting this character always.
```

**Comment by jubalh** [comment]
In Gajim one needs to copy with right click and then selecting `copy` in the context menu. Otherwise it will add those special characters. This way it removes them when copying to clipboard.

**Comment by jubalh** [comment]
So the question is, should we have some general filtering of incoming messages for certain sequences and remove them.
What kind of sequences would that be?

**Comment by mdosch** [comment]
Is there a way to filter nonvisible sequences?

**Comment by jubalh** [comment]
After reading https://en.wikipedia.org/wiki/ANSI_escape_code I'm still not sure. Can I just look for `\\e` and remove this? Seems there are various ways this can be encoded?

**Comment by jubalh** [comment]
Seems this is hard/impossible to do. We have various unicode stuff and escape stuff and we don't know what is what.

mcabber and poezio also seem not to do manipulate this.
Will close for now. Feel free to reopen or comment with ideas.

**Comment by mdosch** [comment]
I created an issue at the Gajim tracker: https://dev.gajim.org/gajim/gajim/issues/9881

**Comment by lovetox** [comment]
Just replace \u200E and \u200F before you send it to display.

these are 2 unicode chars and not disallowed by xmpp or xml standard, so you have to deal with them someway
