### ISSUE TITLE
Highlight nicks (by color) in MUCs

### ISSUE THREAD

**Issue by mejo-** [profanity-im/profanity#1225]
Right now, nicknames of MUC participants aren't highlighted, they just have the same color as the text (`main.text.them`). I find that this makes it rather hard to scan the MUC history, since there's no visual distinction between nickname and written text.

## Expected Behavior

Highlight nicknames in MUCs using the color as defined as `them` in theme.

## Current Behavior

Nicknames in MUCs aren't highlighted at all and have same color as `main.text.them`.

## Environment

```
$ profanity -v
Profanity, version 0.7.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.12.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.3)
GTK icons: Enabled
```

Running on Debian/Buster

**Comment by jubalh** [comment]
This is a new feature/improvement. In the issue template I asked to wait to open new features until we are down to 50 open issues.

Furthermore there is https://github.com/profanity-im/profanity/issues/1191 (which is not the same, and your request clearly makes sense nevertheless), which will add consistent color generation for nicknames. It will be optional.

 > Nicknames in MUCs aren't highlighted at all and have same color as main.text.them.

They are hilighted. The same way the whole message of the other person is.

**Comment by mejo-** [comment]
Thanks for the quick response, @jubalh. I meant that nicknames in MUCs are not highlighted compared to the message of others.

Would you accept a pull request that simply changes the way messages are displayed in MUCs to highlight the nickname using the same color as set in `them`? I could imagine to look into it. But I totally understand if you prefer to work on #1191 and don't want to change the default behaviour.

**Comment by jubalh** [comment]
I think what would make more sense is a new tag `main.theme.nick` right? Since we might not want it to be the same colour as the text they send. Because actually I think that would be much less readable. Right now I think it's readable best. But I can understand if someone wants a different colour for the nick.

**Comment by jubalh** [comment]
Actually we have for the nicks:
```
me=green
them=cyan
```

And for the text I/they send:

```
main.text.me=default
main.text.them=blue
```

So I think (if I understood you correctly) your functionality is already there isn't it?

**Comment by mdosch** [comment]
I understood he wants others nicks within a message highlighted.

E.g. Martin mentions Michael and in Stefans profanity Michael has a different color than main.text.

**Comment by jubalh** [comment]
Oh :)

But then you would have to parse the whole incoming message and add hilighting marks around the nick.

Also some people just have nick like "as" so all kinds of strange behaviour would occur like "I like it as is".

**Comment by mejo-** [comment]
Hehe, confusion :wink:  No, this issue is not about highlighting nicks in the written text. It's about hilighting others nickname in front of the written texts in MUCs.

When I looked up the theme settings, my understanding first also was that `them` is exactly what I want. But either it's not, or it's broken.

E.g. the theme `original` (which I seem to prefer) has `main.theme.text` set to `white` and `them` set to green. While the nickname from others indeed is displayed as green in private chats, it's white (just like the written text) in MUCs.

So then apparently this is a bug, not a feature request :slightly_smiling_face:

**Comment by mdosch** [comment]
Weird, for me this works in mucs as well.

**Comment by mejo-** [comment]
Sorry, for me it works as well. I was confused by the channel history, where nicknames are *not* hilighted. Sorry for the noise.
