### ISSUE TITLE
Wrong message display

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1231]
I received MUC messages which were displayed wrong. The date was also "injected" in the message.

## Expected Behavior
The date should not be "injected" in the message.

## Current Behavior

![2019-11-25-181008_scrot](https://user-images.githubusercontent.com/5103003/69562382-5819ca00-0faf-11ea-835f-191b72e270dd.png)

## Context

```
grep Kter profanity.log.99 
25/11/2019 17:38:44: xmpp: DBG: RECV: <message lang="en" to="REMOVED/rF9sqBAM" type="groupchat" from="conversations@conference.siacs.eu/Licaon_Kter [web]"><inactive xmlns="http://jabber.org/protocol/chatstates"/><no-store xmlns="urn:xmpp:hints"/><no-permanent-store xmlns="urn:xmpp:hints"/></message>
25/11/2019 17:38:44: prof: ERR: Message received without body for room: conversations@conference.siacs.eu/Licaon_Kter [web]
25/11/2019 17:44:08: xmpp: DBG: RECV: <presence lang="en" type="unavailable" to="REMOVED/rF9sqBAM" from="conversations@conference.siacs.eu/Licaon_Kter [web]"><x xmlns="http://jabber.org/protocol/muc#user"><item role="none" affiliation="none"/></x></presence>
25/11/2019 17:44:08: prof: DBG: Unavailable presence handler fired for conversations@conference.siacs.eu/Licaon_Kter [web]
25/11/2019 17:44:08: prof: DBG: Room presence received from conversations@conference.siacs.eu/Licaon_Kter [web]
25/11/2019 18:02:59: xmpp: DBG: RECV: <message id="812fe59f-55d4-4e26-a749-2e084ec9cbef" lang="en" to="REMOVED/rF9sqBAM" type="groupchat" from="operators@muc.xmpp.org/Licaon_Kter"><origin-id id="812fe59f-55d4-4e26-a749-2e084ec9cbef" xmlns="urn:xmpp:sid:0"/><body>Martin: i think the massage comes from /me saying &quot;buy coins from Martin@domain&quot;</body><stanza-id id="2019-11-25-45c772389fbcdf1d" by="operators@muc.xmpp.org" xmlns="urn:xmpp:sid:0"/></message>
25/11/2019 18:02:59: prof: DBG: Attempting notification: Licaon_Kter in operators (win 20)
25/11/2019 18:03:15: xmpp: DBG: RECV: <message id="f54dcc1e-903d-40f5-a905-80c0813f5105" lang="en" to="REMOVED/rF9sqBAM" type="groupchat" from="operators@muc.xmpp.org/Licaon_Kter"><origin-id id="f54dcc1e-903d-40f5-a905-80c0813f5105" xmlns="urn:xmpp:sid:0"/><body>Martin: so...you ban me or Martin@domain ?</body><stanza-id id="2019-11-25-166194fa31362cf0" by="operators@muc.xmpp.org" xmlns="urn:xmpp:sid:0"/></message>
25/11/2019 18:03:15: prof: DBG: Attempting notification: Licaon_Kter in operators (win 20)
```

## Environment
Debian Bullseye (Testing)

profanity -v
Profanity, version 0.7.1dev.master.f0a719d1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.17)
GTK icons: Enabled

**Comment by mdosch** [comment]
Licaon_Kter was using conversations.

**Comment by licaon-kter** [comment]
Ignore the [web] ones as that client is not online and not in that room.

**Comment by jubalh** [comment]
I don't see what's happening here. Can somebody point out what exactly causes this?

**Comment by jubalh** [comment]
![showprofstrangemessage](https://user-images.githubusercontent.com/1658215/70800209-f11c5380-1dab-11ea-9e4b-24e2ada99edc.png)

`/xc2` and `/xa0` ?

@mdosch please paste later the specific color setting you used, that I don't have.

**Comment by mdosch** [comment]
```
roommention=yellow
roommention.term=orange1
```

**Comment by jubalh** [comment]
Probably related to https://github.com/profanity-im/profanity/issues/1220.
Maybe we need to use [utf8proc](https://github.com/JuliaStrings/utf8proc) to normalize displayed strings.

**Comment by mdosch** [comment]
Another example 
![2020-02-07-114131_scrot](https://user-images.githubusercontent.com/5103003/74023351-c3185180-499f-11ea-9604-1d8ef30bdcb0.png)

```
07/02/2020 11:39:27: xmpp: DBG: RECV: <message id="4b504154-f77c-43ac-9777-c592311251ca" lang="en" to="martin@mdosch.de/saWTE9GK" type="groupchat" from="conversations@conference.siacs.eu/Alacer"><archived id="1581071967519266" by="conversations@conference.siacs.eu" xmlns="urn:xmpp:mam:tmp"/><stanza-id id="1581071967519266" by="conversations@conference.siacs.eu" xmlns="urn:xmpp:sid:0"/><origin-id id="4b504154-f77c-43ac-9777-c592311251ca" xmlns="urn:xmpp:sid:0"/><body>&gt; Signal, Threema, Matrix and Telegram everywhere. Seems like XMPP really needs some marketing…
Martin: 100% agreed.... Even Technically what innnovative tech these Apps/App Decelopers are using is not Envisined as IM Solution as Opposed to XMPP.... off course One can always argue ...</body></message>
```

**Comment by wstrm** [comment]
I got weird highlighting in a message today:
![2020-02-10-133837_222x25_scrot](https://user-images.githubusercontent.com/4541181/74150649-a6cc1d00-4c0a-11ea-94a5-781451d3a32a.png)

(`optmzr` is what should have been highlighted)

In this case it could be the letter `ö` that is messing things up, maybe?

**Comment by jubalh** [comment]
Maybe :/ I don't get what's exactly going on here. Still guessing that utf8proc might help.

BTW. not just the highlighting is weird. the text also is :D

**Comment by wstrm** [comment]
> BTW. not just the highlighting is weird. the text also is :D

We're battle testing Profanity's UTF-8 support daily :sunglasses:

**Comment by jubalh** [comment]
![showopt](https://user-images.githubusercontent.com/1658215/74153653-66bc6880-4c11-11ea-9d1a-b2b30df58d22.png)

**Comment by wstrm** [comment]
I'm using:
Profanity: v0.8.1
ncurses: 6.1_p20190609

**Comment by aw32** [comment]
I also get the timestamp/from prefix inserted into the message.
It happens reliably if my nick is mentioned multiple times in the message (with my nick being `asdf` and the message is being sent by `foo`).
```
14:33:33 - foo: asdf14:33:33 - foo:  asdf                                                                                                                                                      
14:35:45 - foo: asdf14:35:45 - foo:  foobar asdf foobar                                                                                                                                        
14:36:03 - foo: asdf foobar foobar
14:39:21 - foo: asdf14:39:21 - foo:  foobar asdf14:39:21 - foo:  foobar asdf foobar
```

Profanity: 0.10.0

**Comment by mdosch** [comment]
> ![showopt](https://user-images.githubusercontent.com/1658215/74153653-66bc6880-4c11-11ea-9d1a-b2b30df58d22.png)
> 
> Now that is confusing. Maybe the locale matters? Maybe the ncurses version/terminal?

You don't have a different color for the highlight term set, compare to my settings:

```
roommention=yellow
roommention.term=orange1
```

The roommention.term is what is doing weird things.

**Comment by jubalh** [comment]
Send from another client to a client with nick jubalh: `õõ jubalh õõ martin õõ jubalh õ asdf`
![showscr](https://user-images.githubusercontent.com/1658215/121225920-4a265400-c88a-11eb-9cfe-a9d3227d03dc.png)
