### ISSUE TITLE
Profanity should allow legacy auth when explicitly requested

### ISSUE THREAD

**Issue by ibotty** [profanity-im/profanity#1236]
Some servers still require legacy auth and worked great with libstrophe < 1.9.3.

**Comment by mdosch** [comment]
Are you talking about [XEP-0078](https://xmpp.org/extensions/xep-0078.html)? As this is obsolete you should rather ask the server operator to not require this.

**Comment by ibotty** [comment]
No doubt, the server should get updated.  For some corporate setups that's rather involved though.

**Comment by jubalh** [comment]
I think he is talking about legacy auth, that was disabled by default here: https://github.com/profanity-im/profanity/issues/905.
So it is disabled in libstrophe 0.9.3 by default. And could be enabled with `XMPP_CONN_FLAG_LEGACY_AUTH`.

**Comment by licaon-kter** [comment]
I'm unable to build this on Debian current, due to the lack of libstrophe 0.9.3 in the repos _(it is in the next version repo for the last 8 months, which is not that encouraging) ;(

Can this be optioned off, eg. no 0.9.3 = no legacy auth support ?

**Comment by jubalh** [comment]
Damn, I forgot to check this!

I decreased the version for glib by using some workarounds specifically for the purpose that we don't rely on a newer glib that Debian has in its repos.

My goal was that 0.9.0 will still run on current Debian stable.

0.10.0 will bump several things that will need newer library versions.

So yeah we should change this for 0.9.1.
