### ISSUE TITLE
Empty line at the bottom of the chat window

### ISSUE THREAD

**Issue by marmulak** [profanity-im/profanity#1245]
When chatting, the space between the title bar (top) and the status bar (bottom) never gets fully filled, but rather a blank line persists. (The blank line is located above the clock.) The chat window does not fill this space, but the chat roster on the right side of the screen does.

Here is a screenshot:

![last-line](https://user-images.githubusercontent.com/40630991/71406447-7b3aa680-264d-11ea-90ee-9755ed34815c.png)

As you can see, the roster reaches all the way with the user "anomie" in the right row, but you can see after the last line (pfm's message) it's as if there's a newline that shouldn't be there.

## Expected Behavior
Would like the window contents to fill the entire area.

## Current Behavior
Text stops before filling the last line in the area.

## Possible Solution
Let the text go all the way down.

## Steps to Reproduce (for bugs)
Built from master on Fedora 31. Run profanity as normal.

## Environment
Profanity, version 0.7.1dev.master.5d7f2d15
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Disabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.5)
GTK icons: Disabled

glib package: glibc-2.30-8.fc31.x86_64

**Comment by marmulak** [comment]
Output of gnome-terminal --version:
# GNOME Terminal 3.34.2 using VTE 0.58.3 +BIDI +GNUTLS

Have tried with other terminals, for example the Linux system console and Konsole as well. Does not affect the behavior.

**Comment by marmulak** [comment]
I'm going to close this issue because while it may not have been properly explained by the devs, it appears that the use of having the empty new line at the end of the buffer is to make it easy to see that you are looking at the end of the buffer and not further back in the conversation, because scrolling back will result in that line being filled. Clients like irssi indicate the scroll state in a slightly different way, but I suppose this way is as good as any.

**Comment by optmzr** [comment]
Yes, I kind of like the empty line. :)
