### ISSUE TITLE
OMEMO 1on1 chats with psi+ fail due to prekey="true/1"

### ISSUE THREAD

**Issue by svensp** [profanity-im/profanity#1247]
## Expected Behavior
I can encrypt 1on1 chats with psi+ users with omemo

## Current Behavior
OMEMO Messages are discarded, silently in case of the UI.

Log says
```
905 01/01/2020 17:45:39: prof: DBG: OMEMO: decrypting message with existing session
906 01/01/2020 17:45:39: prof: ERR: OMEMO: cannot deserialize message
907 01/01/2020 17:45:39: prof: ERR: OMEMO: cannot decrypt message key
```
despite the keys in the message being tagged with `prekey="1"`

## Possible Solution
Checking for `"1"` as well as `"true"` makes the on encryption work both ways but only after the psi+ client sent a message.
```c
323         key->prekey =                                                           
324            (g_strcmp0(xmpp_stanza_get_attribute(key_stanza, "prekey"), "true") == 0)
325            || (g_strcmp0(xmpp_stanza_get_attribute(key_stanza, "prekey"), "1") == 0);
```
A quick google on the type `xs:boolean` looks to me like this should be an expected value here and it is not psi+ breaking the spec

## Steps to Reproduce (for bugs)
1. Turn on debug logging in Profanity 0.7.1
2. Initiate OMEMO between PSI+ 1.4.983 and Profanity(0.7.1)

## Context
I'm trying to use OMEMO encryption between my profanity 0.7.1 on Debian bullseye and a friend who uses Psi+ under Windows

## Environment
Debian bullseye package version 0.7.1-1
```
Profanity, version 0.7.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.17)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
@svensp I highly appreciate that you open a bug and *also* a pull request to address this bug! Very nice! Thanks!

**Comment by jubalh** [comment]
@svensp so is this issue gone with your PR? Can it be closed?

**Comment by svensp** [comment]
The issue described in this issue is indeed gone.

The fact remains that the encryption only works after psi+ sends a message to profanity but while I was not able to pinpoint the exact cause it seems to me that psi+ somehow does not subscribe to the pep events of omemo when sending a `presense` message. Which should be impossible I think.

That said I had to give up looking for now but I'm suspecting the cause in psi+ rather than profanity so I'd say this issue can be closed.

**Comment by jubalh** [comment]
Thanks for the feedback!
