### ISSUE TITLE
Build fail on archlinux, latest release

### ISSUE THREAD

**Issue by nolash** [profanity-im/profanity#1249]
Happy new year.

On build release 0.7.1:

```
$ ./bootstrap.sh 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:90: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

adding `m4_pattern_allow([AC_MSG_ERROR])` to `configure.ac` makes `bootstrap.sh` complete, but `./configure` fails:

```
[...]
./configure: line 9227: AX_PYTHON_DEVEL: command not found
checking for main in -ldl... yes
./configure: line 9361: syntax error near unexpected token `,'
./configure: line 9361: `ACX_PTHREAD(, AC_MSG_ERROR([pthread is required]))'
```

* linux: `archlinux 5.4.7-arch1-1` (updated 2.1.20)

**Comment by jubalh** [comment]
I think you are missing build deps.
https://profanity-im.github.io/guide/latest/build.html

It might be that the Arch docu there is not up to date, also check the package names of the other distros. In case it's not up to date please create a PR.

**Comment by vinegret** [comment]
@nolash , probably missed  *autoconf-archive*. Also you can install full toolchain from package group *base-devel*. This can be useful in the future for build other software.
```bash
pacman -Sy base-devel autoconf-archive
```

**Comment by nolash** [comment]
@jubalh @vinegret `autoconf-archive` indeed. Thanks, works now.

I see that the arch package `0.7.1-1` is not compiled with omemo. Should it be that way?

**Comment by jubalh** [comment]
> @jubalh @vinegret autoconf-archive indeed. Thanks, works now.

You would have found that out by googling too ;)
Every few months someone asks this question in regards to profanity.

> I see that the arch package 0.7.1-1 is not compiled with omemo. Should it be that way?

You need to ask the Arch maintainer.
