### ISSUE TITLE
with /color on, background of nicks is always black

### ISSUE THREAD

**Issue by Misaflo** [profanity-im/profanity#1255]
## Expected Behavior

When we use consistent color generation for nicks  (`/color on`) and a theme with non-black background (for example: `bkgnd=Grey11`), the background of nicknames should be the same color as `bkgnd`.

## Current Behavior

The background color of nicknames is always black.

## Possible Solution

May be use an option to customize nickname background color?

As we don't choose colors of nicks, it may be not be very readable with non-black background?

## Steps to Reproduce (for bugs)

    /color on
    /theme load bios

## Environment

    profanity -v
    Profanity, version 0.7.1dev.makepkg.44204635
    Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
    Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
    License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
    
    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Build information:
    XMPP library: libmesode
    Desktop notification support: Enabled
    OTR support: Enabled (libotr 4.1.1)
    PGP support: Enabled (libgpgme 1.13.1)
    OMEMO support: Enabled
    C plugins: Enabled
    Python plugins: Enabled (3.8.1)
    GTK icons: Enabled

**Comment by jubalh** [comment]
For now we just use the default background color.

**Comment by Misaflo** [comment]
It works! Thanks :-)
