### ISSUE TITLE
Profanity no longer update profrc itself

### ISSUE THREAD

**Issue by Misaflo** [profanity-im/profanity#1258]
## Expected Behavior

When you change something with commands in profanity, the profrc file must be updated.

## Current Behavior

When you changes configuration via commands, the profrc file doesn't change.

## Steps to Reproduce (for bugs)

Change configuration via commands, for example change theme:

    /theme load batman

The theme is not update in `~/.config/profanity/profrc`.

## Environment

    Profanity, version 0.7.1dev.master.3c0647ec
    Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
    Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
    License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
    
    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Build information:
    XMPP library: libstrophe
    Desktop notification support: Enabled
    OTR support: Enabled (libotr 4.1.1)
    PGP support: Enabled (libgpgme 1.12.0)
    OMEMO support: Enabled
    C plugins: Enabled
    Python plugins: Disabled
    GTK icons: Enabled

**Comment by mdosch** [comment]
In recent versions you have to save changes via '/save'

Am January 24, 2020 5:39:32 PM UTC schrieb "Florent Lévigne" <notifications@github.com>:
>## Expected Behavior
>
>When you change something with commands in profanity, the profrc file must be updated.
>
>## Current Behavior
>
>When you changes configuration via commands, the profrc file doesn't change.
>
>## Steps to Reproduce (for bugs)
>
>Change configuration via commands, for example change theme:
>
>    /theme load batman
>
>The theme is not update in `~/.config/profanity/profrc`.
>
>
>## Environment
>
>    Profanity, version 0.7.1dev.master.3c0647ec
>    Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
>    Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
>    License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
>    
>    This is free software; you are free to change and redistribute it.
>    There is NO WARRANTY, to the extent permitted by law.
>    
>    Build information:
>    XMPP library: libstrophe
>    Desktop notification support: Enabled
>    OTR support: Enabled (libotr 4.1.1)
>    PGP support: Enabled (libgpgme 1.12.0)
>    OMEMO support: Enabled
>    C plugins: Enabled
>    Python plugins: Disabled
>    GTK icons: Enabled
>

**Comment by jubalh** [comment]
Yes, we have a `/save` command now.

**Comment by Misaflo** [comment]
OK sorry, it works.
Thank you for the reply.
