### ISSUE TITLE
Send and retrieve encrypted files when using OMEMO

### ISSUE THREAD

**Issue by wstrm** [profanity-im/profanity#1262]
## Expected Behavior

The `/sendfile` command should send the file encrypted as AES-256 in GCM while using OMEMO, according to XEP-xxxx: OMEMO Media Sharing.

Profanity should also be able to decrypt files and save them to the file system as is already supported when retrieving unencrypted files.

## Current Behavior

When sending files with `/sendfile` the files are sent unencrypted and my friends gets upset that I'm not using OMEMO Media Sharing.

When receiving an encrypted files an `aesgcm://` URI is displayed. 

## Possible Solution

N/A

## Context

I am member of a large MUC that uses OMEMO, a lot of memes are shared an I want to save them seamlessly to my file system.

## Environment
N/A

**Comment by wstrm** [comment]
> /close as duplicate #1070

I got told to create this issue

**Comment by jubalh** [comment]
Yep, that's right. This issue is for tracking progress of that feature and so it can be assigned easily.
I added the link to it at the appropriate place in https://github.com/profanity-im/profanity/issues/1262.
Which is just the general feature tracker.

**Comment by moppman** [comment]
There was some discussion the other day in one of the MUCs about profanity sending unencrypted files in an encrypted chat without warning users about it. That's why I made #1270 until we have actual file encryption :)

**Comment by mdosch** [comment]
As I already said in the conversations MUC I'd rather have a way to 
override that.

**Comment by jubalh** [comment]
#1270 got merged. `/omemo sendfile on` is now needed to allow sending unencrypted files using `/sendfile` while in an OMEMO session.
