### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [profanity-im/profanity#1272]
There is a problem in the code:
- https://github.com/xsf/xeps/pull/894

**Comment by wstrm** [comment]
https://github.com/profanity-im/profanity/blob/master/src/omemo/crypto.h#L38

**Comment by paulfariello** [comment]
FTR we use 16 bytes IV when encrypting but we use whatever size was used when decrypting.

**Comment by Neustradamus** [comment]
@jubalh: Thanks a lot!
