### ISSUE TITLE
Send messages to offline clients

### ISSUE THREAD

**Issue by BlackLotus** [profanity-im/profanity#1274]
When communicating (omemo enabled) messages that are sent when clients of a participant are offline are not send. 

## Expected Behavior
When I'm writing with a user that has multiple clients (mobile, desktop and laptop i.e) and one or more of the clients are offline, they should receive the messages after the fact.

Expected behavior is of course that all clients that are known to profanity should receive a message. 

## Current Behavior
I'm chatting with someone that uses conversations on his phone, he comes home starts his gajm session and he gets no messages. (All fingerprints are trusted)

## Steps to Reproduce (for bugs)
1. start profanity
2. chat with someone that has multiple clients
3. tell him/her to go offline in one of the clients and send the message "foobar test"
4. tell him/her to connect again with the client and ask if the person has seen the message

## Environment
*  `0.8.1dev.master.968006e1`
```
Profanity, version 0.8.1dev.master.968006e1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16)
GTK icons: Enabled
```
* Mac OS X high sierra 10.13.6

**Comment by jubalh** [comment]
@paulfariello ?

**Comment by mdosch** [comment]
I just tried it and it works for me.
Maybe the device on the other end or the server does not support MAM?

**Comment by BlackLotus** [comment]
Ok it looks like a problem with the server side settings. Everything seems to work now
