### ISSUE TITLE
Roster contacts are offline

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1280]
## Expected Behavior
If the client has been successfully connected to the XMPP Server, the roster tab should show the current status of the contacts (online, Away, Offline,..).

## Current Behavior
All contacts are displayed as offline. The `/roster` command is working well.
The problem can be solved by, reconnect, resize of window, join a muc,...

## Possible Solution
redraw?

## Steps to Reproduce (for bugs)
Just connect to the XMPP Server.

## Context
If the user as an autojoin bookmark, there is no issue.

## Environment
Profanity, version 0.8.1dev.master.c9fcd018
Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.12.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16)
GTK icons: Enabled

**Comment by jubalh** [comment]
So you are saying the regular roster (not occupants in a MUC) are shown as offline if you have no autojoin bookmarks for a MUC set?

**Comment by jubalh** [comment]
Can anyone else reproduce this?

**Comment by jubalh** [comment]
@DebXWoody still relevant?

**Comment by jubalh** [comment]
I had this recenlty on one machine as well. Will try to investigate if it happens again.

**Comment by jubalh** [comment]
@DebXWoody it should be working now :)
