### ISSUE TITLE
Always show focused window number in statusbar

### ISSUE THREAD

**Issue by Ppjet6** [profanity-im/profanity#1283]
Profanity version: 3c56b289
libstrophe: strophe/libstrophe@c92fc84

## Expected Behavior
Show the number of the focused window always, even if > 10.

## Current Behavior
Only numbers from 1 to 10 (0) are displayed in the statusbar.

## Possible Solution
Either display the number always alongside other numbers, or alongside the room name maybe (sounds even better).

**Comment by jubalh** [comment]
"focused"? I understand it right what you want is: show all windows in the statusbar. Not just 1 - (max) 10.

**Comment by Ppjet6** [comment]
When I move to Win 42, I want 42 to be displayed in the numbers below as "the window I'm currently in". I assume we're on the same page, I just wasn't sure with the "all windows" you mentioned.

**Comment by kaffeekanne** [comment]
Maybe something like `[1][2][3][…][42]` in the statusline with max visible windows set to 5.

**Comment by jubalh** [comment]
And 42 would be the active window in this case or the last one?

**Comment by janteau** [comment]
> Maybe something like `[1][2][3][…][42]` in the statusline with max visible windows set to 5.

> And 42 would be the active window in this case or the last one?

I think it would be nice to show the current window and the max window count.  Possibly something like: `[1][2][3][…][36][…][42]` where 36 is the currently open window and 42 is the last window.

**Comment by kaffeekanne** [comment]
My example was not thought through very well. @janteau did it much better. Also the active window usually has a highlighted color. But i think you get the idea.
