### ISSUE TITLE
Don't show read windows in the statusbar

### ISSUE THREAD

**Issue by Ppjet6** [profanity-im/profanity#1285]
Profanity version: 3c56b28
libstrophe: strophe/libstrophe@c92fc84

## Expected Behavior
Don't display "read" windows in the window list in the statusbar.

## Current Behavior
Numbers and/or names are displayed in the statusbar from 0 up to 10, always.

## Possible Solution
"read" can be interpreted in different ways, you can use the same behaviour as the trackbar for example (that is, "unread until the bar has reached the last message available in the channel").

There is also a new XEP that might be appropriate for (some of) this: https://xmpp.org/extensions/xep-0430.html

**Comment by jubalh** [comment]
We will need a setting for this in `/statusbar` any idea for names?

**Comment by jubalh** [comment]
`/statusbar show|hide read` :-)
