### ISSUE TITLE
Display when window is scrolled up

### ISSUE THREAD

**Issue by Ppjet6** [profanity-im/profanity#1289]
Profanity version: 3c56b28
libstrophe: strophe/libstrophe@c92fc84

## Expected Behavior
When scrolling up or down using PageUp/PageDown, as long as the window is not following live messages, tell the user.

## Current Behavior
Nothing seems to be displayed, the user doesn't know they're scrolled up.

## Possible Solution
Display a sign in the titlebar or statusbar to indicate the window is scrolled up, or maybe display some more useful information such as the number of messages not shown below etc.

**Comment by jubalh** [comment]
Done in 469fa8f863e7fc0c2db7bc9c576071d5d5529ae7 and fcd69532adc12a2d318fb1c96721db91911a0770.
