### ISSUE TITLE
Move away from autotools

### ISSUE THREAD

**Issue by anahata0108** [profanity-im/profanity#1290]
The GNU autotools are between 20 and 30 years old and have accreted so much legacy and cruft that it's difficult to work on or with them—well, it was always difficult to work with them, but these days it's even worse.

Shell scripts are a horrible pain to work with, awful to maintain and even more bug-prone (to say nothing of the portability problems) and this is only exacerbated by the dependency on m4 of all things. Many projects have successfully moved to something more modern that doesn't have the unneeded legacy of the autotools, and it's (well past) time for profanity to do the same.

**Comment by jubalh** [comment]
Similar to https://github.com/profanity-im/profanity/issues/1002
