### ISSUE TITLE
XEP-0384: OMEMO Encryption 0.4.0+

### ISSUE THREAD

**Issue by Neustradamus** [profanity-im/profanity#1291]
Can you update the XEP-0384: OMEMO Encryption support to 0.4.0+?
- https://xmpp.org/extensions/xep-0384.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.7.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

PS: Not sure that 0.3.0 was complete before:
- https://xmpp.org/extensions/attic/xep-0384-0.3.0.html

**Comment by jubalh** [comment]
We plan to.
Instead of just opening issues on all projects that you know about please check their bugtracker in advance the next time.
If you would have done that you would have found our OMEMO tracker but.
And  you would have found that already 16 days ago we mentioned OMEMO 0.4: https://github.com/profanity-im/profanity/issues/1070#issuecomment-597011572

But it takes time. And we also want the thing to major before adopting.

**Comment by Seirdy** [comment]
For others who stumbled upon this issue looking for an OMEMO 7.0+ client:

Kaidan is planning on [supporting OMEMO v0.7+ only](https://invent.kde.org/network/kaidan/-/issues/254#note_304809) and so is UWPX. There's also a branch of Dino with experimental support.

**Comment by jubalh** [comment]
So we support the "old" OMEMO for now.
Like @Seirdy only few clients support OMEMO 7.0+.
We will stay with the old way for now and later switch to the incompatible new way. Not supporting both most likely.

**Comment by Neustradamus** [comment]
@jubalh: I think it is needed to keep this ticket opens before compatibility.
