### ISSUE TITLE
Profanity becomes unresponsive immediately after connection

### ISSUE THREAD

**Issue by janteau** [profanity-im/profanity#1293]
When connecting to an account, profanity becomes very unresponsive and takes over 10 minutes to become usable.  I'm not sure if it has something to do with my config?

## Expected Behavior

Profanity connects and becomes responsive within a few seconds.

## Current Behavior

Profanity launches, a /connect accountName connects quickly, but creating the Roster and joining the rooms takes more than 10 minutes.  During this time the client is very unresponsive and takes over 10-30 seconds to switch windows.  It does not seem to be receiving messages during this time.  Profanity's CPU usage is not high during this time.

## Steps to Reproduce (for bugs)

1. Launch profanity
2. /connect accountName and provide password
3. Immediately after connection the client becomes unresponsive

## Environment
Profanity, version 0.8.1dev.master.1bcfd4ec

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.17)
GTK icons: Disabled

**~/.config/profanity/profrc:**
```
[omemo]
policy=always

log=on

[connection]
carbons=true
autoping=0

receipts.request=true
receipts.send=true

reconnect=10

[ui]
statuses.console=none
roster.by=none
console.chat=none
console.muc=none
console.private=none
resource.message=false
resource.title=false
history=true
statuses.chat=none
statuses.muc=none

roster.order=name
presence=false
roster.unread=before
roster.count.zero=false
roster.rooms.unread=before
roster.count=off

time.chat=%H:%M
time.muc=%H:%M
time.private=%H:%M
time.console=%H:%M

color.nick=true

color.occupants.nick=true
color.roster.nick=false

roster.rooms.use.name=jid

history.muc.color=regular

[logging]
chlog=true
grlog=true
```

**Comment by jubalh** [comment]
Do you run your own server? Which XMPP server software do you use? Does it work with the same server/account with another client?

**Comment by janteau** [comment]
It is not run by me, but it is a private server ran by a friend.  It's running Prosody.  The same account works fine with Conversations and Gajim.

**Comment by jubalh** [comment]
Would it be possible for your friend to create a test account for me?
And could you come to our MUC and send me the JID and password in private?

That would make debugging easier.

**Comment by jubalh** [comment]
Does it still happen?

**Comment by janteau** [comment]
> 
> 
> Does it still happen?

Yes, just tested it with the latest master (`0.8.1dev.master.cb78ee46`) and it took 9 minutes from the time of connect to the MUC auto-join bookmarks finished joining and it became usable.

**Comment by jubalh** [comment]
I remember you gave me an account on the server. But I forgot whether we found anything out. Do you remember?

**Comment by janteau** [comment]
> 
> 
> I remember you gave me an account on the server. But I forgot whether we found anything out. Do you remember?
> I think I couldn't reproduce it with a fresh account on your server.

That's my memory as well.  When you tried with the account on my server, you didn't experience the issue.

**Comment by jubalh** [comment]
@janteau unfortunately I have no way to debug or reproduce this :(

Can you use gdb to see what it is doing?

**Comment by janteau** [comment]
@jubalh I'd be willing to try.  Could you guide me in how to get started?  You can send me a message in the MUC.

**Comment by janteau** [comment]
I'm no longer experiencing this in 0.9.0.  I will close this issue.

**Comment by jubalh** [comment]
Glad to hear! I did something regarding roster retrieval, I wonder whether it was related. But maybe it was also DebXWoodys ping (etc) stuff.
Anyways, glad it is fixed.
