### ISSUE TITLE
Http upload files are not showing inline in other clients when in OMEMO session

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1311]
When uploading files via http upload other clients show the files inline while they only show the URL when uploading in profanity although it sends the URL OOB.
This is an example from profanity:

```
<message type='chat' xml:lang='en' from='REDACTED' id='ZWQ5NmRkOGQtNTcyMy00YWU3LWE0YzItYjAzMDBkMTJiOTIzNWMxMmVkYjJiYWIxODFkMmZjZTkyOGU2NDQxYmMwNzY5ZWEyZTliZWZhZjgzYTBiMzgyNTgyOWFkODJiYzc3OA==' to='REDACTED'>
<body>REDACTED</body>
<active xmlns='http://jabber.org/protocol/chatstates'/>
<x xmlns='jabber:x:oob'>
<url>REDACTED</url>
</x>
<request xmlns='urn:xmpp:receipts'/>
</message>
```
This is a message from another client where the image is shown inline in e.g. Conversations:

```
<message type='chat' to='REDACTED' from='REDACTED' xml:lang='en'>
<x xmlns='jabber:x:oob'>
<url>REDACTED</url>
</x>
<body>REDACTED</body>
</message>
```
I assume other clients expect only the OOB-URL and the body and get confused by the additional `<request xmlns='urn:xmpp:receipts'/>` and `<active xmlns='http://jabber.org/protocol/chatstates'/>`. I am not sure if it is an issue with profanity or the other clients.

## Expected Behavior
Files uploaded with profanity are shown inline in clients supporting this.

## Current Behavior
Files uploaded with profanity are not shown inline in clients supporting this.

## Possible Solution
Don't send chatstates and don't request receipts for http-uploads?

## Steps to Reproduce (for bugs)
1. Have a client showing http uploads inline running (e.g. Conversations)
2. Send an image to (1) from another client using Conversations
3. See the image embedded in the message in (1)
4. Send an image to (1) from profanity
5. See the image is not embedded in (1)

## Context
Uploading images from profanity is irritating conversations users as they have to open the link in the browser instead of downloading it in the client.

## Environment
* Debian Bullseye (Testing)

```
Profanity, version 0.8.1dev.master.c8233a4a
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.18rc1)
GTK icons: Enabled
```

**Comment by mdosch** [comment]
According to @iNPUTmice the only requirement is that the body needs to be equal to the OOB URL, which is the case so I don't understand why it doesn't work.

**Comment by wstrm** [comment]
I am not seeing this behavior. The image is embedded for me when sending from Profanity to Conversations. I also verified the same with ChatSecure.

**Comment by mdosch** [comment]
Ok, I did some more testing and figured out that it only shows you the link only when using OMEMO. Sorry for the confusion. I'll have to get some raw xml of those OMEMO messages later.

**Comment by jubalh** [comment]
I think we send the same when using OMEMO.
So maybe it's Conversations treating them differently when in an OMEMO session?

**Comment by mdosch** [comment]
Yes, because in omemo you shouldn't use x:oob as only the body get's encrypted.

Am April 11, 2020 10:50:38 AM UTC schrieb Michael Vetter <notifications@github.com>:
>I think we send the same when using OMEMO.
>So maybe it's Conversations treating them differently when in an OMEMO session?
>

**Comment by wstrm** [comment]
So this will be "fixed" when #1262 has been implemented. :)

**Comment by jubalh** [comment]
@mdosch now that @1262 is done, does this work for you?

**Comment by mdosch** [comment]
Am 9. Dezember 2020 09:40:36 UTC schrieb Michael Vetter <notifications@github.com>:
>@mdosch now that @1262 is done, does this work for you?
>

works 😃
