### ISSUE TITLE
profanity-0.8.1 does not build on fedora 32

### ISSUE THREAD

**Issue by ibotty** [profanity-im/profanity#1314]
On fedora 32 profanity-0.8.1 does not build due to multiple definition of `lock` and `upload_processes`.

```
[...]
libtool: link: gcc -Wall -Wno-deprecated-declarations -I./src -g -O2 -pthread -o profanity src/xmpp/contact.o src/log.o src/common.o src/profanity.o src/xmpp/chat_session.o src/xmpp/muc.o src/xmpp/jid.o src/xmpp/chat_state.o src/xmpp/resource.o src/xmpp/roster_list.o src/xmpp/capabilities.o src/xmpp/session.o src/xmpp/connection.o src/xmpp/iq.o src/xmpp/message.o src/xmpp/presence.o src/xmpp/stanza.o src/xmpp/roster.o src/xmpp/bookmark.o src/xmpp/blocking.o src/xmpp/form.o src/xmpp/avatar.o src/event/common.o src/event/server_events.o src/event/client_events.o src/ui/window.o src/ui/core.o src/ui/titlebar.o src/ui/statusbar.o src/ui/inputwin.o src/ui/screen.o src/ui/console.o src/ui/notifier.o src/ui/window_list.o src/ui/rosterwin.o src/ui/occupantswin.o src/ui/buffer.o src/ui/chatwin.o src/ui/mucwin.o src/ui/privwin.o src/ui/confwin.o src/ui/xmlwin.o src/command/cmd_defs.o src/command/cmd_funcs.o src/command/cmd_ac.o src/tools/parser.o src/tools/http_upload.o src/tools/autocomplete.o src/tools/tinyurl.o src/tools/clipboard.o src/config/files.o src/config/conflists.o src/config/accounts.o src/config/tlscerts.o src/config/account.o src/config/preferences.o src/config/theme.o src/config/color.o src/config/scripts.o src/plugins/plugins.o src/plugins/api.o src/plugins/callbacks.o src/plugins/autocompleters.o src/plugins/themes.o src/plugins/settings.o src/plugins/disco.o src/ui/tray.o src/plugins/c_plugins.o src/plugins/c_api.o src/otr/otrlibv4.o src/otr/otr.o src/main.o -Wl,--export-dynamic  -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lcurl -lgcrypt -lotr -lreadline -lm -lncursesw -ltinfo /usr/lib64/libstrophe.so -lssl -lcrypto -lexpat -lresolv -ldl -pthread -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/lib64

/usr/bin/ld: src/common.o:/var/home/tf/src/vendor/profanity-spec/profanity-0.8.1/./src/tools/http_upload.h:60: multiple definition of `upload_processes'; src/log.o:/var/home/tf/src/vendor/profanity-spec/profanity-0.8.1/./src/tools/http_upload.h:60: first defined here

[...]
/usr/bin/ld: src/main.o:/var/home/tf/src/vendor/profanity-spec/profanity-0.8.1/src/profanity.h:46: multiple definition of `lock'; src/profanity.o:/var/home/tf/src/vendor/profanity-spec/profanity-0.8.1/src/profanity.h:46: first defined here

collect2: error: ld returned 1 exit status
```

**Comment by jubalh** [comment]
I don't see any multiple definitions.

**Comment by ibotty** [comment]
me neither!  But ld complains.

**Comment by jubalh** [comment]
I don't know why you didnt include the commands you are running. It makes it hard to help.

**Comment by ibotty** [comment]
Sorry for not being as verbose. The interesting command is in line 1
```
gcc -Wall -Wno-deprecated-declarations -I./src -g -O2 -pthread -o profanity src/xmpp/contact.o src/log.o src/common.o src/profanity.o src/xmpp/chat_session.o src/xmpp/muc.o src/xmpp/jid.o src/xmpp/chat_state.o src/xmpp/resource.o src/xmpp/roster_list.o src/xmpp/capabilities.o src/xmpp/session.o src/xmpp/connection.o src/xmpp/iq.o src/xmpp/message.o src/xmpp/presence.o src/xmpp/stanza.o src/xmpp/roster.o src/xmpp/bookmark.o src/xmpp/blocking.o src/xmpp/form.o src/xmpp/avatar.o src/event/common.o src/event/server_events.o src/event/client_events.o src/ui/window.o src/ui/core.o src/ui/titlebar.o src/ui/statusbar.o src/ui/inputwin.o src/ui/screen.o src/ui/console.o src/ui/notifier.o src/ui/window_list.o src/ui/rosterwin.o src/ui/occupantswin.o src/ui/buffer.o src/ui/chatwin.o src/ui/mucwin.o src/ui/privwin.o src/ui/confwin.o src/ui/xmlwin.o src/command/cmd_defs.o src/command/cmd_funcs.o src/command/cmd_ac.o src/tools/parser.o src/tools/http_upload.o src/tools/autocomplete.o src/tools/tinyurl.o src/tools/clipboard.o src/config/files.o src/config/conflists.o src/config/accounts.o src/config/tlscerts.o src/config/account.o src/config/preferences.o src/config/theme.o src/config/color.o src/config/scripts.o src/plugins/plugins.o src/plugins/api.o src/plugins/callbacks.o src/plugins/autocompleters.o src/plugins/themes.o src/plugins/settings.o src/plugins/disco.o src/ui/tray.o src/plugins/c_plugins.o src/plugins/c_api.o src/otr/otrlibv4.o src/otr/otr.o src/main.o -Wl,--export-dynamic  -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lcurl -lgcrypt -lotr -lreadline -lm -lncursesw -ltinfo /usr/lib64/libstrophe.so -lssl -lcrypto -lexpat -lresolv -ldl -pthread -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/lib64
```

I got to that state with the usual `./configure && make`.

```
> rpm -q gcc binutils make
gcc-10.0.1-0.11.fc32.x86_64
binutils-2.34-2.fc32.x86_64
make-4.2.1-16.fc32.x86_64
```

**Comment by jubalh** [comment]
Are you calling make or running this gcc line yourself? oO

**Comment by ibotty** [comment]
make directly.  But it happens as well with the direct invocation of the command (that is run by make).

**Comment by jubalh** [comment]
I'll update my system and see what happens here with gcc 10.
The next time just use the template we created for issues. It's there for a reason.
And include _all_ relevant info.

**Comment by wstrm** [comment]
> I got to that state with the usual ./configure && make.

You ran `./bootstrap.sh` before that, right?

**Comment by ibotty** [comment]
I did not (is that neccessary when using a release-tarball?), but now having done that, I get the same output/problem.

**Comment by jubalh** [comment]
> I did not (is that neccessary when using a release-tarball?)

With the release tarball it's not needed.

**Comment by wstrm** [comment]
Sounds like we should add Fedora to the CI ;) 
-- 
MVH/Regards, William Wennerström.
Phone: +46 (0) 707 21 82 10

**Comment by jubalh** [comment]
> Sounds like we should add Fedora to the CI ;)

Indeed :D

**Comment by jubalh** [comment]
It's sad that Fedora still doesn't have any Profanity package :(((

**Comment by holgersson32644** [comment]
Hi, gcc-10 sets ```-fno-common``` as a default flag. This short note explains the root of the problem and how to fix it: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common)
-- and to tease a bit: Gentoo has a profanity package (outdated, but still :-P)!

**Comment by jubalh** [comment]
@ibotty can you tell me the equivalents of No match for argument:
glibc-locale
libXss-devel
libexpat-devel
libgpgme-devel
in Fedora?
Or just tell me all the deps you needed to install for Profanity.

**Comment by ibotty** [comment]
I don't know what 'No match for argument' is.  I assume you mean packages that need to be installed.

For reference, the spec file I am using is the following (fixed with passing -fnocommon with the define _legacy_common_support).
 https://paste.centos.org/view/c2b0f1c1

The libstrophe spec file I use is https://paste.centos.org/view/762cf1a3.  This might not be necessary (I patch in auth_legacy_enabled in src/conn.c because of a legacy xmpp server).

You can build the spec file with fedpkg (in package fedpkg)
     fedpkg local

The sources (if you don't already have them) can be downloaded with
    spectool -gf profanity.spec

**Comment by ibotty** [comment]
Argh.  Forgot to include the information regarding the packages.

 * glibc-locale is similar to the fedora `glibc-all-langpacks` package.

 * Fedora does not prepend every library with lib. So expat-devel is the devel package of expat, analogous gpgme-devel.

 * `dnf whatprovides /usr/lib64/libXss.so` tells me that it's part of `libXScrnSaver-devel`.  I guess that's the right package.

**Comment by jubalh** [comment]
@ibotty oh you have a spec file!
Does that mean you'll maintain the Fedora package? ;)

**Comment by ibotty** [comment]
I'll try to find time starting the process, yes.

**Comment by jubalh** [comment]
Awesome. If you need help let us know.
