### ISSUE TITLE
Autoping response timed out - Lost connection

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1315]
Starting profanity. Profanity starts and joins the MUCs via autojoin. Profanity reconnects because of autoping timeout:

17:14:19 - Autoping response timed out after 20 seconds.
17:14:19 - Lost connection.

## Environment
Profanity master on Debian Buster

**Comment by DebXWoody** [comment]
I changed the implementation of `iq.c`: `void iq_autoping_check(void)`

```
     gdouble elapsed = g_timer_elapsed(autoping_time, NULL);
     unsigned long seconds_elapsed = elapsed * 1.0;
     gint timeout = prefs_get_autoping_timeout();
+    log_warning("seconds_elapsed %d", seconds_elapsed);
+
     if (timeout > 0 && seconds_elapsed >= timeout) {
         cons_show("Autoping response timed out after %u seconds.", timeout);
-        log_debug("Autoping check: timed out after %u seconds, disconnecting", timeout);
+        log_warning("Autoping check: timed out after %u seconds, disconnecting", timeout);
         iq_autoping_timer_cancel();
-        session_autoping_fail();
+        //session_autoping_fail();
     }
```

Write the seconds_elapsed into logfile (warning) and disable the `session_autoping_fail()` - do not reconnect. - Because the session is not closed.


```
...
prof: WRN: seconds_elapsed 19
prof: WRN: seconds_elapsed 20
prof: WRN: Autoping check: timed out after 20 seconds, disconnecting
prof: DBG: iq_autoping_timer_cancel
prof: DBG: Autoping: Sending ping request: YTExNTQ1ZWEtNzRhOC00NWI0LWIzNWItYTQ2M2ViMjc5ZGVmMmYzOGE0MTNkNTM2MmY5MGM1YjFmYzM2ODg0YTk1OTA5MzQ2NmUxMjU5M2VlOWM2NjNkMzI0MmUxZmI0YWY2Mw==
14/04/2020 17:51:45: conn: DBG: SENT: <iq id="YTExNTQ1ZWEtNzRhOC00NWI0LWIzNWItYTQ2M2ViMjc5ZGVmMmYzOGE0MTNkNTM2MmY5MGM1YjFmYzM2ODg0YTk1OTA5MzQ2NmUxMjU5M2VlOWM2NjNkMzI0MmUxZmI0YWY2Mw==" type="get"><ping xmlns="urn:xmpp:ping"/></iq>
prof: WRN: seconds_elapsed 0
prof: WRN: seconds_elapsed 0
prof: WRN: seconds_elapsed 1
...
```
Profanity sends the autoping, but doesn't get feedback from Server.

```
17:42:58 ! -> Autojoined muc@domain.tld as User (21).
17:43:33 - Roster disabled (was enabled)
17:43:59 - Autoping response timed out after 20 seconds.
17:45:00 - Autoping response timed out after 20 seconds.
17:46:01 - Autoping response timed out after 20 seconds.
17:47:01 - Autoping response timed out after 20 seconds.
17:48:02 - Autoping response timed out after 20 seconds.
17:49:03 - Autoping response timed out after 20 seconds.
17:50:04 - Autoping response timed out after 20 seconds.
17:51:04 - Autoping response timed out after 20 seconds.
17:52:05 - Autoping response timed out after 20 seconds.
17:53:06 - Autoping response timed out after 20 seconds.
17:54:07 - Autoping response timed out after 20 seconds.
17:55:07 - Autoping response timed out after 20 seconds.
17:56:08 - Autoping response timed out after 20 seconds.
17:56:51 - -- xxxxxx (Conversations.xxx) is offline
```
After 13*20 seconds there is feedback from Server.

**Comment by DebXWoody** [comment]
Logging into the logfiles, there is a log of 8,8MB.

 2635 14/04/2020 17:56:48: prof: WRN: seconds_elapsed 0
 2636 14/04/2020 17:56:49: xmpp: DBG: RECV: <iq id="MDZlMzM5NWQtMjYwY
.... lot of OMEMO preKeyPublic keys ...

I checked the log file:

`grep "eu.siacs.conversations.axolotl.devicelist" profanity.* |grep RECV|while read line; do SIZE=`echo $line | wc -c`; if [ $SIZE -ge 1000 ]; then echo $line; fi ; done`

There is an account which a response of 2448 lines of device list.
Retested with gajim as well:
```
<iq xmlns="jabber:client" to="me@domain.tld" id="gfetch0" type="result" from="user@domain.tld">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.devicelist">
<item id="5E0CE8B12345">
<list xmlns="eu.siacs.conversations.axolotl">
<device id="123549123" />
<device id="1237461234" />
<device id="1234551234" />
<device id="123486123" />
<device id="123752123" />
</list>
</item>
<item id="5EC13CC12334C">
<list xmlns="eu.siacs.conversations.axolotl">
<device id="1234491234" />
</list>
</item>
<item id="5F083D12F2C712">
<list xmlns="eu.siacs.conversations.axolotl">
<device id="123457123" />
```
This list has more than 300 items.

**Comment by jubalh** [comment]
@DebXWoody what's current status of this one? :)

**Comment by DebXWoody** [comment]
> @DebXWoody what's current status of this one? :)

Good question, next question? 

I think there are more than one issues with this lost connection.

* #1318 - merged - Problem with OMEMO MUC
* #1343 - this should help also, if there are other incoming messages

I'm not sure about the implementation of OMEMO device list requests, yet. If profanity has connected to the server, profanity will request all contacts in the roster during startup. Maybe #1343 will help solve the problem. Anyway, I think there should be another way to fetch the OMEMO Keys - maybe setup by step in a background tasks.

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1343 got merged.
Please give feedback here if this still occurs or is now fixed. (@mdosch I think you suffered from this recently)

**Comment by equation-group** [comment]
@jubalh still occuring while talking to someone privately using omemo
