### ISSUE TITLE
Add sendxmpp ability

### ISSUE THREAD

**Issue by hashworks** [profanity-im/profanity#1322]
It would be nice to have a similar ability like [sendxmpp](https://github.com/lhost/sendxmpp). What I'm thinking of is a way to provide commands to send after connect:

`profanity -a hashworks@foo.org -e '/msg someone@bar.org Hello!' -e '/quit'`

Implementing it this way would add other capabilities as well.

The reason I can't use `sendxmpp` is that it doesn't support stuff like OMEMO.

**Comment by jubalh** [comment]
Well, I can see some value in that.
But also some things that I don't like.

Why not just request OMEMO support in sendxmpp instead?
AFAIK there are nice python libs.

And I think https://codeberg.org/Anoxinon_e.V./xmppc is also a good candidate for this. I think they already work on OMEMO support, so probably this project is what you are actually looking for.

@DebXWoody maybe you can comment regarding xmppc.

**Comment by mdosch** [comment]
Afaik the CLI tool from salut a toi is the only sendxmpp-like tool with OMEMO support at the moment. Maybe you can have a look at this.

Am April 22, 2020 11:38:07 AM UTC schrieb Michael Vetter <notifications@github.com>:
>Well, I can see some value in that.
>But also some things that I don't like.
>
>Why not just request OMEMO support in sendxmpp instead?
>AFAIK there are nice python libs.
>
>And I think https://codeberg.org/Anoxinon_e.V./xmppc is also a good candidate for this. I think they already work on OMEMO support, so probably this project is what you are actually looking for.
>
>@DebXWoody maybe you can comment regarding xmppc.
>

**Comment by hashworks** [comment]
I'll keep an eye on xmppc, thanks. I would like to avoid sat-xmpp (Python2 and AUR package seems broken).

**Comment by jubalh** [comment]
> Python2

it's dead :)

> and AUR package seems broken).

Doesnt surprise me ;D

**Comment by DebXWoody** [comment]
> And I think https://codeberg.org/Anoxinon_e.V./xmppc is also a good candidate for this. I think they already work on OMEMO support, so probably this project is what you are actually looking for.

xmppc just supports to display the OMEMO device list and fingerprints. It should be possible to send a chat message with pgp (XEP-0027) and openpgp (XEP-0373) via xmppc.

OMEMO has some pros and cons. For **my** use cases I prefer to use OpenPGP instead of OMEMO.

**Comment by hashworks** [comment]
> xmppc just supports to display the OMEMO device list and fingerprints

Are there plans to support OMEMO messaging?

**Comment by jubalh** [comment]
I'm going to close this if that's okay.
I think what you really want is one of the programs  mentioned above supporting omemo.
A general -e for executing something right at the start of profanity might be nice though but I don't see what it brings (other than for your special use case) so I think we won't implement it for now.
