### ISSUE TITLE
Own history messages are not displayed in MUC

### ISSUE THREAD

**Issue by guigot** [profanity-im/profanity#1323]
Hello, 

Here is a report bug for a logging problem.

Thanks for your work !

## Expected Behavior
My own history messages should be displayed in MUC at reconnection

## Current Behavior
When i reconnect to a MUC, only other users history messages are displayed
From `git bisect`, this bug appears from the commit 4ecd4dea6a0a4c216a57d039dc7dc01d5e41d68a

## Steps to Reproduce
1. Connect to an existing MUC
2. Write messages
3. Leave Profanity and restart it
4. Connect to the MUC

## Context 
Logging options (chat and group) are activated

## Environment
Server is Metronome 3.13.4
Debian sid

```
Profanity, version 0.8.1dev.master.4a712fcc
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.18)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
Thanks for your report, and of taking the time to git bisect!

I'll take a look when I find some time.
Right now I think this should only happen if you are connected with the same account twice using Profanity on the same machine.

And on current git master we started to implement a SQL backend. Once this is finished we won't need the check like it's done right now but can test the DB for filtering out our own messages so we don't get MUC reflections twice.

**Comment by jubalh** [comment]
So with how many clients are you connected and which ones?

**Comment by guigot** [comment]
Only the one described above.

I don't know if it can help but i discovered something by chance : my history messages are correctly displayed if they come from Profanity on a different machine (the other's version is 0.8.1).

**Comment by jubalh** [comment]
> my history messages are correctly displayed if they come from Profanity on a different machine (the other's version is 0.8.1).

Like I said, that's to be expected. Because it has a different identifier.

**Comment by toogley** [comment]
@guigot hey :)

to cite the documentation:

```
 Hint: To be able to receive messages from your other devices you need to enable carbons. Also trust your own devices analogous to your buddies fingerprints, as described in the next paragraph.

    /carbons on
```

So i think you are just missing that. So i vote to close this issue.
