### ISSUE TITLE
Status with PGP shows offline in titlebar

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1327]
## Expected Behavior
Profanity shows the current status of the connection. ([TLS] / [online])

## Current Behavior
src/event/server_events.c line 156 is calling ui_init()  🤨 First, profanity goes online (titlebar looks good). I have to enter my PIN. After this, this method is called. ui_init will set OFFLINE and TLS to no.
## Possible Solution

```
git diff origin/master bughunter -- src/event/server_events.c
diff --git a/src/event/server_events.c b/src/event/server_events.c
index 057af9bf..79ac0194 100644
--- a/src/event/server_events.c
+++ b/src/event/server_events.c
@@ -153,7 +153,6 @@ sv_ev_roster_received(void)
         win_clear(win);
         theme_init(theme);
         prefs_free_string(theme);
-        ui_init();
         ui_resize();
         ui_show_roster();
     }

```

## Environment
Profanity, version 0.8.1dev.bughunter.d20b83cb

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Enabled (libgpgme 1.12.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16)
GTK icons: Enabled

**Comment by jubalh** [comment]
Thanks for your work @DebXWoody !
