### ISSUE TITLE
Feature request - XEP-0373: OpenPGP for XMPP (OX)

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1331]
Feature request for profanity: Implementation of XEP-0373: OpenPGP for XMPP (OX)

Information:
* https://xmpp.org/extensions/xep-0373.html
* https://xmpp.org/extensions/xep-0374.html
* https://xmpp.org/extensions/xep-0380.html

**Comment by DebXWoody** [comment]
Idea
Implementation like it is for pgp in the current version of profanity. Instead of `/pgp` command, we can use the command `/ox`. There are some difference between pgp (0027) and openpgp (0373).

* The message can be <signcrypt/>, <sign/> or <crypt/>, not encrypted, only
* signed presences is not part of XEP-0380 and not XEP-0373
* Lookup for a key can be done via XMPP URI (see https://xmpp.org/extensions/xep-0373.html#openpgp-user-ids)
* OX don't use ascii-armor: https://xmpp.org/extensions/xep-0373.html#openpgp-ascii-armor

**Comment by DebXWoody** [comment]
There is a small example here: https://codeberg.org/Anoxinon_e.V./xmppc/src/branch/master/src/mode/openpgp.c#L69

**Comment by DebXWoody** [comment]
I started to implement a `/ox` command for profanity:
https://github.com/DebXWoody/profanity/commits/feature/ox-devel

The command `/ox keys` shows all keys of the gnupg's keyring. Same like `/pgp keys`.

The command `/ox contacts` looks into the keyring and search for uid with a XMPP-URI.

```
OpenPGP keys:
56ECD7B83A173A355C7C18400BF9E946C3DD112D - xmpp:stefan@domain4.tld (not in roster)
2909AF6BF3D6DF3BA1B1805C539F89DC6083AA33 - xmpp:anna@domain3.tld
6D740FE2B1D55DCD74CAAD95AC1A1629095EEDAE - xmpp:alice@domain2.tld (not in roster)
A8431A0170B3EBB564CE294D0C1CE873ED588C2B - xmpp:alice@domain1.tld (not in roster)
7FA1EB8644BAC07E7F18E7C9F121E6A6F3A0C7A5 - xmpp:doctor.snuggles@domain.tld (not in roster)
```

**Comment by DebXWoody** [comment]
Note: https://github.com/profanity-im/profanity/blob/master/src/event/client_events.c#L135

**Comment by DebXWoody** [comment]
Current status for **basic** implementation of:

- [X] Display help information - `/help ox`
- [X] Auto completion of ox command
- [X] List all known keys which are stored in the gnupg's keyring - `/ox keys`
- [X] List all knows keys which are stored in the gnupg's keyring with a XMPP-URI - `/ox contacts`
- [X] Start a OX session - ¸`/ox start`
- [X] Send a OX message
- [X] Receive a OX message - partially implemented
- [ ] Announce public key on PEP - `/ox announce`
- [ ] Discover public keys - `/ox discover`
- [ ] Request public key - `/ox request`

**Comment by jubalh** [comment]
Basic functionality merged in 2c94ee5a88f64332a3f41f41a4d314fc52200e31.

**Comment by DebXWoody** [comment]
Basic functionality for `/ox announce` command is in Pull Request #1390 - can be used to test push a key and should work with gajim :+1:

Add a UID for XMPP like this:

```
gpg --quick-add-uid 12345678901234567890ABCDEF xmpp:user@domain.tld
```
This command will add a new UID with the XMPP-URI.

The user can export his like this:

```
gpg  --export --export-options export-minimal  --export-filter 'keep-uid=uid =~ xmpp:user@domain.tld' 12345678901234567890ABCDEF > /tmp/myxmpppublickey.gpg
```

This command will export the key into a file `/tmp/myxmpppublickey.gpg`

In `profanity` the user can announce his key via `/ox announce /tmp/myxmpppublickey.gpg`

**Comment by jubalh** [comment]
@DebXWoody please update your comment above to check the cases that are handled now. In case all is handled please also close corresponding issues.

**Comment by jubalh** [comment]
@DebXWoody ping

**Comment by DebXWoody** [comment]
@jubalh pong :-)

Few days back I implemented "ox discover" will display the keys which are stored within the PEP.

`/ox discover <jid> ` and ` /ox request <jid> <fingerprint>`

```
/ox discover user@domain.tld
19:57:29 - Discovering Public Key for user@domain.tld
19:57:29 - A1234567890ABCDEF123456789ABCDEF123456789             
```

The command request will request for the key and import the key into the local keyring

```
/ox request user@domain.tld A1234567890ABCDEF123456789ABCDEF123456789
20:00:46 - Requesting Public Key A1234567890ABCDEF123456789ABCDEF123456789 for user@domain.tld
20:00:46 - Public Key imported
```

Sometimes there is still a segfault, but I didn't find time to investigate. I will continuously work on fixing and improve the ox implementation.

**Comment by jubalh** [comment]
Great! Thanks for the feedback!

**Comment by jubalh** [comment]
So the feature is implemented.

> Sometimes there is still a segfault, but I didn't find time to investigate. I will continuously work on fixing and improve the ox implementation.

Let's have new issues for this ;)
