### ISSUE TITLE
Rework - autoping

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1333]
Profanity is doing a lot of thinks during startup. This can take some time. It may happen, that there in a response of autoping to late, because of to much traffic on the road.

**Comment by DebXWoody** [comment]
Example move `iq_autoping_timer_cancel();` into `src/xmpp/iq.c:_iq_handler`

**Comment by DebXWoody** [comment]
> Why do you cancel timer on every incoming IQ stanza? When does it suppose to start again?
> @mdosch
> mdosch 5 days ago Contributor
> 
> Every IQ you receive proofs you're connected to the server so they are as good as ping result I guess.
> @pasis
> pasis 5 days ago Member
> 
> I misunderstood the timer semantics. I thought it is always the same timer, but it rather starts on every ping.
> 
> I won't insist on waiting for only ping reply. But consider the following when you decide what to push to master: receiving a stanza after sending a ping doesn't mean that the stanza arrived after ping had been sent. The stanza could reside in kernel's buffers. And in this scenario you will need 1 more ping interval to detect broken connection. This is not a big deal for profanity's usecases, so it is up to you to decide how to proceed.
>

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1343 got merged.
