### ISSUE TITLE
wrong error message in ./configure

### ISSUE THREAD

**Issue by em92** [profanity-im/profanity#1334]
Hi!
Trying to compile profanity. I already have compiled libmesode* files in `/home/eugene/.local/lib`
and libmesode.h in `/home/eugene/.local/include`.
I run this:

## Steps to Reproduce (for bugs)
```
export libmesode_LIBS="-L/home/eugene/.local/libs -lmesode"  # pay attention to typo in directory. It is "libs", but must be "lib" 
export libmesode_CFLAGS="-I/home/eugene/.local/include"
./configure --prefix=/home/eugene/.local
```
## Expected Behavior

Expecting message like "-lmesode" not found.

## Current Behavior
```
checking for libmesode... yes
checking for ncursesw... yes
checking for wget_wch support in ncursesw... no
configure: error: ncurses does not support wide characters
```

## Possible Solution
Maybe adding extra check when trying to compile this
```
int main() {
  return 0;
}
```

config.log attached. There is `/usr/bin/ld: cannot find -lmesode`

[config.log](https://github.com/profanity-im/profanity/files/4597213/config.log)

**Comment by DebXWoody** [comment]
Did you install libmesode also in your distribution? Will `pkg-config --libs libmesode` find mesode?

**Comment by em92** [comment]
> Did you install libmesode also in your distribution? Will `pkg-config --libs libmesode` find mesode?

```
$ pkg-config --libs libmesode
Package libmesode was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmesode.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmesode' found
```

libmesode.pc existed in my `~/.local/lib/pkgconfig/libmesode.pc` but I didn't set PKG_CONFIG_PATH. So I configurated environment variables `libmesode_LIBS` and `libmesode_CFLAGS` (see first message, there is a comment about a typo).

Anyway, the problem is that error message says "There is a problem with wget_wch" but in fact it just didn't find libmesode with incorrect settings. So I spent time searching solution how to fix problem with wget_wch meanwhile everything was fine with it.

**Comment by pasis** [comment]
I've added additional check that a simple program builds with libstrophe/libmesode. This check makes sense for libstrophe, since the library is not common for all Linux/*nix distributions and users need to install it manually.

But please don't ask to do this for every library that is present in most distributions :).
