### ISSUE TITLE
playerctl status (mpris)

### ISSUE THREAD

**Issue by basedtho** [profanity-im/profanity#1335]
## Expected Behavior

i'd like a way to automatically change my current status according to what's playing on my spotify at the moment

**Comment by jubalh** [comment]
Then you have to write a [plugin](https://github.com/profanity-im/profanity-plugins) for it.
Or create a [bounty](https://www.bountysource.com/teams/profanity/issues) for it.

This is by no means a requirement for Profanitys core.
