### ISSUE TITLE
Incoming typing notifications are no longer showing

### ISSUE THREAD

**Issue by moppman** [profanity-im/profanity#1339]
## Expected Behavior
Make sure you have typing notifications enabled via `/intype on`. 
When a contact is typing, I should be notified in the console and at the top of the message tab (and optionally in a desktop notification).

## Current Behavior
No typing notification is shown if a contact is typing. The contact has outgoing typing notifications enabled. 

## Context
I noticed this behavior a while ago and wasn't sure when it was introduced. I tried `git bisect` and found the last good commit was 8bfb175d03925c8a468eac0660189c86093be2cd. The first bad commit  is 37c2bd9334f67f0e4fd15b4694b35f09b80e8c9b, but there are a couple commits before that I couldn't compile into a build because they belong to the sql implementation branch. 
The incoming typing notification messages show up in profanity's `xml console`

## Environment
* Profanity, version 0.8.1dev.master.7d7f0ef5
* Debian 10

**Comment by jubalh** [comment]
Nice written report, thank you!
Will try to take a look soon.

**Comment by jubalh** [comment]
@moppman can you test latest master?

**Comment by moppman** [comment]
> @moppman can you test latest master?

I just did,  looks fine! Thank you :+1:
