### ISSUE TITLE
carbon copied messages disappear in log on window reopen

### ISSUE THREAD

**Issue by janteau** [profanity-im/profanity#1342]
Messages that are sent from the user's JID are missing when a 1:1 chat window are reopened.

## Expected Behavior

When a 1:1 chat window is reopened, the back log should contain the whole conversation - the received messages, as well as the messages sent by the user.

## Current Behavior

When the a 1:1 chat window is opened the back log only contains messages sent by Profanity and the received messages.  It seems the issue may be related to carbons not being displayed in the back log.  All messages do appear in the actual chat log files.

## Steps to Reproduce (for bugs)

1. Open 1:1 chat, send messages from profanity and other client, other user responds.
2. Close and then reopen 1:1 chat
3. Messages sent by other devices will not be displayed, but profanity sent messages and other user's messages are.

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version

```
Profanity, version 0.8.1dev.master.cb78ee46
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.17)
GTK icons: Disabled
```

**Comment by jubalh** [comment]
@janteau please test latest master and give us feedback here.

**Comment by janteau** [comment]
@jubalh it seems to still perform the same with `0.8.1dev.master.86f0e0ea`.  If I close a 1:1 OMEMO (not sure if it's that's important) chat with messages between my contact and me (messages sent from Conversations on my phone), when I reopen the window in profanity, only my contact's messages are displayed.

**Comment by jubalh** [comment]
@mdosch can you confirm this?

**Comment by mdosch** [comment]
When I closed a OMEMO chat window where I had some messages sent before and reopened it most of my messages where not shown except the very last one but it was shown as sent by the other person. 😲

**Comment by jubalh** [comment]
Can you guys check whether the received messages are in the database?
`sqlitebrowser ~/.local/share/profanity/database/your_account/chatlog.db`.

So to reproduce:
- one needs an OMEMO session
- one needs to be connected with Profanity and another client (with one account)

result: everthing we write from another client will be displayed in Profanity but when we close and reopen the window only what the other person sent and what we sent from Profanity will be shows

Did I understand this right?

**Comment by mdosch** [comment]
Open chat window in profanity, send a message and send a message by two other clients.
![2020-05-27-113443_grim](https://user-images.githubusercontent.com/5103003/83004514-0f9ba180-a010-11ea-86d9-c70b77101c12.png)

Close window and open it again.
![2020-05-27-113504_grim](https://user-images.githubusercontent.com/5103003/83005084-b1bb8980-a010-11ea-833d-a29642513f2d.png)


Sqlite shows some messages with the recipient in from instead of the sender. Ignore blue messages, they came in between from a MUC.
![2020-05-27-115240_grim](https://user-images.githubusercontent.com/5103003/83005050-a700f480-a010-11ea-8e8c-fe9be375e2ac.png)

**Comment by janteau** [comment]
What @mdosch pointed out is what I'm seeing as well.  Messages sent by my other client are showing as sent from the other other person instead of as being sent by me.

This may have changed with `0.8.1dev.master.86f0e0ea`, I just may not have noticed when I commented previously.

**Comment by jubalh** [comment]
@janteau , @mdosch please test latest master :)

I'm not entirely sure whether carbon is now handled perfectly. So would be super nice if you can test all scenarios that you can think of.
I tested what came to mind and seems good.

**Comment by mdosch** [comment]
Looks good from a first test. :D

**Comment by jubalh** [comment]
@janteau said the same in the MUC. Going to close this. Feel free to reopen in case you notice something strange.
