### ISSUE TITLE
OMEMO encryption is not shown in header bar

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1346]
Usually it was shown in the header bar when a chat was encrypted OMEMO but now this information is no more shown. Also there is a `]` without opening `[`.

![2020-05-26-143734_grim](https://user-images.githubusercontent.com/5103003/82917316-9189bd00-9f73-11ea-8396-49fcafe6a212.png)

## Expected Behavior
It should be shown in the header bar if the chat is OMEMO encrypted.

## Current Behavior
It is not shown in the header bar if the chat is OMEMO encrypted.

## Environment
```
profanity --version                                                                     :(
Profanity, version 0.8.1dev.master.de8975c0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.3)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
I assume that happened when fixing https://github.com/profanity-im/profanity/issues/715
