### ISSUE TITLE
Profanity 0.9.0 can't be compiled on Debian stable

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1358]
0.9.0 was supposed to work on current Debian stable.
For this reason we decreased glib versions in the past.

The workarounds were supposed to only be removed for 0.10.0.

When merging https://github.com/profanity-im/profanity/issues/1236 I did not check whether Debian stable has libstrophe 0.9.3.

See comment: https://github.com/profanity-im/profanity/issues/1236#issuecomment-641631541

0.9.1 should have legacy auth optional or remove it and only have it in 0.10.0.

**Comment by jubalh** [comment]
Done in https://github.com/profanity-im/profanity/pull/1360

@licaon-kter can you test whether latest master works for you?

**Comment by licaon-kter** [comment]
Builds fine and runs, thanks
