### ISSUE TITLE
[request merge] Define external commands to open and save URLs according to file types and protocols

### ISSUE THREAD

**Issue by pmaziere** [profanity-im/profanity#1361]
The following changes since commit 74ff38f0bda6e365bdedf29fbd53eedfa520ed74:

  Start new cycle (2020-06-11 10:07:51 +0200)

are available in the Git repository at:

  https://framagit.org/peetah/profanity.git/ revampUrlopen

for you to fetch changes up to 72487041253ae959117e056fce83c4d0017fba34:

  Display default value for /url associated commands (2020-06-12 09:35:55 +0200)

----------------------------------------------------------------
Pierre Mazière (6):
      add aesgcm to urls grabber
      refactor cmd_urlopen
      Add string and string list preferences with option
      Replace /urlopen with /url and adapt /executable
      Add /url autocompletion
      Display default value for /url associated commands

 src/command/cmd_ac.c     |  26 ++++++++++++++++++----
 src/command/cmd_defs.c   |  49 ++++++++++++++++++++++++-----------------
 src/command/cmd_funcs.c  | 190 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------
 src/command/cmd_funcs.h  |   3 ++-
 src/config/preferences.c | 105 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----
 src/config/preferences.h |   5 +++++
 src/ui/console.c         |  14 +++++++-----
 src/ui/window_list.c     |   2 +-
 8 files changed, 343 insertions(+), 51 deletions(-)

**Comment by jubalh** [comment]
Thanks! Will try to take a look soon :)

**Comment by jubalh** [comment]
@pmaziere merged your branch in a test branch ontop of current master.
`/url open https://github.com/profanity-im/profanity` segfaulted.

**Comment by jubalh** [comment]
`/executable` needs to have conisistent indenting:

```
19:30:20 - '/avatar' command (/executable avatar)                                   : xdg-open                                                                
19:30:20 - Default '/url open command' (/executable urlopen)                                 : xdg-open %u                                                    
19:30:20 - Default '/url save' command (/executable urlsave)                                 : curl -o %p %u   
```

**Comment by pmaziere** [comment]
There is a default value in case `/executable` is not configured yet.
The segfault was caused by the URL missing a file extension.
This is now fixed, as well as the `/executable` output indenting.
I also fixed the detection of the URL first level domain as a file extension.
Finally I rebased revampUrlopen branch on top of HEAD.

**Comment by jubalh** [comment]
Thanks, I'll review it again :-)

> BTW: I know I'm a pain :) but I want to keep my contributions centralized in a single repository. I believe that if everybody accepts to create a new account on every git based service, there will never be the slightest possibility of a chance to see interoperability between these services; even if I'm not very confident about it: Gitlab itself does not event consider allowing interoperability between its instances…

I doubt that your action makes GitHub/Gitlab etc change their ways ;) To them it doesn't really matter whether you choose to work like this or not. It has no consequence for them :)

**Comment by jubalh** [comment]
* You need to handle `/url save https://github.com/profanity-im/profanity/issues/1361` with no location properly.
* And where will it save it the location if we use `/url save https://github.com/profanity-im/profanity/issues/1361 test` ?
* You should print out a message if url save worked. Including the location of the file.
* you do `suffix = g_strdup(suffixStart);` but don't free it
you do `char *scheme = g_uri_parse_scheme(args[1]);` but dont free it

Will review more once this is adressed :)

**Comment by pmaziere** [comment]
> You need to handle `/url save https://github.com/profanity-im/profanity/issues/1361` with no location properly.

Please, precise 'properly'.
Currently, it is saved in `./1361`, `./` being the path from where profanity was started.

> And where will it save it the location if we use `/url save https://github.com/profanity-im/profanity/issues/1361 test` ?

in `./test`, `./` being the path from where profanity was started.

> You should print out a message if url save worked. Including the location of the file.

Done.

> you do suffix = g_strdup(suffixStart); but don't free it
> you do char *scheme = g_uri_parse_scheme(args[1]); but dont free it

Fixed.

I also fixed other edge cases.

**Comment by jubalh** [comment]
>>    You need to handle /url save https://github.com/profanity-im/profanity/issues/1361 with no location properly.
> Please, precise 'properly'.
> Currently, it is saved in ./1361, ./ being the path from where profanity was started.

Properly: a location that makes sense. Either in a ./local/share/profanity/downloads dir or in ~/Downloads (which we cannot be sure whether it exists or is wanted) or deny this action altogether.

Because if Profanity is installed in /usr/bin/profanity I doubt the user will have rights to save files there ;)

**Comment by pmaziere** [comment]
if Profanity is installed in /usr/bin/profanity it won't necessarily be the path from where it is called.
What about adding a preference for a download directory and set $HOME as default ?
`./local/share/profanity/downloads` does not seem the right place to me, being too deep into the dotfiles hierarchy, hence not the place people are used to navigate.

**Comment by mdosch** [comment]
I'd prefer it hidden there than littering my $HOME.

**Comment by jubalh** [comment]
> I'd prefer it hidden there than littering my $HOME.

Me too. But on the other hand it is just the default location and people could set it somewhere else. And most probably if one actually uses `/url save` instead of `/url open` one wants this file to do something with it. Also one could still use `/url save someurl somelocation` if one wants to do something specific with it. So I'm not sure my this is against or for my own last argument :D 

Maybe someone else has also an opinion and we vote?

**Comment by wstrm** [comment]
I prefer it being saved to `.`, i.e. the path that Profanity was
started. Isn't this the default when retrieving files?

Another application that I can think of is `scrot` that saves the
screenshot in the directory where it was started.

On Mon, Jun 15, 2020 at 03:47:03AM -0700, Michael Vetter wrote:
> > I'd prefer it hidden there than littering my $HOME.
> 
> Me too. But on the other hand it is just the default location and people could set it somewhere else. And most probably if one actually uses `/url save` instead of `/url open` one wants this file to do something with it. Also one could still use `/url save someurl somelocation` if one wants to do something specific with it. So I'm not sure my this is against or for my own last argument :D 
> 
> Maybe someone else has also an opinion and we vote?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/profanity-im/profanity/issues/1361#issuecomment-644053264

-- 
MVH/Regards, William Wennerström.
Phone: +46 (0) 707 21 82 10

**Comment by pmaziere** [comment]
So, to sum it up, we are OK for a new preference that would set the default directory where to save anything downloaded by users on purpose, but we still need to define a default value for this preference. This would, for example, includes downloaded avatars.
right ?

**Comment by jubalh** [comment]
Right I forgot about avatars.

There I chose exactly the nested location `~/.local/share/profanity/avatars` because I personally liked this the most.

But also because:
* [later](https://github.com/profanity-im/profanity/issues/1301) we might want to display them without downloading new each time, so we want a permanent location
* AFAIK the XEP allows for multiple avatars to be uploaded. And we can get notified when a new one is uploaded. So we can automatically download them

So on one side a unified approach would be good. On the other side the purpose of avatar might be a bit different than of `/url save`.

**Comment by pmaziere** [comment]
that is exactly why I precised 'downloaded by users on purpose', to differentiate what could be done behind the scene by profanity, which should be saved in `.local/share/profanity/somewhere` , and what is done on purpose by the users.

**Comment by jubalh** [comment]
default PREF_URL_SAVE_CMD relies on curl which is not installed by default on many linux installations.
We also rely on xdg-default, which probably is not present on headless systems.

Since the user can configure this its not a big deal, but maybe we need to tell about this somewhere.

**Comment by jubalh** [comment]
I squashed the fixing commits together with their original commit and created a PR: https://github.com/profanity-im/profanity/pull/1374
Let's review there.
