### ISSUE TITLE
Expansion of ~ to home directory in eval_password does not work

### ISSUE THREAD

**Issue by huhndev** [profanity-im/profanity#1364]
Since Profanity 0.9, a path included in eval_password can no longer contain a ~, but must be specified completely.

## Expected Behavior
Using `eval_password=gpg2 --batch -q --decrypt ~/path/to/password` should work.

## Current Behavior
Throws an error:
`Error evaluating password, see logs for details.`
and in the log:
`15/06/2020 14:00:00: prof: ERR: Calling 'gpg2 --batch -q --decrypt ~/path/to/password' failed: Child process exited with code 2.`

## Workaround
Specify the full path, e.g.:
`eval_password=gpg2 --batch -q --decrypt /home/user/path/to/password`

## Environment
* Output of `profanity -v`:
```
version 0.9.2dev..
[...]
Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Enabled
```

* Operating System/Distribution: OpenBSD 6.7
* Version of glib: glib2-2.62.6

**Comment by jubalh** [comment]
Probably due to https://github.com/profanity-im/profanity/commit/d92c576aa53505d712715b1acc6344af3262c84f
