### ISSUE TITLE
Handle all types of messages

### ISSUE THREAD

**Issue by pasis** [profanity-im/profanity#1366]
Profanity doesn't handle all message types and silently drops unknown ones.

According to https://tools.ietf.org/html/rfc6121#section-5.2.2, clients should handle all the types and additionally process messages without the type attribute as messages with `normal` type.

Current unknown types are `headline` and `normal`. Also, Profanity drops messages without the attribute.

**Comment by DebXWoody** [comment]
What should happen, when we get a headline message?

`<message type="headline"><body>Text</body></message>`

Display in the console window?

**Comment by jubalh** [comment]
I started with cleanup for message.c.
The following two commits take care of the allowed message types now:
46a00317ee85be02fc9174315db24297079d5c4d
3640900cf64f00591526444a80d9c412ba302a0a

Will still cleanup more, once I read the corresponding XEPs.

> Also, Profanity drops messages without the attribute.

What do you mean by that?

**Comment by jubalh** [comment]
3640900cf64f00591526444a80d9c412ba302a0a takes care of 'headline'.
Feel free to reopen (will close to have a better overview).
