### ISSUE TITLE
Proposal to make /tiny provider configurable or remove it

### ISSUE THREAD

**Issue by pmaziere** [profanity-im/profanity#1370]
The `/tiny` command  sends the URLs to shorten to tinyurl.com, a website whose goal is to gather and sell to third parties its users data as stated in their [privacy policy](https://tinyurl.com/privaicy.php) :
> We may share aggregated information, Non-Identifying Information and Log Data with third parties for industry analysis and demographic profiling and to deliver targeted advertising about other products and services.

In order to remain neutral according to the service that provides this functionality, the URL shortener feature must propose a mechanism that allows profanity's users to define which third party service to use, how to submit a URL to this service and how to retrieve the shortened URL from this service. 
 
Should this feature be kept, it should propose, as default provider, a libre software based equivalent, preferably instantiated by a non commercial entity.

**Comment by jubalh** [comment]
Personally I would just remove the behaviour. I always thought that this should just be a plugin in the first place.

But now that we have it already, maybe it's best to just alter the behaviour like you suggested:
* make it configurable so that the user can decide on the service being used
* use a privacy friendly service by default

**Comment by pmaziere** [comment]
I do not use it myself, and I think URL shorteners are something to avoid since it breaks the web once these services are offline.
So, if we could remove it all along, I'll be fine with it: 
 - first step: deprecation with a clear and loud message in the window where the shortened link  is displayed to let users know that this feature will disappear if someone who cares does not make the necessary changes
 - second step: if nobody steps up, let's go for full removal

**Comment by mdosch** [comment]
What's the use of URL shorteners in XMPP? I never had any URL exceeding the maximum message length (whatever that is) and I really dislike if I don't see where a link is leading to.

Am June 23, 2020 9:04:31 AM UTC schrieb Michael Vetter <notifications@github.com>:
>Personally I would just remove the behaviour. I always thought that this should just be a plugin in the first place.
>
>But now that we have it already, maybe it's best to just alter the behaviour like you suggested:
>* make it configurable so that the user can decide on the service being used
>* use a privacy friendly service by default
>

**Comment by jubalh** [comment]
> What's the use of URL shorteners in XMPP?

I guess the use was the following: Very long lines will be not clickable due to breaking the URL. Probably people used the url shortener so that a short URL is produced so it is more likely to be clickable.

**Comment by jubalh** [comment]
We don't need such a dramatic title but what it is actually about ;)

**Comment by jubalh** [comment]
> Should this feature be kept, it should propose, as default provider, a libre software based equivalent, preferably instantiated by a non commercial entity.

Like which one?

**Comment by wstrm** [comment]
I vote to remove `/tiny`. 

As @pmaziere says:
> I do not use it myself, and I think URL shorteners are something to avoid since it __breaks the web__ once these services are offline.

URL shorteners are just bad, even if they do not sell anyone's data. If long URL's are an issue, the application should be improved to handle them in a better way instead.

**Comment by mdosch** [comment]
+1 for removing `/tiny`
If you really, really want shorter URLs and send around URLs which do not tell others where they are leading to than use a tool that can do this and paste the result into profanity.
Profanity itself shouldn't support this behavior of breaking the internet by using URLs which do not indicate where they are leading to and which might be provided by services tracking the user.

**Comment by jubalh** [comment]
> Should this feature be kept, it should propose, as default provider, a libre software based equivalent, preferably instantiated by a non commercial entity.

Which one? I don't find any.
