### ISSUE TITLE
Notify only on mention in MUCs

### ISSUE THREAD

**Issue by jugendhacker** [profanity-im/profanity#1371]
## Expected Behavior
It would be cool if profanity had a setting to only count messages as new and notify the user if he or she was mentioned in this message. Ideally I would like to be able to set this per MUC like other XMPP clients can do.

## Current Behavior
Currently you can either decide between all messages, first message and no message for notifications in win 1 via `/console muc [all,first,none]` but there is no option to select "only on mention" and even if I choose none the window title of my terminal emulator still says `Profanity (1)` although this message is in a muc. 

## Possible Solution
I'm thinking about two possible solutions:

1. Have a `/console muc mention` option, but this will not fix the notification count in the windows title
2. Have a `/mute [on,mention,off]` option or so to mute all notifications for a specific muc or only get notifications on mentions

## Context
I'm in a MUC where sometimes hundreds of messages are sent during one hour or so. In conversations (and Dino at least) I could set this MUC to "Only notify on mention" and so I'll just get notifications if it's really important. My current workaround is to leave the MUC via `/close` or as @jubalh pointed out let Profanity ignore the bookmark via `/bookmark ignore`

## Environment
Profanity version: 0.9.2
Distro: Arch Linux

**Comment by jubalh** [comment]
`/notify room mention on` ?

**Comment by jugendhacker** [comment]
> `/notify room mention on` ?

According to https://profanity-im.github.io/guide/090/reference.html#notify this is only for Desktop notifications...

**Comment by jubalh** [comment]
@jugendhacker you can now use `/console muc mention`.
