### ISSUE TITLE
./configure fails  with allegedly missing sqlite3

### ISSUE THREAD

**Issue by maste9** [profanity-im/profanity#1388]
I faced a problem while trying to build package myself. Maybe s.o. has an idea how the following might happen ...

The ```./configure``` process fails with
```
checking for SQLITE... no
configure: error: sqlite3 3.22.0 or higher is required for profanity
Error 1 with command './configure' on line 100. Exiting.
```
while 
```
sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
```

## Environment
* It happens with both the current master as with 0.9.5 tarball
* on Ubuntu 18.04

**Comment by jubalh** [comment]
I doubt this is true.
It builds fine for everybody I know and Profanity 0.9.5 is in Ubuntu Groovy without problems: https://packages.ubuntu.com/source/groovy/profanity.
So I guess the fault is on your end.

**Comment by mdosch** [comment]
Probably you are missing the -dev package for building.

Am July 4, 2020 9:26:40 PM UTC schrieb maste9 <notifications@github.com>:
>I faced a problem while trying to build package myself. Maybe s.o. has an idea how the following might happen ...
>
>The ```./configure``` process fails with
>```
>checking for SQLITE... no
>configure: error: sqlite3 3.22.0 or higher is required for profanity
>Error 1 with command './configure' on line 100. Exiting.
>```
>while 
>```
>sqlite3 --version
>3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
>```
>
>## Environment
>* It happens with both the current master as with 0.9.5 tarball
>* on Ubuntu 18.04
>
>
>
