### ISSUE TITLE
Can't open websites

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1391]
I can't open urls with the following set up:

```
05.07.20 10:17:23 - `url open` command set to: firefox %u for html files
05.07.20 10:17:28 - `url open` command set to: firefox %u for DEF files
```

No URL is opened in the browser, profanity freezes and I get a lot of this in my log:

```
05/07/2020 10:11:05: stderr: ERR: 
05/07/2020 10:11:05: stderr: ERR: (profanity:83234): GLib-CRITICAL **: 10:11:05.506: g_string_insert_len: assertion 'len == 0 || val != NULL' failed
```

## Expected Behavior
URL is openend in the browser and profanity works normal.

## Current Behavior
URL is not opened in the browser and profanity freezes for ~20 s

## Steps to Reproduce (for bugs)
1. Open profanity
2. /executable urlopen html false "firefox %u"
3. /executable urlopen DEF false "firefox %u
4. Go to a chat with a URL in the last messages
5. /url open <tab><return>

## Environment
```
Profanity, version 0.9.5dev.master.d2c3aa56
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.4rc1)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
What does the `[executables]` section in your profrc look like?

Mine has:
```
url.open.cmd[DEF]=false;xdg-open %u;
url.open.cmd[mp3]=false;mpv %u;
```

/url is now also blocking (I mentioned that in the MUC already) which it wasn't before and I don't like.
This needs to get changed.

**Comment by mdosch** [comment]
It was my fault. From my last sway experiment I had the following lines in my ~/.zshrc.local

```
export MOZ_DBUS_REMOTE=1    
export GDK_BACKEND=wayland   
```

Without those env settings it works.
