### ISSUE TITLE
Incorrect libstrophe dependency check in configure 

### ISSUE THREAD

**Issue by danshearer** [profanity-im/profanity#1401]
On stock Ubuntu 20.04, git clone of the tree current as of this issue:

ii  libstrophe-dev                             0.9.3-1                             amd64        Library for writing XMPP clients - development files
ii  libstrophe0                                0.9.3-1                             amd64        Library for writing XMPP clients - shared library

checking for libstrophe... no
configure: error: libstrophe-0.9.2 or later is required for profanity

Perhaps this was introduced when 0.9.3 was made optional.

**Comment by jubalh** [comment]
I don't understand why people remove an issue template when it's provided...

Debians Profanity package is build using libstrophe. For testing that appears to be 0.9.3 too. Seems to work fine there.

I don't care about Ubuntu nor do I like it when the issue template is not used. Send a PR if you want a fix, I won't investigate.

**Comment by jubalh** [comment]
No problem here it seems: https://packages.ubuntu.com/groovy/profanity

**Comment by wstrm** [comment]
> No problem here it seems: https://packages.ubuntu.com/groovy/profanity

Groovy is 20.10.


Anyhow, I tried to build Profanity using a Docker container, and I couldn't reproduce this issue on 20.04.

**Comment by jubalh** [comment]
> Groovy is 20.10.

And is using Profanity 0.9.5 and libstrophe 0.9.3 and detects it just fine. Like I said I won't investigate, so I don't need to use his exact system. But by mentioning Groovy it shows that it's quite unlikely that this bug is real.

> Anyhow, I tried to build Profanity using a Docker container, and I couldn't reproduce this issue on 20.04.

Which also hints to that its not real :-)

**Comment by mdosch** [comment]
Yes, but they build 0.9.5 with libstrophe 0.9.3 there, so it should also work in 20.04.

Am July 10, 2020 12:08:10 PM UTC schrieb "William Wennerström" <notifications@github.com>:
>> No problem here it seems: https://packages.ubuntu.com/groovy/profanity
>
>Groovy is 20.10.
>
>
>Anyhow, I tried to build Profanity using a Docker container, and I couldn't reproduce this issue on 20.04.
>

**Comment by wstrm** [comment]
> Yes, but they build 0.9.5 with libstrophe 0.9.3 there, so it should also work in 20.04.
Yes, of course, but you never know.

@danshearer you got any more details? This is how I set up my container: https://github.com/profanity-im/profanity/blob/1de9cffd1a71e0e3b2f26feb6e6cb832d78b67f7/Dockerfile.ubuntu
