### ISSUE TITLE
Command argument parsing and "" - /correct - /msg - etc

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1404]
If you use `/correct` with a message containing `"` they will get stripped in latest profanity.

## Expected Behavior
Don't strip any symbols.

## Current Behavior
At least `"` get stripped, I'm not aware if other characters are also affected.

## Steps to Reproduce (for bugs)
1. Send `"This a test"`
2. `/correct <tab>`
3. Change the text to `"This is a test."` (or don't change anything, as it doesn't affect the behavior if the message get's actually changed) and send
4. See the message `This is a test.` without the `"`

## Environment
Debian Bullseye Testing

```
profanity -v                                                                                :(
Profanity, version 0.9.5dev.master.39315483
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.4rc1)
GTK icons: Enabled
```

**Comment by mdosch** [comment]
@pmaziere discovered that it only strips `"` when they are at the beginning of a word, so for `This is a "test"` they will be stripped but for `This" is" a" test"` they will not be stripped.

**Comment by jubalh** [comment]
That's to be expected.
Actually it is done for every command.
Did you ever try: `/msg a@b.c "hi!`

See https://github.com/profanity-im/profanity/blob/master/src/tools/parser.c#L95

I assume this was implemented in such a way to group parameters together.

**Comment by mdosch** [comment]
I only use `/msg` to start a new conversation and later open it with 
`/win` so the chance to have `"` in there is low. I just discovered this 
behavior with `/correct`.

Anyway, for other commands it makes sense to strip the `"` after parsing 
the command (like you probably don't want the `"` at the beginning and 
end of the topic you set) but I think `/msg` and `/correct` shouldn't 
alter your message. Especially when you need the `"` for grouping 
parameters together for a bot you control via xmpp messages.

**Comment by jubalh** [comment]
Certainly :)

**Comment by jubalh** [comment]
Need to check parse_args_with_freetext() that should be doing it but doesnt quite work right now.

**Comment by jubalh** [comment]
Apparently I did https://github.com/profanity-im/profanity/commit/8f37afcd37ad8663ca36c13ca7fbc4a431119f73#diff-c826ead0eca1a0f4a2f45a456ddca65f in the past without knowing about freetext. Reminder to myself to improve this.

**Comment by jubalh** [comment]
Probably we should split the code in parse_args() and parse_args_with_freetext() in helpfer functions. Seems duplicate..
And then maybe have a new one for not removing the "". Depending in what conditions parse_args_with_freetext() is currently used.

**Comment by mdosch** [comment]
Thanks, I tested it with `/correct` and it works well. :)
