### ISSUE TITLE
Error in build process on Ubuntu 20

### ISSUE THREAD

**Issue by amacfie** [profanity-im/profanity#1406]
On Ubuntu 20.04, building from source generates an error.
I followed the [instructions](https://profanity-im.github.io/guide/latest/build.html) including installing the Debian dependencies

```bash
apt-get install libcaca-dev libnotify-dev libgtk2.0-dev libotr5-dev libssl-dev libstrophe-dev pkg-config python3-dev libexpat1-dev libncursesw5-dev libglib2.0-dev libreadline-dev libgpgme11-dev libcurl4-gnutls-dev uuid-dev libcmocka-dev libgcrypt20-dev libsignal-protocol-c-dev libxss-dev libsqlite3-dev
```

Running `bootstrap.sh` or `./configure` give errors.

## Current Behavior

```
% ./bootstrap.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:90: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

```
% ./configure
[...]
./configure: line 9383: syntax error near unexpected token `,'
./configure: line 9383: `ACX_PTHREAD(, AC_MSG_ERROR([pthread is required]))'
```

**Comment by wstrm** [comment]
This looks like something that would happen if `autoconf-archive` is missing, could you try to install that package?

**Comment by amacfie** [comment]
@wstrm `autoconf-archive is already the newest version (20190106-2.1ubuntu1).`

**Comment by wstrm** [comment]
Are you missing any of these packages,
[https://github.com/profanity-im/profanity/blob/master/Dockerfile.ubuntu#L5-L30](https://github.com/profanity-im/profanity/blob/master/Dockerfile.ubuntu#L5-L30)?

Maybe the instructions doesn't reflect something in that Dockerfile.

**Comment by amacfie** [comment]
@wstrm Thanks, that worked. There must be a package missing from the instructions.

**Comment by wstrm** [comment]
Perfect! I'll take a look on the instructions.
