### ISSUE TITLE
Input cursor jumps to the statusbar clock seconds digit

### ISSUE THREAD

**Issue by licaon-kter** [profanity-im/profanity#1409]
...every second, then back to the input field

![jump](https://user-images.githubusercontent.com/2282799/88156959-abedb900-cbf9-11ea-8776-bddcaad30df4.png)  ![jumping2](https://user-images.githubusercontent.com/2282799/88163431-2f130d00-cc02-11ea-8f1a-66b3a3d556af.png)

HEAD (5a9f76c16aaf58cabb9cf9cb84479a5eec2a24b1), Raspbian Buster RPi1B/256Mb, armv6

Fixed by: `/time statusbar set %H:%M`

**Comment by wstrm** [comment]
Isn't this just your RPi being slow and you're able to see the flicker from when ncurses moves the cursor?

**Comment by licaon-kter** [comment]
It's not doing anything else, yes it could be slow, but I'm not seeing this on minutes change.

Slow or not, why isn't the text background of the status bar respected then? Why use the one from the input field?

**Comment by mdosch** [comment]
It might also be of interest for the devs what version of profanity you 
are using.

I don't have this behavior with my Pi 3B and profanity 0.9.5 from 
buster-backports.

uname -a
Linux radio 5.6.0-0.bpo.2-arm64 #1 SMP Debian 5.6.14-2~bpo10+1 
(2020-06-09) aarch64 GNU/Linux

**Comment by licaon-kter** [comment]
Right, using HEAD on RPi1B/256Mb

**Comment by jubalh** [comment]
Unfortunately I don't have a raspberry pi to test this.

HEAD is a variable btw :)

**Comment by wstrm** [comment]
I cannot reproduce this on c5c969a9295abe688ad7fd9afce430bae5df910c. Is that the color of your default cursor, or is it the background of the input field?

**Comment by licaon-kter** [comment]
Of course, HEAD is "HEAD at this moment when I post" else it's "HEAD(hash)" ;)

Should I list some libs versions or smth?

**Comment by licaon-kter** [comment]
This appears in every theme. Looks like cursor background to me.

Updated OP with input picture.

**Comment by jubalh** [comment]
> Of course, HEAD is "HEAD at this moment when I post" else it's "HEAD(hash)" ;)

So in case I only get a Rasperry Pi in 3 months, you expect me to check the time you posted, look what commit has been the latest until then and use that?

So first you decide to remove the issue template, which asks for the version -> someone of us has to ask you for the version manually -> taking from our time.
Then you mention a variable, expecting us to do the work and finding out which version this actually is -> taking more from our time.

That's not very nice is it? :)

If you need help it would be great if you could also do it in a way not to waste time for everybody.

**Comment by jubalh** [comment]
Regarding the actual issue:

I think we have/had something similar in the past. That some ncurses block wasn't ended properly and thus the formatting leaked.
I can't find the issue right now :(

Maybe it's something similar here.

**Comment by jubalh** [comment]
A friend has an rpi, he installed Profanity on it. Couldn't reproduce it.

**Comment by licaon-kter** [comment]
Might be a term issue, thanks.
