### ISSUE TITLE
Show bookmarks in roster

### ISSUE THREAD

**Issue by licaon-kter** [profanity-im/profanity#1412]
...not only joined rooms

It's the equivalent of `/roster show offline` but for bookmarks.

Also maybe this needs a `char` too, eg. have `#` for joined and `none` for bookmarks

**Comment by jubalh** [comment]
Yeah a lot of new things internally just for this feature that is quite unlikely in my opinion to be of much use.
Certainly we can do this, but do we want it?

I don't see much value in the feature yet.

**Comment by jubalh** [comment]
@mdosch @wstrm what do you guys think about this?

**Comment by mdosch** [comment]
I have no strong opinion on this one.

**Comment by wstrm** [comment]
Neither do I. :)

**Comment by licaon-kter** [comment]
So you just remember what rooms you've joined or hit TAB until you get to the one you want? What;'s the workflow?

**Comment by jubalh** [comment]
> So you just remember what rooms you've joined or hit TAB until you get to the one you want? What;'s the workflow?

I just use `/bookmark list` and then see a list of bookmarks. the green ones i have joined the others not.

**Comment by wstrm** [comment]
I wouldn't be against this feature if someone made good PR :)

**Comment by jubalh** [comment]
So what would the roster then look like:
So far I see:
```
# Online
@user1
@user2
# Offline
@user3
@user4
# Rooms
@room1
@room2
```

And then what? Have a section:
```
# Bookmarks
@room3
``` 
? But will this then contain all boomarks and mark some as green (joined) or will it only contain not joined bookmarks? Or should the heading be "Offline rooms" which might be too long for some users taste.

Only small questions but they make the difference :D

**Comment by jubalh** [comment]
Opinions?

**Comment by kaffeekanne** [comment]
Difficult one. Joined MUCs that are not bookmarked are in danger to be lost when quitting profanity. Also what happens when switching the roster "group by" option.
I like the idea, but can not provide more valuable input.

**Comment by jubalh** [comment]
I rather will not have them there.
