### ISSUE TITLE
Not persistent bookmarks

### ISSUE THREAD

**Issue by BlaiseEbuth** [profanity-im/profanity#1418]
## Expected Behavior

When connecting I want to retrieve my bookmarks and to auto-join some rooms.

## Current Behavior

After each deconnection all my bookmarks disappear.

## Environment
* System: Debian 10
* profanity -v:
Profanity, version 0.9.5
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.12.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.3)
GTK icons: Enabled

**Comment by jubalh** [comment]
> After each deconnection all my bookmarks disappear.

"Deconnection" ? You mean you close profanity and open it again? Or you mean you loose your network connection?
Did you use `/bookmark add myroom@myjid.org autojoin on` ?

**Comment by BlaiseEbuth** [comment]
I mean use the /disconnect command or the /quit command.
And yes I use the /bookmark command. It works fine, and I can see my room in the bookmarks list. But next time it disappeared...
I also noticed the same problem with the aliases.

**Comment by jubalh** [comment]
Did you use /save ? ;)

**Comment by BlaiseEbuth** [comment]
Yes I do. And nothing is saved... :/

**Comment by jubalh** [comment]
What server are you using? Does it work with other clients?

**Comment by BlaiseEbuth** [comment]
It's the Codingame.com server, and yes it work perfectly with Gajim and Pidgin.

**Comment by jubalh** [comment]
I just created an account.
They seem to run Prosody but don't say which version.

Please ask your admin whether they support XEP-0048.

**Comment by BlaiseEbuth** [comment]
It seems they don't support it...

**Comment by jubalh** [comment]
;)
