### ISSUE TITLE
Messages from MUC history show wrong time stamp

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1423]
When joining a MUC the timestamp for messages retrieved via MUC history is shown in UTC not in local time.

## Expected Behavior

The MUC history messages should be shown in local time as other messages are also.

## Current Behavior

Messages retrieved via MUC history show the time in UTC while messages received while being joined show the local time (UTC+2 in my case).

## Possible Solution

Convert the time for MUC history messages into local time for display.

## Steps to Reproduce (for bugs)

1. Leave the MUC in profanity
2. Write a message in another client at e.g. 08:30
3. Join with profanity
4. See the message sent in 2 with a timestamp of 06:30 (in case of TZ UTC+2)
5. Send a new message → timestamp shows 8:30

## Environment

Debian Bullseye (Testing)

```
rofanity, version 0.9.5dev.master.98b9cf06
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.5)
GTK icons: Enabled
```

**Comment by MarcoPolo-PasTonMolo** [comment]
I want to try to solve this, where should I look?

**Comment by DebXWoody** [comment]
On Sa, 02.10.2021 10:33:15, MarcoPolo-PasTonMolo wrote:
> I want to try to solve this, where should I look? 

I'm not sure, but I would start to look into

static void                                                                                                              
_handle_chat(xmpp_stanza_t* const stanza, gboolean is_mam, gboolean is_carbon, const char* result_id, GDateTime* timestamp)

and 

static gboolean                                                                                                          
_handle_mam(xmpp_stanza_t* const stanza) 

file: src/xmpp/message.c

**Comment by MarcoPolo-PasTonMolo** [comment]
I found that I can fix this by instead of picking the oldest delay in stanza_get_oldest_delay, to pick the newest one. The delay from xep0091 seems to be wrong sometimes. This however might reintroduce #1254.

**Comment by jubalh** [comment]
Hey @MarcoPolo-PasTonMolo ! It's great that you took a look at the existing issues and right away started to try to solve one! Thanks a lot for that <3 !

I'm not entirely sure yet, will try to take a look soon: but are you sure that we need to use a different delay stanza?
From Martins description above it looks like we use a different time format. So it might be that we just need to transform that when assigning.

**Comment by MarcoPolo-PasTonMolo** [comment]
I am not entirely sure myself either. What I noticed is that when I used the xep0091 delay in some chats the timestamp would be wrong and that the code for getting both delays was identical with the exception that we are getting information from different attributes/elements(I don't know the correct name).
The procedure to get both delay was to get time_value_from_iso8601 then get date_time_new_from_timeval_utc and then date_time_to_local

**Comment by MarcoPolo-PasTonMolo** [comment]
Ok never mind just found out the real issue, I'll have the pull request updated in a bit

**Comment by mdosch** [comment]
After a first test it seems to consider my local timezone now. Thanks. :)
