### ISSUE TITLE
configure.ac:92: error: possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by spth** [profanity-im/profanity#1429]
I tried to build current profanity on a Debian GNU/Linux testing system. When I invoked ./bootstrap, I got:

~~~~
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:92: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
~~~~

The usual attempt to get autotools stuff to work "autoreconf --install --force" didn't help either (same output as above).

**Comment by jubalh** [comment]
Do you have all dependencies installed? Also autoconf-archive? See https://github.com/profanity-im/profanity/blob/master/Dockerfile.debian#L4

**Comment by spth** [comment]
Thanks. Missing autoconf-archive was the problem. Would it be possible to check for that and give a meaningful error message in bootstrap.sh?

**Comment by jubalh** [comment]
Not sure, maybe. If you find a way you can create a PR.

But we also mentioned that you need autoconf-archive in https://profanity-im.github.io/guide/latest/build.html and we have the example of the Debian docker file in our repo. And we have existing issues which I guess one finds if one uses the search functionality. Like from 2017: https://github.com/profanity-im/profanity/issues/897

**Comment by jubalh** [comment]
I think it's also possible that some distros have the needed things just in a package named autoconf and not split out into one named autoconf-archive. I'm not sure if there is a way to detect whether the necessary files are installed or macros present.
