### ISSUE TITLE
Get idle status independent of Xserver

### ISSUE THREAD

**Issue by freswa** [profanity-im/profanity#1431]
## Expected Behavior
Show the correct idle time when using a Wayland based DE.

## Current Behavior
Idle time depends from time actively using profanity only

## Possible Solution
Implement the [Gnome](https://github.com/GNOME/mutter/blob/master/src/org.gnome.Mutter.IdleMonitor.xml) and [KDE](https://github.com/swaywm/sway/blob/master/protocols/idle.xml) DBus interfaces to get the idle time independent from the Xserver.

**Comment by jubalh** [comment]
And if the user uses another wayland compositor?

**Comment by freswa** [comment]
I digged through the existing wayland compositors. I could only find sway implementing the KDE protocol and a [ticket](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/8) on the wayland protocols repo to merge the KDE approach into the official protocol repository. Other compositors seem to not have picked up any idle protocol at all.
Imho writing the DBus integration is the big problem here. Switching between protocols or integrate protocol changes should be rather straight forward.

**Comment by freswa** [comment]
I checked both protocols and they both use a subscription mechanism. In the end events get fired if the user is idle for a certain amount of time and when he's back.

A small summary what has to be done imho, comments appreciated:
1. If we detect that we can subscribe to a DBus interface, we should disable the call of `session_check_autoaway();` in `src/profanity.c:113`.
2. We should refactor some logic out of `void session_check_autoaway(void)` at `src/xmpp/session.c:375`. We don't need the time calculation for the DBus approach, but the logic about what away msg to set depending on the fired event. I propose to implement a method `void set_activity_state(activity_state_t)` to make that logic available by the dbus code.
3. The DBus stuff itself.

**Comment by jubalh** [comment]
@freswa can you implement this?

**Comment by freswa** [comment]
@jubalh My work schedule is to tight for now - sorry. Maybe later this year. I'm happy to test and help anyone who like to implement this :)

**Comment by jubalh** [comment]
Ok I don't plan to implement this myself. Feel free to open a PR when you have time :-)
