### ISSUE TITLE
Text chatlogs only recording my messages

### ISSUE THREAD

**Issue by aereaux** [profanity-im/profanity#1439]
When examining the text logs in the chatlogs directory (at least the non-room ones), only the messages I send are recorded.

## Expected Behavior

The text chatlogs should also include the messages that others send to me.

## Current Behavior

Only the messages I send are recorded in the text chat logs

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

1. Converse with someone (1:1) with profanity
2. Examine chatlogs
3. Observe a one-sided conversation

## Context

Not too important, as I can use the sqlite chatlogs, but it is a little weird.

## Environment
* Give us the version and build information output generated by `profanity -v`
```
Profanity, version 0.9.5dev.master.35aecd42
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.6)
GTK icons: Disabled
```
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution: Arch Linux
* glib version: glib2 2.66.2-1

**Comment by jubalh** [comment]
No encryption used (OMEMO)?
No other devices with the same account online (carbons)?

**Comment by aereaux** [comment]
No, sorry, this is with OMEMO encryption, and I have a conversations client online as well.  Both clients should have carbons enabled.

**Comment by jubalh** [comment]
Might be also related in case something else doesn't work: https://github.com/profanity-im/profanity/commit/5a0a6c97e228e07be68d04a42464b340d2d3c4e7
