### ISSUE TITLE
main.text.me = main.text.them?

### ISSUE THREAD

**Issue by aba-hollerer** [profanity-im/profanity#1441]
## Expected Behavior

I'd expect that setting main.text.me different to main.text.them in a theme would result in two different colors.

## Current Behavior

I am setting main.text.me=white and main.text.them=blue but I always get blue.

## Steps to Reproduce (for bugs)

1. emerge -aq profanity
2. set colors in theme file like "main.text.me=white" and "main.text.them=blue"
3. /theme load [mycolortheme]
4. in chats all text will be blue

## Context

It's not critical or anything I just thought somebody should know.

## Environment
* Give us the version and build information output generated by `profanity -v`
Profanity, version 0.9.5
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Disabled
C plugins: Enabled
Python plugins: Enabled (3.7.9)
GTK icons: Enabled

* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
Gentoo amd64
* glib version
ldd (Gentoo 2.32-r2 p2) 2.32

**Comment by jubalh** [comment]
Must be a problem with your theme.
You can check your colors with `/theme properties`.

![showprof1](https://user-images.githubusercontent.com/1658215/101475410-ab598300-394c-11eb-9555-e2edce521e04.png)

```
main.text=white
main.text.me=cyan
main.text.them=red   
```

**Comment by aba-hollerer** [comment]
My problem was that `/theme properties` was correct!
This seems to fix the issue for me.

```diff --git a/src/ui/window.c b/src/ui/window.c
index 687af3b2..663b49b5 100644
--- a/src/ui/window.c
+++ b/src/ui/window.c
@@ -1215,7 +1215,7 @@ win_print_outgoing(ProfWin* window, const char* show_char, const char* const id,
         _win_correct(window, message, id, replace_id, myjid);
     } else {
         //TODO my jid
-        _win_printf(window, show_char, 0, timestamp, 0, THEME_TEXT_THEM, "me", myjid, id, "%s", message);
+        _win_printf(window, show_char, 0, timestamp, 0, THEME_TEXT_ME, "me", myjid, id, "%s", message);
     }

     inp_nonblocking(TRUE);

**Comment by jubalh** [comment]
> My problem was that /theme properties was correct!

What do you mean?

**Comment by aba-hollerer** [comment]
I mean that `/theme properties` correctly resolved the colors fot main.text.me and main.text.them.
However all text in the chat appeared as main.text.them.

**Comment by jubalh** [comment]
@aba-hollerer but in my screenshot it looks correct, doesn't it?
Can you provide your theme file and/or screenshot?

**Comment by aba-hollerer** [comment]
I used the following testing theme:
```
[colours]
main.text=white
main.text.me=cyan
main.text.them=red
```
This resolved as follows:
![2020-12-11-075353_366x226_scrot](https://user-images.githubusercontent.com/58429747/101873474-450c7480-3b87-11eb-8e35-f6f089d4ee1f.png)

But:
![2020-12-11-075425_158x37_scrot](https://user-images.githubusercontent.com/58429747/101873511-5786ae00-3b87-11eb-8b9a-0f8231a5a804.png)

However I don't really see the point in all of this since I already posted the patch...

**Comment by wstrm** [comment]
@aba-hollerer are you sending from two different instances here?

Then, I'm able to reproduce it like (in a MUC):
![2020-12-11-083607_380x93_scrot](https://user-images.githubusercontent.com/4541181/101876012-fca38580-3b8b-11eb-9e26-b8132e36ff0e.png)

(@jubalh is this expected?)

> However I don't really see the point in all of this since I already posted the patch...

I think we're just trying to understand what this solves :)

**Comment by aba-hollerer** [comment]
@wstrm: No this was on the same instance.
With the patch applied:
![2020-12-11-091036_264x41_scrot](https://user-images.githubusercontent.com/58429747/101878944-c3b9df80-3b90-11eb-8161-b63d55d96e12.png)

**Comment by jubalh** [comment]
> However I don't really see the point in all of this since I already posted the patch...

Your patch looks right to me on first glance. The point is to verify the root cause of this. Is it a misunderstanding? Is it an error that you found and solved? Is it another error and your solution is only covering it up?

As stated above we cannot reproduce this issue on our side (both @wstrm and me), which is suspicious don't you agree?

Like you saw in the code there are many cases. I also think that it is possible that you send with another client/instance and thus carbons are used.

**Comment by aba-hollerer** [comment]
So I dug a little further in src/ui/window.c. The problem seems not to be present for MUC:
In win_print_outgoing_muc_msg:
```
_win_printf(window, show_char, 0, timestamp, 0, THEME_TEXT_ME, me, me, id, "%s", message);
```
But in win_print_outging:
```
_win_printf(window, show_char, 0, timestamp, 0, THEME_TEXT_THEM, "me", myjid, id, "%s", message)
```

**Comment by jubalh** [comment]
I still don't see why I couldn't reproduce it.

But I think you are right. The mistake seems to be introduced in https://github.com/profanity-im/profanity/commit/b6b7dd5ad497a71e250b8b3cef0bb987314b141d

**Comment by jubalh** [comment]
I have `/receipts` set to on. Thus `win_print_outgoing()` isn't used.

**Comment by jubalh** [comment]
Thanks for your investigations @aba-hollerer !

**Comment by aba-hollerer** [comment]
Thank you for maintaining such an awesome piece of software:)
