### ISSUE TITLE
Disable profanity logging (not chatlogs) alltogeter or choosing where to write them

### ISSUE THREAD

**Issue by mrkiko** [profanity-im/profanity#1442]
Thus not having ~/.local/share/profanity/logs/profanity.log around.

Sorry if this is possible and I am missing the way to do it.
Thanks!!

**Comment by jubalh** [comment]
You can use `profanity -f logfile1` to use `~/.local/share/profanity/logs/logfile1.log` instead. of default filename.

**Comment by mrkiko** [comment]
Thanks!! I was looking for a way to use e.g.: /tmp/logfile1 ... ...

**Comment by jubalh** [comment]
I don't remember the reason why I made `-f` use a filename in the log dir and not let the user define the whole filename. I think there was one.. I'll look into it.
Then one could also do something like `profanity -f /dev/null`.

**Comment by wstrm** [comment]
@jubalh did you find any reason? Doing stuff like `profanity -f /dev/null` that you noted would be nice :)

**Comment by jubalh** [comment]
@mrkiko please test with the new -f behaviour. We will notify people in the changelog of the behaviour change.
