### ISSUE TITLE
Manpages for profanity commands

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1444]
People can use `/help` inside profanity.
When a browser is available they can also use: https://profanity-im.github.io/guide/latest/reference.html

Some users expressed interest in man pages for the same information.

We have `profanity docgen` which creates the reference.html (or more precisely its parts).

Let's have a `profanity mangen` too.
It should create a `profanity-command.1` in the `docs` folder. Where `command` is `account`, `roster` etc.
The files should be generated and added to git once a command changes.

The new manpages should also be installed upon `make install`.

Mock by @mdosch :
![profmm](https://user-images.githubusercontent.com/1658215/101186215-122c2300-3653-11eb-9527-bd08acd9ad90.png)

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1389 was also created for a similar purpose.

**Comment by jubalh** [comment]
```
21:08:07 - DebXWoody: I would recommend to use markdown for manpage and html and use the code for the help commands. In some cases it would be nice to have more information in manapage / html instead of the help command. I think this are two different usecases. One example is the OMEMO stuff. In the application I just need some basics to use it. It would be nice to have more information ( maybe background information ) on website an manpage.
10:12:01 - jubalh: DebXWoody: well several people asked already for manpages regarding the commands. we could also rename them into profanity-cmd-account etc. and then have profanity-omemo or profanity-ox as other info manpages
```

**Comment by pasis** [comment]
> The files should be generated and added to git once a command changes

You don't have to add generated man pages to git. I believe you can run `profanity mangen` build-time and install the mans via man_MANS variable.

**Comment by jubalh** [comment]
> You don't have to add generated man pages to git. I believe you can run profanity mangen build-time and install the mans via man_MANS variable.

My idea is to add them to git so that the GitHub generated tarball will contain them when we do a release.
Othewise they won't be part of the release tarball. And users will have to set to status `development` in `configure.ac` run `profanty mangen` and then again set to `release` and compile for regular usage.
Am I missing something?

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1445 got merged. So man pages can be created now.
Are not added to git yet. Maybe I only add them on the release commit and remove when setting to the next version.
