### ISSUE TITLE
Move `/executable` sub-commands to related parent commands

### ISSUE THREAD

**Issue by wstrm** [profanity-im/profanity#1464]
## Expected Behavior
For proximity reasons, it may be more logical for the user if the commands are grouped as:

```
/avatar set <cmd>                   # Set executable used for viewing avatar
/avatar reset                       # Reset executable to default

/url save <url>                     # Save URL content
/url set save <cmdtemplate>         # Set executable used for saving
/url reset save                     # Reset executable to default

/url open <url>                     # Open URL
/url set open <cmdtemplate>         # Set executable used for opening
/url reset open                     # Reset executable to default

/url set directory <dir>            # Set default directory for storing content
/url reset directory                # Reset to default directory (pwd)
```

**I see one issue with this, `/avatar set` may be mistakedly intepreted as "set my avatar" and not "set the executable for `/avatar open <...>`".**

Another variant could be to mimick WeeChat's way of changing settings. They group every setting under `/set <key> <value>`. Settings are "unset" (or reset) with `/unset <key>`. The actual keys/settings are grouped and dot-separated, like: `weechat.network.<...>`. That would require quite a large refactor, though.

## Current Behavior
Currently, executable settings are grouped under `/executable`, like so:
```
/executable avatar          # Set executable that is run by /avatar open.

/executable urlopen set     # Set executable that is run by /url open.
/executable urlopen default # Restore to default settings.

/executable urlsave set     # Set executable that is run by /url save.
/executable urlsave default # Use the built-in download method for saving.


```
There is no default directory setting yet, and it isn't obvious where to have this setting with the current layout.

## Possible Solution
I write some code that changes the behavior.

## Steps to Reproduce (for bugs)
N/A.

## Context
I get confused by the commands and settings.

## Environment
N/A.

**Comment by jubalh** [comment]
This is related to https://github.com/profanity-im/profanity/issues/1116 where we already tried to improve the grouping of commands. It was a first step. But clearly we need another go.

**Comment by wstrm** [comment]
Maybe it's best to not touch `/avatar` and `/executable avatar` yet, and instead just change for the other two?

**Comment by jubalh** [comment]
Okay :-)

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1485 might introduce an `/executable editor` or something like that.
I'm not sure whether getting rid of /executable is good or not. It seems like a nice way to group all settings of external programs. So one could see the proximity reasons in this regard too.

**Comment by jubalh** [comment]
Now there comes a new one with `/editor`. I actually like `/executables` to be the one place to configure all external programs. Going to close this for now.
