### ISSUE TITLE
TLS policy of trust does not work for self-signed certificates as expected

### ISSUE THREAD

**Issue by SamWhited** [profanity-im/profanity#1468]
When setting `tls.policy=trust` in the account config it still asks if I want to connect for a self-signed certificate.

## Expected Behavior

The documentation says that a TLS policy of trust will "Force TLS connection and trust server's certificate" so I would expect that to be true even if the certificate is self-signed.

## Current Behavior

Profanity asks if I want to accept the TLS certificate. To do so permanently I have to add it to the `tlscerts` file.

## Possible Solution

Either make a policy of `trust` also include self-signed certificates, or add a new level that does not verify TLS certificates at all.

## Context

The machine I'm trying to connect to is a testing machine that will generate a new self-signed certificate on every startup, making it difficult to write the `tlscerts` file over again every time.

## Environment

```
$ profanity -v
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.1)
GTK icons: Disabled
```
* Arch
* glibc 2.32-5

**Comment by pasis** [comment]
This must be related to libmesode and shouldn't happen with libstrophe. 

@jubalh could you check this?:
1. remove https://github.com/profanity-im/libmesode/blob/master/src/tls_openssl.c#L366
2. replace https://github.com/profanity-im/libmesode/blob/master/src/tls_openssl.c#L378 with:
```C
SSL_set_verify(tls->ssl, mode, conn->tls_trust ? 0 : verify_callback);
```

**Comment by jubalh** [comment]
Probably then I should also take the latest libstrophe changed done in 0.10.1 and make a new release.

I really hope we can deprecate libmesode soon and have it's extra functionality in libstrophe.

**Comment by jubalh** [comment]
Since libstrophe supports this and we plan to deprecate libmesode soon I'll close this as no work in Profanity is needed.
