### ISSUE TITLE
Message body not being displayed if the "lang" attribute is missing

### ISSUE THREAD

**Issue by royrwood** [profanity-im/profanity#1469]
Profanity does not display the body of a received message if the "lang" attribute is missing.

## Expected Behavior
Profanity should display messages even if the "lang" attribute is missing

## Current Behavior
It seems that profanity is not displaying the body of a received message if the "lang" attribute is missing.  In local testing using ejabberd, I noticed that newer versions of ejabberd sometimes do not include the "lang" attribute in messages.  This only happens when using the REST API or ejabberdctl to send the message, so it does not show up for normal usage.  Looking at the packets received in profanity's XML console, here are sample messages received from two versions of the ejabberd server:

```
Ejabberd 20.01:
<message id="6479759090134302045" type="groupchat" to="roy@ejabberd.roy.org/profanity.E" from="test_muc_room@conference.ejabberd.roy.org/admin">
    <body lang="en">Message via REST API</body>
    <subject lang="en">Subject via REST API</subject>
</message>


Ejabberd 20.12:
<message id="6371662130715871347" type="groupchat" to="roy@ejabberd.roy.org/profanity.E" from="test_muc_room@conference.ejabberd.roy.org/admin">
    <body>Message via REST API</body>
    <subject>New Subject</subject>
</message>
```

When the messages are received, profanity correctly processes the subject change for both server versions.  Profanity displays the message body correctly when the "lang" attribute is present (ejabberd 20.01), but does NOT display the message body when the "lang" attribute is missing (ejabberd 20.02 or later, including the latest, ejabberd 20.12).

## Steps to Reproduce (for bugs)

1. Connect a profanity client to an ejabberd server and join a MUC room
2. Send a message to the MUC room using the ejabberdctl command: `ejabberdctl send_message groupchat admin@debian.roy.org test_room@conference.debian.roy.org "" "Test Message via ejabberdctl"`
3. Maybe specify a non-empty subject as well as a non-empty message body

## Context
I am trying to send messages to a MUC room using the ejabberd REST API or ejabberdctl command line interface, and then view those messages using profanity.

## Environment
```
$ profanity -v
Profanity, version 0.9.5
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.6)
GTK icons: Enabled
```
This is on Ubuntu 20.04 with glib 2.66.1-2.

**Comment by licaon-kter** [comment]
Ref: https://github.com/processone/ejabberd/issues/3485

**Comment by jubalh** [comment]
I just tried with both regular chat messages and MUC message.
It worked both times.

Profanity doesn't even check for `lang`, nor send it.

```
11:59:02 - RECV:
11:59:02 - <message                                                                                                                                           
           id="123"      
           to="test@domain.org" type="chat" from="ne@domainorg/profanity><body>hi</body><active                                               
           xmlns="http://jabber.org/protocol/chatstates"/><request xmlns="urn:xmpp:receipts"/><stanza-id id="aIFiIVVFF9UeKcg8" by="test@domain.org"      
           xmlns="urn:xmpp:sid:0"/></message>
```

```
18/01/21 11:59:02 - me@domain.org/profanity: hi
```

I doubt it's profanitys fault here.

**Comment by mdosch** [comment]
Did you verify that "roy@ejabberd.roy.org/profanity.E" is the right 
resource?
