### ISSUE TITLE
Switching windows while sending OMEMO encrypted message causes incorrect highlight in statusbar

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1473]
When in a private, OMEMO encrypted MUC with around 20 participants, sending messages can take noticeable time in which profanity does not react to input. Switching windows with `Alt-1` leads to a window switch the moment profanity gets responisve again. The just sent message causes the corresponding statusbar window to be highlighted.

## Expected Behavior
After becoming responsive again and switching to console window, the window left should not be highlighted in status bar as we send the "new" message ourself.

## Current Behavior
After some time unresponsive, the window is switched (console window in this case) and the window left is highlighted in the statusbar.

## Possible Solution
I guess it should be checked if we sent the message ourself. On the otherhand, messages from other devices from us might be wanted highlights (not for me, but maybe others).

## Steps to Reproduce (for bugs)
1. Have a private, OMEMO encrypted group chat (around 20 participants, 3-4 devices each) on window 2.
2. Send an OMEMO encrypted message
3. profanty becomes unresponsive for a short while
4. Attemt `Alt-1` to switch to console window
5. profanity switches windows and becomes responsive again
6. Windows 2 is now highlighted by our own message

## Context
One can be tricked into thinking, there are new messags, while there aren't any. Also one could think, one missed other messages.

## Environment
* Raspberry Pi B, hence slow
* Raspberry Pi OS, Debian-testing
```
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Disabled
```

**Comment by jubalh** [comment]
I don't think there is much we can do here. Except make some parts of profanity more efficient/faster. We have this planned already.
