### ISSUE TITLE
Cycle through Nicknames breaks on slashes

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1474]
When cycling through nicknames with tab in a MUC, it stops when there is a nickname containing slash `/`.

## Expected Behavior
Cycle through all nicknames.

## Current Behavior
Cycles until the nick starting with `/` is reached.

## Steps to Reproduce (for bugs)

1. Have a MUC with a participant named `/something`
2. Have an empty input window
3. cycle through nicknames to mention with tab
4. upon reaching nick `/something`, further cycling with tab stops working

## Context

Since i can't type cyrillic letters i tried to tab until that nick is reached to be highlighted.

## Environment
```
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Disabled
```
Raspberry Pi OS (Debian Testing/Bullseye)

**Comment by jubalh** [comment]
@mwuttke97 something for you?

**Comment by jubalh** [comment]
@mwuttke97 if I remember correctly you mentioned in the MUC that this bug should be trivial. Do you think you can tackle it soonish so it will be in 0.11? :)

**Comment by jubalh** [comment]
@xenrox do you think you have time to tackle this one?
