### ISSUE TITLE
`/statusbar room room` does not show room name or room jid

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1475]
Using `/statusbar room room` to display the room name (or jid?) between clock and window tabs does not seem to have any effect.

## Expected Behavior

I would expect, that either the MUC name like in the titlebar or the MUC JID (or its local part) is displayed.

## Current Behavior

`/statusbar room room` seems to have no effect at all. In fact so does `/statusbar room jid`.

## Steps to Reproduce (for bugs)

Vary settings for `room`, `chat` or self in `/statusbar`.
1. `/statusbar self (...)` switches betwen bare JID, full JID and account name on our server.
2. `/statusbar self off` removes display of information about ourself.
3. `/statusbar room (...)` does not change anything at all.

## Context
For what it's worth, i tried to find a setting that shows my nick of a currently joind MUC, as that may differ from account name. I don't know if the statusbar settings got broken over the years.

## Environment
```
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Disabled
```
Raspberry Pi OS (Debian Testing/Bullseye)

**Comment by jubalh** [comment]
What's your output of `/statusbar` in console?

**Comment by jubalh** [comment]
It works alright here. But you need to have `/statusbar show name` of course. Then `/statusbar room room` and `/statusbar room jid` only can make a difference ;)

**Comment by kaffeekanne** [comment]
Ok, i absolutely misinterpreted that setting then. `[1:<name|jid)]` works. I thought `/statusbar room <room|jid>` will have an effect on the information next to the window list. But thats only handled by `/status bar self`. Ok, this is done then, i dont use window names, as they eat to much space, hence i did not notice the change. Thanks for clarifying.
