### ISSUE TITLE
`/url save` produces garbage file with default settings

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1479]
When using default settings for `/url save` the downloaded file is not usable.

## Expected Behavior

Download the file somewhere to be used furhter.

## Current Behavior

Downloaded file is downloaded to home directory without extension. In particular an image does not have the remote file name and extension nor the correct data to be viewed with an image viewer.

## Possible Solution

Setting `/executable urlsave set "curl -O %u %p"` segfaulted profanity while `curl -O <url>` does download the file and it is viewable afterwards.

## Steps to Reproduce (for bugs)

1. In a public MUC with posted image invoke `/url save <tab>`
2. Progressbar is shown and downloaded file is saved in `~/` with a filenname like `12ef45ba23` (hex).
3. file is not viewable

## Context

Maybe related to #1478 2) as it downloads garbage.

## Environment
```
Profanity, version 0.10.0dev.HEAD.09d7f07e

Build information:
XMPP library: libstrophe
Desktop notification support: Disabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Disabled
Python plugins: Disabled
GTK icons: Disabled
```

**Comment by wstrm** [comment]
Was the original filename `12ef45ba23` (my guess is no;))?

**Comment by jubalh** [comment]
So I use the default settings myself:

```
Default '/url save' command (/executable urlsave)                        : (built-in)
```

And just ran `/url save https://someurl/pic.jpg` afterwards I had `pic.jpg` in my home folder.
Worked like a charm.

**Comment by kaffeekanne** [comment]
Not reproducable anymore with the same and different links, closing.
