### ISSUE TITLE
Unable to initiate OMEMO with Monal

### ISSUE THREAD

**Issue by gitbugged** [profanity-im/profanity#1480]
## Expected Behavior
I should be able to initiate an OMEMO conversation with my iOS friend using open source client [Monal](https://monal.im/) 4.9.1 

## Current Behavior
User receives a message saying "your client doesn’t support OMEMO"

## Possible Solution
No idea, both clients claim to support OMEMO and both are regularly updated. They are able to use OMEMO with other clients.

## Environment
OS: Debian Bullseye
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.1)
GTK icons: Enabled

**Comment by jubalh** [comment]
You need to tell us which commands you ran. It appears you did something wrong there.

**Comment by jubalh** [comment]
Make sure to read https://profanity-im.github.io/guide/latest/omemo.html and https://profanity-im.github.io/guide/latest/reference.html#omemo
