### ISSUE TITLE
Profanity doesn't work with prosodys new http_upload module

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1499]
Profanity doesn't work with prosodys new [http upload module](https://prosody.im/doc/modules/mod_http_file_share). As go-sendxmpp had the same problem before (which got fixed by @Zash) I assume profanity is also violating this part of [XEP-0363](https://xmpp.org/extensions/xep-0363.html):

> In addition to the Content-Length and Content-Type header the client MUST include all allowed headers that came with the slot assignment.

## Expected Behavior
Profanity should upload the file.

## Current Behavior
> XEP-0363 HTTP File Upload is not supported by the server

## Environment
* Debian Testing/Unstable

```
Profanity, version 0.10.0dev.master.96580f91
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.2)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
@mdosch I assume this is the relevant commit in go-sendxmpp: https://salsa.debian.org/mdosch/go-sendxmpp/-/commit/0d26691606b6236d853a280d12c5e1e69eb33aef ?
