### ISSUE TITLE
Add support for XEP-0045 8.6 "Approving Voice Requests"

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1507]
As #1211 got implemented via #1504 and profanity can now request voice it would be also nice for an MUC admin to be able to approve those requests from within profanity. Therefore support for [XEP-0045 §8.6](https://xmpp.org/extensions/xep-0045.html#voiceapprove) would be much appreciated.

**Comment by jubalh** [comment]
Done in https://github.com/profanity-im/profanity/issues/1508
