### ISSUE TITLE
Fuzzing and integration with OSS-Fuzz

### ISSUE THREAD

**Issue by jvoisin** [profanity-im/profanity#1509]
Since profanity is processing untrusted data coming from the internet, it would be nice to [fuzz it]( https://en.wikipedia.org/wiki/Fuzzing ) a bit, ideally via [libfuzzer]( https://llvm.org/docs/LibFuzzer.html#fuzz-target ) so that it can be integrated with [OSS Fuzz]( https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/ ).

I'll be happy to help make this happen :)

**Comment by jubalh** [comment]
@jvoisin thanks for linking the articles. I took a quick look.
I imagine that you can find many things when sending XML that is not according to what we expect from the description of a certain RFC or XEP. Feel free to work on any area you see fit and opening PRs :-)
Maybe take a look at the `src/xmpp` files like `src/xmpp/message.c` or `src/xmpp/stanza.c`.

**Comment by jubalh** [comment]
@jvoisin maybe wait a bit. I started with https://github.com/profanity-im/profanity/pull/1513.

**Comment by jubalh** [comment]
@jvoisin I guess you can start :)

**Comment by jvoisin** [comment]
It seems that it might make more sense to fuzz libmesode instead, since it's the one dealing with "low-level" shenanigans.

**Comment by jvoisin** [comment]
I gave it a try, with something like this, but I can't make it compile:

```C
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "strophe.h"
#include "parser.h"

void cbtest_handle_start(char *name, char **attrs, void *userdata) { (void)attrs; (void)userdata; }

void cbtest_handle_end(char *name, void *userdata) { (void)userdata; }

void cbtest_handle_stanza(xmpp_stanza_t *stanza, void *userdata) { (void)userdata; }

int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    xmpp_ctx_t *ctx;
    parser_t *parser;
    int ret;

    char* dup = malloc(Size);
    memcpy(dup, Data, Size);

    ctx = xmpp_ctx_new(NULL, NULL);
    parser = parser_new(ctx, cbtest_handle_start, cbtest_handle_end,
                        cbtest_handle_stanza, NULL);

    parser_feed(parser, dup, Size);

    free(dup);
    parser_free(parser);
    xmpp_ctx_free(ctx);

  return 0;  // Non-zero return values are reserved for future use.
```

**Comment by jubalh** [comment]
> It seems that it might make more sense to fuzz libmesode instead, since it's the one dealing with "low-level" shenanigans.

Please use libstrophe. We plan to deprecate libmesode.

> I gave it a try, with something like this, but I can't make it compile:

That are linker issues that you mentioned above.

**Comment by jvoisin** [comment]
Making progress:

![xxx](https://user-images.githubusercontent.com/325724/114693154-d6901c80-9d08-11eb-8375-54ccea9a65bb.png)

**Comment by jubalh** [comment]
@jvoisin any news?

**Comment by jubalh** [comment]
https://github.com/strophe/libstrophe/pull/179 got merged in libstrophe.
