### ISSUE TITLE
Vertical status bar (like poezio's)

### ISSUE THREAD

**Issue by qorg11** [profanity-im/profanity#1517]
Is it possible to set the status bar (or at least the open windows bar) in vertical? like poezio
![1617149183](https://user-images.githubusercontent.com/53711069/113217052-99924780-927d-11eb-939e-6fd769c8f633.png)

**Comment by jubalh** [comment]
Nope. Not yet. Only top or bottom but always vertical. Keep in mind that the design is based on irssi.
Here is the reference to manipulate the statusbar: https://profanity-im.github.io/guide/latest/reference.html#statusbar
