### ISSUE TITLE
Unexpectedly creates a file named `./profanity`

### ISSUE THREAD

**Issue by mwgamera** [profanity-im/profanity#1518]
## Current Behavior
After running for a while (apparently when the log file reaches the maxsize limit), profanity changes the log file location to `profanity` in the current working directory.

## Expected Behavior
It shouldn't do that.

## Steps to Reproduce
0. Ensure `./profanity` doesn't exist and `.` is writable.
1. Run `profanity -l DEBUG` (but without `-f`) to make it write a lot of log.
2. Set `/log maxsize 64`.
3. Do anything DEBUG-log-worthy like issuing any command.
4. Observe `./profanity` being created.

## Possible Solution
Pass NULL as a second argument of `log_init` in `_rotate_log_file`: https://github.com/profanity-im/profanity/blob/1ec606540eb0f474f3d968d3566a7c56d778a367/src/log.c#L249-L260
Apparently, the `_rotate_log_file` function tried to extract user-provided name from currently used `mainlogfile` and restart logging to the same place after rotation, but currently this is interpreted as a full path instead. As I understand, the log rotation is no longer done with user-provided paths at all so this should be simply skipped altogether now as passing any non-NULL value is interpreted as user-provided. Replacing `start` with NULL appears to fix it for me.

**Comment by raspbeguy** [comment]
Can confirm that, with up-to-date master version.

**Comment by jubalh** [comment]
@mwgamera can you test whether https://github.com/profanity-im/profanity/pull/1563 fixes this?

**Comment by mwgamera** [comment]
Yes, it fixes it and I can no longer reproduce it on master. But I think it introduces another subtle bug that the file will be rotated at most once because `log_file = g_strdup(mainlogfile)` is not NULL so `log_init` will set `user_provided_log` to TRUE.

**Comment by jubalh** [comment]
You mean in `_rotate_log_file()`? That function is only called if `user_provided_log` is false.

**Comment by mwgamera** [comment]
Yes, and as `_rotate_log_file` invokes  `log_init` with non-NULL `log_file`, it _changes_ the value of `user_provided_log` from FALSE to TRUE here:
https://github.com/profanity-im/profanity/blob/482f8955d7ee21515a82d1844620385ad4503079/src/log.c#L152-L163
Unless I'm missing something, when `_rotate_log_file` is reached, the actual path returned by `files_get_log_file(NULL)` should be the same as current `mainlogfile`. The only difference is that non-NULL `log_file` also sets `user_provided_log` to TRUE disabling further rotations.

**Comment by jubalh** [comment]
Ah yes, so it should actually pass NULL. Do you want to make a PR?

**Comment by mwgamera** [comment]
No, please handle it in whatever way you like.
