### ISSUE TITLE
Feature: Spawn external editor to edit message

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1521]
@StefanKropp had this idea and started it in https://github.com/profanity-im/profanity/pull/1485.

What needs to be done:
* [x] Decide what PREF_COMPOSE_EDITOR should return by default `/usr/bin/vim`, `xdg-open`, `$EDITOR`, `$VISUAL`? Right now we use `fork()`/`execl()` we need a whole path. So just `xdg-open` or `$EDITOR` won't work right now. #1546
* [x] Check whether it works with a graphical editor -> https://github.com/profanity-im/profanity/issues/1521#issuecomment-854110973
* [ ] Fix cleanup error when quitting Profanity

Last thing happens when:
Test1:

    start profanity
    /msg someone
    /quit

Test2:

    start profanity
    /msg someone
    write a message using /editor
    /quit

In Test2 the terminal will not be cleared properly. There is still part of profanity visible. Maybe something ncurses related.

* [x] Remove the "EDITOR PREVIEW" from the chatwindow. Or let it stay but replace it later when the actual message have been sent. -> a4deec8b8d26c7bd7312b972372b4ef3aab8eeda
* [ ] Since the inputline is empty it might confuse some people at the start. Let's indicate with something like `[Editor]` in the statusbar that we are in a special state.
* [x] Make it configurable which editor to use. Done in 19c5925c378edc12e383278561e1a2f5e2d1f597
* [x] Save in `.local/share/profanity/editor/barejid.md` instead of `/tmp/profanity-uuid.md`. Advantages: not a place where other users have access. By using barejid we can also reopen this later and only delete it once sent. -> 242381cfd012edbba3f502aaa287aa4a3806dddf
* [x] (Maybe) delete the tmp file only once we sent the message. So that one could run `/editor` several times and amend some text. -> not done

**Comment by jubalh** [comment]
Some ideas where this could lead:

This can later be used to reply to messages too.
Maybe a workflow like his:
* /reply
* each line gets a number
* press the number (3)
* editor gets opened containing ">" + the content of line 3

@kaffeekanne also suggest to use it for correct via `/edit correct`

**Comment by mdosch** [comment]
I'd prefer to have a number per message and quote the full message even if it's multiline.

**Comment by jubalh** [comment]
> I'd prefer to have a number per message and quote the full message even if it's multiline.

That's what I said?

**Comment by mdosch** [comment]
You said 'line' but a message could be several lines.

**Comment by jubalh** [comment]
You are right, that was not clear. I meant the same though. Maybe a better word would be entry. An entry starting with date + nick + message. That entry will have `-` char where we want the number. And then the message (possibly spread along several lines).

**Comment by DebXWoody** [comment]
> Decide what PREF_COMPOSE_EDITOR should return by default /usr/bin/vim, xdg-open, $EDITOR, $VISUAL? Right now we use fork()/execl() we need a whole path. So just xdg-open or $EDITOR won't work right now.

See: #1546

**Comment by DebXWoody** [comment]
I just tried to use a graphical editor ( `gvim` ). At the beginning everything looks fine, but after saving the file, the text will not be added to readline. gvim will run in the background, so we are not able to wait for the session.

I created a file `/usr/local/bin/gvimf`

``` 
#!/bin/bash
gvim -f $1
```
In profanity I set `compose.editor=gvimf`.
This was working.

**Comment by jubalh** [comment]
Good enough for now.

**Comment by Hund** [comment]
How do I bind the editor to a key so I can spawn the editor using a keybinding?

**Comment by jubalh** [comment]
Most likely by reading the documentation https://profanity-im.github.io/guide/latest/keybindings.html

**Comment by Hund** [comment]
> > English is not my native language,
> 
> Mine neither. Probably that's part of the problem :D

I'm pretty sure it's me, I'm getting old and grumpy. :)

> > The issue I have is that I sometimes write a message and then realize it's getting lengthy and would like to format in in fancy ways or just be able to access spellchecking. That's not possible if I have already written any text.
> 
> I see. Makes sense. Personally I think it would be best to think about it before :) But I can see the point. Maybe `/editor` should also allow unlimited arguments and just put them into the editor window if they are there. So that one can just POS1 and prefix /editor to the line. Would that help?

Think before doing something? You have high hopes about me for sure. I don't always how lengthy a message might be before it's too late.

Jumping to the beginning of the line and adding the `/editor` before the message text would be an okay compromise, but I would prefer to be able to use a keybinding, which I'm used to do with my web browser.

**Comment by Hund** [comment]
> Maybe let's wait until #1596.
> 
> But if above mentioned idea helps you could maybe try to implement it if you want. I can also guide you, like which files to touch and where to look for inspiration on how to do it. Interested?

That sounds awfully helpful. I'm not the one to say no to any help. :)

**Comment by jubalh** [comment]
> Jumping to the beginning of the line and adding the /editor before the message text would be an okay compromise, but I would prefer to be able to use a keybinding, which I'm used to do with my web browser.

Maybe this can be done as a second step.

> That sounds awfully helpful. I'm not the one to say no to any help. :)

Great! So you will need to check out `src/command/cmd_defs.c` and grep for `cmd_editor(` this is where the defintion is stored. You will need to take a look at the line starting with `parse_args` where we tell it how many arguments it allows. Look at another command to see what you need to use there. Also at the bottom there is `CMD_NOARGS` which you will need to change.
Then you will need to check out `src/command/cmd_funcs.c` and grep for the same function name. You will need to adapt it so that it writes the args passed to it into the file before opening it.

If you have more questions you can also contact my on XMPP or in our MUC.

As I said I would wait for that PR mentioned above to be merged since it will touch that code too.
