### ISSUE TITLE
Add XEP-0157 server contact information discovery

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1524]
There are various reasons why you'd want to contact a servers operator. As a lot of servers support [XEP-0157: Contact Addresses for XMPP Services](https://xmpp.org/extensions/xep-0157.html) it would be handy if those could be queried from within profanity.

**Comment by jubalh** [comment]
@mdosch your server supports that/has those infos set?

**Comment by mdosch** [comment]
Am 9. Juni 2021 16:57:05 UTC schrieb Michael Vetter ***@***.***>:
***@***.*** your server supports that/has those infos set?
>

Yes.
