### ISSUE TITLE
Can't send OMEMO messages after reconnect

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1530]
Whenever profanity reconnects I can't send OMEMO encrypted messages afterwards. I can provide you a log file (but I won't publish it) if you contact me via XMPP or Email: martin@mdosch.de

## Expected Behavior
OMEMO still works after reconnect.

## Current Behavior
Profanity tells me it doesn't have any key to encrypt to the contact. I have to do `/omemo end` and `/omemo start` to get it working again.

## Steps to Reproduce (for bugs)

1. Start profanity
2. Configure autoping
3. Send OMEMO encrypted messages to a contact
3. Switch of WiFi or unplug Ethernet to force a connection loss
4. Wait till profanity realizes it's disconnected
5. Reconnect the machine to the internet
6. Wait for the reconnect to succeed
7. Try to send another OMEMO encrypted message to the contact from 3.

## Environment

Profanity, version 0.10.0dev.master.1ef700f9
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.2)
GTK icons/clipboard: Enabled

**Comment by DebXWoody** [comment]
I think we need to do a "omemo session start" for all open windows where the chat mode is "OMEMO".
