### ISSUE TITLE
build error: undefined reference to `xmpp_stanza_etc...

### ISSUE THREAD

**Issue by al-al-physics** [profanity-im/profanity#1535]
When building, command "make" gives me errors of the type:

undefined reference to `xmpp_stanza_etc

where etc is either "get_child_by_name_and_ns" and "new_from_string"

Current distribution, XUbuntu 20.04

Both profanity and libmesode pulled from last version. 

building of libmesode without errors

./configure of profanity recognizes libmesode

last part of the output of "make":

/usr/bin/ld: src/xmpp/iq.o: in function `_muc_register_nick_handler':                                                     
/home/user/programs/profanity/src/xmpp/iq.c:2759: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'          
/usr/bin/ld: /home/user/programs/profanity/src/xmpp/iq.c:2745: undefined reference to `xmpp_stanza_get_child_by_name_and_
ns'                                                                                                                       
/usr/bin/ld: /home/user/programs/profanity/src/xmpp/iq.c:2767: undefined reference to `xmpp_stanza_get_child_by_name_and_
ns'                                                                                                                       
/usr/bin/ld: /home/user/programs/profanity/src/xmpp/iq.c:2750: undefined reference to `xmpp_stanza_get_child_by_name_and_
ns'                                                                                                                       
/usr/bin/ld: src/xmpp/iq.o: in function `_muc_register_nick_response_handler':                                            
/home/user/programs/profanity/src/xmpp/iq.c:2691: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'          
/usr/bin/ld: src/xmpp/iq.o:/home/user/programs/profanity/src/xmpp/iq.c:2703: more undefined references to `xmpp_stanza_ge
t_child_by_name_and_ns' follow                                                                                            
/usr/bin/ld: src/xmpp/message.o: in function `_handle_ox_chat':                                                           
/home/user/programs/profanity/src/xmpp/message.c:1464: undefined reference to `xmpp_stanza_new_from_string' 
/usr/bin/ld: src/xmpp/message.o: in function `_handle_chat':                                                              
/home/user/programs/profanity/src/xmpp/message.c:1361: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'     
/usr/bin/ld: src/xmpp/message.o: in function `_handle_form':                                                              
/home/user/programs/profanity/src/xmpp/message.c:271: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'      
/usr/bin/ld: src/xmpp/message.o: in function `_handle_groupchat':                                                         
/home/user/programs/profanity/src/xmpp/message.c:1052: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'     
/usr/bin/ld: /home/user/programs/profanity/src/xmpp/message.c:1060: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'                                                                                                                  
/usr/bin/ld: src/xmpp/message.o: in function `_handle_mam':                                                               
/home/user/programs/profanity/src/xmpp/message.c:1487: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'     
/usr/bin/ld: src/xmpp/bookmark.o:/home/user/programs/profanity/src/xmpp/bookmark.c:312: more undefined references to `xmpp_stanza_get_child_by_name_and_ns' follow                                                                                 
collect2: error: ld returned 1 exit status                                                                                
make[1]: *** [Makefile:1628: profanity] Error 1                                                                           
make[1]: Leaving directory '/home/user/programs/profanity'                                                               
make: *** [Makefile:1241: all] Error 2

**Comment by jubalh** [comment]
1) I should close this without any answer since you chose to not follow the issue template
2) You are missing dependencies. Go to our website and read how to build Profanity.

**Comment by al-al-physics** [comment]
1. how rude and rigid: I read the template and followed its structure
2. I read it all, and checked dependencies twice
3. the name "profanity" is not earned if you apply church-like rules
