### ISSUE TITLE
Improve Tab completion

### ISSUE THREAD

**Issue by g4570n** [profanity-im/profanity#1536]
## Expected Behavior

![Image of Tab leaving a space after autocomplete a command](https://0x0.st/-jRv.png)
For example: if I type `/conn` and press the `TAB` key, the `/connect` command is autocompleted, adding a space ready to start writing the account name, avoiding having to press the `space bar`.

## Current Behavior

![Image of Tab not leaving a space after autocomplete a command](https://0x0.st/-jRw.png)
If I now type `/conn` and press the `TAB` key, the `/connect` command is autocompleted with the cursor glued to the word `connect`, it forces me to have to press the `space bar` to start writing the account name.

## Context

The same happens with all other commands. I use other command line chat tools such as: `irssi` that do not have this behavior.
In `profanity` I usually expect the behavior that I am already used to when I press the `TAB` key to autocomplete, it is annoying when I have to delete to go back and add a space between the command and the arguments.

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version

```
$ uname -a
OpenBSD 6.9 GENERIC#464 amd64

$ profanity -v
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.8)
GTK icons: Disabled

```

**Comment by jubalh** [comment]
Honestly I like the behaviour like it is. There are also commands that don't take any arguments. And i don't think pressing space is taking so much time..

**Comment by jubalh** [comment]
So I talked with others about this and noone sees much value in this change.

Also so far the space is what lets tab completion know whether to complete the first word or another parameter of that command. I'm not sure how we would otherwise do it.

Will close this.
