### ISSUE TITLE
Message Reflection

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1544]
# How should we implement message reflection?

## xep-0045

> The service SHOULD reflect the message with the same 'id' that was generated by the client, to allow clients to track their outbound messages. If the client did not provide an 'id', the server MAY generate an 'id' and use it for all reflections of the same message (e.g. using a UUID as defined in RFC 4122 [18]).
> 
> Note: the requirement to reflect the 'id' attribute was added in version 1.31 of this XEP. Servers following the new specification SHOULD advertise that with a disco info feature of 'http://jabber.org/protocol/muc#stable_id' on both the service domain and on individual MUCs, so that clients can check for support.

https://xmpp.org/extensions/xep-0045.html#message

## Wiki

> 1. you recently sent a message to the MUC, AND
> 2. the received message is from your participant JID, AND
>     1. the XEP-0359 origin ID matches (probably not a transport) OR
>     2. the message ID matches (a nice MUC, but not required by the XEP) OR
>    ....

https://wiki.xmpp.org/web/XEP-Remarks/XEP-0045:_Multi-User_Chat#Matching_Your_Reflected_Message

## xep-0359

> They are also useful in the context of Multi-User Chat (XEP-0045) [2] conferences, as they allow to identify a message reflected by a MUC service back to the originating entity.

https://xmpp.org/extensions/xep-0359.html

**Comment by jubalh** [comment]
What's wrong with our current approach?

**Comment by DebXWoody** [comment]
When I understood well, we should use message-id (muc#stable_id) instead of
XEP-0359. If we assume that the implementation follows xep-0045, it will be
possible to build message reflection based on message-id, only.
See XSF-MUC log (today)

**Comment by jubalh** [comment]
https://logs.xmpp.org/xsf/2021-06-02?p=h#2021-06-02-d1cb6d2c74b524e1
```
DebXWoody "How should we implement message reflection?

#1: In XEP-0045:
The service SHOULD reflect the message with the same 'id' that was
generated by the client, to allow clients to track their outbound messages.
If the client did not provide an 'id', the server MAY generate an 'id' and
use it for all reflections of the same message.

#2: On the Wiki page:
1) you recently sent a message to the MUC, AND
2) the received message is from your participant JID, AND
 I) the XEP-0359 origin ID matches (probably not a transport) OR
 II )the message ID matches (a nice MUC, but not required by the XEP) OR

#3: In XEP-0359
They are also useful in the context of Multi-User Chat (XEP-0045) [2]
conferences, as they allow to identify a message reflected by a MUC service
back to the originating entity.

When I understood well, we should use message-id (muc#stable_id) instead of
XEP-0359. If we assume that the implementation follows #1, it will be
possible to build message reflection based on message-id, only.

The text in the wiki #2 should change the order of I) and II) or drop I) at
all.

( I just talk about basic XMPP via MUC - without the idea to have stanzas
forwarded my different servers etc. - where XEP-0359 may helpful.)

Is this correct or did I misunderstood something?"
7:19:16 PM
MattJ "You're right, practically all services take the muc#stable_id approach (jabber.org/M-Link used to be, and may currently still be, an exception)"
7:20:01 PM
MattJ "This happened because originally XEP-0045 did not specify the behaviour, so that text about reflecting with the same id was added later on"
7:20:32 PM
DebXWoody "Yes, I saw. But we should fix XEP-0359 and wiki as well?"
7:25:26 PM
MattJ "In my opinion yes, and origin-id should be removed from the XEP"
7:25:42 PM
MattJ "But last I knew the author disagreed :)"
7:26:11 PM
DebXWoody "Maybe there are other use cases where it can be helpful."
7:26:37 PM
DebXWoody "But at least for MUC it will not"
7:27:56 PM
DebXWoody "Maybe in IoT where messages get routed by lot of "things", each can att a origin-id ID."
7:28:16 PM
DebXWoody "s/att/add"
7:32:57 PM
flow "I think having a mechanism allowing an originating entity to signal that it has assigned the given unique and stable ID to one an outgoing stanza could become handy. That said, the use origin-id use case for MUC is now gone and the XEP should reflect that. "
7:33:08 PM
flow "DebXWoody, in that case you would use probably <stanza-id/>"
8:34:46 PM
Geno "test"
8:41:43 PM
eta "MattJ, there are decent arguments against using the client ID"
8:41:55 PM
eta "the client-supplied ID is not always unique"
8:42:15 PM
eta "oh wait, but I guess that's what XEP-0359 is for"
8:58:15 PM
DebXWoody "To be unique is an agreement which can be defined in origin-id and also in message-id. At the end of the day the client has to generated the id and as to make sure it's unique. Should be a problem - for both concepts."
8:58:42 PM
DebXWoody "Shouldn't be a problem"
8:59:05 PM
Kev "Until you have to trust hostile clients :)"
9:11:36 PM
flow "DebXWoody, sure, you *could* have also a marker extension telling that the rfc id is globally unique (as opposed to unique within the scope of a single stream)" 
```

**Comment by weiss** [comment]
> If we assume that the implementation follows xep-0045, it will be possible to build message reflection based on message-id, only.

Only if you assume the implementation follows XEP-0045, [version 1.31][1] (2018-03-06) or newer, which is of course not true for all servers in the wild.  So the question would be how to deal with services not announcing that feature.

I fully agree that Origin ID is a workaround that should become redundant over time.  Question is how to get there, and I think the first step would be making sure all maintained servers announce that feature.  I'm aware of at least one [piece of server software][2] which doesn't seem to announce that feature yet.  So I'd suggest [kicking those lazy devs][3], checking other server implementations, and sticking to Origin ID on the client side for a while.

[1]: https://xmpp.org/extensions/xep-0045.html#revision-history-v1.31
[2]: https://ejabberd.im
[3]: https://github.com/processone/ejabberd/issues/new/choose

**Comment by jubalh** [comment]
Thanks for the feedback!

So I think it's best to stay with our current model of message reflection. And switch in a few years :)
