### ISSUE TITLE
OMEMO - announce device id after clear_device_list

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1545]
## Expected Behavior
We should announce the OMEMO device ID, just after we did a `/omemo clear_device_list`.

## Current Behavior
The user needs to restart profanity to announce the current device.

See: #1538

**Comment by DebXWoody** [comment]
I think the `<publish-options/>` should be used when we creating the node ( node does not exists ). If the node exists, we shouldn't use this option. Maybe we should display a working if there is another access_model used ( not `open`).

See: https://github.com/profanity-im/profanity/issues/1538#issuecomment-851033245

**Comment by jubalh** [comment]
I think this is done in https://github.com/profanity-im/profanity/pull/1591.
Feel free to reopen/comment in case there is still work to be done.
