### ISSUE TITLE
gentoo dependency on shell unmask by missing keyword without any environment 

### ISSUE THREAD

**Issue by catafest** [profanity-im/profanity#1547]
gentoo dependency on shell unmask by missing keyword without environment
select profile set to desktop 

## Steps to Reproduce (for bugs)

1. command :
...
emerge --ask --autounmask-write net-im/profanity
...
2. output with :
...
 - net-im/profanity-0.9.5::gentoo (masked by: missing keyword)
...
## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version

**Comment by jubalh** [comment]
@catafest that's not a upstream issue. That rather sounds like it's an issue on your system.

@andrey-utkin I just checked the Gentoo ebuild. would you mind updating to 0.10.0? So far it seems Gentoo is still having 0.9.5.
