### ISSUE TITLE
OMEMO - Check implementation - headline / devicelist

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1551]
When I remember well, profanity asks the buddy`s via <iq/> to get the OMEMO device list.

The OMEMO device list will be send via headline from the buddy to the user.

`
<message type="headline" to="user1@domain/profanity.37lb" from="user2@domain"><event xmlns="http://jabber.org/protocol/pubsub#event"><items node="eu.siacs.conversations.axolotl.devicelist"><item id="current"><list xmlns="eu.siacs.conversations.axolotl"><device id="179620673"/><device id="260570434"/><device id="898388139"/><device id="1185166165"/><device id="176266165"/></list></item></items></event><addresses xmlns="http://jabber.org/protocol/address"><address jid="user2@domain/abc" type="replyto"/></addresses></message>
`

- [ ] Check the implementation of `headline` to get the device list via `headline`

**Comment by DebXWoody** [comment]
It would be very nice if we will be able to get notifications about device list changes. I will take a look.

**Comment by jubalh** [comment]
When do we get this send?
What do we want to display?

**Comment by jubalh** [comment]
Any news?

**Comment by jubalh** [comment]
Not sure what should be done here.
Feel free to reopen/comment in case there is still work to be done.
