### ISSUE TITLE
Buddy status is offline in chat window

### ISSUE THREAD

**Issue by DebXWoody** [profanity-im/profanity#1555]
## Expected Behavior
If the buddy is online, the status in chat window should be online as well.

## Current Behavior
Sometimes, the buddy is online in the roster and in MUCs. When I open a dialog `/msg buddy` the buddy is shown as offline. I also didn't get MAM request.

## Steps to Reproduce (for bugs)
Not reproducible, always. If it's the case, it look quite reproducible.
1. Buddy is online ( Roster )
2. `/msg Buddy`
3. Check online state in the chat window

## Environment
* Version 0.10.0dev.master.e1fbe3be
* Debian testing

**Comment by jubalh** [comment]
Can't reproduce at all :)
