### ISSUE TITLE
Paste detection

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#156]
Currently blocks of text pasted into Profanity are sent as many single line messages.

Handle pasting of block text as a single message with newlines.

**Comment by JIoJIaJIu** [comment]
Requesting feature, plz

**Comment by sudo-nice** [comment]
Requesting for the feature too.

**Comment by rajmahaul** [comment]
Are there any updates with this issue? So far I really like this messenger, but for my use I will need this capability to paste multi-line copies. The messenger sees other multi-line messages without issue, and copies them fine. I am just not able to paste my own. Any ideas on when this might be resolved?

**Comment by boothj5** [comment]
There's been no work in the core code to add this feature

However, if you have the time to install it, the latest code in master branch allows plugins, and I've written a plugin that will send the contents of the clipboard using a "/paste" command, I've tested it on Ubuntu and OSX.

The build just requires a couple of extra dependencies when compiling profanity, mentioned in the readme here: https://github.com/boothj5/profanity-plugins

The [paste](https://github.com/boothj5/profanity-plugins/blob/master/paste.py) plugin requires the [Python TKinter](https://tkinter.unpythonic.net/wiki/How_to_install_Tkinter) package.

I'd still like to support this natively, but in the meantime this should work.

The plugins functionality will be in the next release (0.5.0).

**Comment by sudo-nice** [comment]
> The plugins functionality will be in the next release (0.5.0).

Nice!

**Comment by mrsdizzie** [comment]
Would love this feature also -- or even just a way to have a plugin like this default to all text input when installed so it doesn't need to be invoked manually with /paste (Imagine this could be similar to VIM paste mode where it is either on or off).
