### ISSUE TITLE
Can't install Profanity with terminal-notifier using Homebrew

### ISSUE THREAD

**Issue by mhmdanas** [profanity-im/profanity#1588]
## Expected Behavior

`brew install profanity --with-terminal-notifier` should work.

## Current Behavior

```console
$ brew install profanity --with-terminal-notifier
[Homebrew help text]
Error: invalid option: --with-terminal-notifier
```

## Possible Solution

Not sure, maybe provide a tap with this option?

## Steps to Reproduce (for bugs)

1. Run `brew install profanity --with-terminal-notifier`

## Context

Homebrew has removed all options for homebrew-core formulae: https://github.com/Homebrew/homebrew-core/issues/31510

## Environment
* Trying to install Profanity 0.11.0
* Operating System/Distribution: macOS 11.4
* glib version: um, not sure how to get this one.

**Comment by jubalh** [comment]
Where do you have the `--with-terminal-notifier` from?
In our configure script we use `--enable-notifications`.

> Not sure, maybe provide a tap with this option?

Wouldn't that be a bug for homebrew instead of us?

Generally I think that this bug belongs to downstream homebrew and not to us.

**Comment by mhmdanas** [comment]
> Where do you have the --with-terminal-notifier from?

I got it from [the installation guide on the website](https://www.profanity.im/install.html#os-x).

> Wouldn't that be a bug for homebrew instead of us?

This is not a bug; they disabled it intentionally.

**Comment by jubalh** [comment]
BTW that is the old website URL you need to use: https://profanity-im.github.io/guide/latest/install.html#os-x
But since we didn't have feedback from OSX users since some time this information might be outdated.

> This is not a bug; they disabled it intentionally.

Then I don't understand. What do you need then?

> Edit: I get the same error with brew install profanity --enable-notifications.

I don't know brew. So I can't tell you whether that is the right way to pass a configure flag to it. I was saying that `--enable-notifications` is the configure flag we use.

**Comment by mhmdanas** [comment]
> BTW that is the old website URL you need to use: https://profanity-im.github.io/guide/latest/install.html#os-x

Welp, my bad, though it contains the same info as the one I posted.

> But since we didn't have feedback from OSX users since some time this information might be outdated.

I'm willing to open some PRs to update the info on macOS.

> Then I don't understand. What do you need then?

I opened this issue more as a sort of heads up, since I thought the maintainers might not be aware of it (as I found no previous issues about this).

> I don't know brew. So I can't tell you whether that is the right way to pass a configure flag to it. I was saying that --enable-notifications is the configure flag we use.

Yeah, I just wanted to try and see if it works.

Anyway, I thought up some more alternatives since I opened the issue:
- direct users to build from source if they want notifications
- change formula to enable terminal notifications by default (I personally prefer this one)

**Comment by jubalh** [comment]
> I'm willing to open some PRs to update the info on macOS.

That's great! It would be very helpful to have someone with a macOS system who can proofread the information and update it accordingly.

> direct users to build from source if they want notifications

You can improve the macOS instructions in case they differ from regular builds. Here are some resources:

Building guide (it has a macOS section that might need updates?):
* https://profanity-im.github.io/guide/latest/build.html

How we build for macOS for our CI:
* https://github.com/profanity-im/profanity/blob/master/.github/workflows/main.yml#L25
* https://github.com/profanity-im/profanity/blob/master/Brewfile
* https://github.com/profanity-im/profanity/blob/master/ci-build.sh

**Comment by mhmdanas** [comment]
Thanks for the resources.

So I quickly took a look at [Profanity's formula](https://github.com/Homebrew/homebrew-core/blob/1e4a5248f4c630f3de5e6e65a258ea0f8701cfbf/Formula/profanity.rb), and oddly enough, it depends on `terminal-notifier` even while not using it. I suppose the fix is very simply to add an `--enable-notifications` argument to the `./configure` call. I'll try to open a PR for this on https://github.com/Homebrew/homebrew-core.

**Comment by jubalh** [comment]
> it depends on terminal-notifier

I'm no macOS expert. We use a library called `libnotify` if `terminal-notifier` works with that then all will be good :)

> I'll try to open a PR for this on https://github.com/Homebrew/homebrew-core.

Great!

> Would you mind enabling it by default?

We have an --enable-X and --disable-x for everything. And if some dependencies are autodetected the --enable will be the default.
It is best if distributions/users just specify the flags they want.

**Comment by mhmdanas** [comment]
> I'm no macOS expert. We use a library called libnotify if terminal-notifier works with that then all will be good :)

It used to work for me a while ago (I re-installed Profanity because of some issues), so it should work.

> We have an --enable-X and --disable-x for everything. And if some dependencies are autodetected the --enable will be the default.
It is best if distributions/users just specify the flags they want.

I was referring to enabling it by default in the Homebrew formula.

**Comment by jubalh** [comment]
> It used to work for me a while ago (I re-installed Profanity because of some issues), so it should work.

I see. Good to know.

> I was referring to enabling it by default in the Homebrew formula.

I see. Sure, the homebrew maintainers should do whatever they see fit. If they don't used fixed maintainers you can certainly enable it by default there. We don't mind.

**Comment by mhmdanas** [comment]
So I figured out that the formula already has notifications enabled, so this issue is kinda unnecessary now. Sorry for the disturbance.

I'll be making PRs to update the info for macOS sometime soon.

**Comment by mhmdanas** [comment]
Well, it has notifications enabled, but I still can't get them to work. Will post findings if I discover anything. Sorry for all the spam on this issue.
