### ISSUE TITLE
Chat history lost after closing window

### ISSUE THREAD

**Issue by ghost** [profanity-im/profanity#1589]
## Expected Behavior
When closing a chat window and re-opening one, the entire chat history should be displayed when `history=true` is set in the configuration file.

## Current Behavior
During a chat, messages are displayed in the window. Once the window is closed and that I re-open the same one, chat history is blank. `history=true` is set in the configuration file.

## Possible Solution
Chat is logged, as per the configuration file, in `.local/share/profanity/chatlogs/`. However, the SQLite database is not updated.
Closing Profanity, deleting the database in `.local/share/profanity/database/` and re-starting Profanity creates a new empty one. Then I initiate a chat with few messages. The first one is stored in the database, but not the following ones. If I close and re-open the window, only the first message (the one saved in the database) is displayed in the chat window history.

So, this is probably an issue with updating the database. It started with Profanity 0.11. The database from 0.10 worked and those messages are still displayed in the chat history.

## Steps to Reproduce (for bugs)
1. Start a new conversation with `/msg nick`
2. Send and/or receive a few messages
3. Close this chat window with `/close`
4. Re-initiate a conversation with the same person `/msg nick`

## Context
It is impossible to keep a history of any conversations. 

## Environment
* Operating System/Distribution: Parabola GNU/Linux
* glib version: 2.33
* Window Manager: sway 1.6.1
* Terminal Emulator: termite 15

`profanity -v`

Profanity, version 0.11.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.16.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.6)
GTK icons/clipboard: Disabled

**Comment by huhndev** [comment]
I can reproduce the bug. However, for me only the messages sent by me disappear.

### Environment
Operating System/Distribution: OpenBSD 6.9

`profanity -v`
Profanity, version 0.11.0dev.master.c89e3126
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.10)
GTK icons/clipboard: Enabled

**Comment by jubalh** [comment]
Note: Most likely I changed something when I was starting to implement MAM, and didn't think about it correctly before finishing MAM.

**Comment by lynix** [comment]
I'm also experiencing this issue. Old messages are loaded from the database when opening a new chat window but new ones only get saved to the `chatlogs/` directory.

    Profanity, version 0.11.1
    Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
    Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
    License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
    
    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Build information:
    XMPP library: libmesode
    Desktop notification support: Enabled
    OTR support: Enabled (libotr 4.1.1)
    PGP support: Enabled (libgpgme 1.16.0)
    OMEMO support: Enabled
    C plugins: Enabled
    Python plugins: Enabled (3.9.7)
    GTK icons/clipboard: Enabled

**Comment by jubalh** [comment]
> Old messages are loaded from the database when opening a new chat window but new ones only get saved to the chatlogs/ directory.

I think this might be yet another issue.

https://github.com/profanity-im/profanity/blob/master/src/database.c#L118 we have `NOT NULL` there. Maybe one of them is NULL? Could you debug and check?

**Comment by JurajMlich** [comment]
Hi @jubalh,

I've looked into the problem and have identified what's causing this issue.

In `src/database.c`, the function `_add_to_db` contains 

```
    query = sqlite3_mprintf("INSERT INTO `ChatLogs` (`from_jid`, `from_resource`, `to_jid`, `to_resource`, `message`, `timestamp`, `stanza_id`, `archive_id`, `replace_id`, `type`, `encryption`) SELECT '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q' WHERE NOT EXISTS (SELECT 1 FROM `ChatLogs` WHERE `archive_id` = '%q')",
                            from_jid->barejid,
                            from_jid->resourcepart ? from_jid->resourcepart : "",
                            to_jid->barejid,
                            to_jid->resourcepart ? to_jid->resourcepart : "",
                            message->plain ? message->plain : "",
                            date_fmt ? date_fmt : "",
                            message->id ? message->id : "",
                            message->stanzaid ? message->stanzaid : "",
                            message->replace_id ? message->replace_id : "",
                            type ? type : "",
                            enc ? enc : "",
                            message->stanzaid ? message->stanzaid : "");
```

The thing is that OMEMO encrypted messages for some reason do not have stanzaid set (I didn't investigate why that's the case), so the default value "" (empty string) is used. The commit which introduced the subselect for the NOT EXISTS clause says the following

```
In case no archive_id will be set, it will be `(null)` and thus should
be inserted anyways because it won't find a value with (null) in that
row.
```

This however is not what's happening. An empty string is inserted instead of NULL. And therefore when trying to insert the second message, there EXISTS a row with an archive_id set to an empty string, thus the row is ignored and not created. And that's what's causing the history to not work properly.

I have temporarily modified the condition to
```
    query = sqlite3_mprintf("INSERT INTO `ChatLogs` (`from_jid`, `from_resource`, `to_jid`, `to_resource`, `message`, `timestamp`, `stanza_id`, `archive_id`, `replace_id`, `type`, `encryption`) SELECT '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q', '%q' WHERE NOT EXISTS (SELECT 1 FROM `ChatLogs` WHERE `archive_id` = '%q' AND `archive_id` != '')",
     ...
```
Note the added ` AND `archive_id` != ''` part. It fixes the problem. Would you like me to submit a PR? A better solution would obviously be to use NULLs instead of empty strings but that could potentially require a lot of testing as it could break other parts of the app that currently rely on that. But I'm afraid I don't have enough time to get to know the codebase well enough to be able to do that, so for the time being we could settle on this. 

What do you think?

**Comment by jubalh** [comment]
@JurajMlich good job! Thanks a lot for looking into this!

>  A better solution would obviously be to use NULLs instead of empty strings but that could potentially require a lot of testing as it could break other parts of the app that currently rely on that.

Right now I also don't know the details of the code anymore.

> Would you like me to submit a PR?

Yes, please do that :)

**Comment by JurajMlich** [comment]
@jubalh will do, either tomorrow or the day after
