### ISSUE TITLE
Error during python detection on Debian 11

### ISSUE THREAD

**Issue by vit1251** [profanity-im/profanity#1590]
Since Debian 11 is release I try to compile latest reelase and meet with next one error:

```
...
checking whether to build static libraries... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for python-config... no
checking for python3-config... yes
checking for python... no
configure: error: Cannot find python in your system path
```

My system contain python3.9 version and package was installed.

**Comment by jubalh** [comment]
See https://salsa.debian.org/xmpp-team/profanity/-/blob/debian/master/debian/rules#L41
There is no `/usr/bin/python` just `/usr/bin/python3` on recent Debian since the py2 -> 3 change afaik.
