### ISSUE TITLE
Do not check for OMEMO device id for JIDs banned of a MUC

### ISSUE THREAD

**Issue by pmaziere** [profanity-im/profanity#1594]
I recently had an issue with my prosody server that kept trace of a banned user among the participant of a private MUC.
This resulted in profanity spitting "Can't find a OMEMO device id for <banned_JID>." each time I was sending a message in the MUC.  Removing the banned JID in the relevant MUC related file on the server side and restarting profanity prevented this annoying error message to come back.

I then realized that  it does not make sense for profanity to check for OMEMO device id of MUC banned JIDs.
But that may trigger some security issues that I'm not aware of, so I let this discussion to the OMEMO gurus :)

Thanks again for this great piece of useful software !

**Comment by jubalh** [comment]
@paulfariello does this make sense?

**Comment by jubalh** [comment]
We go through all members in https://github.com/profanity-im/profanity/blob/master/src/omemo/omemo.c#L783
When a ban occured it seems we never removed the person from the members list.
