### ISSUE TITLE
Announcing public key is undocumented

### ISSUE THREAD

**Issue by marhu98** [profanity-im/profanity#1602]
Is there a way to announce the public key so that people can send you pgp encrypted messages? Currently if there are, it appears to be undocumented.

**Comment by jubalh** [comment]
You need to get their public key from a keyserver. Like with EMail too.

**Comment by marhu98** [comment]
But, what is the command? It doesn't say...

**Comment by jubalh** [comment]
It's not a command in Profanity.
Maybe:
* https://www.gnupg.org/gph/en/manual/x56.html
* https://www.gnupg.org/gph/en/manual/x457.html

can help you to learn how to use GPG  in general.

**Comment by marhu98** [comment]
Aaah it needs to be in the local key ring. In my case the key was in the keyring but I guess the uid has to match as well?

**Comment by jubalh** [comment]
About  XEP-0027: Current Jabber OpenPGP Usage
