### ISSUE TITLE
Persistent /silence on?

### ISSUE THREAD

**Issue by beaglesnuf** [profanity-im/profanity#1606]
Where is this pref saved? profrc nor the accounts files appear to be modified when this pref is enabled. How to enable persistently? 

$ profanity -v                                                                   
Profanity, version 0.11.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Disabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Disabled
Python plugins: Disabled
GTK icons/clipboard: Disabled

**Comment by mdosch** [comment]
Am 17. Oktober 2021 08:55:29 UTC schrieb beaglesnuf ***@***.***>:
>Where is this pref saved? profrc nor the accounts files appear to be modified when this pref is enabled. How to enable persistently? 
>
>$ profanity -v                                                                   
>Profanity, version 0.11.1
>Copyright (C) 2012 - 2019 James Booth ***@***.***>.
>Copyright (C) 2019 - 2021 Michael Vetter ***@***.***>.
>License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
>
>This is free software; you are free to change and redistribute it.
>There is NO WARRANTY, to the extent permitted by law.
>
>Build information:
>XMPP library: libstrophe
>Desktop notification support: Disabled
>OTR support: Disabled
>PGP support: Disabled
>OMEMO support: Enabled
>C plugins: Disabled
>Python plugins: Disabled
>GTK icons/clipboard: Disabled
>
>
>

Did you try `/save`?

**Comment by jubalh** [comment]
It is saved in profrc.
