### ISSUE TITLE
After profanity restart, a message sent to some recipient is not encrypted for another sender device

### ISSUE THREAD

**Issue by nandesu-utils** [profanity-im/profanity#1609]
## Expected Behavior

After profanity restart, a message sent to some recipient must also be encrypted and be sent to another sender device.
## Current Behavior

They are not encrypted.

That is, once a chat with someone is opened, any message sent within profanity to that participant will not be encrypted for another *sender* device, i.e. mobile phone.

```
# on profanity, a mobile sents a message to some jid
felix@montague.net/profanity: foo
ann@florence.org/any: bar
# on mobile at the same moment
felix@montague.net/profanity: This message was not encrypted for your device.
ann@florence.org/any: bar
```

Though messages from other clients are received by profanity as expected.

## Possible Solution

As I have observed, the device list does not contain key for ourselves as it is used in this snippet:
```c
// src/omemo/omemo.c, char *omemo_on_message_send(...)
                                           "It could also be that the key bundle of the recipient(s) have not been received. "
                                           "In this case, you could try \"omemo end\", \"omemo start\", and send the message again.");
        goto out;
    }

    // Encrypt keys for the sender
    if (!muc) {
        GList* sender_device_id = g_hash_table_lookup(omemo_ctx.device_list, jid->barejid);
        // ! at this point omemo_ctx.device_list does not contain entry for our jid.
        // ! this has been observed by me by checking through iterating and logging entries
        // ! though just right after key creation device_list CONTAINS sender devices

        for (device_ids_iter = sender_device_id; device_ids_iter != NULL; device_ids_iter = device_ids_iter->next) {
```

I may be wrong, since I'm not attentive at all. Though by acquiring device list manually (see the comment) I've managed to fix the problem.

## Steps to Reproduce (for bugs)

1. Generate keys `/omemo gen`
2. Open the same chat within profanity and arbitrary client. Both with OMEMO encryption of course.
3. Join a conversation with someone, send a message. The message is seen on both clients as expected.
4. Restart profanity client.
5. Open the same chat in restarted profanity.
6. Send a message.
7. Receive the message that it was not encrypted for this particular device on another client.

## Context

Basic usage of profanity and other clients.

## Environment
```
Profanity, version 0.11.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Disabled
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.6)
GTK icons/clipboard: Enabled
```

Master's head is modified here but the commit hash must be valid.
```
Profanity, version 0.12.0dev.HEAD.b4d65335
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.6)
GTK icons/clipboard: Enabled
```

Observed in `Gentoo` with `glib-2.68.3`.

**Comment by jubalh** [comment]
@nandesu-utils thanks for looking into this and providing the PR!
