### ISSUE TITLE
`configure.ac` hardcodes a non-portable `/usr/local/opt/readline`

### ISSUE THREAD

**Issue by carlocab** [profanity-im/profanity#1612]
## Expected Behavior

`profanity` should build even when Homebrew is not installed into `/usr/local` and/or `libreadline` cannot be found at `/usr/local/opt/readline`.

## Current Behavior

The `configure` script checks for `libreadline` only at `/usr/local/opt/readline`, so the script fails whenever `libreadline` is not installed into this location.

This is the case, for example, when:
1. Homebrew is installed into the default location (`/opt/homebrew`) on an Apple Silicon Mac
2. a user has installed Homebrew into a non-`/usr/local` prefix
3. `libreadline` is installed through MacPorts.

## Possible Solution

If you're happy with the `configure` script assuming that `libreadline` is installed via Homebrew (I am fine with this), then it would be more portable to query `brew --prefix` and use that as the value for `/usr/local`.

Alternatively, it might help to allow the user to pass a flag for `readline`'s prefix.

I've tested that replacing `/usr/local/opt/readline` with the correct prefix seems to work. See Homebrew/homebrew-core#88600.

## Steps to Reproduce (for bugs)

1. Install Homebrew into a non-`/usr/local` prefix. This is the default on an Apple Silicon Mac. On an Intel Mac, one can use [this installation method](https://docs.brew.sh/Installation#untar-anywhere).
2. Build Profanity from source. This can be done either with `brew install --build-from-source profanity` or by invoking `configure` and `make` directly.

## Context

I'm a Homebrew maintainer, and we package Profanity. I'd like Profanity to work for more Homebrew users.

## Environment
* Profanity 0.11.1
* macOS
* glib version 2.70.1

**Comment by jubalh** [comment]
Can you open a PR with a portable solution?

**Comment by carlocab** [comment]
I'm currently swamped over at Homebrew (a new macOS version just dropped), but if you ping me in two weeks or so I'd be happy to take a look.

**Comment by jubalh** [comment]
Sounds good.
Thanks for taking care of Profanity in homebrew.

BTW there is a new libstrophe version (0.11.0) out in case you guys didn't update that already.

**Comment by jubalh** [comment]
@carlocab ping

**Comment by carlocab** [comment]
Thanks for the reminder. Having a look.

**Comment by carlocab** [comment]
#1617

**Comment by jubalh** [comment]
Thanks for your contribution @carlocab !
