### ISSUE TITLE
Breaks RFC 6120 11.6 by sending non-UTF8 encoded characters

### ISSUE THREAD

**Issue by mjk-gh** [profanity-im/profanity#1626]
## Current Behavior
I have a non-UTF8 locale on all my systems (ISO-8859-15 aka Latin9),
and recently tried Profanity 0.11.1. Among other messages, I used
umlauts in some of my messages, and it seems that they got sent by
Profanity as Latin9-encoded umlauts, i.e. 1 byte (in my example, it
was the letter o-umlaut ("ö"), which is 0xFE in Latin9.

Quote from RFC 6120:
<blockquote>
11.6.  Character Encoding

   Implementations MUST support the UTF-8 transformation of Universal
   Character Set [UCS2] characters, as needed for conformance with
   [CHARSETS] and as defined in [UTF-8].  Implementations MUST NOT
   attempt to use any other encoding.
</blockquote>

The problem with these wrongly encoded messages is that some applications
crash as soon as they encounter them, e.g. [Dino](https://github.com/dino/dino).

Conversations replaces the wrongly encoded umlauts in messages with a
Unicode REPLACEMENT CHARACTER, but I would love to be able to use
Dino again. :-}

## Expected Behavior
I would expect either of the following:
- translate non-UTF8 umlauts to UTF8 (very much preferred)
- replace non-UTF8 umlauts with the official [Unicode REPLACEMENT CHARACTER](https://www.fileformat.info/info/unicode/char/fffd/index.htm)
- replace whole message with "message contained wrongly encoded characters and was therefore not sent"

## Steps to Reproduce (for bugs)
1. Have Latin9 locale (LC_ALL=en_US.ISO-8859-15)
2. Use Profanity and type messages containing umlauts, e.g. "ö" (o-umlaut, 0xFE)
3. See Dino crash trying to display that message.

## Environment
* Give us the version and build information output generated by `profanity -v`
```
profanity -v
Profanity, version 0.11.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.9.2)
GTK icons/clipboard: Enabled
```

* Operating System/Distribution
Debian stable (amd64)
* glib version
```
$ dpkg -l | grep -i libglib
ii  libglib2.0-0:amd64                                          2.66.8-1
[...]
```

**Comment by mar-v-in** [comment]
Note: When sending messages without OMEMO, the server will just close the stream, but with OMEMO, servers can't detect the invalid encoding and thus the error only shows up at the recipient after decrypting the message.

**Comment by jubalh** [comment]
Thanks for this report.

Just for the record, we also have:
* https://github.com/profanity-im/profanity/issues/672
* https://github.com/profanity-im/profanity/issues/248

**Comment by jubalh** [comment]
Isn't this the same as https://github.com/profanity-im/profanity/issues/1437
