### ISSUE TITLE
libnotify causes timeout on console clients

### ISSUE THREAD

**Issue by hbarel** [profanity-im/profanity#1639]
I (try to) use Profanity on a console-only server. Each time a notification arrives, either a new message, a "typing" notification, or even just a carbon-copy of a message sent by myself from another device, the application freezes for _libnotify_ to time-out.

The log reads:

`13/02/2022 17:12:01: prof: DBG: Message stanza handler fired`
`13/02/2022 17:12:01: prof: DBG: Attempting notification: xxx@yyy.com: typing...`
`13/02/2022 17:12:01: prof: DBG: Initialising libnotify`
`13/02/2022 17:12:26: prof: ERR: Error sending desktop notification:`

Needless to say, this happens repeatedly.
Switching off notifications using:

`[notifications]`
`message=false`
`room=false`
`room.text=false`
`message.text=false`
`typing=true`

does not help, even if typing is also switched off, and in any event is not desirable, as in-console notifications are still welcome...

I believe there should be a way to configure Profanity to ignore any desktop integration whatsoever, for console-only use, but could not find such.

**Comment by jubalh** [comment]
> I believe there should be a way to configure Profanity to ignore any desktop integration whatsoever, for console-only use

Sure there is, you need to compile profanity without notifications `--disable-notifications`.

If you don't want to compile yourself you need to contact your distribution. Distributions like openSUSE and Debian have a dedicated package for console only systems. Called `profanity-mini` or something like this.

**Comment by hbarel** [comment]
Indeed, `profanity-light`. I was not aware of that. Thank you.
