### ISSUE TITLE
Add autocompletion for quotes

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [profanity-im/profanity#1649]
Autocomplete previous messages when `>` is typed at the beginning of the line

I already have implemented most of this. Just posting this to be sure that it is something that's accepted by the main devs.
## Expected Behavior
When I type `>` and then tab or shift tab previous messages should autocomplete

## Current Behavior
No previous message autocompetion

**Comment by jubalh** [comment]
So what would the workflow look like? I guess something like:

* type >
* tab until correct message is autocompleted
* press key to open editor
* enter for newline
* type reply

Or do you have another plan about the newline so that the formatting in other clients will be correct for the quote?

**Comment by MarcoPolo-PasTonMolo** [comment]
That's the workflow I had in mind

**Comment by jubalh** [comment]
Sounds good to me!
