### ISSUE TITLE
libgcrypt not found even though it is installed

### ISSUE THREAD

**Issue by herrmoltke** [profanity-im/profanity#1676]
Appears to be similar to #1128. I have libgcrypt and its development files installed, but when I run `./configure --enable-omemo` I get the following error:

```
checking for gcry_md_extract in -lgcrypt... no
configure: error: gcrypt >= 1.7.0 is required for OMEMO support
```

I tried all the workarounds mentioned in that issue, but none solved the problem.

## Steps to Reproduce (for bugs)

1. Install all dependencies, including `libgcrypt-devel`
2. After running `./bootstrap` run `./configure --enable-omemo`

## Environment
OS: Fedora 35
glib version: 2.34
libgcrypt version: 1.9.4

Please let me know if I can provide any additional info. Thanks for building profanity!

**Comment by jubalh** [comment]
Hard to believe :-)
Seems to work fine on our Fedora CI: https://github.com/profanity-im/profanity/runs/5788382597?check_suite_focus=true
We use fedora:latest there.

You didn't mention which version of Profanity you are running btw.

**Comment by herrmoltke** [comment]
Thanks for linking to the successful CI build! Went through it and saw I was missing `libsignal-protocol-c-devel` - so this was a user error, sorry about that. 

Is there a way to make the error message clearer?

**Comment by jubalh** [comment]
You still didnt mention which version you are trying to build. Which is very annoying. 1) It's in the issue template 2) I asked for this specifically.

**Comment by herrmoltke** [comment]
My apologies, this is for 0.12.0. Had the same error when pulling the latest master.

**Comment by jubalh** [comment]
I see. Actually I tried to clean up the configure files for 0.12. And I thought that it should print the correct message now. Maybe I need to revisit this then!
