### ISSUE TITLE
How to disable groupchat autojoining at startup/connection?

### ISSUE THREAD

**Issue by GasparVardanyan** [profanity-im/profanity#1686]
When I connect to my accaunt, it autojoins all of my groupchats. I can't figure it out how to disable this behaviour. Probably there's some config option to deal with it.

**Comment by jubalh** [comment]
It is documented in the user guide.
Issues are for bugs/feature requests. In the README we describe where you can get help. Like joining the MUC, reading the FAQ, reading the user guide. And recently we added GitHub discussions including an Q&A tag.

I prefer if people who ask support questions are sponsors.

Finding this out shouldn't take a long time with all the help and documentation that we provided.

https://profanity-im.github.io/guide/latest/reference.html#bookmark -> `/bookmark update <room> [nick <nick>] [password <password>] [name <roomname>] [autojoin on|off]`.

**Comment by GasparVardanyan** [comment]
But what if I have 100 rooms joined and want to disable autojoin for all of them? Manually?
