### ISSUE TITLE
Feature request: toggle showing previous presence changes with /presence

### ISSUE THREAD

**Issue by aabacchus** [profanity-im/profanity#1689]
## Expected Behavior
In a room or MUC, if `/presence room online` (or `/presence chat online`) is set, there may be many lines of presence updates visible. Now running `/presence room none`, all the presence updates should be hidden, and other message still visible. If `/presence room online` is now set, the presence updates should be made visible again.

## Current Behavior
Toggling `/presence` affects presence changes after the command is run, it has no effect on presence updates already visible in the window.

## Possible Solution
I don't know how or if lines sent to the screen to be displayed are kept track of, but to be able to scroll surely they must be kept track of? Toggling `/presence` should toggle the visibility of lines marked as presence updates. Lines which aren't affected by the change in visibility of presence updates should be scrolled up or down accordingly to fill in the space / create space.

## Context
Sometimes I don't want to have the screen clobbered by presence updates, which can make it difficult to follow a conversation, but I want to check if a particular user has gone offline or come back online.

**Comment by jubalh** [comment]
Well. We just discard the message if we don't want it printed. We don't save this anywhere. It's no message and it's quite useless information so we don't add this to the database.
