### ISSUE TITLE
Notification issue in one to one

### ISSUE THREAD

**Issue by jas01** [profanity-im/profanity#1691]
I use those options for notification

```
[notifications]
room=true
room.text=true
message=true
message.text=true
typing=true
invite=true
sub=true
room.current=true
```
and the notification is working when I'm in a chat room, meaning when the «xterm» is not focus and they are a new message in the chat room I got a notification. 
Now let's say I got 
```
16:30:27 - Active windows:
16:30:27 - 1: Console
16:30:27 - 2: Room ABC                           
16:30:27 - 3: Room XYZ            
16:30:27 - 4: Chat someone A - online
16:30:27 - 7: Chat someone B - chat
```
if I'm in «/win 2»  and I got a message in room ABC and the «xterm» are not in focus, I'll got a notification (exactly what I want).

If I'm in «/win 2» and I got a message from «someone A» and the «xterm»  are not in focus, I'll got a notification (exactly what I want)

But If I'm in win 4 “/win 4” and the «xterm» are not in focus and I received a message from «someone A» I will not get any notification. 
 
## Expected Behavior
Notification when the «xterm» are not in focus and the «win» (in profanity) are not in focus, whatever it's Room Chat or one to one. 

## Current Behavior
No notification in one to one chat if the «win» are in focus but the windows are not.

## Context
It's very annoying because let's take the scenario : 
1/ Your profanity are in a chat room (/win 2 with the previous example), your windows are not in focus
2/ Someone send you a one to one message
3/ You switch to this windows (in profanity), you do some tchat with the person. 
4/ You change «xterm», the person send you a new message.. and you never know

## Environment
Using «termite» as «xterm»

```
Profanity, version 0.12.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.17.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.4)
GTK icons/clipboard: Disabled
```
Arch Linux

**Comment by jas01** [comment]
I'm using i3. But I'm don't think (not 100% sure of course), that come from the windows manager. Because the situation seem to link to the focus *in* profanity and not in the xterm_ish running profanity.

**Comment by jas01** [comment]
Hi, 

Can you provide the reason for the «rejected» label ? 

Thanks

**Comment by jubalh** [comment]
Oops, that was the wrong issue haha

**Comment by jubalh** [comment]
Didn't check the code but I'm not entirely sure if we even check the state of the window.
Personally I always switch to window 1 (console) anyways. So I never suffer from such behaviour (maybe you can use this as a workaround).

I plan to to check later if we check the window state anywhere.

**Comment by MarcoPolo-PasTonMolo** [comment]
@jas01 Try `/notify chat current on`

**Comment by jubalh** [comment]
That will work in sending always notifications. Also when the window is focused.

**Comment by jubalh** [comment]
Probably good enough.
