### ISSUE TITLE
Remember encryption status for PGP and Ox

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1694]
If I enable PGP or Ox for an contact I have to remember to perform `/pgp start` or `/ox start` every time I restart profanity as I will otherwise accidentally send unencrypted messages. For `/omemo start` profanity remembers the encryption stat.

## Expected Behavior
Activate PGP or Ox encryption for chats where it was enabled before.

## Current Behavior
Profanity forgets the state for PGP and Ox.

## Environment
Debian Unstable

```
profanity -v                                                                      :(
Profanity, version 0.12.1dev.master.8ffd8079
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.16.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons/clipboard: Disabled
```

**Comment by jubalh** [comment]
Isn't there already an issue for this?

**Comment by mdosch** [comment]
I haven't seen it. Maybe I used the wrong search terms if there is already one.

**Comment by mdosch** [comment]
There was none for Ox. 😁
