### ISSUE TITLE
Dunst Notifications

### ISSUE THREAD

**Issue by Andonome** [profanity-im/profanity#1709]
## Expected Behavior

Profanity should give some system-notification when a message comes in.

## Possible Solution

An option to use notify-send would be good.

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version

````
Profanity, version 0.11.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.4)
GTK icons/clipboard: Enabled
```

**Comment by MarcoPolo-PasTonMolo** [comment]
I do get notifications with Dunst. Maybe you got notifications off? Try /help notify

**Comment by Andonome** [comment]
Aha! It's working now that I've explicitly turned notifications on.

Cheers.
