### ISSUE TITLE
sending multi-line messages

### ISSUE THREAD

**Issue by christf** [profanity-im/profanity#1723]
For sending longer messages it sometimes is helpful to be able to send newlines. For other clients, ENTER sends the message but Shift + ENTER inserts a newline into the message.

I have tried a few things but have not been able to send a message containing a new line. How do I do it?

## Expected Behavior

pressing Shift + Enter should not send the message but insert a new line into the message being composed.

## Current Behavior

Shift + Enter sends the message

## Steps to Reproduce (for bugs)

1. try to send the message "Hello
World" to someone using profanity
2. 
3.
4.

## Context
I tried providing structure to a long message

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version

this is profanity 0.12 from debian testing:

Profanity, version 0.12.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.14.0-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.5)
GTK icons/clipboard: Enabled

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/issues/182

**Comment by christf** [comment]
thank you!
