### ISSUE TITLE
/autoaway message and /autoaway check are not working

### ISSUE THREAD

**Issue by netboy3** [profanity-im/profanity#1737]
## Expected Behavior
/autoaway message ...
/autoaway check ...
Should function with their respective options

## Current Behavior
Both /autoaway options above (with any of their sub-options) fail with "Invalid usage, see '/help autoaway' for details."

## Possible Solution
Fixed in #1736 

## Steps to Reproduce (for bugs)
1. /autoaway message away Away from computer for a while
Invalid usage, see '/help autoaway' for details.

2. /autoaway check off
Invalid usage, see '/help autoaway' for details.

## Environment
This issue is happening on the latest master (commit 9605334)

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1736 got merged.

Thanks for including the fix in your report!
