### ISSUE TITLE
make install with error (0.12.1)

### ISSUE THREAD

**Issue by TravelTrader** [profanity-im/profanity#1741]
## Expected Behavior
Installing profanity 0.12.1 with [this instruction](https://profanity-im.github.io/guide/0120/build.html#build).

## Current Behavior
I get the following errors at the end:
```
make[1]: *** [Makefile:1653: profanity] Fehler 1
make[1]: Verzeichnis „/home/user/Data/Installationen/profanity“ wird verlassen
make: *** [Makefile:2561: install] Fehler 2
```

## Environment
I had the Ubuntu 20.04. version of profanity 0.8 and wanted to update.

Thank you for your help!

**Comment by jubalh** [comment]
Please provide more of the log file. In the part you are showing it doesn't say what error you get. Do you have all [dependencies](https://profanity-im.github.io/guide/0120/build.html#pkgdeps) installed?
I wonder if Ubuntu 20.04 has all the library versions needed ;)

**Comment by TravelTrader** [comment]
> Please provide more of the log file. In the part you are showing it doesn't say what error you get.

```
/usr/bin/ld: src/xmpp/session.o: in function `_receive_mood':
/home/user/Data/Installationen/profanity/src/xmpp/session.c:297: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/session.c:303: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/connection.o: in function `_xmppcert_to_profcert':
/home/user/Data/Installationen/profanity/src/xmpp/connection.c:1031: undefined reference to `xmpp_tlscert_get_string'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: undefined reference to `xmpp_tlscert_get_pem'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: undefined reference to `xmpp_tlscert_get_string'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: undefined reference to `xmpp_tlscert_get_string'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: undefined reference to `xmpp_tlscert_get_string'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: undefined reference to `xmpp_tlscert_get_string'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: undefined reference to `xmpp_tlscert_get_string'
/usr/bin/ld: src/xmpp/connection.o:/home/user/Data/Installationen/profanity/src/xmpp/connection.c:1033: more undefined references to `xmpp_tlsce
rt_get_string' follow               
/usr/bin/ld: src/xmpp/connection.o: in function `_conn_apply_settings':
/home/user/Data/Installationen/profanity/src/xmpp/connection.c:182: undefined reference to `xmpp_ctx_set_verbosity'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:223: undefined reference to `xmpp_conn_set_capath'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:227: undefined reference to `xmpp_conn_set_certfail_handler'
/usr/bin/ld: src/xmpp/connection.o: in function `_get_soh_error':
/home/user/Data/Installationen/profanity/src/xmpp/connection.c:828: undefined reference to `xmpp_stanza_get_child_by_path'
/usr/bin/ld: src/xmpp/connection.o: in function `connection_get_tls_peer_cert':
/home/user/Data/Installationen/profanity/src/xmpp/connection.c:571: undefined reference to `xmpp_conn_get_peer_cert'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/connection.c:573: undefined reference to `xmpp_tlscert_free'
/usr/bin/ld: src/xmpp/iq.o: in function `_muc_register_nick_handler':
/home/user/Data/Installationen/profanity/src/xmpp/iq.c:2756: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/iq.c:2742: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/iq.c:2764: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/iq.c:2747: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/iq.o: in function `_muc_register_nick_response_handler':
/home/user/Data/Installationen/profanity/src/xmpp/iq.c:2688: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/iq.o:/home/user/Data/Installationen/profanity/src/xmpp/iq.c:2700: more undefined references to `xmpp_stanza_get_child_by_n
ame_and_ns' follow                  
/usr/bin/ld: src/xmpp/message.o: in function `_handle_ox_chat':
/home/user/Data/Installationen/profanity/src/xmpp/message.c:1527: undefined reference to `xmpp_stanza_new_from_string'
/usr/bin/ld: src/xmpp/message.o: in function `_handle_chat':
/home/user/Data/Installationen/profanity/src/xmpp/message.c:1438: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/message.o: in function `_handle_jingle_message':
/home/user/Data/Installationen/profanity/src/xmpp/message.c:1745: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/message.o: in function `_handle_form':
/home/user/Data/Installationen/profanity/src/xmpp/message.c:293: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/message.o: in function `_handle_groupchat':
/home/user/Data/Installationen/profanity/src/xmpp/message.c:1121: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: /home/user/Data/Installationen/profanity/src/xmpp/message.c:1129: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
/usr/bin/ld: src/xmpp/message.o:/home/user/Data/Installationen/profanity/src/xmpp/message.c:1561: more undefined references to `xmpp_stanza_get_
child_by_name_and_ns' follow        
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1653: profanity] Fehler 1
make[1]: Verzeichnis „/home/user/Data/Installationen/profanity“ wird verlassen
make: *** [Makefile:2561: install] Fehler 2
```

> Do you have all [dependencies](https://profanity-im.github.io/guide/0120/build.html#pkgdeps) installed? I wonder if Ubuntu 20.04 has all the library versions needed ;)

I installed all recommended here: https://profanity-im.github.io/guide/0120/build.html#distrodeps
Only `libstrophe-dev` was not the version expected and I installed the newest one manually. So, `./bootstrap.sh` and `./configure` ran without any errors.

Do you think that I cannot install the newest version on Ubuntu 20.04?

**Comment by jubalh** [comment]
> /home/user/Data/Installationen/profanity/src/xmpp/session.c:297: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'

`xmpp_stanza_get_child_by_name_and_ns()` was added in libstrophe 0.10. The version of libstrophe that you are using is older than that and doesn't have this function. That's why you get the error.

If you build libstrophe manually (the newest version) then you also need to tell Profanity to use that version and not the one installed on your distribution.

@mdosch did this recently I think, maybe he can give you instructions in case you don't know how to do that.

**Comment by mdosch** [comment]
Ok, I assume that you have the version of libstrophe and profanity that 
you want to build on your system.
No guarantees, but I just tried on my system (debian testing) and this 
_might_ work:

- If not yet enabled, enable the `deb-src` entries in your 
   `/etc/apt/sources.list`
- `sudo apt update`
- `sudo apt build-dep libstrophe0 profanity`
- In the folder containing libstrophe source run the following (adjust 
   the path to somewhere were you want to store the selfcompiled 
   libstrophe):
   `./configure --prefix=/home/martin/.local/ && make && make install`
- `export LD_LIBRARY_PATH=/home/martin/.local/lib:$LD_LIBRARY_PATH` 
   (also adjust the path to where you stored libstrophe)
- In the folder containing profanity run the following:
   `./bootstrap.sh && ./configure && make && make check && sudo make 
   install`
- You should have profanity now in `/usr/local/bin/profanity`

On 02.08.2022 06:35, Michael Vetter wrote:
>> /home/user/Data/Installationen/profanity/src/xmpp/session.c:297: undefined reference to `xmpp_stanza_get_child_by_name_and_ns'
>
>`xmpp_stanza_get_child_by_name_and_ns()` was added in libstrophe 0.10. The version of libstrophe that you are using is older than that and doesn't have this function. That's why you get the error.
>
>If you build libstrophe manually (the newest version) then you also need to tell Profanity to use that version and not the one installed on your distribution.
>
***@***.*** did this recently I think, maybe he can give you instructions in case you don't know how to do that.

**Comment by jubalh** [comment]
Since on your other bug there was some progress I think this one is solved as well.
