### ISSUE TITLE
building error xmpp_tlscert_get_string

### ISSUE THREAD

**Issue by fluxion-t** [profanity-im/profanity#1754]
## Expected Behavior

In Debian 11.4, after building latest libstrophe from git, pulling latest profanity from git (with all required dependencies satisfied), with a clean ./configure, I expected 'make' to compile without issues. 

## Current Behavior

Instead, I got the following messages:
`undefined reference to `xmpp_tlscert_get_string'`
and other subsequent 'undefined reference' error messages. 

## Steps to Reproduce (for bugs)

1. Debian 11.4
2. Latest libstrophe compiled without issues.
3. All dependencies as suggested from docs installed
4. Latest profanity cloned from git
5. successful ./bootstrap
6. successful ./configure (exit code 0)
7. make

## Context

I would like to build profanity but I could not. Repository versions are too old.
## Environment
* Give us the version and build information output generated by `profanity -v`
 Since I could not build, I can't write this command. I suppose it is 0.13.0
* If you could not yet build profanity, mention the revision you try to build from
0.13.0-4-g496eb6ce
* Operating System/Distribution
Debian 11.4
* glib version
ldd (Debian GLIBC 2.31-13+deb11u3) 2.31

Thanks!

**Comment by jubalh** [comment]
Do you have libstrophe installed from your package manager?
My guess is that you are building against that one instead of the git one that you pulled.

BTW AFAIK Debian has a backports repo. But I'm not sure for which versions and if it's already ready. Maybe @mdosch knows more about this.

**Comment by fluxion-t** [comment]
Indeed, I had libstrophe installed from package manager (unknowingly). Purging it solved the issue. 

Debian backports offers 0.12.1-1 but I really wanted to try the latest.

Many thanks!
