### ISSUE TITLE
Opening a URL or avatar freezes Profanity for as long as the opened executable is currently running

### ISSUE THREAD

**Issue by techmetx11** [profanity-im/profanity#1759]
## Expected Behavior

Being able to use profanity while the opened executable is running

## Current Behavior

Profanity freezes until I kill the opened executable

## Possible Solution

Replace `g_spawn_sync` with `g_spawn_async` in `call_external`

## Steps to Reproduce (for bugs)

1. Have `/url open` set to open a browser, for example like Firefox or Chromium
2. Close any existing browsers
3. Open a URL in profanity using `/url open`

## Context

This is noticable, if for example, `/url open` opens a new browser

## Environment
* Artix Linux (OpenRC)
* glib:  2.72.3
```
Profanity, version 0.13.0dev.feature/1158-vcard.2e84acce
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.18.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.7)
GTK icons/clipboard: Enabled
GDK Pixbuf: Enabled
```

**Comment by jubalh** [comment]
Doesn't happen to me and neither to @mdosch. Which executable did you set? So I can test with that one.

**Comment by jubalh** [comment]
> Replace g_spawn_sync with g_spawn_async in call_external

But sounds like this would make sense anyways. Will you open a PR for this?

**Comment by techmetx11** [comment]
> Doesn't happen to me and neither to @mdosch. Which executable did you set? So I can test with that one.

`firefox`, but make sure that Firefox isn't running already, or else it will just open a new tab and quit

> > Replace g_spawn_sync with g_spawn_async in call_external
> 
> But sounds like this would make sense anyways. Will you open a PR for this?

Sure

**Comment by jubalh** [comment]
So to clarify: if people use `xdg-open` everything works fine. If they call their browser directly (ie via setting `/executable urlopen set "chromium %u"`) we get this behaviour.

**Comment by techmetx11** [comment]
> So to clarify: if people use `xdg-open` everything works fine. If they call their browser directly (ie via setting `/executable urlopen set "chromium %u"`) we get this behaviour.

`xdg-open` or whatever browser don't fork into the background when there's no browser currently open
