### ISSUE TITLE
Profanity hangs, and segfaults when attempting to find mentions in an extremely long message

### ISSUE THREAD

**Issue by techmetx11** [profanity-im/profanity#1761]
## Expected Behavior

Profanity continues as normal

## Current Behavior

Profanity hangs without drawing the message, and soon after, crashes

## Possible Solution

Implement a size limit in the `get_mentions` function

## Steps to Reproduce (for bugs)

1. Send an extremely long message to someone using Profanity

## Environment
* Operating System: Artix Linux (OpenRC)
* glib: 2.72.3
```
Profanity, version 0.13.0dev.feature/1158-vcard.d259b9fe
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.18.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.7)
GTK icons/clipboard: Enabled
GDK Pixbuf: Enabled
```

**Comment by jubalh** [comment]
I'll need to test this. Feel free to open a PR if you want to.

> Implement a size limit in the get_mentions function

If we do that, we should make it configurable by the user.

**Comment by jubalh** [comment]
@techmetx11 are you in the mood to tackle this one?
