### ISSUE TITLE
OTR's policy is harrasing MAM

### ISSUE THREAD

**Issue by tran-h-trung** [profanity-im/profanity#1775]
# MAM is enabled but messages are missing.

When you are supporting 3 methods of encryption and a ton of options for
configurations, bugs naturally get mixxed up with each other.

This is a very confusing issue to track down. Because the problem was not
with MAM but with the configuration: `otr.policy=opportunistic`.

This issue was caught by mere accident.

We had to designed a test and did a bit of investigation.

## Environment

Build Version: 
»    aa9b96e25cf19c8e5dab3167e8e575916106297b

Test were conducted between 2 client machines.

Software       |           Version          
-----------------|--------------------------
Profanity      |  0.13.1dev.aa9b96e2
Conversations  |  2.10.10+free           

Prosǒdy was the server.

## The Test:

    00. Open Profanity and run: `/carbons on` and `/mam on`.
    01. user.1@domain.org log into Profanity.
    02. user.2@domain.org log into Conversations.
    03. user.1@domain.org send to user.2@domain.org.
    04. user.2@domain.org reply to user.1@domain.org.
    05. user.2@domain.org log out Conversations.
    06. user.1@domain.org log out of Profanity.
    07. user.2@domain.org log into Profanity.
    08. user.2@domain.org runs: `/msg user.1@domain.org`.
    09. user.2@domain.org runs: [PageUp] to request for MAM from server.

All exchanged messages were UNENCRYPTED.

## Expected Behavior

Receive and read all messages that were exchanged between both Profanity
and Conversations when `user.2@` log in to Profanity (07.) and open the chat
window with `user.1@` at (08.).

## Current Behavior

At (08.) `/msg user.1@domain.org` returns ONLY messages that were sent
from Conversations. 

Profanity did flash "Loading old messages…" but messages that were sent
previously from `user.1@` on Profanity (03.) are NOT displayed even though 
`[PageUp]` were pressed multiple time (09.).

## Investigation

After sharing this issue in our MUC, atomicwatch pointed out from my
Profanity's log that ‘the server did not send back the messages that Profanity
had sent’ at (03.). 

I first suspected a mis-configuration on the server. However, I found that
server configurations were correct but it did not save the messages from
Profanity as mentioned.

I then did the test again with the `/xmlconsole` and finds that `user.1@` on
Profanity were consistantly sending:
```
xx:xx:xx - SENT:
xx:xx:xx - <message id="[some-long-ass-hash]"
                    to="user.2@domain.org"
                    type="chat">
               <body>ping 10</body>
               <private xmlns="urn:xmpp:carbons:2"/>
               <no-copy xmlns="urn:xmpp:hints"/>
               <no-store xmlns="urn:xmpp:hints"/>
               <request xmlns="urn:xmpp:receipts"/>
           </message>
```

Digging through the source code, I found that `<no-copy>` and `<no-store>` are
sent when OTR is enabled as @mdosch also pointed out in [XEP-0334](https://xmpp.org/extensions/xep-0334.html).
These tags are triggered only in
`stanza_attach_hints_no_copy()` and `stanza_attach_hints_no_store()`.

So I went to look at `user.1@` configuration and found that in
`$HOME/.local/share/profanity/accounts`, under config for `user.1@`, there is
this entry: `otr.policy=opportunistic`.

I deleted this line and re-run the test and the `/xmlconsole` no longer produce
those `<no-copy>` and `<no-store>` tags along with the messages. 

Thus, MAM was working as expected. (Thanks to atomicwatch!)

## Steps to Reproduce (for bugs)

Instead of using Conversations, I ran the test again with Cheogram and had the
same result. Here is how to reproduce:

0. Have 2 accounts on a same domain (`user.1@` and `user.2@`).
1. Put `otr.policy=opportunity` under account config of `user.1@` of targeted Profanity.
2. Exchange messages with `user.2@`.
3. `user.2@` log out of one client and then back into another.
   (different database is the minimum requirement.)
4. Open chat and see that `user.2@` is missing messages from `user.1@`.

All clients and server must support MAM (obviously).

I have not test with other OTR policies but I do suspect they will cause
similar issue.

## Possible Solution

Avoid using OTR. (short term)

OR

Fix parsing|triggering policy of OTR. (long term)

**Comment by jubalh** [comment]
Based on the conversation in the MUC: it is quite likely that everything is working as it should.
For this reason I would like to ask you to start with a fresh setup of Profanity again, and see what's happening. Does the problem really exist?

Did you ever enable/play around with OTR at all? Who put the setting to `opportunity`? Did you enable OTR for this chat?

Your investigation sure was good. You assumed the MAM feature was broken, and then found out it wasn't. You realized MAM works as expected and the no-store was there. The question still is: did *you* create the mess up? The problem is that in the conversation in the MUC it became apparent that sometimes you left out some things that you did, didn't mention them. And other times presented assumptions as facts. And that you edit the config file by hand (where we recommend to use commands only). Etc.

So before diving into this I would like to be certain that you get the same behaviour when you start with a fresh setup.
Best in a new /home. Create two accounts. Test your thing. Does it work? Probably yes. Now lets try to enable OTR -> does everything work as expected? If yes, then good. Disable OTR, does still everything work as it should?

**Comment by tran-h-trung** [comment]
Me, myself, and I did created this big fat ugly pile of a mess, yes!

This was "accidental" as stated above. 

`user.1@` was used to test OTR prior to this test and I forgot to disable it. I didn't realized this fact before started testing so I could not have mentioned it in our MUC. Without this mistake, it is very likely that I would *not* had caught this bug in the first place.

Before reporting this bug, I *did* reproduce this issue quite a n° of time with a n° of accounts as mentioned above. 

( After testing the above, I even try the test using only 1 machine with the same Profanity build and just use different databases. This was done to eliminate suspicion with database and narrow down this particular issue *only* exists with `otr.policy=opportunistic`. 

This is NOT official and highly NOT recommended ! Use the bloody command in the software ! Don't freakin blame me for your mess if you do stupid shit like this ! )

Anyhow, I *did* find MAM was working as it should when `otr.policy=opportunistic` was no where to be found.

**Comment by jubalh** [comment]
> user.1@ was used to test OTR prior to this test and I forgot to disable it. 

That's great. Then everything is working as expected.
