### ISSUE TITLE
Doesn't launch after the latest Termux packages update

### ISSUE THREAD

**Issue by spertulo97** [profanity-im/profanity#1778]
After the latest Termux packages update, Profanity stopped launching. It shows "CANNOT LINK EXECUTABLE "profanity": library libpython3.10.so.1.0 not found: needed by main executable" error. Termux has already switched to Python 3.11

## Expected Behavior
To simply start

## Possible Solution
Maybe just switch Profanity to Python 3.11?

## Steps to Reproduce (for bugs)
1. Just launch Profanity
2.
3.
4.

## Context
Because of all this, Profanity just can't be used on Android.

## Environment
OS: Android 12, Termux version 0.118.0 (GitHub release) (the same bug is also on Android 8.0 with an F-Droid release of 
![Screenshot_20221104-205143_Termux](https://user-images.githubusercontent.com/117475512/200045310-93ad9e6b-4e58-4109-bccd-2aa0aa544120.jpg)
Termux 0.119.0)
Devices: Samsung Galaxy S20 FE G780G and Samsung Galaxy A8 (2018) A530F

**Comment by jubalh** [comment]
@fantomfp already mentioned a problem with building for Python 3.11 in https://github.com/profanity-im/profanity/issues/1634.
And for Profanity 0.13.1 we received PR https://github.com/profanity-im/profanity/pull/1756 which fixes the build with Python 3.11.

My assumption is that both @fantomfp and @sgn actually also tried to run it with Python 3.11?

> CANNOT LINK EXECUTABLE "profanity": library libpython3.10.so.1.0 not found: needed by main executable

And that doesn't look like it is build/linked to 3.11 but 3.10.

**Comment by spertulo97** [comment]
Python 3.10 was deleted from Termux after the last packages update.

**Comment by fantomfp** [comment]
> Python 3.10 was deleted from Termux after the last packages update.

This is why profanity's binary is now broken.

The fix for this issue is to rebuild profanity's binary. Linking to python 3.11 will be done automatically (if support is enabled at the packaging level).

**Comment by jubalh** [comment]
> Python 3.10 was deleted from Termux after the last packages update.

Then you need to open a bug for the Termux folks, nothing we can do about it here ;)
That's why some distros rebuild all packages upon a change in a dependency package :)

**Comment by spertulo97** [comment]
I don't think I should. Everything in my Termux works fine, except Profanity.

**Comment by jubalh** [comment]
Did you read what we wrote? Specifically:

> The fix for this issue is to rebuild profanity's binary. Linking to python 3.11 will be done automatically (if support is enabled at the packaging level).

**Comment by jubalh** [comment]
@neo-oli can you help here?

**Comment by sgn** [comment]
@spertulo97  I created a bug report in correct place https://github.com/termux/termux-packages/issues/12920 for you.
This is a downstream issue. Nothing can be done in profanity upstream.

**Comment by sgn** [comment]
To be honest, all bug reports should go to downstream (distribution) first, their developers will analyze and see if it's their bugs.
If it's really upstream bug, they will report to upstream and/or ask the users to report to upstream, you shouldn't come to upstream directly.

**Comment by sgn** [comment]
@spertulo97 Downstream has rebuilt profanity.

**Comment by jubalh** [comment]
@spertulo97 please listen the next time and don't let others do the work for you.

**Comment by spertulo97** [comment]
Thanks a lot to all of you!
And sorry for disappointing you.
