### ISSUE TITLE
Profanity stops working after some time

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [profanity-im/profanity#1779]
Left profanity running for about an hour and when i got back to it, it wouldn't receive new messages and commands wouldn't work. I think I was able to make commands work by pressing Ctr-c a bunch of times (not sure if that's what made it work), but still doesn't get new messages. Opening xmlconsole and pinging the server only shows sent stanzas in xmlconsole, nothing is getting received.
A possible cause would be my laptop going to sleep but I'm not sure.

## Expected Behavior
Profanity should work normally indefinitely

## Current Behavior
Stops working at some point

## Possible Solution
Possible reason: my laptop going to sleep.

## Steps to Reproduce (for bugs)
1. Open profanity
2. Wait
3. Should stop working

## Context
Can't get or send new messages

## Environment
* Lates master of profanity, though I'm pretty sure I had this issue since I first started using it on version 0.10
* Arch linux
* glib version: I think 2.74.1-1

**Comment by MarcoPolo-PasTonMolo** [comment]
16 minutes later profanity decided that it lost connection then re-established the connection and now everything is ok

**Comment by jubalh** [comment]
I have Profanity running for weeks/months and it works.
Not going to sleep though.

I'm quite certain that it just doesn't realize that the connection is lost. So you need to set the ping/timeout settings properly.

Then it will realize this sooner and try to reestablish the connection.
I'm closing this, feel free to reopen if it doesn't help.
