### ISSUE TITLE
Python Not Found for Python Plugins

### ISSUE THREAD

**Issue by fictitiousexistence** [profanity-im/profanity#1793]
## Expected Behavior

./configure --enable-python-plugins , completes without error 
## Current Behavior

checking for python... no
checking for python... no
configure: error: Python not found, cannot enable Python plugins
## Steps to Reproduce (for bugs)

1.Git clone master 
2../bootstrap.sh
3. `./configure 
      --prefix=/usr
      --disable-icons-and-clipboard
      --without-xscreensaver
      --enable-notifications
      --enable-python-plugins
      --enable-c-plugins
      --enable-plugins
      --enable-otr
      --enable-omemo
      --enable-pgp`

## Context

Unable to build Profanity with Python Plugin support
## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
Github master or 0.13.1
* Operating System/Distribution
Gentoo with Python 3.11.1
* glib version
glib-2.74.5

**Comment by jubalh** [comment]
So any idea why you get `checking for python... no` ? On our openSUSE CI we have `python310-devel` installed, and that seems to work.

**Comment by fantomfp** [comment]
Please provide infos about: how you installed python and how you installed development files of Python library, on your system.

**Comment by fictitiousexistence** [comment]
@fantomfp 

On gentoo its just emerge --ask dev-lang/python

There appears to be no seperate development package but rather the headers are installed with the main python package like arch. 

Python.h is at  /usr/include/python3.11/Python.h along with the others.

**Comment by fictitiousexistence** [comment]
Found I had to link /usr/lib64/pkgconfig/python-3.11-embed.pc to /usr/lib64/pkgconfig/python3-embed.pc


Arch linux creates that symlink automatically so I suppose its a gentoo bug. 

Thanks.
