### ISSUE TITLE
Download progress does not update when saving the same file twice

### ISSUE THREAD

**Issue by IsaacM88** [profanity-im/profanity#1794]
## Expected Behavior

When using "/url save" to download the same file twice within the same window, download progress should appear for both downloads.

## Current Behavior

When using "/url save" to download the same file twice within the same window, download progress appears for the first download, but subsequent downloads print progress to the first download. Subsequent downloads show 0% progress even when downloading is complete. See the attached image.

![GitHubIssue](https://user-images.githubusercontent.com/45052253/223593880-832270cc-e68b-4e3c-93e1-5f4afb87afca.png)

## Possible Solution

Assign a unique ID to each download. I have a pull request on the way.

## Steps to Reproduce (for bugs)

1. Use "/url save" to download a file.
2. Use "/url save" to download the same file again.

## Context

Sometimes I download the same file twice for reasons unknown to me.

## Environment
* Give us the version and build information output generated by `profanity -v`

Profanity, version 0.13.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.17.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.11.2)
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled

* If you could not yet build profanity, mention the revision you try to build from

Able to build from source.

* Operating System/Distribution

Fedora 37 Workstation.

* glib version

$ sudo dnf list --installed glib*
glib-networking.x86_64, 2.74.0-1.fc37
glib2.x86_64, 2.74.6-1.fc37
glib2-devel.x86_64, 2.74.6-1.fc37
glibc.x86_64, 2.36-9.fc37
glibc-all-langpacks.x86_64, 2.36-9.fc37
glibc-common.x86_64, 2.36-9.fc37
glibc-devel.x86_64, 2.36-9.fc37
glibc-gconv-extra.x86_64, 2.36-9.fc37
glibc-headers-x86.noarch, 2.36-9.fc37
glibc-langpack-en.x86_64, 2.36-9.fc37
glibmm2.4.x86_64, 2.66.5-2.fc37

**Comment by jubalh** [comment]
That's a good catch!
Thanks for investigating this and providing a PR!

**Comment by jubalh** [comment]
Thanks for your contribution!
