### ISSUE TITLE
`libsignal-protocol-c` project is archived

### ISSUE THREAD

**Issue by chenrui333** [profanity-im/profanity#1798]
👋 just a note that `libsignal-protocol-c` project is archived now, maybe switch off to use that as dependency?

relates to https://github.com/Homebrew/homebrew-core/pull/125554

**Comment by jubalh** [comment]
That's no problem. We will use https://github.com/dino/libomemo-c in the future anyways.
Already prepared this by packaging it for openSUSE:  https://build.opensuse.org/package/show/network:messaging:xmpp/libomemo-c

**Comment by jubalh** [comment]
See https://github.com/profanity-im/profanity/issues/1070#issuecomment-1401489326 for more info.
