### ISSUE TITLE
Discussion about executables being open inside the TTY

### ISSUE THREAD

**Issue by alexandre1985** [profanity-im/profanity#1805]
I am opening this issue to create a discussion about making executables opening inside the TTY (instead of opening inside a graphical environment). For example, using the image viewer `fbi` and the video player `mpv` (mpv also works inside a TTY) and the internet browser `w3m` (for opening HTML URLs). I have made a shell script that does this and have put that shell script in each `/executable`.

My Profanity C code modification is working. It is not complete, therefore I want to know what you think is the best direction for this feature being implemented in Profanity.

As for the executables programs of TTY, they have to be set with `/executable` (like it is being done now). No doubt in my mind about this.

But when an executable is being called, in Profanity, it is called asynchronously. This only does work, and makes sense, inside a graphical environment. For an executable to be called inside TTY, for example, to open a TTY image, the call has to be synchronous (in order to see the image). For a video in a URL, also has to be synchronous. As a generalization, and since I only use Profanity inside the TTY, I have made all calls of executables synchronous.

Now what I am thinking is making a setting that says if you want the call of executables to be inside a TTY (synchronous), or to be inside a graphical environment (asynchronous, like it is now). And the call to the executables would be set as synchronous or asynchronous.

Three questions:
 1. What should be the default value of this setting? (I believe I will make it asynchronous by default - the way that it is now. No breaking changes.)
 2. Should this command setting be it's own command (such as `/tty <on|off>`) or should this setting be configured inside `/executable` (such as `/executable tty set <on|off>`)?
 3. What is the best name for this setting? (I am thinking of `tty`, like how it is on the second question)

Cheers

**Comment by jubalh** [comment]
I need to think more about it. 
But so far:

> What should be the default value of this setting? (I believe I will make it asynchronous by default - the way that it is now. No breaking changes.)

Yes the way it is now.

> Should this command setting be it's own command (such as /tty <on|off>) or should this setting be configured inside /executable (such as /executable tty set <on|off>)?

I would say it should be in /executable

> What is the best name for this setting? (I am thinking of tty, like how it is on the second question)

I would name it `async` or something like that. And in the command description describe the behaviour and the purpose regarding tty.

**Comment by jubalh** [comment]
Another thing is that I think there can be timeout issues if the executable is running too long. But I guess go for it. The same should be true for the editor if I'm not mistaken. As long as you don't run the exec too long probably will be fine.

**Comment by jubalh** [comment]
Also see https://github.com/profanity-im/profanity/issues/1759

**Comment by sjaeckel** [comment]
Yeah, let's just try it out.

> Another thing is that I think there can be timeout issues if the executable is running too long. But I guess go for it. The same should be true for the editor if I'm not mistaken. As long as you don't run the exec too long probably will be fine.

I think that this will be the biggest problem for users, and I also don't see yet how to solve this.

**Comment by alexandre1985** [comment]
> > Another thing is that I think there can be timeout issues if the executable is running too long. But I guess go for it. The same should be true for the editor if I'm not mistaken. As long as you don't run the exec too long probably will be fine.
> 
> I think that this will be the biggest problem for users, and I also don't see yet how to solve this.

Yes, there are timeout issues. This is a bit inconvenient when using the browser to view some HTML URL.
I have mostly mitigated this by doing `/reconnect 5` (instead of `30`).

Is there a function for a keep-alive connection? Maybe with signals this can be done (I am not that good at system C programming).

**Comment by alexandre1985** [comment]
I will have to redo my code about this feature, because I was using fork and exec (took code from `/editor`), and reading https://github.com/profanity-im/profanity/issues/1759 made me see that probably is best to use the `g_spawn_sync` function (like it was before this feature being async).

But this time, the user will be able to configure either sync or async behaviour of the whole executables.

**Comment by alexandre1985** [comment]
one C programming question:

when a C program has a `execvp()` call to a text editor and the next line of code is for example a `printf()`, does the execution stop at `execvp()` until the text editor is closed? Or does the C program opens the editor and then continues with the `printf()` while the editor is still opened?

Because if C programs stops at the `execvp()` while the text editor is opened, for the connection issues of profanity, there could be a `fork()` and then a `g_spawn_*` on one process, while of the other process there could be an infinite loop of maintaining the connection alive. Then after the `execvp()`, there could be a line to kill the forked process, and afterwards return.
