### ISSUE TITLE
"Login failed" when connecting to secure port

### ISSUE THREAD

**Issue by shahab-vahedi** [profanity-im/profanity#1812]
I tried connecting to TLS port of `disroot.org` [1], but the connection is closed. `gajim` is able to connect with the same settings when I set its encryption to `DIRECT TLS`.

[1]
Prosody server

```
$ dig +short -t SRV _xmpps-client._tcp.disroot.org @208.67.220.220
  0 5 5223 disroot.org

profanity> /account show disroot
           Account disroot:
           enabled           : TRUE
           jid               : user@disroot.org
           resource          : profanity.12345
           server            : disroot.org
           port              : 5223
           muc nick          : resu
           TLS policy        : force
           Auth policy       : default
           Last presence     : online
           Login presence    : online
           Priority          : chat:0, online:0, away:0, xa:0, dnd:0

DBG: Input received: /connect disroot
INF: Connecting using account: disroot
INF: Connecting as user@disroot.org/profanity.12345
DBG: Connecting with flags (0x2):
DBG:   XMPP_CONN_FLAG_MANDATORY_TLS
DBG: Connecting via altdomain.
DBG: sock_connect() to disroot.org:5223 returned 15
DBG: Attempting to connect to disroot.org
DBG: connection successful
DBG: SENT: <?xml version="1.0"?><stream:stream to="disroot.org" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
DBG: Socket closed by remote host.
DBG: Closing socket.
DBG: Connection handler: XMPP_CONN_DISCONNECT
DBG: Connection handler: Login failed
DBG: Connection handler: No reconnect timer
INF: Login failed

$ profanity -v
  Profanity, version 0.13.1
  ...

  Build information:
  XMPP library: libstrophe
  Desktop notification support: Enabled
  OTR support: Enabled (libotr 4.1.1)
  PGP support: Enabled (libgpgme 1.18.0)
  OMEMO support: Enabled
  C plugins: Enabled
  Python plugins: Enabled (3.11.2)
  GTK icons/clipboard: Enabled
  GDK Pixbuf: Enabled
```

**Comment by shahab-vahedi** [comment]
I tried against another XMPP server which is a bit more verbose, and I got this error in the log:

```
prof: DBG: Input received: /connect another
prof: INF: Connecting using account: another
prof: INF: Connecting as alice@another.org/profanity.abcd
prof: DBG: Connecting with flags (0x2):
prof: DBG:   XMPP_CONN_FLAG_MANDATORY_TLS
xmpp: DBG: Connecting via altdomain.
xmpp: DBG: sock_connect() to another.org:5223 returned 9
xmpp: DBG: Attempting to connect to another.org
xmpp: DBG: connection successful
conn: DBG: SENT: <?xml version="1.0"?><stream:stream to="another.org" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
xmpp: DBG: parse error [^U^C^A]
conn: DBG: SENT: <stream:error><invalid-xml xmlns="urn:ietf:params:xml:ns:xmpp-streams"/><text xmlns="urn:ietf:params:xml:ns:xmpp-streams">parse error</text></stream:error>
xmpp: DBG: Socket closed by remote host.
xmpp: DBG: Closing socket.
prof: DBG: Connection handler: XMPP_CONN_DISCONNECT
prof: DBG: Connection handler: Login failed
prof: DBG: Connection handler: No reconnect timer
prof: INF: Login failed
prof: DBG: Input received: /quit
prof: INF: Profanity is shutting down...
```

**Comment by fantomfp** [comment]
@shahab-vahedi what is the version of the openssl lib? which distro?

**Comment by sjaeckel** [comment]
Port 5223 is for "legacy" TLS-only connections. "Modern" XMPP connects to port 5222 and uses `starttls`.

You have to set the `tls legacy` flag for such a connection/account.

**Comment by shahab-vahedi** [comment]
> @shahab-vahedi what is the version of the openssl lib? which distro?

OpenSSL (libssl) 1.1.1t1
Void Linux

**Comment by shahab-vahedi** [comment]
> Port 5223 is for "legacy" TLS-only connections. "Modern" XMPP connects to port 5222 and uses `starttls`.
> 
> You have to set the `tls legacy` flag for such a connection/account.

Thanks @sjaeckel ! `/account set <account_name> tls legacy` does solve the problem. I am confused though. Does the port number affect the negotiation from the server side? What if a server wants to have `starttls` connection on a custom port?

**Comment by sjaeckel** [comment]
> * `STARTTLS` is really what its name suggests to be? "start TLS" after connected through a plain channel?

yes

> * Therefore, `STARTTLS` is supposed to be always on (default) plain port?

no, you can also run on a different port, but it must start as a plain xmpp connection

> * What if there is a server that only provides TLS connections (no plain channel) through a custom port?

You should still be able to set the port manually and the `tls legacy` flag. That shouldn't be a problem.

> I think this won't affect the ciphers or algorithms. It's just a different sort of negotiation/handshake. Please correct me if I am wrong. I'm just a bit spooked by the term "legacy".

At one point it was decided that `starttls` is the 'modern' way to go ... The TLS negotiation happening in the two different ways is exactly the same.
