### ISSUE TITLE
Page occupants or roster up/down not working

### ISSUE THREAD

**Issue by alexandre1985** [profanity-im/profanity#1818]
In profanity inside a TTY, I want to pageup and pagedown occupants in a muc, and ALT+PAGEUP or ALT+PAGEDOWN is not working.

## Expected Behavior

PageUp and PageDown the occupants in a MUC.

## Current Behavior

Does nothing.

## Steps to Reproduce (for bugs)

1. Go to a TTY and open Profanity
2. Go to a MUC window
3. Press ALT+PageDown / ALT+PageUp

## Context

I am trying to view all ocupants in a MUC (I know that `/who` also does this). Because in the man page it says that Alt+PageDown does scroll the MUC occupants list.

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version
Artix Linux (updated)
glib version: 2.76.1
profanity version: 0.13.1

**Comment by jubalh** [comment]
AFAIK there was a lengthy discussion about this on the MUC and in the end it got solved. I didn't follow it closely however.
In any case this user has been abusive and thus the ticket will be closed.
