### ISSUE TITLE
`gchar*` vs. `char*`

### ISSUE THREAD

**Issue by sjaeckel** [profanity-im/profanity#1819]
Currently there's a mixed usage of GLib and stdlib API's when dealing with strings. In general this also applies to other types, but I'm not aware of any other cases where type casts from GLib to stdlib happen or would matter.

There are some functions using GLib API's but treating the returned value as `char*`.

This will cause problems if the memory allocator of GLib is different than standard `malloc()`, which apparently can be the case if running on Windows 

[glib/gmem.c:39-52](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gmem.c#L39-L52)
```
#if defined(HAVE_MEMALIGN) || defined(HAVE__ALIGNED_MALLOC)
/* Required for _aligned_malloc() and _aligned_free() on Windows */
#include <malloc.h>
#endif

#ifdef HAVE__ALIGNED_MALLOC
/* _aligned_malloc() takes parameters of aligned_malloc() in reverse order */
# define aligned_alloc(alignment, size) _aligned_malloc (size, alignment)

/* _aligned_malloc()'ed memory must be freed by _align_free() on MSVC */
# define aligned_free(x) _aligned_free (x)
#else
# define aligned_free(x) free (x)
#endif
```

This is a huge task, as it involves touching most of the profanity code base, so it will have to be done over a longer stretch of time.

Another option to tackle this, could also be to define a rule, that we'll never make profanity build on platforms which don't use `malloc()` in the GLib memory allocator ;)

**Comment by H3rnand3zzz** [comment]
Can you, please, provide details on correct usage with examples? Theoretically, we can catch all the mistakes made even with regex and fix it.

And I think that we should add these details into documentation since "auto_char" is something unique, as far as my knowledge goes.

**Comment by H3rnand3zzz** [comment]
`[^g]char\s?\*.+\sg_`
150+ occurrences

**Comment by sjaeckel** [comment]
> Can you, please, provide details on correct usage with examples? Theoretically, we can catch all the mistakes made even with regex and fix it.

That's a regex I'd like to see :grinning: 

What we have to do is: if we use a GLib API which returns newly allocated memory, make sure that this memory is later on free'd via `g_free()`.

One example module which just came to my mind and violates this in some places is `src/config/preferences.c`, e.g. here:

https://github.com/profanity-im/profanity/blob/5f078f95f2b0d77f1f94fbe69aaa0b6ae605b398/src/config/preferences.c#L904-L911

`g_key_file_get_string()` returns a `gchar*` which gets returned as a `char*`.

Remember: this is also not solved by using `auto_gchar` everywhere, since some of those strings have a "longer lifetime".

> And I think that we should add these details into documentation since "auto_char" is something unique, as far as my knowledge goes.

Indeed, this should be documented.

This `auto_[g]char` stuff is not really unique, but yes it's not very often used as most codebases claim to be "portable to other compilers". Since the `__attribute__((__cleanup__()))` functionality originates in GCC, there's only Clang which also supports it AFAIK.

I decided to introduce usage of it in this project, since it doesn't claim to be portable over compilers, and it makes code so much more readable and robust.

> Maybe we can even add tests for incorrect usage in CI pipeline.

That's also what I'd like, but I've no clue how to accomplish it. AFAIK there's no easy way to detect a typecast from `gchar*` to `char*`, but I'd love to be proven wrong. We could probably start by fixing the types used and then hopefully [-Wmismatched-dealloc](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmismatched-dealloc) helps us further down the line!?

**Comment by H3rnand3zzz** [comment]
> > `[^g]char\s?\*.+\sg_`
> > 150+ occurrences
> 
> not including the cases where `char* foo() { return g_something(); }` happens

Even if it covers 30% of misuses, it's already good result for 1-2 minutes of typing. It's somewhat easy to use and integrate in test system. Other cases can be covered by different techniques as well.

Of course there might be a lot of edge cases, such as:
```
char* s;
...
s = g_func();
```
and other, but if we cover 80% of cases automatically with 20% of the effort, it can save a lot of time on code review.

Btw, `gchar\s?\*.+\sg_` shows just a bit more results, which tells us how widespread the problem is. About 40-50% of usages are incorrect.

**Comment by H3rnand3zzz** [comment]
Solved?

**Comment by jubalh** [comment]
I would say so :)
