### ISSUE TITLE
Allow manual multiline messages

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#182]
Allow users to send multiline messages, using ctrl-enter or some keyboard combination for the new lines.

Up/down arrow should behave accordingly and move through the message rather than previous commands.

**Comment by moorchegue** [comment]
:+1:

**Comment by yumitsu** [comment]
Any progress on this?

**Comment by mdosch** [comment]
I stumbled upon this [Ncurses Multi-Line Text Editor](http://www.melvilletheatre.com/articles/cstuff/4.html) and not being a programmer I don't know if this could be reused for profanity. 
Although it might be a problem that there is not mentioned a license but maybe this is somehow comparable to MIT:

>Redistribution and use in source and binary forms, with or without modification, are permitted
>provided that the following conditions are met:
>    * Redistributions of source code must retain the above copyright
>      notice, this list of conditions and the following disclaimer.
>    * Redistributions in binary form must reproduce the above copyright
>      notice, this list of conditions and the following disclaimer in the
>      documentation and/or other materials provided with the distribution.

**Comment by jubalh** [comment]
Thanks a lot for researching this!
I'll take a lot when I find time :-)

**Comment by jubalh** [comment]
mcabber does this via a `/multi` in the input field.

> I stumbled upon this Ncurses Multi-Line Text Editor

Is actually ncurses only, but we use readline to handle the line editing.

Maybe we can look at [rlwrap](https://github.com/hanslub42/rlwrap) for inspiration.

**Comment by michaelgreenburg** [comment]
I was able to work around this with a simple Python plugin (inspired by @boothj5's [syscmd.py](https://github.com/profanity-im/profanity-plugins/blob/0.5.1/stable/syscmd.py)) that allows one to use e.g. `/printf "here is a\nmessage with a couple lines"` to send multiline messages until there's native support:

```python
import prof
from subprocess import Popen, PIPE

def _cmd_printf(format):
    if not format:
        prof.cons_bad_cmd_usage("/printf")
        return
    try:
        cmd_string = '"' + format + '"'
        result = Popen("printf " + cmd_string, shell=True, stdout=PIPE).stdout.read()
        prof.send_line(result)
    except Exception as e:
        prof.cons_show("Internal error: " + repr(e))
    # TODO: real error handling

def prof_init(version, status, account_name, fulljid):
    synopsis = ["/printf <format-string>"]
    description = "Use your system's printf to send a formatted message"
    args = [["<format-string>", "the format string to print"]]
    examples = ["/printf \"this message will display\\non multiple lines\"", 
                "/printf \"my home directory is $HOME\"",
                "/printf \"here are the contents of my clipboard:\\n$(xclip -o)\""]
    prof.register_command("/printf", 1, 1, synopsis, description, args, examples, _cmd_printf)
    prof.filepath_completer_add("/printf")
```

It needs work and has only been tested on my system, but it's an easy way to send arbitrary multiline messages, with the added benefit of being able to incorporate the output of shell commands.

Feel free to modify/suggest changes, it's still kind of a rough draft.

**Comment by mdosch** [comment]
Also there is some workaround using Ctrl+V (^V) and Ctrl+J (^J):

* Write `This should be the first line.This should be the second.` 
* Place your cursor between `line` and `.`
* Press `^V` and afterwards `^J`
* Press Enter

**Comment by jubalh** [comment]
pasis found: https://github.com/ulfalizer/readline-and-ncurses
I should read that when trying to solve this issue.

**Comment by kaffeekanne** [comment]
An `/editor` command for extended message composing was introduced by #1521.

**Comment by jubalh** [comment]
As @kaffeekanne mentioned we have an `/editor` command now.
And for 0.12.0 https://github.com/profanity-im/profanity/pull/1645 (and https://github.com/profanity-im/profanity/pull/1648) was added.
The workflow seems to be quite nice now. Even more powerful than just regular multi line.
Let's close this issue.

**Comment by sjaeckel** [comment]
And there's a shortcut that spawns the editor, per default alt+c

**Comment by Ryuuusuke** [comment]
> Also there is some workaround using Ctrl+V (^V) and Ctrl+J (^J):
> 
>     * Write `This should be the first line.This should be the second.`
> 
>     * Place your cursor between `.` and second `This`
> 
>     * Press `^V` and afterwards `^J`
> 
>     * Press Enter

this one is cool. should be added to docs

**Comment by jubalh** [comment]
> this one is cool. should be added to docs

Feel free to open a PR for https://github.com/profanity-im/profanity-im.github.io/blob/master/faq.html or for this repo in the man pages.
