### ISSUE TITLE
Introduce new `/privacy` group of commands

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1836]
Idea started here: https://github.com/profanity-im/profanity/pull/1827#issuecomment-1509712722

I think we could use something like a new `/privacy` command.

Recently we received
* https://github.com/profanity-im/profanity/pull/1815 which let's users set their client identification (XEP-0092) name in `/account`.
* https://github.com/profanity-im/profanity/pull/1827 which let's users enable a notice when more devices sign in (`/session_alarm`)

I think we should group them together in something like `/privacy`.

And maybe also include other already existing commands in there:
* `/os`
* `/silence` ?
* ..?

I also think the accounts structure can get too bloated. And we should put some things in a different structure. The settings still can be individual per account. But leave the account structure for really account related settings (I hope you get what I mean).

And things like session alarm need to be off by default and configurable by the user.
So we also need to check that preference like mentioned in: https://github.com/profanity-im/profanity/pull/1827#discussion_r1168413011

**Comment by jubalh** [comment]
I think `/privacy` can also mention/forward to other commands to look at.
For example we could implement XEP-0441: Message Archive Management Preferences and add it to `/mam` and mention it in privacy. Similar like we do in `/color` where it prints:

```
Consistent color generation for nicks (/color)                     : OFF 
Consistent color generation in roster (/roster color)              : OFF 
Consistent color generation for occupants (/occupants color)       : OFF
```

**Comment by H3rnand3zzz** [comment]
Introduced in #1857, but since the design is yet to be completed, I did not introduce full set and limited it to logging, to keep things simple, especially since it's a new feature. I would suggest to add additional commands after logging integration. We can gradually introduce them or use full command reference to add all suitable commands at once.
