### ISSUE TITLE
Cover code in Doxygen-style comments

### ISSUE THREAD

**Issue by H3rnand3zzz** [profanity-im/profanity#1859]
## Expected Behavior

All code should be documented using Doxygen-style comments to provide clear and comprehensive documentation for the project.

## Current Behavior

Not all code is covered with Doxygen-style comments, which makes it challenging for developers to understand the purpose, behavior, and usage of different code elements. This lack of documentation hinders code comprehension, maintenance, and collaboration efforts.

## Possible Solution

Cover all code in the project with Doxygen-style comments. This involves adding appropriate comments to files, functions, variables, macros, and other relevant code elements. The comments should follow the Doxygen format and provide descriptions, parameter details, return value information, and any additional relevant documentation.

## Steps to Reproduce (for bugs)

N/A

## Context

The absence of comprehensive Doxygen-style documentation affects the developers' ability to understand and maintain the codebase effectively. It especially affects new devs. It hampers collaboration and slows down development efforts, as developers need to spend additional time deciphering code functionality and usage.

## Motivation
1. Communication: By documenting code using Doxygen-style comments, developers convey the purpose, behavior, and usage of code elements to their peers.
2. Code Understanding: Well-documented code is easier to comprehend, navigate, and maintain. Doxygen-style comments serve as a reference, providing insights into functionality, inputs, outputs, and potential side 
3. API Reference Generation: Doxygen generates API documentation (e.g., HTML or PDF) based on code comments, facilitating reference access for 
4. Collaboration: Consistent Doxygen-style documentation fosters collaboration among developers by ensuring a unified approach to documenting 
5. Onboarding: Comprehensive Doxygen-style documentation helps new developers quickly understand the codebase, reducing the learning curve and enabling effective contributions.

**Comment by jubalh** [comment]
Personally I'm not a big fan of this.
I find it quite unreadable and bloating. I think for libraries it makes sense but here I'm not sure.

Would need to find some convincing examples.

I'm all for regular comments though, to explain tricky and unclear parts. Point to important information etc.

How do others see it?

**Comment by sjaeckel** [comment]
I appreciate your push for this, but I'm with @jubalh here.

IMO Doxygen is overrated for application documentation. It's fine to describe library APIs but what would make more sense for profanity is a higher level view of the interaction of the different parts. Doxygen does this also kind of, but IME it's not really useful.

Drawing a kind of high level class diagram would be sufficient with a lot less effort required. And then again I'm not sure if even that is worth the effort since this needs to be maintained or it starts to rot.

**Comment by H3rnand3zzz** [comment]
I think that it might make sense to partially implement it, especially for some important and project-specific things, such as auto_gchar, auto_gcharv etc. We want to keep the code unified and, in my opinion, it's better to have commentary instead of pointing out old issues by their numbers or reexplaining the same things.

One of the most important applications is to show which functions have to be cleaned using free/g_free after and which ones manipulate input. It could save a lot of time, so instead of looking at implementation, glimpse of the docs shown through IDE can reveal what some function does internally, thus reducing chances of introducing new bugs.

**Comment by jubalh** [comment]
> especially for some important and project-specific things, such as auto_gchar, auto_gcharv etc

Not sure what you mean here. But I guess that could be done in a doc folder or in the CONTRIBUTING.md, right?

> One of the most important applications is to show which functions have to be cleaned using free/g_free after

Usually I check the function. I think that takes the same amount of time than reading the comment about it.
And I think in C we usually signify if the return needs to be freed or not by using const for the pointer.
