### ISSUE TITLE
SegFault on 0.13.1dev.master.6247c28e

### ISSUE THREAD

**Issue by tran-h-trung** [profanity-im/profanity#1860]
SegFault when launching 0.13.1dev.master.6247c28e

## Expected Behavior

Should just work.

## Current Behavior

Launching failed so:

0. I switch to 88d383b052cb7f6e8afcd15dc8043bb683f8a687
1. I build and launch successfully.
2. I then switch back to master, build and it launch successfully.

## Possible Solution

Don't know.

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version
Debian 12 amd64

**Comment by jubalh** [comment]
> I switch to https://github.com/profanity-im/profanity/commit/88d383b052cb7f6e8afcd15dc8043bb683f8a687
    I build and launch successfully.
    I then switch back to master, build and it launch successfully.

That is confusing :) It sounds like it always launches successfully :)

I'm running 6247c28e as well, without problems so far.

Are you familiar with gdb? It would be good to get a backtrace.
See this post by Martin: https://profanity-im.github.io/blog/post/how-to-get-a-backtrace/
