### ISSUE TITLE
Unable to enter PGP Key passphrase from Profanity

### ISSUE THREAD

**Issue by Macr0Nerd** [profanity-im/profanity#1861]
When associating a PGP Key with an account, upon trying to connect the user is prompted for the passphrase for the PGP key. This does not seem to work, and the user is unable to enter anything and is forced to wait for the prompts to time out.

## Expected Behavior
The user connects and the GPG passphrase prompt appears, and the user is able to input their key passphrase.

## Current Behavior
The user connects and the GPG passphrase prompt appears, but the user is unable to input their password to unlock the key.

## Possible Solution
I'm guessing that the prompt is output by an underlying function but isn't expected or handled by profanity, and as such input is not passed in between

## Steps to Reproduce (for bugs)
1. Associate a PGP key with an account
2. Attempt to connect to the account

## Context
Attempting to begin using XMPP and trying to set up a new account.

## Environment
```
Profanity, version 0.13.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.20.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.11.3)
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled
```

```
$ uname -a
Linux BackpackTARDIS 6.1.33-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Mon, 19 Jun 2023 07:36:10 +0000 x86_64 GNU/Linux
```

**Comment by H3rnand3zzz** [comment]
Do you use the latest build from master branch (6247c28e) or do you use the latest release version (https://github.com/profanity-im/profanity/releases/tag/0.13.1 3e7457f4)?

**Comment by jubalh** [comment]
> Do you use the latest build from master branch or do you use the latest release version

In the report he mentions that he uses 0.13.1 :)

@Macr0Nerd do you use Profanity on a headless system or on your desktop machine?
Do you have gpg agent running? pinentry-curses if you don't have X11 or Wayland?

**Comment by Macr0Nerd** [comment]
My apologies for the late response. I use the version packaged in the Arch repos ([`profanity 1:0.13.1-4`](https://archlinux.org/packages/extra/x86_64/profanity/)) on Wayland (sway). I do have pinentry-curses on my system but I'll double check which pinentry program I'm using once I'm back at a terminal.

**Comment by Macr0Nerd** [comment]
Changing my pinentry to `pinentry-curses` worked. I had `pinentry-tty` before. My mistake.

**Comment by jubalh** [comment]
> Would there be a way to help make pinentry-tty work better with profanity?

I don't know :) If you find out we are happy to take improvements.
Do other ncurses based programs work with pineentry-tty for you?
