### ISSUE TITLE
Issue with connection, password wrong char

### ISSUE THREAD

**Issue by HumanG33k** [profanity-im/profanity#1866]
One of my account refuse to connect but i can connect with for ie pidgin without an issue. 

for the record and without a full disclose current password contain for ie following special char : 

```
? ; = [ ' | 
```

Also my password is quite long (more than 20 char)
 

## Expected Behavior

I hope i can connect 

## Current Behavior
The connexion not occurs. 
 

## Possible Solution
Add a unit test with lot of special char

## Environment

profanity -v 
```
Profanity, version 0.13.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2022 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.18.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.11.2)
GTK icons/clipboard: Enabled
GDK Pixbuf: Enabled
```

*  OS: Debian GNU/Linux 12 (bookworm) x86_64
* glib version : libglib2.0-0/stable,now 2.74.6-2 amd64

**Comment by jubalh** [comment]
Feel free to reopen with more information or questions.

**Comment by HumanG33k** [comment]
Sry i m quite busy.

I investigate a little more and i just see /account list not list the current account i try to connect to. :\ I will investigate and make more test. my last one says (after adding my account) wrong jid or password.
