### ISSUE TITLE
My messages from a previous session are not persisted on reconnect

### ISSUE THREAD

**Issue by stevemolloy** [profanity-im/profanity#1873]
## Current Behavior
I suspect this is a misconfiguration of my profrc, but I'm not sure.  Hopefully someone here can advise.

Profanity works as expected during a single session, with my messages appearing as they should.  However when I disconnect and reconnect (for example when I leave work and reconnect from home), any messages that I have posted disappear from the chat.  Messages by everyone else in the room are still present.

I can confirm that my messages are all present when I connect with a different client (pidgin).

## Expected Behavior
I would expect profanity to show my messages, as well as those of others, after reconnecting.

## Steps to Reproduce (for bugs)
1.  Connect to the network
2.  Chat
3.  Close the profanity application and restart
4.  My messages are gone

## Environment
My profrc:
```
[ui]
splash=true
intype=true
beep=false
statuses.muc=all
theme=default
history=true
titlebar=true
mouse=false
flash=false
vercheck=false
statuses.console=all
statuses.chat=all
color.nick=true

[connection]
autoping=60
reconnect=5
account=blahblah@jabber.blah.blah

[chatstates]
enabled=true
outtype=false
gone=10

[notifications]
remind=60
invite=true
sub=true
message=true
room=false
message.current=true
room.current=true
typing=true
typing.current=false
message.text=true
room.text=true
room.offline=true

room.mention=true

[alias]
colour=/color
topic=/subject
friends=/who online friends
bob=/msg bob@server.org hey wassup?

[logging]
chlog=true
grlog=true
maxsize=1048580
rotate=true
shared=true

[otr]
warn=true
log=redact
policy=manual

[presence]
autoaway.mode=away
autoaway.check=true
autoaway.awaytime=15
autoaway.awaymessage=Away from computer
```

profanity -v
```
Profanity, version 0.14.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2023 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.21.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.11.3)
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled
```

**Comment by jubalh** [comment]
This feature is called MUC MAM and is not implemented yet. It is being worked on here: https://github.com/profanity-im/profanity/pull/1862
And possibly is finished in the next couple of weeks.

**Comment by stevemolloy** [comment]
Thanks for the fast reply.  Looking forward to the new feature :)

**Comment by jubalh** [comment]
I think we might do a fresh release right after this feature got merged. Since many people probably would appreciate to have it. And we originally planned to have it in 0.14.0 anyways.
