### ISSUE TITLE
Profanity fails to properly detect URLs wrapped in <>

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1877]
If an URL is wrapped in <>, e.g.:

```
Fürst Pückler bezeichnet: (<https://de.wikipedia.org/wiki/F%C3%BCrst_P%C3%BCckler>)
```

profanitys `/url open <tab>` will try expand to `/url open https://de.wikipedia.org/wiki/F%C3%BCrst_P%C3%BCckler>)`.

I think `<` and `>` should not be considered as part of an URL as they are unsafe characters that must be escaped:

> Characters can be unsafe for a number of reasons.  The space
> character is unsafe because significant spaces may disappear and
> insignificant spaces may be introduced when URLs are transcribed or
> typeset or subjected to the treatment of word-processing programs.
> The characters "<" and ">" are unsafe because they are used as the
> delimiters around URLs in free text; […]
https://datatracker.ietf.org/doc/html/rfc1738

## Expected Behavior

`/url open <tab>` with the previous example should expand to `/url open https://de.wikipedia.org/wiki/F%C3%BCrst_P%C3%BCckler`.

## Current Behavior

`/url open <tab>` expands to `/url open https://de.wikipedia.org/wiki/F%C3%BCrst_P%C3%BCckler>)`.

## Steps to Reproduce (for bugs)

1. See explanation at the beginning.

## Environment
* Debian Testing/Unstable

```
profanity --version
Profanity, version 0.14.0dev.master.492efc43
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2023 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Enabled (libgpgme 1.18.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled
```

**Comment by jubalh** [comment]
I tried parsing it with `g_uri_parse()` and then making a string out of it with `g_uri_to_string()` but that unfortunately does: `https://de.wikipedia.org/wiki/F%C3%BCrst_P%C3%BCckler>)` -> `https://de.wikipedia.org/wiki/Fürst_Pückler%3E)`. So it encodes it. Maybe there is no glib function and we need to ignore invalid chars on our own?
