### ISSUE TITLE
`/plugins install` without connected account crashes

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1880]
Reason is: https://github.com/profanity-im/profanity/commit/3a86b8c29
Created to fix: https://github.com/profanity-im/profanity/issues/1624

It wants to get the tls setting based on account but doesn't check whether account != NULL.

Options:
1) `/plugins install` should only work when we are connected and respect the tls setting according to account
2) it should take the tls setting from the default account and if none is set cancel
3) it should always validate the cert. Since it's actually an unrelated decision whether the user wants to validate the certificate of his xmpp server vs any web server where he wants to install his plugins from
4) a new setting

Personally I like 1 the most.

**Comment by jubalh** [comment]
@sjaeckel opinion? :)

**Comment by sjaeckel** [comment]
> @sjaeckel opinion? :)

c.f. https://github.com/profanity-im/profanity/pull/1882#pullrequestreview-1597717430 :)
