### ISSUE TITLE
Deprecated cmocka Functions

### ISSUE THREAD

**Issue by ike08** [profanity-im/profanity#1907]
Profanity is using deprecated cmocka functions described [here](https://api.cmocka.org/deprecated.html).  

What do you think about replacing them with current supported functions?

**Comment by jubalh** [comment]
> Profanity is using deprecated cmocka functions described [here](https://api.cmocka.org/deprecated.html).

I wasn't aware.

> What do you think about replacing them with current supported functions?

That sure would make sense.
