### ISSUE TITLE
older messages not loading.

### ISSUE THREAD

**Issue by ShroomiePerson** [profanity-im/profanity#1945]
i've enabled chat history/logging, and whenever i enter a chat i've started, it displays at the top that profanity is `Loading older messages...` but nothing ever loads.

## Expected Behavior

i expect my previous messages to show up after some time, but they never do.

## Steps to Reproduce (for bugs)
1. enable `/logging chat` or `/history`
2. send some messages
3.
4.

## Context

i just want to view my chat history as it's inconvenient to have to view it from a separate client.

## Environment
* Give us the version and build information output generated by `profanity -v`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution
* glib version

`profanity -v

Profanity, version 0.14.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2023 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.23.2)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons/clipboard: Disabled
GDK Pixbuf: Disabled`

i use a 2019 intel iMac running Mac OSX 14.2 and use the terminal emulator iTerm2. while i am better than the majority of the US population at working with Unix-like operating systems, i am still not extremely good at it, and i don't know what glib is.

**Comment by ShroomiePerson** [comment]
<img width="537" alt="ProfanExample" src="https://github.com/profanity-im/profanity/assets/129551111/5bd4c1e5-feb3-44ee-8d88-32eadf2dc763">
forgot to add a photo, sorry.

**Comment by jubalh** [comment]
Did you set `/mam on`?

Weird that it prints `Loading older messages...` without doing anything.
Even if MAM is off it should do something, we might have to investigate.

**Comment by ShroomiePerson** [comment]
`/mam` is on.

**Comment by ShroomiePerson** [comment]
update: according to the console-thing in tab one, my server doesn't support MAM. ig i'll bring this up with them then.

**Comment by jubalh** [comment]
> my server doesn't support MAM

So we have the fault why you dont see your old messages.
But still Profanity shouldn't just print `Loading older messages...` and that's it. It should 1) not try to load MAM (probably its doing that) 2) load from SQL DB what's there and then stop this action.

**Comment by sjaeckel** [comment]
I recently looked into this and the mechanism that determines whether MAM is supported, resp. whether this error message should be printed, is not correct. I'll create a write-up when I have the time, but for now we should treat MAM as "works if the stars align" a.k.a "incomplete". This error message can be ignored in most of the cases, especially when it's printed at profanity start-up time.

FTR: #1944 was also incomplete. The PR doesn't make the situation worse, but it also didn't improve it.

**Comment by sjaeckel** [comment]
As a work-around you can close that window and once the hot phase of the connection setup is finished you can re-open it again and then 1-on-1 MAM should work, if it's supported by the server.

**Comment by ShroomiePerson** [comment]
hey it's just a server issue, i moved somewhere else and everything's good now.
