### ISSUE TITLE
Mouse selection is not working properly

### ISSUE THREAD

**Issue by H3rnand3zzz** [profanity-im/profanity#1947]
Reported by another Profanity user.

## Expected Behavior
When user holds LMB (left mouse button) and drag mouse, text selected.

## Current Behavior
When user holds LMB and drags, selection is not happening.

## Possible Solution
It might be related to #1943.

## Steps to Reproduce (for bugs)
1. Hold LMB, drag it.
2. Text is not selected.

## Context
The problem is not reproducible by me and some other users, but the user that has a problem claims that the problem appeared after he updated Profanity 17.01.24

## Environment
Tilix, master branch of the profanity running in arch docker.

**Comment by jubalh** [comment]
I don't see how the mainloop can have any effect on this.
Most likely that user updated his terminal, ncurses, tmux, tinfo or anything else on the system.
Furthermore I cannot reproduce this issue with or without running in tmux.

**Comment by jubalh** [comment]
I still believe this is a user/system issue and not ours. Any feedback from the user?

**Comment by H3rnand3zzz** [comment]
> I still believe this is a user/system issue and not ours. Any feedback from the user?

The following experiment has been conducted: the user opened a second "window/session/tab" withing a same window with the profanity, the selection problem persisted on the profanity's side, but not on the other one. My conclusion is that the problem is somehow related to the new way that we process user input.

**Comment by jubalh** [comment]
> the user opened a second "window/session/tab" withing a same window with the profanity

window within same window?

Maybe interesting to try with: xterm, vte based (gnome-terminal for example) with and without tmux (if they are a temux user).

**Comment by H3rnand3zzz** [comment]
> > the user opened a second "window/session/tab" withing a same window with the profanity
> 
> window within same window?
> 
> Maybe interesting to try with: xterm, vte based (gnome-terminal for example) with and without tmux (if they are a temux user).

Tilix is similar to TMUX.
![image](https://github.com/profanity-im/profanity/assets/129467592/c7f6c74c-b303-4a41-8fdd-fcffc0e58f19)

**Comment by jubalh** [comment]
> Tilix is similar to TMUX.

Does it work without it?

**Comment by H3rnand3zzz** [comment]
> > Tilix is similar to TMUX.
> 
> Does it work without it?

For me problem with Tilix is not reproducible with the same OS. Though I asked whether it's reproducible for the user without the Tilix.

**Comment by jubalh** [comment]
Does this behaviour happen for the user in xterm, other vte based terminal or only with Tilix?
Does this happen only with latest master (containing gmainloop) or also before that, for example with 2ec94064ed341f0ea5b197a283c6ebfb15716bd0?

**Comment by H3rnand3zzz** [comment]
Change reverted, it fixed the issue
