### ISSUE TITLE
`/url save` and `/sendfile` do nothing after introducing Gmainloop

### ISSUE THREAD

**Issue by ike08** [profanity-im/profanity#1953]
`/url save` and `/sendfile` do nothing with and without OMEMO when running the latest development version.

Rolling back commits reveals the problem was introduced in commit 609fde099857d4d9b2bd8d421bdb0a5059a53dfc (https://github.com/profanity-im/profanity/pull/1943).

I noticed that `pthread_mutex_lock(&lock)` would hang in **src/tools/http_download.c:118**. I added `pthread_mutex_trylock(&lock)` before it to see what it would return. It returned 16, which means EBUSY; so the mutex is busy. I'm thinking that `/url save` does not execute fully because `pthread_mutex_lock(&lock)` is waiting to acquire a locked mutex.

## Environment
* Profanity, version 0.14.0dev.fix/1939.569e37f0
* Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.20.0)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.12.1)
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled
* Fedora 39 Workstation
* glibc 2.38-16.fc39

**Comment by H3rnand3zzz** [comment]
I think that a proper solution to this would be getting rid of the `inp_readline` function and not locking the mutex by default in `profanity.c:173`.

Though the challenge is to capture and return the input line without select/other stuff. We can implement it through a way of adding custom callbacks in `cmd_process_input`, but there might be other ways that I am failing to see.

**Comment by jubalh** [comment]
I believe now that we use gmainloop we shouldn't use pthreads anymore should we? There is GMainContext.

**Comment by H3rnand3zzz** [comment]
> I believe now that we use gmainloop we shouldn't use pthreads anymore should we? There is GMainContext etc

We don't have to use a new thread for each connection (in fact, it's kind of wasteful since most of the time we wait for the server's response, so thread is just idling), though multithreading might prove useful for resource-intensive tasks (e.g. UI drawing). We can make everything single-threaded now with the GMainLoop, we can just wait for the events from the sockets together with the events from other parts of the program.

https://docs.gtk.org/glib/main-loop.html

**Comment by jubalh** [comment]
We reverted the gmainloop changes: https://github.com/profanity-im/profanity/commit/88b26cfdb9bd8468c9b7f9131dea55ed35bbd751
