### ISSUE TITLE
OMEMO messages in private MUC do not decrypt after being archived with message archive

### ISSUE THREAD

**Issue by wisheth** [profanity-im/profanity#1959]
## Expected Behavior

In other XMPP clients with message archiving enabled, I can log out of my client and log back in while still being able to view OMEMO messages previously sent.

## Current Behavior

Reconnecting to the MUCs in my XMPP account shows me a sea of various "client doesn't support OMEMO" messages in the forms shown by various clients, including for my own messages.

## Possible Solution

I wonder if it's something to do with how OMEMO encrypted messages are stored, or if there's nothing in place to decrypt OMEMO messages after the fact; I'm not aware if this extends to other encryption methods as well and, due to the fact that I'm not too knowledgeable on OMEMO/XMPP cryptography in general and the people I use XMPP with aren't that tech savvy, I can't test for myself. There's a chance that this is because I have multiple OMEMO keys on my account, but I doubt that's it.

## Steps to Reproduce (for bugs)

1. Open Profanity and /connect to an XMPP account that's in a private MUC
2. Autojoin said private MUC
3. Receive an OMEMO message (this could be one that's sent in before you log in; for some reason those work)
4. /quit
5. Reopen Profanity and /connect again
6. Autojoin said private MUC to a wall of "OMEMO not supported" messages

## Context

This makes it difficult to keep a message history with my friends who use XMPP with OMEMO without using another client; I like to have an archive that I can look back on, and this makes it difficult to do that without exposing myself to another host server.

## Environment
Profanity, version 0.14.0

EndeavourOS Linux (Arch Linux "Extra" repo)
I see nothing about glib, which was asked for for this section, but glibc is version 2.39-1

XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.23.2)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.11.7)
GTK icons/clipboard: Disabled
GDK Pixbuf: Enabled

**Comment by wisheth** [comment]
MAM is enabled, but according to the documentation for /mam it's not supported for MUCs. Using PG UP doesn't load anything in these MUCs, even though I know there are previous messages.

**Comment by jubalh** [comment]
Sorry I was confused.
MUC MAM is WIP here: https://github.com/profanity-im/profanity/pull/1862

**Comment by jubalh** [comment]
@H3rnand3zzz didnt we implement that we load messages from DB when we scroll up even when MAM is not available?
