### ISSUE TITLE
Rename `/reconnect now` -> `/reconnect`

### ISSUE THREAD

**Issue by Privat33r-dev** [profanity-im/profanity#1965]
Current `reconnect` command is requiring to use `now` argument to actually initialize reconnect. At the same time, it performs no action. I can even go as far to suggest the following scheme:
`/reconnect` - initialize reconnect
`/autoreconnect {secs}` - set automatic reconnection time (more intuitive than `reconnect`, follows the analogy of `autoconnect`; it's *auto*matic because no manual action is required from user to reconnect on connection loss)

**Comment by jubalh** [comment]
Well we could have `/reconnect` to reconnect immediately and `/reconnect seconds` for seconds. But honestly I think the `now` is not so bad.. :)
