### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by avidseeker** [profanity-im/profanity#1967]
A commandline interface would make it possible to use profanity in scripts. Currently the only supported commands are:

```
profanity [-vh] [-l level] [-a account]
```

**Comment by jubalh** [comment]
There are specific projects for such things, for example:
* https://codeberg.org/Anoxinon_e.V./xmppc
* https://salsa.debian.org/mdosch/go-sendxmpp

**Comment by sjaeckel** [comment]
> There are specific projects for such things, for example:

Or if you want to stay within C you could write a tool with a CLI interface using libstrophe. 

https://github.com/strophe/libstrophe/tree/master/examples could give you a good starting point.

If I may ask: what's your use case?

**Comment by avidseeker** [comment]
Use case: creating bots using other CLI programs

**Comment by jubalh** [comment]
https://github.com/bluszcz/awesome-xmpp?tab=readme-ov-file#bots

**Comment by avidseeker** [comment]
Another use case: send messages as current account (not bot account) by integrating with other commands through piping. E.g.:

```sh
echo 'Hey, check out this cool URL' | profanity -a account1 -to friend@example.org
xclip -o -sel c | profanity -a account1 -to friend@example.org
```

**Comment by jubalh** [comment]
That's exactly what the above mentioned projects are for.

**Comment by avidseeker** [comment]
What about a command to check number of unread messages? This would be useful for scripts and status bar configs.
