### ISSUE TITLE
Parse JID from URI

### ISSUE THREAD

**Issue by avidseeker** [profanity-im/profanity#1968]
XMPP JIDs are usually shared as a URL or a URI. It would be convenient to have profanity parse it automatically. Currently, `/join editor@muc.xmpp.org` works, but
* `/join xmpp:editor@muc.xmpp.org?join`
* `/join xmpp:editor@muc.xmpp.org`
* `/join editor@muc.xmpp.org?join`

do not work.

**Comment by sjaeckel** [comment]
Duplicate of #1782
