### ISSUE TITLE
statusbar actlist doesnt respect `/statusbar show` setting

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1974]
statusbar actlist doesnt respect `/statusbar show` setting.

## Expected Behavior
`/statusbar tabmode default`
`/statusbar show name`
Shows the name in the statusbar tab.

`/statusbar tabmode actlist`
`/statusbar show name`
Should do the same

## Current Behavior
`/statusbar tabmode actlist`
`/statusbar show name`
Does not show the name in the statusbar tab.

**Comment by sjaeckel** [comment]
FTR: I did this explicitly to only show numbers in #1813 since irssi's actlist also only shows numbers.

One could still want to see names instead, so this feature request is valid.
