### ISSUE TITLE
In-band account registration

### ISSUE THREAD

**Issue by alandrees** [profanity-im/profanity#199]
Allow for in-band account registration as per:
http://xmpp.org/extensions/xep-0077.html

**Comment by xeverse** [comment]
Any progresss?

**Comment by TheBrainScrambler** [comment]
This issue seems to be very old but would be really useful. Does someone plan to implement it in profanity one day ?

**Comment by jubalh** [comment]
@pasis ping ^

**Comment by pasis** [comment]
libstrophe has example of in-band registration: https://github.com/strophe/libstrophe/blob/master/examples/register.c . I've used that to register users on my test server. Good implementation also requires support of forms. The example can be a starting point for profanity.

**Comment by binex-dsk** [comment]
eight year old issue, add wehennn????

**Comment by jubalh** [comment]
@binex-dsk we waited 8 years for the chosen one to appear. The issue is quite hard and only a very special person with unlimited access to the timestream can solve it.
We are delighted that the chosen one finally appears, it is **you**!

Now that you have found your purpose in life we estimate that you will solve this issue by next week. Please hurry up and create a PR.

**Comment by binex-dsk** [comment]
Hi what is this a joke or is this serious sorry i am unable to tell because autism funny

though i suppose it would finally be an excuse to do some C stuff but then I'd also have to learn to do xmpp stuff

**Comment by jubalh** [comment]
Just give your best!

**Comment by binex-dsk** [comment]
well i could if this had documentation for how to add commands and actually do stuff

**Comment by jubalh** [comment]
You need to check git log or look here for PRs that add commands. Then you can see how others did it before you. But you did a good job for a start!

**Comment by binex-dsk** [comment]
yea I just checked the PRs and logs for how commands were added. Some stuff i wasnt sure about but it looks to be working (minus the SIGABRT)

**Comment by jubalh** [comment]
`/register` command has been added by @binex-dsk.
