### ISSUE TITLE
MUC history not saved

### ISSUE THREAD

**Issue by emmatebibyte** [profanity-im/profanity#1996]
When `/history` is set to `on`, profanity does not preserve MUC history locally.

## Expected Behavior

Profanity saves MUC history from logged in sessions.

## Current Behavior

Profanity does not save history from logged in sessions.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Open MUC
2. previous history from the same client, received while logged in, does not display

## Context

I want to save history.

## Environment
* profanity 0.14.0
* OpenBSD 7.6-beta
* glib2 2.80.4
* libstrophe 0.13.1
* prosody 0.12.4 on OpenBSD 7.5

**Comment by jubalh** [comment]
History is saved in in sql database.
But for MUC it isn't retrieved yet. The feature to load the history from the database via page up keys was developed at the same time when MAM implementation started. So somehow its coupled.
MUC MAM isn't finished yet it is being worked on (somehow paused) at https://github.com/profanity-im/profanity/pull/1862
In earlier issue I mentioned as well that the page up - load from db should be decoupled from MAM.

I'm assuming here that your title is wrong and that history is actually saved and that you just mean that its not displayed after reopening. If so this is expected and WIP. `/help mam` also mentions this.

**Comment by emmatebibyte** [comment]
I see. Thank you.
