### ISSUE TITLE
irssi down arrow behaviour

### ISSUE THREAD

**Issue by alandrees** [profanity-im/profanity#200]
In irssi, the down arrow stores the current line in history and blanks the input line.  Due to the similarity of interfaces, I find myself looking for the same functionality.

**Comment by Ppjet6** [comment]
I still have this problem on Arch with aur/profanity-git (4789.44979ac-1)

**Comment by jubalh** [comment]
In case we switch for https://github.com/profanity-im/profanity/issues/228 away from using readline for history we also need to be aware of this here.

**Comment by kaffeekanne** [comment]
I like the idea of that feature, although one could use the terminal multiplexer/emulators copy paste function, to achieve this. But how would that down-arrowed message/command be brought back to the input line? Down arrow again if input line is empty, append to text on input line, over write current input line?
