### ISSUE TITLE
More comprehensive chat history

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#205]
Many people have requested the option to be able to scroll through all previous logs with a contact whilst in chat with that contact.

Some form of streaming from the available logs to the current window would be required.

**Comment by jubalh** [comment]
Once we support [MAM](https://github.com/profanity-im/profanity/issues/660) we could get the history from there instead of from the log files. This way it would also include content send from other devices.

**Comment by mdosch** [comment]
I see some value to also include the log files as MAM is usually not unlimited so it would be nice if you could also access your old messages from profanity.
