### ISSUE TITLE
Multi account support

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#207]
Some people have request being able to login to more than one account using profanity.  The current suggestion is to run more than one instance of profanity, use GNU Screen etc.  Features like #170 are intended to make this easier.

It's still debatable whether the additional complexity added to both the code and the user interface merits adding this feature.

Any comments here are welcome.

**Comment by varac** [comment]
For me this is missing feature no. 1 in profanity, and I'd love to have it implemented.

**Comment by jubalh** [comment]
I don't see us doing this for now.

I brings some questions on how to display things, a lot of more complexity and rewriting many things.

I think just using tmux/screen is fine. As I would say people who have 5 different accounts are doing something wrong anyways ;)
