### ISSUE TITLE
OTR encrypted messages sent to other clients

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#295]
When having an OTR session with a recipient, if that recipient is connected via more than one resource, all resources may be sent the message, but all others (not in the OTR session) will not decrypt the message.

This may be the only behaviour available.

Testing should also be done for when the recipient is connected via two resources, both of which attempt an OTR session with the profanity user.

**Comment by jubalh** [comment]
In `message_send_chat_otr()` we attach `<no-copy/>`, `<private/>` and `<no-store/>`, this is all that we can do to work well with other clients.
