### ISSUE TITLE
Pasting is "slow"

### ISSUE THREAD

**Issue by dreh23** [profanity-im/profanity#302]
When I paste a long URL (ebay) in the field. I can watch the terminal writing the URL like a typewriter. 

Ubuntu 64 - 0.4.0dev.master.bbdf2be

**Comment by paulfariello** [comment]
Is the solution to #156 also the official solution for this issue ?
IIUC Paste plugin can't work on a remote server. So user running profanity over ssh are doomed to have slow paste.

@boothj5 In #156 you say: "There's been no work in the core code to add this feature". Is it still true ? What would be required to fix this issue ?
