### ISSUE TITLE
Support XEP-0066: Out of Band Data

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#316]
http://xmpp.org/extensions/xep-0066.html

http://xmpp.org/extensions/xep-0096.html

Done: http://xmpp.org/extensions/xep-0363.html

**Comment by sammcj** [comment]
I can't imagine using an XMPP client without being able to send and receive files, that's one of the core uses of XMPP across our teams.

**Comment by asdil12** [comment]
XEP-0363 is already implemented in profanity (`/sendfile`)

**Comment by jubalh** [comment]
XEP-0363 is probably what most users nowadays use. So I think we are good already. Keeping this open in case we want to add the other methods too though.

**Comment by jubalh** [comment]
XEP-0096 is deprecated since 2017-11-29.

**Comment by optmzr** [comment]
Are you able to rename this issue, to something like: "Support XEP-0066: Out of Band Data", so people aren't confused and think sending files isn't implemented? :)

**Comment by jubalh** [comment]
Good idea!

**Comment by jubalh** [comment]
I think everybody is using XEP-0363: HTTP File Upload nowadays.
