### ISSUE TITLE
Make use of instance tags with libotr 4.0.0

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#320]
Currently although profanity will compile with libotr 4.0.0, none of the additional features in the OTR spec v3 are being used.

Add support for instance tags.

https://otr.cypherpunks.ca/UPGRADING-libotr-4.0.0.txt

**Comment by boothj5** [comment]
Allow OTR sessions to be started with a specific resource.

**Comment by jubalh** [comment]
It seems there are not many clients out there that still use OTR. So I'll close this since I think it doesn't give us much.
