### ISSUE TITLE
Cache theme list

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#327]
Cache themes list on first autocomplete action or every `/theme list` command. This would avoid unnecessary syscalls and/or I/O operations during autocomplete. But every `/theme list` should load list from file system because users want to see their themes immediately after copying to home directory.

**Comment by jubalh** [comment]
Actually I'm not sure what should be done here.
@boothj5 or @pasis do you remember? :)

**Comment by pasis** [comment]
As I understand from the description, Profanity searches for filenames every time user uses autocompletion. It can be slow in some scenarios . The idea here is to create a cache (list or so) and put all filenames there after the 1st search. When you enter command `/theme list` Profanity should refresh the cache and then display it.

Depending on current sources, the idea could be implemented as follows:
```C
_init():
    theme_cache_refresh();

autocomplete_theme:
    return theme_cache;

theme_list:
    theme_cache_refresh();
    print_to_console(theme_cache);
```

**Comment by jubalh** [comment]
But if I understand it the following can happen:
A user starts profanity. Looks at the themes with `/theme list` then copies over a theme to the directory. Then wants to load the new theme with `/theme load mytheme` but autocompletion doesnt work for it. Because we initialized the list of themes on the first run of `/theme load` (or `/theme list`) and need a new `/theme list` to refresh that list.

So it's always expected of the user to run `/theme list` before autocompletion works for freshly copied themes. I'm not sure this is good? Isn't it better like it is right now?

**Comment by mdosch** [comment]
Maybe refresh the list if the theme is not found after using the cached list and look up again. Or consider this as overengineered and leave it as it is. 😃

**Comment by pasis** [comment]
@mdosch, Cache in the above scenario works only for autocompletion. When a command is typed the cache is refreshed or a particular filename is searched.

@jubalh, You're right, this is a trade off. When we implement a cache we will save syscalls and I/O in some cases. Usually OS should cache information about files to RAM and I/O won't be performed often. The issue may be if user put theme files to a network filesystem or to a drive which can "sleep". In this case the user will experience a delay during autocompletion.

From other side, if we leave it as it is now, users will be able to autocomplete new themes right away. And it will work fine in most cases (unless users have network fs or drive with powersave mode). However, even for drives with powersave mode, Linux caches files information to RAM and it should work fast after 1st access.

Anyway, personally I'm fine with any solution.

**Comment by jubalh** [comment]
I think I will close this and leave it as is. I understand the advantage but personally I think the downside of not having autocomplete behave as nicely is bigger. I think it's not often that a user has his home directory on a network filesystem that might take some time to read **and** that he changes the theme every day.

In case somebody else has different opinion we can certainly reopen this issue.
