### ISSUE TITLE
sound using mplayer/aplay

### ISSUE THREAD

**Issue by lucianbach** [profanity-im/profanity#334]
Pidgin is doing this very simply, executing a predefined app (mplayer etc) to play some wav files when a message is received/sent, buddy comes online/offline.

This should be implemented in profanity too. I know about the beep thing, but for example it won't work some times, and also you can't compare it to some nice sounds.

This should be for linux only I guess.

**Comment by jubalh** [comment]
I suggest you solve this by writing a plugin. I don't see why this is a big feature that should be added to Profanity itself.
