### ISSUE TITLE
Support XEP-0186 invisibility

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#340]
http://xmpp.org/extensions/xep-0126.html

**Comment by jubalh** [comment]
It seems neither [prosody](https://prosody.im/doc/xeplist) nor [ejabberd](https://www.process-one.net/en/ejabberd/protocols/) support XEP-0186 as of now.

This and the fact that it was deferred in [2018](https://xmpp.org/extensions/xep-0186.html) makes me think that we should close this feature request.
