### ISSUE TITLE
/info should show last seen

### ISSUE THREAD

**Issue by brzezinki** [profanity-im/profanity#360]
When user does /info about jid, a last seen should be shown, when jid is offline.

**Comment by jubalh** [comment]
You need to use the `/lastactivity jid` command for this.

**Comment by jubalh** [comment]
There seem to exist XEP-0012, XEP-0256 und XEP-0319.
All about this subject.

We could also save the timestamp of the last stanza ourselves.

Problem seems to be that with XEP-0012 we wake up mobile clients unneccesary.
