### ISSUE TITLE
Ability to highlight messages based on regex

### ISSUE THREAD

**Issue by mudrd8mz** [profanity-im/profanity#369]
Use case: I would like to define a regex. If the incoming message matches it, either the matched pattern(s) or the whole message or both (depending on what is easier to implement) would get highlighted with a color defined in the theme.

This could be used in MUC rooms to highlight messages mentioning my name or other things I'm particularly interested in.

**Comment by arthurlogilab** [comment]
As mentioned in #1027 I would be interested in this plugin. 

An added use case from the `@all` use case, would be that in a group chat, we code notify teams or subsets of people that have a particular skill without having separate groupchats, for example `@pythonistas` or `@devops` or `@ops`...

**Comment by jubalh** [comment]
@mwuttke97 something for you?

**Comment by MarcoPolo-PasTonMolo** [comment]
Isn't this pretty much the same as `/room trigger add <word>` ?

**Comment by jubalh** [comment]
I guess you are right. Just with the option to define it as a regex.
Then on the other hand..when do we need that?
Should we close this?

**Comment by MarcoPolo-PasTonMolo** [comment]
I think so
