### ISSUE TITLE
Include nickname in chat logs path

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#380]
Find a way to include the nickname of a user in the chat logs path. Currently only the jid is used, but facebook uses an ID for the jid which makes it difficult to tell who the logs are for e.g.:

`642288786_at_chat.facebook.com`

**Comment by jubalh** [comment]
Nicks could have some special characters that are not okay for some filesystems.
Also FB use case is not valid anymore.
Should we close this?

**Comment by kaffeekanne** [comment]
As for the facebook use case, that is irrelevant now, i think. I have not used any transports, that might lead to cryptic folder names. 

According to https://xmpp.org/extensions/xep-0029.html#sect-idm45522446772976 a JID can also contain almost any strange character that might cause hickups on filesystems.

No idea if that might get back to us some time in future. But then its another issue, i guess.

**Comment by jubalh** [comment]
> According to https://xmpp.org/extensions/xep-0029.html#sect-idm45522446772976 a JID can also contain almost any strange character that might cause hickups on filesystems.

Right!

For now I don't see a reason why we would need it. So I'll close this and we can reopen it later or create a new issue.
