### ISSUE TITLE
Segfault after attempting to connect

### ISSUE THREAD

**Issue by michaeljoelphillips** [profanity-im/profanity#404]
Greetings,

After building Profanity, I get a segfault after entering my password for any account.  I've built Profanity manually as well as using the install-all.sh script.  Both have the same result.  The version I'm currently running is Version 0.4dev.master.2253128 on Debian Wheezy.  Profanity returns:

"**\* stack smashing detected ***: profanity terminated
Segmentation Fault"

I apologize if there is a preexisting ticket for the same issue.  I searched through them, but didn't find this particular issue.  Thanks in advance.

**Comment by arno01** [comment]
Just if someone will get 'segfault' I've tested that it: 
is KO with Debian Jessies's libstrophe-dev 0.8.6-1
is OK with Debian Stretch's libstrophe-dev 0.8.8-2
