### ISSUE TITLE
Lost Connection after messaging with user with Apostrophe in his name

### ISSUE THREAD

**Issue by flexo3001** [profanity-im/profanity#405]
I'm losing the connection after i tried to messaging an user at facebook. The name is like "xxxx xx'x xxxxx". In profanity the user-completion in the /msg-command complets to '"xxxx xx"x xxxxx"'. After entering the message the connection gets lost and i have to wait to reconnect. The third " maybe causes the problem getting a string with an unclosed string appended.

**Comment by jubalh** [comment]
Both `/msg test'user` and `/msg "test'user" ` work for me.
