### ISSUE TITLE
Generate OTR without mouse

### ISSUE THREAD

**Issue by SimWhite** [profanity-im/profanity#425]
I'm trying to generate OTR key, but it seems to system stuck at:

```
21:12:59 - Generating private key, this may take some time.
21:12:59 - Moving the mouse randomly around the screen may speed up the process!
```

I use SSH-only connection, there is no GUI or mouse. How can I generate OTR without mouse?

**Comment by jubalh** [comment]
@paulfariello we probably have this with OMEMO too?

**Comment by paulfariello** [comment]
If libotr is generating its keys from `/dev/random ` then it's the same issue yes.

**Comment by optmzr** [comment]
This is the problem I always hit when setting up Profanity on a new computer. Running Haveged solves this for me.

**Comment by jubalh** [comment]
So should we mention this somewhere in the documentation that one could run Havaged?
