### ISSUE TITLE
Crash when switching to a tab with msg received

### ISSUE THREAD

**Issue by mudrd8mz** [profanity-im/profanity#458]
This seems to be similar to bug #332 I am using master.

When I start profanity
And there is an incoming message that was sent when I was offline
And I attempt to switch to the tab with it
Then profanity crashes with

```
profanity: src/contact.c:264: p_contact_presence: Assertion `contact != ((void *)0)' failed.
```

This happens with a contact I do not have in the roster, have not had a chance to test with contacts in the roster.

**Comment by unInstance** [comment]
I experience the same issue but in my case it crashes with any user/room. Not just profanity closes but the terminal too.
