### ISSUE TITLE
Would it be possible to support terminal multiplexer?

### ISSUE THREAD

**Issue by mudrd8mz** [profanity-im/profanity#459]
I am not familiar with C (although I would love to :-)) and know nothing about the architecture of profanity.im. However, would it be possible to have single profanity instance running and connect/attach to it somehow from another terminal window?

This is my use case: I use terminal multiplexer (tmux). I would like to use profanity in a way that I could have individual tabs (with MUC rooms) opened in separate tmux pane (or terminal windows, it should not matter). That way, I could organise the layout of the UI as I want.

Something like running the program with

```
$ profanity
```

and then in another terminal window (tmux pane)

```
$ profanity --attach
```

or so that would basically use the existing connection, it would just provide a new UI instance. So I could launch multiple UI instances and individual profanity tabs opened in each of it.

**Comment by stm555** [comment]
Has native window splitting been considered as an alternative? I too would like to have a few channels/groups visible at the same time.

**Comment by jubalh** [comment]
I don't plan on implementing this myself.
