### ISSUE TITLE
Importing OTR keys and fingerprints from another client

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#479]
Since profanity uses the libotr library to store keys and trusted fingerprints, files created by another client which uses libotr should also work with profanity.

The files need to be placed in the following locations:

```
$XDG_DATA_HOME/profanity/otr/<account>/keys.txt
$XDG_DATA_HOME/profanity/otr/<account>/fingerprints.txt
```

On most systems `$XDG_DATA_HOME` is `~/.local/share`.
The `<account>` folder is the account name with `_at_` replacing the `@` symbol, for example account `my.account@server.org` will have the above two files stored as:

```
~/.local/share/profanity/otr/my.account_at_server.org/keys.txt
~/.local/share/profanity/otr/my.account_at_server.org/fingerprints.txt
```

This issue will be closed once the above and any additional information have been added to the website.

**Comment by shibumi** [comment]
Any update for this issue?

**Comment by boothj5** [comment]
Sorry for the delay, been a bit busy over the holiday period.

This issue was really just information to be added to the website which I haven't done yet, did you have any other question about OTR files?

**Comment by shibumi** [comment]
Yep it doesn't worked. I have tried that with importing my otr keys and everything from mcabber.. but something went wrong. No error-messages but the otr module said there is no otr key although it was loaded.. iirc.. not sure it's already over 22 days ago. I just generated new otr keys. I could try to reproduce this issue if you really want to trace it :)
