### ISSUE TITLE
Split Windows

### ISSUE THREAD

**Issue by stm555** [profanity-im/profanity#490]
Monitoring multiple conference/group/channels at a time is a common use case for me. It would be great if I could split the windows like in vim/screen/tmux.

**Comment by j6k4m8** [comment]
I'd love to see this too. Not entirely sure how to implement, but I'd be more than happy to contribute if we had a gameplan.

**Comment by MelkorNemesis** [comment]
+1

**Comment by jubalh** [comment]
We need to wait until @weiss finally joins us and implements his more flexible UI here ;p
I'm not interested in this myself.
