### ISSUE TITLE
A beep is a nice thing to have ringing. Sometimes.

### ISSUE THREAD

**Issue by quite** [profanity-im/profanity#511]
A beep() is a nice thing to have ringing. It propagates out through my tmux, into the terminal, and into the window manager, which highlights the terminal in the list of clients, and as well the virtual screen the client is on. So I'll catch that message, for sure.

But when I'm trying to hold a conversation, having the beep/flash in my face as my friend is typing is pretty darn annoying.

What can be done about that. On beep(), let x minutes pass before beep() is allowed to go off again? Per jid of course. Does that make sense?

**Comment by boothj5** [comment]
Ideally I'd like to use the window manager to tell if a window is visible and only beep/flash when it isn't (for the active profanity window).

Failing that, some kind of timeout sounds reasonable.

Added to the list for 0.4.7.

**Comment by quite** [comment]
Yeah, that sounds great. Hm, is it really possible to speak to the window manager? Or is it perhaps possible to speak to the terminal window we're in to hear whether he is visible and/or active?
If we're in a terminal multiplexer, things probably get different as well.

**Comment by devhell** [comment]
This would be great to have. As it stands i3 doesn't seem to react to new messages coming in.

**Comment by quite** [comment]
And/or perhaps a way to toggle whether a window, or MUC, should cause beep at all...jjj

**Comment by jubalh** [comment]
@quite still relevant? If yes, do you maybe want to implement it yourself? :)

**Comment by quite** [comment]
I think we can rule out trying to ask the window manager if our window is visible. It'll end up being very complex, even if such a function exists for the most simple case.I think we can rule out trying to ask the window manager if our window is visible. It'll be very complex, even if such a function exists for the most simple case.

**Comment by jubalh** [comment]
I don't have interest in implementing this myself.
