### ISSUE TITLE
Let aliases take parameters, and allow completion

### ISSUE THREAD

**Issue by quite** [profanity-im/profanity#514]
$ /alias add /m /msg
$ /m foo
Unknown command: /m foo
$ /m fTAB  [nothing happens]

**Comment by incertia** [comment]
Completion shouldn't be too hard to implement. Just unalias the command string before sending to completion subsystem. I'll take a look at this once I free up some more time.

**Comment by jubalh** [comment]
@quite still relevant? If yes, do you maybe want to implement it yourself? :)

**Comment by quite** [comment]
No. And closing is fine...
