### ISSUE TITLE
Logrotate does not appear to increment suffix and create new files

### ISSUE THREAD

**Issue by ephphatha** [profanity-im/profanity#519]
Every time the log file hits the size limit it gets renamed to profanity.log.1 and overwrites the old .1 file. I'd expect it to create a new file with .2, .3, etc suffixes each time it hits the limit when rotate is set.

**Comment by jubalh** [comment]
When PR is merged we will have profanity.log -> profanity.log.01 -> profanity.log.99.
After that only profanity.log.99 is used.
