### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#52]
GTalk is deprecating other methods of authentication in favour of OAuth2.

Support authentication using OAuth perhaps along the lines of:

https://developers.google.com/accounts/docs/OAuth2ForDevices

There is a deferred XEP which may be of use:

http://xmpp.org/extensions/xep-0235.html

**Comment by pasis** [comment]
I have successfully passed authentication with X-OAUTH2 mechanism. I constructed auth stanza manually using token that I obtained at the [playground](https://code.google.com/oauthplayground/).

The problem with tokens is that they require too high level logic and user interaction for obtaining. This can't be implemented in libstrophe. Even if user or profanity obtained token somehow libstrohpe doesn't have interface for choosing or configuring particular auth mechanism.

**Comment by boothj5** [comment]
Indeed.  I will eventually look into this, perhaps adding a callback in libmesode/libstrophe, or whatever is needed to complete the steps for logging in.

**Comment by jubalh** [comment]
There is also XEP-0235: OAuth Over XMPP.
Since Gtalk is not a thing anymore and I don't use oauth myself I'll close this for now.

**Comment by rjc** [comment]
I'd like to re-open this ticket - https://talk.google.com/ which redirects to https://hangouts.google.com/ is still a thing and only recently had they disabled _insecure apps access_, which affected using their service via _profanity_. It's been working fine for years, until last week. Is there any chance to add support for `X-OAUTH2` or `X-GOOGLE-TOKEN` mechanism?

**Comment by jubalh** [comment]
> https://talk.google.com/ which redirects to https://hangouts.google.com/ 

You can log in with Profanity there? (before the insecure apps switch)

AFAIK they do not only offer OAUTH but also application specific passwords, right? So that could be a way to make it work for you?

>  Is there any chance to add support for X-OAUTH2 or X-GOOGLE-TOKEN mechanism?

Well sure. Just I'm not interested in implementing this myself. Do you wan to open a PR?
