### ISSUE TITLE
Abbreviation

### ISSUE THREAD

**Issue by leowzukw** [profanity-im/profanity#520]
It would be nice to allow to use abbreviations when chatting, a bit like [vim](http://vim.wikia.com/wiki/Using_abbreviations) does.

It could be
- `/abbreviate add Req Request`
- `/abbreviate list`
- `/abbreviate remove Req`

**Comment by leowzukw** [comment]
Updated issue

**Comment by PMaynard** [comment]
This should be easy with the current alias command. If you want to chain commands there is an issue open for that. #514 

Alias docs: 

	alias
	-----

	Synopsis
	/alias list
	/alias add <name> <value>
	/alias remove <name>

	Description
	Add, remove or list command aliases.

	Arguments
	list               : List all aliases.
	add <name> <value> : Add a new command alias.
	remove <name>      : Remove a command alias.

	Examples
	/alias add friends /who online friends
	/alias add /q /quit
	/alias a /away "I'm in a meeting."
	/alias remove q
	/alias list

Does that help you?

**Comment by leowzukw** [comment]
Sorry, I didn't see your answer.

I was thinking to abbreviation when chatting, for example, in the middle of a conversation you are speaking to your friend, entering something like this

See ll. 112-115 of [The Picture of Dorian Gray](http://www.gutenberg.org/files/26740/26740-h/26740-h.htm)

Which would be translated to:


See lines 112-115 of [The Picture of Dorian Gray](http://www.gutenberg.org/files/26740/26740-h/26740-h.htm)

We would define the translation of `ll.` as `lines`. That’s what I call abbreviate.

I hope my idea is clearer now.

**Comment by leowzukw** [comment]
Ping

**Comment by jubalh** [comment]
I don't think this is worthy to add.
