### ISSUE TITLE
Option to auto focus rooms with activity

### ISSUE THREAD

**Issue by mattroid** [profanity-im/profanity#526]
I prefer to leave profanity open monitoring company chat rooms and would like to see what's being said accross rooms. I have the same functionality in irssi with a perl script. Can I do this in profanity?

**Comment by mrsdizzie** [comment]
A really basic version of this would be to do this inside of a plugin:

`def prof_pre_room_message_display(room, nick, message):
        prof.send_line("/win %s" % (room))`

Imagine this might be annoying if rooms are constantly receiving messages and the client is switching you back and forth but is fine for low traffic situations.

**Comment by jubalh** [comment]
> Imagine this might be annoying if rooms are constantly receiving messages and the client is switching you back and forth but is fine for low traffic situations.

I imagine so too. Also if you go away for just a couple of minutes it might switch to a room and then switch back to the first room. And you won't see that there were new messages in the other room.

The plugin way is fine. But I don't think it's worth implementing this in Profanity itself.
