### ISSUE TITLE
Script install-all.sh should tidy up on fail

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#531]
See example issue: #499

Clear up directories when script fails part way through install.

**Comment by incertia** [comment]
by clean up directories, would this refer to doing the same thing as a `make clean` on error? if so, the easy way would to use a wrapper script to run `sh -e ./install-all.sh` and test against `$?`.

**Comment by boothj5** [comment]
Actually, it's probably just the `libstrophe` directory that needs cleaning, which is cloned during install.  Calling `cleanup()` from the error handler.

**Comment by jubalh** [comment]
Currently libmesode cleanup happens [here](https://github.com/profanity-im/profanity-im.github.io/blob/master/install-all.sh#L155).
I think this enough. And people might want to investigate more on a failure. So I would not destroy everything on a fail. In any case users probably run this in a own directory so they can cleanup easily.
