### ISSUE TITLE
Poor handling of UTF-8 characters

### ISSUE THREAD

**Issue by kseistrup** [profanity-im/profanity#539]
Profanity seems so be unable to handle certain UTF-8 characters — specifically those made of 4 bytes.

While I can enter a 3-byte UTF-8 character like the horizontal ellipsis (U+2026 HORIZONTAL ELLIPSIS):

``` sh
/away zZzZ…
```

I cannot enter a 4-byte character like ‘😴’ (U+1F634 SLEEPING FACE), it simply doesn't appear after the space

```
/away 
```

It is also impossible to paste said character onto profanity's commandline.

The terminal in which profanity runs shows both characters as expected.

**Comment by kseistrup** [comment]
In a similar vein profanity can only receive a very limited number of UTF-8 characters.  E.g., if a friend sends a ‘🐍’ (SNAKE), I receive ‘ὀd’ (GREEK SMALL LETTER OMICRON WITH PSILI + LATIN SMALL LETTER D) in profanity.

I'd say that this is a bug, not an improvement request.

**Comment by kseistrup** [comment]
Shouldn't being able to send PILE OF POO back a forth between clients have a high priority in a program called profanity? :wink:

**Comment by boothj5** [comment]
Which terminal are you using?

I can actually send and receive all of the above using iTerm2 on a Mac, but can't paste them successfully into my Linux terminal (Terminator).

**Comment by jubalh** [comment]
Works well for me (gnome-terminal).
