### ISSUE TITLE
Parse HTML links

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#543]
Although there is a separate spec for sending HTML http://xmpp.org/extensions/xep-0071.html, some clients (reportedly Pidgin) send links as an `<a href="link">link</a>` element.

Add checks for these elements and strip the HTML before displaying.

**Comment by boothj5** [comment]
Further reporting is that this only happens when the other client (Pidgin, Adium) is using an OTR plugin.  Related to: #364

**Comment by boothj5** [comment]
https://bugs.otr.im/issues/85

https://trac.adium.im/ticket/6901

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/issues/364 got closed.
OTR isn't used widely anymore.

Generally stripping away any HTML sounds wrong to me since it could be that people send me code snipptes to look at.
