### ISSUE TITLE
256 colour support.

### ISSUE THREAD

**Issue by kierun** [profanity-im/profanity#593]
Is there any chance of 256 colour support?

**Comment by boothj5** [comment]
It's something I'd like to implement when I get the time, or if anyone else knows how...

**Comment by kierun** [comment]
The last time I did anything with curses and colours was in Python. It was fairly easy at the time.  Sadly, I have no time to help -- works, twins, ...  However, I can test and do a theme.

**Comment by seamus-45** [comment]
I just leave it here: [ncurses.faq.html#xterm_16MegaColors](http://invisible-island.net/ncurses/ncurses.faq.html#xterm_16MegaColors)

**Comment by jubalh** [comment]
256 colour support was added by @aaptel in #1177.

See 269afa53b4167223e1b7ebd8b3b4e8ef8402d959 until c2a565c2ec3a9f22ce6c4c97ef5ba219981462a5.

We can now use Xterm colour names in our themes: https://jonasjacek.github.io/colors/
