### ISSUE TITLE
Implement mouse support

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#594]
Previously the `/mouse` preference enabled scrolling the current window contents with the mouse wheel.  However the setting was experimental and had a number of issues.
#401
#160

With the introduction of GNU Readline, the mouse handling needs to be rewritten, so has been disabled. This issue is to add mouse support back in, fix the issues, and potentially implement some other requested features.
#400

**Comment by jubalh** [comment]
Mouse support has been disabled in 46e2f11b93bb3dfed7b9f5c780961d18cb327b12.
I don't intend to bring it back.

**Comment by H3rnand3zzz** [comment]
Will the PR be accepted if someone would provide good mouse support?

**Comment by jubalh** [comment]
> Will the PR be accepted if someone would provide good mouse support?

Yes!
