### ISSUE TITLE
Resizing occasionally results in a badly drawn UI

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#609]
Sometimes resizing the window will not redraw the UI correctly.

**Comment by MelkorNemesis** [comment]
Same happens to me all the time. Whenever I resize the terminal I gotta scroll to the very bottom in the chat window in profanity.

**Comment by PMaynard** [comment]
Resizing the window does not work correctly when the dialogue for TLS action is active. e.g. select options for self signed, allow, deny and always.

**Comment by boothj5** [comment]
@PMaynard good spot, the same happens when entering a password on login.

Both cases should be fixed now in master.

**Comment by PMaynard** [comment]
Can confirm both cases are not fixed.

**Comment by jubalh** [comment]
Seems this was fixed long ago. Closing.
