### ISSUE TITLE
Show OTR session ID, and add a command to show it.

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#612]
From comments on: #558

Show the OTR session ID when OTR sessions are started/ended.

Also add a command to show the current session ID.

**Comment by devhell** [comment]
Also, very good idea!

**Comment by jubalh** [comment]
I didn't find anything about a otr session ID in the code nor in https://xmpp.org/extensions/xep-0364.html
Also not sure why one would need to display it. Going to close for now.
