### ISSUE TITLE
SSL: Restrictions on TLS versions and ciphers.

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#617]
As per comment by @PMaynard at #280

**Comment by pasis** [comment]
Recently, related patch was added to libstrophe: strophe/libstrophe#103

**Comment by jubalh** [comment]
@pasis do you maybe have time for this?

**Comment by pasis** [comment]
From the description I understand that with the feature user controls what TLS versions and algorithms may be used by libstrophe. But I don't think this is a good idea for most users and I don't want to overcomplicate libstrophe API to control such a behavior.

After the feature request is created, libstrophe has blocked insecure TLS versions and improved verification. I guess this works for most users who don't want to go deep in TLS stuff.

**Comment by jubalh** [comment]
Thanks @pasis, in this case I'll close this.
