### ISSUE TITLE
Allow ignoring users

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#618]
Allow the user to specify users to ignore in chat rooms, by nickname.

Allow the user to specify users to ignore one to one chat message from, by JID.

**Comment by jubalh** [comment]
There is [XEP-0191](https://xmpp.org/extensions/xep-0191.html) Blocking Command.

**Comment by mdosch** [comment]
I successfully used `/blocked` commands to block MUC participants by their full JID: `/blocked add room@conference.example.org/spammy-user`. But I don't know if these persons ever tried to send me a MUC pm.

**Comment by jubalh** [comment]
@mdosch that's right! I added it to the help command for `/blocked`. In this case I'll close this issue.
