### ISSUE TITLE
Implement Publish/Subscribe functionality (various XEPs)

### ISSUE THREAD

**Issue by jmthackett** [profanity-im/profanity#642]
It's a fairly big ask, I realise, but a way of browsing, subscribing to and publishing similar to what movim.eu implements would be good. The pubsub model can be used as either a forum or a blogging service (or both) so there's a lot of potential there, and it'd be really good if there was a way to interact with those services, particularly as support for them is becoming more common.

I can elaborate further if required, but on the face of it, is this a feature request that's likely to make it into the project's game plan? The scope of the task is fairly large though, so I understand if it's to be kept permanently out of scope.

There are a few XEPs involved, a subset of [this](http://wiki.movim.eu/en:dev:protocol_implementations) list (ctrl+f "pub").

**Comment by jubalh** [comment]
The link  you mentioned is unfortunately dead. So I'm not sure what this issue is exactly about.
We use XEP-0060 Publish-Subscribe for OMEMO.
