### ISSUE TITLE
Support voice/video

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#643]
Raised at the mailing list. The Jingle specifications are a good place to start:

http://xmpp.org/about-xmpp/technology-overview/jingle/

**Comment by pasis** [comment]
If you ever start working on voice support I'd recommend to look at toxic. In meaning how console-based voice application can look. This is ncurses-based tox client.

**Comment by jubalh** [comment]
I think this is out of scope.

**Comment by jubalh** [comment]
If somebody wants to work on this, please feel free to do so. We can reopen this issue and assign it to you.
