### ISSUE TITLE
Can't use OTR

### ISSUE THREAD

**Issue by ghost** [profanity-im/profanity#647]
I'm trying to set up IM between me and a cousin. We can chat fine though ChatSecure using OTR, but I can't get his messages in Profanity because it can't unencrypt it. '/otr start' does nothing. How do I get both ChatSecure and Profanity to work at the same time? Can they work at the same time?

Pidgin lets me use OTR, but I can't verify, it fails when I get it and nothing happens when I send it. I'd like to use Profanity. Anyone know what's going on?

**Comment by boothj5** [comment]
Some questions:

1) If you run `profanity -v` does it say OTR support is enabled?
2) Have you generated an OTR private key using `/otr gen`?
3) Do you see any errors in the console window when trying to start an OTR conversation using either Profanity, or ChatSecure?

The following page might be useful if you haven't seen it already: http://www.profanity.im/otr.html

Could you also attach the output from `profanity -v` to this issue.  Also useful would be the logs (running in debug mode with `profanity -l DEBUG`) around the time you are expecting an incoming OTR message, or sending one.

**Comment by Zaukaj** [comment]
Here's the output of profanity -v:

Profanity, version 0.4.7
Copyright (C) 2012 - 2015 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
Desktop notification support: Enabled
OTR support: Enabled
PGP support: Enabled

I did generate a key. When I try /otr start (buddy) it opens a regular window that says it is unencrypted. I may have to wait on the -l part, I'll post when I do it.

**Comment by jubalh** [comment]
I'm going to close this. Quite old issue. OTR works fine for me.
