### ISSUE TITLE
Add more customisation options to occupants panel

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#690]
Similar to the recent additions to the `/roster` panel (https://github.com/boothj5/profanity/issues/665), add further customisations to the chat room `/occupants` panel.

Ideas:
1) Enable/disable word wrapping
2) Option to show presence and status message
3) Options to group/order by presence

**Comment by jubalh** [comment]
Added some more features to the occupants panel. I think they make the most sense. Will close this issue for now and tackle more improvements in new issues/PRs if someone requests it or starts to work on it.
