### ISSUE TITLE
Allow MUC room nicknames

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#697]
Whilst MUC room JID's are autocompleted when bookmarked, and aliases could be added to join certain rooms, a request has been made to add MUC room nicknames to save typing e.g.:

```
/join profdev
```

Would be equivalent to:

```
/join profanitydev@conference.jabber.org
```

Either the `/room` or `/rooms` command could be used e.g.:

```
/room nick add profdev profanitydev@conference.jabber.org
/room nick remove profdev
```

**Comment by mdosch** [comment]
I already have nicks/aliases [1] in my MUC bookmarks and would prefer to also use them in profanity instead of having to set them up myself.

[1]: See https://xmpp.org/extensions/xep-0048.html Chapter 2.1 `'name' attribute`

**Comment by jubalh** [comment]
`/bookmarl list` lists the name now.
`/bookmark add` and `/bookmark update` have a `name` field now. So we can specify the bookmark name there and it will be the same across clients.

`/join` still autocompletes for the roomjid which I think is fine. Not sure how it should be "better".
One could have a setting for it to complete on either bookmark name or bookmarked roomjid but don't see much use for this.

**Comment by mdosch** [comment]
I would prefer to have `/join <tab>` cycle through the aliases as well if set (or maybe for bookmarks with alias only through the alias and for others through the JIDs). Maybe also for `/win <tab>`.
There are chats that don't have the topic in the local part e.g. chat@dino.im and I always want to go there by `/win dino<tab>` but it doesn't work.
