### ISSUE TITLE
Better UI behaviour in MUC windows when connection re-established

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#704]
Currently when the connection is lost the following is displayed in any open MUC windows:

```
Lost connection
```

If and when the connection is re-established, the room history is shown again which messes up the flow of messages.

Change this behaviour to not show the room history but instead something like:

```
Connection re-established
```

**Comment by jubalh** [comment]
Closed by https://github.com/profanity-im/profanity/pull/1110
