### ISSUE TITLE
Narrow terminal && long resource causes messy chat window titlebar 

### ISSUE THREAD

**Issue by quite** [profanity-im/profanity#715]
First line is now the following for one of my chats:

```
foo@example.com/2f874a53-ffff-ffff-ffff-ffffffffffff [online] [OT[TLS]r[away]
```

That should somehow be "[OTR] [Trusted] [TLS] [away]".

**Comment by boothj5** [comment]
That's pretty ugly! Time to rewrite the title bar code.

**Comment by jubalh** [comment]
@quite pretty long waiting time I know. Sorry about that.

I see ` foo@example/resource [online] [OTR] [untrusted]                       [TLS] [online] `.
So I assume this was solved some time ago. Or does it still happen for you?

**Comment by quite** [comment]
Is the `resource` there long enough to mess up to the left? And if it is, is it then truncated, or?

**Comment by quite** [comment]
OK, I found a contact with a very long resource, and can verify that it still looks bad:
```
xxxx@example.com/12345678901234567890123456 [away[TLS]R[online]]
```

**Comment by jubalh** [comment]
Right. Thanks for checking! Will take a look at this soon.

**Comment by jubalh** [comment]
Yeah lots of code needs to be rewritten to have this properly..

Anyways what theme are you using? Which version of profanity?
With current master `/resource title on` doesnt work for me with `boothj5` theme (and others I tested).

I also think that this setting should move to `/titlebar` instead of being in `/resource` too, since its about the titlebar. `/roster` also contains `/roster show resource`. So titlebar should have an `/titlebar show/hide resource`.

**Comment by quite** [comment]
I seem to be using a theme of my own creation... I haven't touched it in years. Running profanity from git now. 

I see you're doing a lot to revive profanity, nice! It is the terminal-xmpp client i've been most comfortable with, but i still find it quite clunky to use.

**Comment by jubalh** [comment]
> I see you're doing a lot to revive profanity, nice!

Thanks!

> It is the terminal-xmpp client i've been most comfortable with, but i still find it quite clunky to use.

I hope that changes with the next couple of releases ;)

**Comment by jubalh** [comment]
@quite maybe you want to tackle this yourself? :)

**Comment by quite** [comment]
Yeah this is a mess. I know I will not have time to rewrite this. Not 100% sure if should be closed though... Hm.

Btw, I see there is `/titlebar show|hide resource` now, are you keeping `/resource title on|off` for people's convenience?
