### ISSUE TITLE
Version Control Friendly Config

### ISSUE THREAD

**Issue by PMaynard** [profanity-im/profanity#721]
I store my configs in git. 'profanity/.local/share/profanity/accounts' adds last.activity to this file, which I don't want to sync between machines and don't care about as its nothing really related to my account configuration. 

Is there a better place for this, like /tmp ?

**Comment by kennyballou** [comment]
This probably isn't a solution, but you may want to look into smudge and clean Git filters. These would essentially trick Git into thinking the file was never changed in the first place.

Add something like the follow to your dotfiles `.git/config`:
```
[filter "remove-last-activity"]
    clean = "sed -e '/last/d'"
```

Add the following line to your dotfiles `.gitattributes` file:

```
profanity/.local/share/profanity/accounts filter=remote-last-activity
```

Again, this probably isn't a solution, but may be enough of a bandaid for now.

**Comment by PMaynard** [comment]
Thank you, a nice solution.

**Comment by jubalh** [comment]
The config file is `profrc`. There you configure your behaviour for profanity.
The `accounts` file contains other specific things like `resource` and `last.activity` and `presence.last`. The file is not really meant to be shared.
