### ISSUE TITLE
(typing...) should be under the messages in chat

### ISSUE THREAD

**Issue by nexustwo** [profanity-im/profanity#723]
(typing...) should be under the messages in chat

**Comment by jubalh** [comment]
I think in the titlebar is enough.

**Comment by devhell** [comment]
I'd like to respectfully argue against that. I use i3, and of course I can tile the terminals in such a way as to give profanity a small-ish terminal where all UI elements are easily identifiable without having to strain too much.

However, this isn't always the case when I run profanity in a larger terminal (half screen or even full-screen on a multi-monitor setup). In such cases the UI elements are really far apart and having to check for the title bar and then drop the sight down to the newest message gets tiring on the eyes.

From a usability perspective, I'd really appreciate if you'd maybe give this another thought.

Thank you :)

**Comment by jubalh** [comment]
Okay, good use case example.

**Comment by jubalh** [comment]
Seems noone was interested in implementing this.
Personaly I also don't need it. So closing for now.
