### ISSUE TITLE
C Plugins: Not working on Cygwin

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#749]
On Cygwin, C plugins cannot call the `prof_*` functions as they are all assigned `NULL`, the assignment in `c_api_init` seems to have no effect.

This is probably due to creation and linking of shared libraries on Cygwin needing more platform specific options in the build.

**Comment by boothj5** [comment]
Moved to 0.5.1 release, giving up on this one for 0.5.0 since I still haven't found a solution and it's holding up the release.

Will list it as a known issue for 0.5.0 on the website.

**Comment by jubalh** [comment]
https://github.com/boothj5/profanity/commit/56c0c533e3f2d8b01be16eecdafa39dc6ebb4e32 disables C Plugins for cygwin

**Comment by jubalh** [comment]
Can't support this since I don't have any Windows machine with Cygiwin.
Users can use WSL to get Profanity on Windows.
