### ISSUE TITLE
Profanity ignores the nick sent to it

### ISSUE THREAD

**Issue by kousu** [profanity-im/profanity#757]
If I join a MUC with profanity and the MUC gives me a different nick than I joined with, profanity says "you have joined the room as $requested_nick, role: $role, affiliation: member" in the room and possibly "Autojoined $room as $requested_nick".

The actual room roster doesn't list $requested_nick though, and messages come with the right nickname (because in MUC, all messages are echoed from the server, so the clients are not responible for choosing nicks there).

There are [one and a half ways](http://xmpp.org/extensions/xep-0045.html#enter-pres) a room can give you a different nick. First, in the `<status code=110>` stanza, it can give you a different nick than you requested. Second, if it gives you a different nick, it is supposed to attach `<status code=210>` as well, but that doesn't seem to be widely supported (I've only found Gajim paying attention to 210 so far) and I would be happy if you just declared the `<status code=110>` nick to be The Nick. You need to be careful about handling the case where $requested_nick matches a nick that is on the roster but is not the nick the room gives you.

Conversations had the same bug https://github.com/siacs/Conversations/issues/1732.

**Comment by kousu** [comment]
I should emphasize: this happens when the nick is silently changed, not if you are rejected and asked to pick a different nick. The 210 feature doesn't make a lot of sense for plain MUCs, but it's key for transports.

**Comment by MarcoPolo-PasTonMolo** [comment]
How do I reproduce this?

**Comment by kousu** [comment]
Well, it's been a while, so I'm sorry for not having been more specific. But one way should be to use [biboumi](https://github.com/louiz/biboumi) to join an IRC room with a nickname with spaces -- biboumi should rewrite it to use underscores.

I can probably use aioxmpp to rig up a minimal transport that always corrupts your nickname.

**Comment by MarcoPolo-PasTonMolo** [comment]
Ok I was able to replicate this. Let's hope I can also fix it
