### ISSUE TITLE
Connection lost when inserting a ^D (EOF) in the message

### ISSUE THREAD

**Issue by 1ace** [profanity-im/profanity#766]
#595 is not quite fixed yet: `^V^D` (which inserts a `^D`/EOF/ASCII(4) in the stream) still causes a crash, but it looks like it's happening at the network level:

> me: yay, I can send ^D without crashing now :D
> Lost connection.
> me: spoke too soon…

**Comment by ReneVolution** [comment]
This seems to be an reintroduced issue somewhere within the last 7 days.
I can reproduce this on OS X 10.11.1.

**Comment by 1ace** [comment]
Right, forgot to mention: I'm running 0.4.7, not directly on git.

**Comment by sjaeckel** [comment]
I just tried to reproduce with current master and couldn't.

Please re-open if there are further questions/comments.
