### ISSUE TITLE
Double quotes are not un-escaped when receiving a message. 

### ISSUE THREAD

**Issue by Tombert** [profanity-im/profanity#767]
Hello!  
When I receive a message with double-quotes, I get this: 

```
16:27:07 ~ xxx@xxx.xxx/15726799171458656725991366: &quot;guess i'm doing fine&quot; is a great beck song
```

This also seems to happen with `<` and `>`. 

Without going into detail about my friend's questionable taste in music, where would I go to look to fix this?

**Comment by Tombert** [comment]
I'm not sure if this is particularly relevant, but the chat server powering this is ejabberd, and the client my friend is using is Pidgin.

**Comment by yumitsu** [comment]
Have the same bug. Looks like it's related to #364.

**Comment by jubalh** [comment]
@mwuttke97 ? :)

**Comment by jubalh** [comment]
Some weird html otr thing? Can't reproduce.
