### ISSUE TITLE
Add autocompleter for plugins

### ISSUE THREAD

**Issue by ReneVolution** [profanity-im/profanity#769]
I am developing a plugin which let's you save shortcuts e.g. /shortcuts set omg "Oh my god..." which later can be used with :omg: which replaces exactly that. Also it will come with some predefined shortcuts for some ascii emoticons etc :).

Anyway, it would be great if i could also add auto-completion to it so :o<Tab> completes to :omg: etc.

**Comment by jubalh** [comment]
I don't plan to implement this myself and it seems like @ReneVolution moved on too.
