### ISSUE TITLE
Feature: XEP-0308 Last Message Correction

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#805]
http://www.xmpp.org/extensions/xep-0308.html

**Comment by mdosch** [comment]
I'd really appreciate this feature. A possible UI would be that Ctrl+Up brings the last message back to the input line and let you edit it. 
Messages edited by others could be shown with a special char (like omemo char).

**Comment by jubalh** [comment]
Already planned for 0.9.0 :)
