### ISSUE TITLE
Long lines with full chat screen overwrites chat in tmux

### ISSUE THREAD

**Issue by rldleblanc** [profanity-im/profanity#814]
I keep profanity in a tmux session so that I can always get to it easily. I've found that when a chat screen is filled with chats and I type a long line so that it wraps to two or more lines (n), then the chat screen only advances one line and n-1 lines above it are overwritten with my text. I don't know if this happens without tmux (I don't chat that much). I'm using 0.4.7 from Debian Stretch.

**Comment by jubalh** [comment]
Never happened to me. Maybe this was a tmux problem in the past. Closing this for now.
