### ISSUE TITLE
OTR message with line breaks

### ISSUE THREAD

**Issue by user578** [profanity-im/profanity#824]
When I receive OTR message with line breaks the client shows only last line and other lines showed as empty lines. Also, the client doesn't show timestamp and sender name for this message. So this looks weird and buggy. Anyone else have this problem?

**Comment by boothj5** [comment]
I can't seem to recreate.  I tried by sending an OTR message with newlines to Profanity, both from Profanity and form Conversations, and in both cases the newlines appear as expected in the message.

A few questions that might help:

1) Which version of Profanity are you using?
2) Which version of OTR is the build compiled against (run `/otr libver`)
3) Which client is the message sent from?

Thanks.

**Comment by user578** [comment]
Hello. I use Profanity version 0.4.7 with libotr version 4.0.0
The other client is Miranda NG (Windows) with MirOTR.dll library. Maybe the reason is different line break character code on Windows or something like that.
Is there a way to use the newer libotr? Can I just update it? Maybe the problem is solved in following versions.
Thanks for help.

**Comment by boothj5** [comment]
Just tested on Profanity 0.4.7 (again from Profanity and Conversations) and worked ok.

You could try upgrading libotr, but I'm guessing the issue has something to do with windows line breaks as you mention.  I have a Windows VM on which I'll try to recreate the problem.

I'll update this issue once I've tried it.

**Comment by jubalh** [comment]
No Windows here either.
