### ISSUE TITLE
Better handling of connection losses

### ISSUE THREAD

**Issue by nd2s** [profanity-im/profanity#832]
When Profanity loses its connection because I turn on OpenVPN or connect an Ethernet cable, it does not detect a problem. All new messages I write are are not delivered and stay red because its waiting for ACKs of receipt requests that never arrived, and commands like `/otr start` never return any result.

`/autoping` is set to 15 seconds and `/reconnect` is set to 1 second. I would expect Profanity to establish a new connection in that time period.

**Comment by boothj5** [comment]
What is the autoping timeout setting?  This is how long profanity will wait before considering the connection dead.

**Comment by nd2s** [comment]
I mentioned that in the second paragraph!

**Comment by boothj5** [comment]
I can't recreate this one, with the same settings and disabling my wireless connection.

Do you see the following in the console window?

```
21:37:32 - Autoping response timed out afer 10 seconds.
21:37:35 - Lost connection.
```

After switching the connection back on, Profanity reconnects almost immediately and I can use `/otr start` etc.

Running with debug (``profanity -l DEBUG``) enabled and attaching some logs might help.

**Comment by nd2s** [comment]
I didn't just disconnect. I connected via Ethernet while keeping the current wifi connection, same with OpenVPN. This has probably something to do with how the routes change.

I tried to reproduce but it doesn't seem to fail every time. The time if failed, Profanity actually DID reconnect as it seems, but the chat I was in did not show the "Lost connection" message but showed the behaviour described above (I never saw the `Autoping` message btw). But I noticed, in the chat window,  the contact was displayed as offline even though it was actually online.

I will test some more tomorrow, maybe I can get relevant logs. It's getting a bit too late here to think properly.

**Comment by boothj5** [comment]
Ok thanks, I also tried by switching wireless networks while connected and didn't see the issue (I got the disconnected message, and reconnect worked).

**Comment by nd2s** [comment]
Here are some logs:

* Started client and (auto)connected account
* Opened chat window with online contact
* Initiated (required) OTR session
* Connected to VPN
* Sent single message (stayed red)
* Ended OTR session and tried to start new one (no result)

```
09/08/2016 16:59:09: xmpp: DBG: RECV: <iq id="prof_ping_41" to="foo@domain.com/resource" type="result"/>
09/08/2016 16:59:09: prof: DBG: IQ pong handler fired, id: prof_ping_41.
09/08/2016 16:59:24: conn: DBG: SENT: <iq id="prof_ping_42" type="get"><ping xmlns="urn:xmpp:ping"/></iq>
09/08/2016 16:59:26: prof: DBG: Input received: start
09/08/2016 16:59:26: conn: DBG: SENT: <message id="prof_msg_43" to="bar@domain.org" type="chat"><body>?OTR:AAID[...]RAAAAAA==.</body><private xmlns="urn:xmpp:carbons:2"/><no-copy xmlns="urn:xmpp:hints"/><no-store xmlns="urn:xmpp:hints"/><request xmlns="urn:xmpp:receipts"/></message>
09/08/2016 16:59:39: conn: DBG: SENT: <iq id="prof_ping_44" type="get"><ping xmlns="urn:xmpp:ping"/></iq>
09/08/2016 16:59:45: prof: DBG: Input received: /otr stop
09/08/2016 16:59:48: prof: DBG: Input received: /otr end
09/08/2016 16:59:48: conn: DBG: SENT: <message id="prof_msg_45" to="bar@domain.org" type="chat"><body>?OTR:AAID[...]QAA.</body><private xmlns="urn:xmpp:carbons:2"/><no-copy xmlns="urn:xmpp:hints"/><no-store xmlns="urn:xmpp:hints"/><request xmlns="urn:xmpp:receipts"/></message>
09/08/2016 16:59:51: prof: DBG: Input received: /otr start
09/08/2016 16:59:51: conn: DBG: SENT: <message id="prof_msg_46" to="bar@domain.org" type="chat"><body>?OTR?v2? This user has requested an Off-the-Record private conversation. However, you do not have a plugin to support that. See http://otr.cypherpunks.ca/ for more information.</body><private xmlns="urn:xmpp:carbons:2"/><no-copy xmlns="urn:xmpp:hints"/><no-store xmlns="urn:xmpp:hints"/><request xmlns="urn:xmpp:receipts"/></message>
09/08/2016 16:59:54: conn: DBG: SENT: <iq id="prof_ping_47" type="get"><ping xmlns="urn:xmpp:ping"/></iq>
09/08/2016 17:00:09: conn: DBG: SENT: <iq id="prof_ping_48" type="get"><ping xmlns="urn:xmpp:ping"/></iq>
```

**Comment by rumpelsepp** [comment]
Our jabber server at work does not support the autoping extension; so this becomes a problem since disconnects are not detected and profanity becomes stalled.

**Comment by jubalh** [comment]
Done in 5dd6ba73f43e8540872cb01ea3549c7d6e972101 and da54eaf42b88be62bfebbb84dd11cb9bdd4cd9bd
