### ISSUE TITLE
Can not cross compile python plugin support

### ISSUE THREAD

**Issue by Neo-Oli** [profanity-im/profanity#851]
The configure scrip doesn't work when trying to cross compile with --enable-python-plugins
It will find the build systems python version, rather than the prebuilt version for the target system. This however can be solved by some of the following Environment variables. 

```
export PYTHON_LDFLAGS+=" -L${PREFIX}/lib/python3.5"
export PYTHON_CPPFLAGS+=" -I${PREFIX}/include/python3.5m"
export PYTHON="$PREFIX/bin/python"
export PYTHON_VERSION=3.5
```

The bigger problem is, that the build script wants to execute python at several points in the configure script, which doesn't work when cross-compiling because the python binary is built for the target system and can't run on the build system. 

To solve this in [Termux ](http://termux.com), @fornwall figured out [a neat trick,](https://github.com/termux/termux-packages/blob/master/packages/profanity/build.sh) We run configure with --disable-python-plugins and afterwards [hack it into the makefile](https://github.com/termux/termux-packages/blob/master/packages/profanity/build.sh#L18). 

While this is solved for Termux for now, it probably shouldn't happen that the configure script would want to run python directly. 

(glow from xmpp)

**Comment by jubalh** [comment]
Is this related to https://github.com/profanity-im/profanity/issues/804 ?

**Comment by jubalh** [comment]
We have checks like `#if PY_MAJOR_VERSION >= 3` which is set at build time depending on the system. We should probably make this configurable or check the version at runtime since the system profanity is build on can be different than the one where it is run.

**Comment by jubalh** [comment]
@pasis do you have an idea here?

**Comment by jscott0** [comment]
I didn't realize it was a duplicate, but I posted a couple ideas at #1519

**Comment by jubalh** [comment]
@jscott0 would you mind creating a tested PR with the pkgconfig solution?

**Comment by jscott0** [comment]
> @jscott0 would you mind creating a tested PR with the pkgconfig solution?

I'm not familiar with Autotools or Python but wouldn't mind learning the former. Give me a few weeks and I'll try experimenting

**Comment by jubalh** [comment]
@jscott0 ping :-)

**Comment by jubalh** [comment]
In https://github.com/profanity-im/profanity/pull/1641 I tried to clean up the build files and make them work better for cross compilation.

The Python thing you mentioned isn't solved yet but I also have no idea how to do it.
I'll close this issue and wait for an PR or further details in case it's still relevant.
