### ISSUE TITLE
OTR restart, and always setting

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#857]
Taken from an email request:

The first is the command `/otr restart`. When you lose connection, you
cannot just `/otr start`. You are already in the OTR session,
so you have to `/otr end` it first and only after that use `/otr start`. Alias of `/otr stop` && `/otr start` would be a great solution.

The other one is not so easy to implement, but will be also quite handy.

When you've selected `/otr always`, messenger won't let you send any
unencrypted messages, and that's a right behavior. But what if it will
start OTR session automatically when one attempts to send a message, and
then send it in the session?

**Comment by nd2s** [comment]
Second is last item in #840.

**Comment by jubalh** [comment]
Not many use OTR. Since second issue is tracked in 840. I think typing `start` and `end` insted of `restart` is ok.
