### ISSUE TITLE
Disable autojoin of rooms and only join ones in the script

### ISSUE THREAD

**Issue by neeravkumar** [profanity-im/profanity#872]
Hi,

I want to disable autojoin of rooms and manually join rooms myself when needed, is that possible?

**Comment by boothj5** [comment]
Hi,

You can disable the autojoin for any room with:

```
/boookmark update <room> autojoin off
```

I have the same situation where sometimes I want to join a list of rooms, to do this I have a script full of `/join` commands e.g.:

```
/join jabber@conference.jabber.org
/join jdev@conference.jabber.org
/join profanitydev@conference.jabber.org
```

The script is stored at:

```
~/.local/share/profanity/scripts/joinall
```

You can then execute the script with `/script run joinall`.  I've also added an alias:

```
/alias add joinall /script run joinall
```

So all I have to do is:

```
/joinall
```

**Comment by neeravkumar** [comment]
The room list comes from the server though, I have not added bookmarks.

**Comment by boothj5** [comment]
What does `/bookmark list` show?
