### ISSUE TITLE
Profanity lost connection after account start script used

### ISSUE THREAD

**Issue by seamus-45** [profanity-im/profanity#873]
| Name | Value |
| --- | --- |
| Profanity | 0.5.0 |
| XMPP library | libmesode |
| Desktop notification support | Enabled |
| OTR support | Disabled |
| PGP support | Disabled |
| C plugins | Enabled |
| Python plugins | Enabled |
| GTK icons | Disabled |

Profanity always lost connection right after auto connection to default account, when start script used, like this:

```
/join one
/join two
/join three
```

Second connection is successful. Manual connecton without default account configured, also is successful.

Also, the following problem can be related. With script content like this: `/ping foo` Profanity always crashed (during auto connection).

**Comment by mdosch** [comment]
I never used a start script. Is there any reason you use a script rather then bookmarking the MUCs and set the autojoin flag ([See XEP-0048](https://xmpp.org/extensions/xep-0048.html#format-conference))?
This works well with profanity.

**Comment by pasis** [comment]
This is a bug (if reproducible), so should be fixed anyway. Would be useful to see debug logs if someone reproduced the issue.

**Comment by jubalh** [comment]
I tried this and for me it works just fine.

Will close this. In case it persists for you please mention exact commands to run.
