### ISSUE TITLE
Incorrectly coloured date after regaining connection

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#875]
In a chat room for example, when the connection is lost the message:

`lost connection`

Is shown in red.

The date on the next line is also red, but should be white.

The above is with no theme chosen.

**Comment by boothj5** [comment]
Same issue when joining a room, the first line shows:

`07/11/16 21:38:44 ! -> You have joined the room as boothj5, role: moderator, affiliation: owner ` in yellow, and the date on the next line is yellow, but should be white.

**Comment by jubalh** [comment]
This actually works for me.
Both with and without theme set.
