### ISSUE TITLE
Highlight unread messages with a different color in /wins

### ISSUE THREAD

**Issue by asmartin** [profanity-im/profanity#895]
The `/wins` command is useful for getting an overview of the open windows, but it would be even better if it would display windows with an unread message in a different color, that way you could easily pick out which windows need your attention

**Comment by boothj5** [comment]
I've been thinking the same thing for a while.  Will try to get it in the 0.5.1 release.

**Comment by asmartin** [comment]
Excellent, thanks!

**Comment by boothj5** [comment]
Changed to the 0.5.2 release as I need to get 0.5.1 out in the next week or so.
