### ISSUE TITLE
Handle click on libnotify notification

### ISSUE THREAD

**Issue by asdil12** [profanity-im/profanity#900]
The libnotify notifications support clicking.
Profanity should try to bring the xterm window to the front and switch to the right chat window within the application.

xterm can be brought to front by setting "enable bell urgency" to true in the xterm config.
Then a `\a` will make the xterm urgent which will make the window manager bring it to the front.

A click on a notification can be detected by registering a callback using libnotify:

```c
#include <libnotify/notify.h>
#include <gtk/gtk.h>

void ncb(NotifyNotification* n, char* action, gpointer user_data) {
        printf("Callback: %s!\n", action);
}

int main(int argc, char *argv[]) {
        gtk_init(&argc, &argv);
        notify_init("Hello world!");
        NotifyNotification * n = notify_notification_new("Hello world", "This is an example notification.", "thunderbird");
        notify_notification_add_action(n, "default", "open the thing", NOTIFY_ACTION_CALLBACK(ncb), NULL, NULL);
        notify_notification_show(n, NULL);
        g_usleep(5000000);
        gtk_main_iteration_do(FALSE);
        //gtk_main();
        g_object_unref(G_OBJECT(n));
        notify_uninit();
        return 0;
}

// compile with: gcc -o nt `pkg-config --cflags --libs libnotify gtk+-2.0` nt.c
```

**Comment by jubalh** [comment]
@asdil12 since you contributed to profanity in the past already, do you maybe have the time to create a patch for this?

**Comment by asdil12** [comment]
As I switched from awesome to i3 WM and now use dunst for notifications which AFAIK doesn't support click callbacks, I for myself don't need this anymore.
We could just add a callback for the gtk tray icon which would work anywhere. Maybe with a config option to disable that behaviour.
That would be rather simple.

**Comment by jubalh** [comment]
@asdil12 would you like to integrate that ?

**Comment by jubalh** [comment]
Is there another way to raise the terminal window than `xdotool` which would rely on the window name?

**Comment by jubalh** [comment]
So as I see it we need to:
get the currect PID -> get the window where pid is running -> raise the window.

Anybody knows a way to handle the second step?

**Comment by jubalh** [comment]
I don't plan to do this myself.
