### ISSUE TITLE
Window 1 continues to blink even when all unread messages have been read

### ISSUE THREAD

**Issue by asmartin** [profanity-im/profanity#907]
I'm running profanity 0.4.7 (the latest version shipped with Ubuntu 16.04) and have noticed that window `[1]` will blink to indicate that a new message is present on one or more of the windows (e.g. `[15]`) along with the actual windows themselves blinking. This is a nice feature, however once I've viewed all the windows with unread messages (and there are no more unread messages), window `[1]` continues to blink until I visit it. Is it possible to notify it to stop blinking once the last unread notification has been dismissed?

**Comment by boothj5** [comment]
Currently not possible, but I'll tag this as an improvement.

**Comment by jubalh** [comment]
I think this is now in Profanity since a long time:
https://profanity-im.github.io/guide/latest/reference.html#console
