### ISSUE TITLE
Facebook chat with purple?

### ISSUE THREAD

**Issue by GhostValk** [profanity-im/profanity#911]
Hi,

Is there any chance to implement access to the Fb chat protocol using jgeboski's purple plugin?

**Comment by boothj5** [comment]
In principle it should be possible to write a plugin to allow facebook chat in profanity.  If anyone wants to have a go, I can add any missing API calls needed.

**Comment by GhostValk** [comment]
I would love if my programming skills were better, but i'm a newbie in C/Perl..

**Comment by asdil12** [comment]
You could use the spectrum2 transport on the xmpp server.
Spectrum2 uses this purple-facebook module.
It will allow you to talk to facebook (and other network, eg, Telegram) contacts and even join facebook groups as MUCs.

You will need an xmpp client like PSI+ to set up the transport in your account but then it will work with any xmpp client. - A server where you can try this out is https://jabjab.de/zertifikate.php?lang=gb

**Comment by GhostValk** [comment]
Thanks a lot!!!

Would you mind to explain how to use jabjab with profanity?

**Comment by asdil12** [comment]
You will need Register an Account (https://jabjab.de/registrieren.php?lang=gb) and then set up the psi+ jabber client for this account (you can't use profanity for this step, as it doesn't support in-band registration).

Then after you are online, click the "Service Discovery" button.
You should see the components of the xmpp server.
There should be something like `facebook.jabjab.de` in the list. Right-Click on the entry and Click "Register". Fill in your Facebook Username and password and send the form.
Now the hell will break loose as you will get subscription requests from `facebook.jabjab.de` which must always be in your contact list to let the transport do its work and requests for every friend in your facebook contact list. Their jabber ids will look like `somenumber@facebook.jabjab.de`.
When you accepted everything and added them to your contactlist, it will work in any jabber client.
Note that you might get a message with a link to click on and confirm, that you are trying to access your account via your webbrowser.

**Comment by jubalh** [comment]
Yes, there exist Gateways like https://spectrum.im/

I have heard that they are fairly unreliable. I don't know of anyone who used them over a longer period of time. I don't think it's worth the hassle of implementing support for this.

**Comment by jubalh** [comment]
Won't do this now.
