### ISSUE TITLE
Remote Controlling Clients

### ISSUE THREAD

**Issue by Spacewalker2** [profanity-im/profanity#913]
https://xmpp.org/extensions/xep-0146.html

**Comment by jubalh** [comment]
https://xmpp.org/extensions/xep-0146.html was marked as obsolete in 2017.

I doubt it's useful nowadays.
Here are it's use cases copied from the XEP and my thoughts:

    Change status -> many people dont care about the status anymore
    Forward unread messages residing at the remote client to the local client -> most people use carbons
    Change run-time options 
    Accept pending file transfer requests -> useful for p2p sent files but most people probably use http upload
    Leave groupchats -> bookmarks2 is around the corner

Will close this because I don't see a need to implement it.
