### ISSUE TITLE
Resource override is forgotten on presence change

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#914]
The command `/resource set <resource>` forces messages to be sent to a specific resource.  When messages are received from another resource, messages are still sent to `<resource>` as expected.

However, when the contact's presence changes, the resource override is no longer used.

**Comment by jubalh** [comment]
Not sure whether we should remove that functionality alltogether due to what is written on: https://wiki.xmpp.org/web/XMPP_2.0

If we want to have this still we should only reset the resource once the one currently is set goes offline.

**Comment by kaffeekanne** [comment]
Like #912 i would vote for dismissing this feature as well.

**Comment by jubalh** [comment]
Okay. Let's remove resource locking for 0.8.0.
Displaying resource in UI will of course still be supported.

**Comment by jubalh** [comment]
Actually I think setting the resource according to the presence is what should happen.
Also I assume that almost everybody uses Carbons now, so all the clients will receive the messages anyway.

I'll close this issue for this reason.
