### ISSUE TITLE
HTTPS for website

### ISSUE THREAD

**Issue by oodbur** [profanity-im/profanity#927]
the website profanity.im should get a TLS certificate thats valid for this domain and then default to HTTPS.
this could make the published hash values on there useful for securing downloads, among other things.

**Comment by pasis** [comment]
I think this issue is related to https://github.com/boothj5/www_profanity_im. I propose to create ticket there and close this one.

**Comment by jubalh** [comment]
Had this for some time now. But didnt work anymore at one point, see https://github.com/profanity-im/profanity/issues/1028.
Now moved to GH pages: https://github.com/profanity-im/profanity/issues/1085
