### ISSUE TITLE
Don't redraw far enough when switching windows with large unicode characters

### ISSUE THREAD

**Issue by gunnihinn** [profanity-im/profanity#929]
When I switch from window A to window B, and window A has lines with large unicode characters (see a few below), window B may contain "phantom" characters from window A. These characters then persist when switching into other windows.

If I scroll up or down in window B, and the scrolling happens to draw a line over one of these phantom characters, it goes away. Depending on the amount of text in the window, I may get lucky and clear the window that way.

I get this problem when these characters are on a line:
▶️
↪️
❤️
Other unicode characters (😛, 😐 for example) don't seem to cause the problem.

It's just a guess, but from a glance at http://www.ltg.ed.ac.uk/~richard/utf-8.html it seems like the problem characters are encoded by 3 hex UTF-8 bytes, while the ones that don't cause problems are encoded by 4 bytes.

This problem happens on OSX in iTerm2, both inside and outside of tmux, and independently of the console font used. I can provide more info about the environment, and check if the problem persists on Fedora if needed.

This is actually a real nuisance for me, because I use profanity to monitor jabber channels at work, and unfortunately a bunch of bots flag their messages with these "bad" characters. Their presence quickly makes the profanity screen unreadable. I'd really like profanity and would prefer to keep using it over some inferior GUI client just because of this. :)

**Comment by variablenix** [comment]
I was going to open a new issue but found this thread. I am also experiencing this weirdness where characters will randomly move to different parts of the screen across different windows. I updated Profanity to use `profanity-git` in my Linux distro thinking maybe the community package of `'profanity` was the issue, but the issue remains. 

I connect to my Linux box from macOS using iTerm2 and have profanity running inside a tmux session. I'm using `ncurses 6.0+20170902` and `profanity-git 4858.4c7396e7` on the Linux box where I have profanity running.

**Comment by jubalh** [comment]
Can you guys still reproduce this? Can you attach a screenshot?

**Comment by gunnihinn** [comment]
I don't know, I switched to irssi over bitlbee sometime in 2018 because of this. I don't have the time to reproduce this, sorry.

**Comment by jubalh** [comment]
Oh irssi + bitlbee has a lot less features doesnt it?
Ok, will close this then :)
