### ISSUE TITLE
PGP partially doesn't work

### ISSUE THREAD

**Issue by Fraterius** [profanity-im/profanity#937]
My scenario is as follows:

All scenarios are using carbons and pgp encryption. I'm running latest version of Archlinux which has:

profanity 0.5.1
libmesode 0.9.1
gpgme 1.9.0

I'm using three clients Conversations, Gajim (on Linux) and Profanity.
The other end uses Conversations and Gajim (on Windows).

In Profanity I'm manually setting pgp keys for myself and for the contact who is my friend sitting next to me. /pgp shows and sets the correct values. PGP turns green for receiving and sending (upper status bar).

1) As long as Profanity is offline everything works great.
2) When I'm turning Profanity online and I'm not sending messages it works ok. Profanity is receiving messages and decrypts everything correctly (by carbons).
3) Problem starts when I try to send messages using Profanity.
- both Gajim's (my own and the other end) not showing a thing. Simply nothing happens (which I think is standard behaviour for this program when it can't decrypt messages it simply drops them).
- both Conversations (my own and the other end) showing message "Unable to decrypt" it tries to open OpenKeychain to specify other key to decrypt whcich is completely strange for me .
- after a while other end Conversations looses ability to encrypt messages (from what I know Conversations takes keyid from what is reported back to it by the other end, conclusion is that the profanity must reports it badly)

If there is anything else I can provide, I'll do that gladly. Today I've tried mcabber which uses the same library to encrypt messages (gpgme) and it works flawlessly within 10 minute setup maybe we can track down how they deals with pgp, carbons and so on. I've got no idea where the problem lies but I've read that profanity had some issues with cabons and pgp used together.

**Comment by Weirdei** [comment]
I have the same issue on the latest profanity version 0.5.1.
On the other end is PSI+

**Comment by jubalh** [comment]
@Fraterius @Weirdei can you please retest this with latest master?

**Comment by jubalh** [comment]
I tested with https://github.com/boothj5/profanity/commit/6034b833be41909982b0d2bdac0a1d8499ad8e76 as follows:

user1 logs in via PSI+
user2 logs in via Gajim

They write -> works
They write encrypted -> works
user1 logs in via profanity. calls `/pgp start`

user1 writes from profanity -> all instances see it
user1 writes from psi -> all instances see it
user2 writes from gajim -> all instances see it

**Comment by jubalh** [comment]
Seems similar if not the same to https://github.com/boothj5/profanity/issues/796

**Comment by Fraterius** [comment]
@jubalh yes #796 is very similar but there where some differences that's why I decided to make new issue.

Right now I've switched to mcabber where PGP works without a glitch with every client I've been using since (with carbons support).

If I'll have some free time together with the other end that I'm using encryption we'll test the latest master.

**Comment by jubalh** [comment]
> If I'll have some free time together with the other end that I'm using encryption we'll test the latest master.

Great, will be looking forward to your feedback.
As you can see above I did some tests myself, where everything worked.

**Comment by jubalh** [comment]
@Fraterius any news?

**Comment by Fraterius** [comment]
Please give me some more time. I literally have no free time right now. Recently I also needed to fully reinstall my main server where I'm using console jabber. I'll try to get some feedback this month, if that's not OK please close it and I'll reopen the issue when I'll find some spare time.

Best regards.

**Comment by jubalh** [comment]
Sure, take your time.

**Comment by Fraterius** [comment]
I've just tested it out. It all looks good, works without any issue with carbons enabled and with multiple different clients connected.

Great I'll give it a try ;).
Closing.
