### ISSUE TITLE
Global plugin installation dir

### ISSUE THREAD

**Issue by flocke** [profanity-im/profanity#945]
Would it be possible to create a global plugin location so it would be easier for packagers to distribute plugins?

For example I could package the OMEMO plugin and have it installed directly in the right place without the user having to copy/link a file manually to `~/.local/share/profanity/plugins/` afterwards.

I would suggest something like `${DATADIR}/profanity/plugins` (e.g. `/usr/share/profanity/plugins`) for python plugins and `${LIBDIR}/profanity/plugins` (e.g. `/usr/lib/profanity/plugins` or `/usr/x86_64-pc-linux-gnu/lib/profanity/plugins`) for C plugins.

**Comment by philipflohr** [comment]
@boothj5 @jubalh  what do you think of this?
IMO this is a good idea, but as omemo gets implemented in profanity I don't know if there are any plugins worth getting packaged;)

**Comment by jubalh** [comment]
I agree that this is a good idea. Even though OMEMO is planned to be implemented in profanity directly, this feature makes sense.

Looking for plugins in `${LIBDIR}/profanity/plugins` sounds right.

**Comment by philipflohr** [comment]
According to https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html the proposal of @flocke to seperate c and python plugins should be used.

**Comment by jubalh** [comment]
Good point! I didn't know about it.

**Comment by jubalh** [comment]
@philipflohr do you want to implement this?

**Comment by jubalh** [comment]
@philipflohr ping :)

**Comment by jubalh** [comment]
@philipflohr ?

**Comment by jubalh** [comment]
@mwuttke97 maybe something for you?

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/pull/1598 got merged.
