### ISSUE TITLE
Log filtered chat text

### ISSUE THREAD

**Issue by mrsdizzie** [profanity-im/profanity#948]
When using a plugin to modify text in a room/chat (stripping HTML from incoming messages) it would be nice if the modified text is what is logged in the chatlogs so it matches what the user actually saw.

Is this already possible in some way? Thx!

**Comment by ari** [comment]
Where are you finding a plugin to strip html?

**Comment by mrsdizzie** [comment]
I don't have a plugin that strips HTML. When using Apple Messages as an XMPP client it (annoyingly) identifies URLs and e-mail addresses and modifies the text it sends to the server so writing something like test.com or test@test.com get sent to the server as:

`test.com <http://test.com>`
`test@test.com <mailto://test@test.com>`

That doesn't look very nice in a text based chat client so I wrote something to strip out the <> part. Since I'm not actually seeing that text any more I wouldn't want it in the logs either.

fwiw here is the code I used:

```
def sanitize(message):
    """ Cleans message
    """
    try:
        #strip the <> link part messages sends only if that domain matches the one before like test.com <http://test.com>
        match = re.search("([^<]+)\\s(?=((<http://|<mailto:)\\1>\\s?))", message)
        prof.cons_show('stripped %s from message' % match.group(2))
        message = message.replace(match.group(2), "")
    except:
        pass
    finally:
        return (message)
```

Then you can use something like:

```
def prof_pre_chat_message_display(jid, resource, message):
    message = sanitize(message)
```

**Comment by ari** [comment]
Nice, thanks. I need it to remove the <FONT> tags Adium puts in, but I can do that with some simple regex. I just need to figure where to put this plugin code.

**Comment by jubalh** [comment]
We call plugins_pre_priv_message_display() (for example) upon receival and plugins_post_priv_message_display() before exiting the receival function.
In between we display/log things.

The pre funtion is able to manipulate the message.
