### ISSUE TITLE
Provide application / window focus state via plugin API

### ISSUE THREAD

**Issue by mrsdizzie** [profanity-im/profanity#949]
Is it possible to expose via the plugin API if Profanity is the currently focused/active window or application? This would be useful in trying to include custom notifications that a user wouldn't necessarily want to see if they were already looking at the chat window. Am using profanity on MacOS 10.12 if relevant.

**Comment by mrsdizzie** [comment]
Also if anybody else is interested in this my workaround for now is something like this using apple script:

```
import subprocess
ascript = '''
    tell application "System Events"
        set frontApp to name of first application process whose frontmost is true
    end tell
    tell application frontApp
        if the (count of windows) is not 0 then
            set window_name to name of front window
        end if
    end tell
    '''
if "profanity" not in (asrun(ascript)):
     os.system('terminal-notifier...')

def asrun(ascript):
  "Run the given AppleScript and return the standard output and error."

  osa = subprocess.Popen(['osascript', '-'],
                         stdin=subprocess.PIPE,
                         stdout=subprocess.PIPE)
  return osa.communicate(ascript)[0]
```

This doesn't seem to return the window information for all apps for some reason, but it does work with iTerm2/Profanity which is all that is really needed to see if you're focused or not.

**Comment by jubalh** [comment]
Unfortunately I don't own a Mac, so I cant implement this.
I assume this is different among different operating systems / X11 / Wayland.

Maybe you can write your plugin in a way that it checks the active window of your environment (`xdotool getwindowfocus getwindowname` (on Linux)) and if the title of the window is your terminal with Profanity in it do something.

Closing as out of scope.
