### ISSUE TITLE
PGP: How to run my gpg2 command, like eval_password allows?

### ISSUE THREAD

**Issue by eduncan911** [profanity-im/profanity#953]
Similar to Thunderbird's ability, how do I configure Profanity to run my own specific GPG command line?  Exactly like how the `eval_password` feature works?

I use QubesOS, which has an awesome feature called "Split GPG."  What this does is it keeps the private keys in an air-gapped Vault VM.  When a program wants to access PGP, I configure it to run a command line utility.  For example, my Thunderbird is configured with:

    /usr/bin/qubes-gpg-client --no-emit-version --no-comments --display-charset utr-8 

Then whenever that program needs to do anything with PGP (encrypting, decrypting), it uses the above command line util.

How can I configure Profanity to do the same as `eval_password`?

For example, my `eval_password` is set to:

    eval_password=/usr/bin/qubes-gpg-client < ~/.local/share/profanity/accounts.passwd

And `accounts.passwd` is simply a PGP encoded string, that gets decoded upon connecting.  Works beautifully in QubesOS to keep my passwords off of the VMs, and where they belong in my Vault VM that is air-gapped.

I tried symlinking the machine's local `/usr/bin/gpg2` to `/usr/bin/qubes-gpg-client` as well as the additional `wrapper` they provide.  But Profanity continues to list `/gpg keys` as None.  Whereas in CLI, I can issue `gpg2 --list-keys` and it uses the symlink `qubes-gpg-client` to print my keys.

---

After looking at other PGP-related issues here, it seems Profanity is trying to use a lib?  Not running a command line?  

That would make sense for performance, I see.

But if you think about it, if you did shell out to run the actual gpg2 commands, a lot of those PGP issues here may be closed?  :)

I guess the only option is to write a different PGP/GPG Plugin?  To access the command line and not use Profanity's built-in PGP feature?

**Comment by jubalh** [comment]
@wstrm @DebXWoody thoughts?

**Comment by jubalh** [comment]
@eduncan911 interested in working on this yourself?

**Comment by eduncan911** [comment]
I'm not actively using profanity (phun) at this time.  Not sure I have the bandwidth.

**Comment by jubalh** [comment]
What a shame :) I'll close this then since I'm not interested in it myself.

**Comment by eduncan911** [comment]
Oh,I prefer this over any other client I've used!

I just haven't had the need for a few years now.
