### ISSUE TITLE
Persistent priority

### ISSUE THREAD

**Issue by goberghen** [profanity-im/profanity#963]
As far as I can see there are no persistent priority settings in _profrc_ file, i.e. commands like `/account set ACCOUNTNAME online 5` only works for the current session.
Also please make command `/priority NUM` to change only current status priority and/or not override global status priority settings.
Thanks.

**Comment by jubalh** [comment]
Help sais: `set <account> <presence> <priority>   : Set the priority (-128..127) to use for the specified presence.`
