### ISSUE TITLE
Profanity 0.5.1 unit test crashes on s390s

### ISSUE THREAD

**Issue by Ejxqzgds** [profanity-im/profanity#981]
See the build log here:

https://buildd.debian.org/status/fetch.php?pkg=profanity&arch=s390x&ver=0.5.1-1&stamp=1519170089&raw=0

Near the end of the page you find:

```
[ RUN      ] handle_offline_removes_chat_session
Test failed with exception: Segmentation fault(11)[  FAILED  ] handle_offline_removes_chat_session
[ RUN      ] lost_connection_clears_chat_sessions
unittests: src/xmpp/roster_list.c:82: roster_create: Assertion `roster == NULL' failed.
FAIL tests/unittests/unittests (exit status: 134)
```

Interestingly, it works on all other architectures:

https://buildd.debian.org/status/package.php?p=profanity

Any idea, what's going wrong with s390s?

**Comment by jubalh** [comment]
Seems like 0.6.0 works: https://buildd.debian.org/status/fetch.php?pkg=profanity&arch=s390x&ver=0.6.0-1&stamp=1551401223&raw=0
