### ISSUE TITLE
Feature Request: XEP-55 Search

### ISSUE THREAD

**Issue by kedorlaomer** [profanity-im/profanity#982]
I would greatly appreciate if searching as per [XEP-55](https://xmpp.org/extensions/xep-0055.html) would be supported. After all, `/disco items` already lists search, if supported, and `/disco info` outputs it as `jabber:iq:search`.

If it's not already supported (and I just cannot find it in the docs, nor the sources), I wouldn't mind adding it as a plugin or possibly even as a patch to the main code (although I'm a bit scared of it).

**Comment by boothj5** [comment]
Would be a good feature to have. I'd like to add it to the main code, but don't have much time at the moment.  If you want to try adding it, a plugin would be fine if you'd prefer.

**Comment by jubalh** [comment]
Seems like people don't really use this anymore nowadays.
