### ISSUE TITLE
RFCs and XEPs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [profanity-im/profanity#985]
On the XEPs support page, it is possible to add version of XEPs?
http://www.profanity.im/xeps.html

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by jubalh** [comment]
I think this request should have been filed under https://github.com/boothj5/www_profanity_im

**Comment by jubalh** [comment]
Website has been updated to display a table: https://github.com/boothj5/profanity/issues/985
Not used on official website yet.
Will have to look at the versions soon. Anybody who knows or wants to help to find out which versions are implemented are welcome.

**Comment by Neustradamus** [comment]
@fbsb @jubalh: Thanks but there are always missing version of XEP-XXXX and RFCs in the same time ^^

Example:
- XEP-0045 1.2.1

**Comment by jubalh** [comment]
It's a work in progress. As you can see this issue is not closed.

**Comment by jubalh** [comment]
I'm not sure about all the versions. Will leave some blank for now.

**Comment by Neustradamus** [comment]
@jubalh: It is not up-to-date: http://www.profanity.im/xeps.html
And No RFCs information!

**Comment by optmzr** [comment]
@Neustradamus we do not have access to update http://www.profanity.im anymore, see: https://profanity-im.github.io/xeps.html instead :)

**Comment by Neustradamus** [comment]
@optmzr :/
Who has access to the official website?
@boothj5? @jubalh? @pasis?

It is not possible to have only one official host?
Make a redirection?

**Comment by jubalh** [comment]
Use https://profanity-im.github.io/xeps.html

**Comment by optmzr** [comment]
@Neustradamus I believe boothj5 has access but he's probably busy.
